### ISSUE TITLE
Expand GCP selectors to include labels and metadata

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#1001]
GCP node attestation currently produces a selector per instance tag but does not include selectors for labels and metadata. Selecting on certain labels and metadata may make sense in some deployment environments.

The GCP node attestor should be updated to allow specific labels/metadata keys to contribute to the selectors. It probably isn't a good idea to just add selectors for all labels and metadata since the list of items and their values can be arbitrarily large (metadata values themselves can be as large as 256KiB).

I'd propose we add something like the following to the plugin configuration to allow operators to opt in to the metadata and label keys they want to use for node selection: 

```
use_instance_metadata_keys = ["some-metadata-key"]
use_instance_labels = ["some-label-key"]
```

The attestor could then produce selectors for metadata and label keys that match those sets:
```
gcp_iit:instance-metadata:some-metadata-key:some-metadata-value
gcp_iit:instance-label:some-label-key:some-label-value
```

We might consider an upper bound on the size of values for candidate metadata/labels to prevent stuffing large values into the data store.

**Comment by azdagron** [comment]
An alternate selector syntax might  match the existing selectors (i.e.` gcp_iit:tag:...`) more closely:
```
gcp_iit:label:<key>:<value>
gcp_iit:metadata:<key>:<value>
```

**Comment by ajessup** [comment]
For the `use_instance_metadata_keys` and `use_instance_labels` fields, would it be reasonable to include a wildcard syntax here if the exact metadata value or label value is unknown (eg. `use_instance_metadata_keys = ["goog-dataproc-*"]`)?

**Comment by azdagron** [comment]
My only concern with opening wildcard matching is unintentionally pulling in keys that are not interesting for selection, especially if they have large values that will burden the data store.

Do we expect people to select on more than a few of the metadata keys or order to identity a node set?

**Comment by ajessup** [comment]
The concern is that the person creating registration entries may not be in
a position to reconfigure the SPIRE server. But it's not a significant
concern right now.
