### ISSUE TITLE
possible split up of sql files due to size

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#1002]
It may be beneficial for readability/maintainability to split up `sql.go` and `sql_test.go` files based on model type (registration, node...). Both these files are getting rather large.
One proposal is a subpackage with one file for init/configure related things, and another file each for every model type.

This is also a bit of a style debate, since some may prefer keeping all functions for a struct in the same file, as that comes with its own readability benefits. The subpackage proposal is a bit of a compromise between splitting up all within the current `sql` package (which likely would cause readability loss) and keeping as is (which is a monster to look at and find desired code).

**Comment by azdagron** [comment]
We've started splitting this up with new additions, but we're unsure of the future of the current code. If the prototype/exploration efforts don't pay off and we decide to stick with the current plugin, we'll be making some larger refactoring efforts to clean things up and can consider this then.
