### ISSUE TITLE
Incorrect Version on proto/spire

### ISSUE THREAD

**Issue by Pwpon500** [spiffe/spire#1021]
* **Version**: commit 8d4a2538e330e6d6346d1877d160987c26b70474
* **Platform**: macOS
* **Subsystem**: N/A

In the repo's `go.mod` file, it has the following:

```
github.com/spiffe/spire/proto/spire v0.0.0-00010101000000-000000000000
```

This is an invalid version and should be changed to the most recent commit. When you're building the actual spire project, you don't notice the issue because of the replace line:

```
replace github.com/spiffe/spire/proto/spire => ./proto/spire
```

However, when you're building an external application that uses some spire libraries, that application tries to grab the incorrect version of the spire proto, and the build fails:

```
$ go build
go: finding github.com/spiffe/spire/pkg/common/catalog latest
go: finding github.com/spiffe/spire/pkg/common latest
go: finding github.com/spiffe/spire/pkg latest
go: finding github.com/spiffe/spire latest
go: finding github.com/spiffe/spire/proto/spire v0.0.0-00010101000000-000000000000
go: github.com/spiffe/spire/proto/spire@v0.0.0-00010101000000-000000000000: unknown revision 000000000000
go: error loading module requirement
```

I put together a [dummy sample project](https://github.com/pwpon500/spire-test). If you clone it and do a `go build`, you'll see what I'm talking about.

**Comment by azdagron** [comment]
I agree this is problematic. Remembering to bump this every time a proto revision is committed is going to need to make it into our process somehow. We might need to reorganize these protos into separate repo's to make it more explicit.

**Comment by Pwpon500** [comment]
IMO, it'd be better to split it into its own repo. Otherwise, it's super easy to forget to bump the version in `go.mod`. We could also add a CI step in Travis that automatically bumps the version and commits it, but then there would be an extra commit from Travis each time someone updates the proto information. Seems a little wrong.

**Comment by evan2645** [comment]
We should think through which protos go and which stay. Not all (like node api) are meant for external consumption, and having them live in a dedicated repo might send the wrong signal?

Perhaps registration api, all of the plugin interfaces... Maybe workload api can live in spiffe/spiffe?
