### ISSUE TITLE
Updating node attestation entries is not crash-consistent

### ISSUE THREAD

**Issue by APTy** [spiffe/spire#1033]
### Problem

If the Server or Agent crashes during a rotation of the Agent SVID, the Server and Agent can become inconsistent, causing the Agent to fail permanently.

### Detail

The flow for an Agent to rotate/update its own SVID is:

1. Agent calls FetchUpdates, including a CSR for itself
2. Server signs all CSRs
3. Server updates the node attestation entries table with the Agent's latest serial number and cert expiration
4. Server responds to Agent with signed SVIDs
5. Agent updates its local cache with its new SVID

If the Server crashes (or is restarted) in between (3) and (4), or if the Agent crashes after (3) or if the Agent fails to handle the response in (4), then the Agent will fail permanently with:
```
ERRO[0000] failed to consume entire SVID update stream: rpc error: code = PermissionDenied desc = agent is not attested or no longer valid
```

server log:
```
ERRO[0002] agent "spiffe://example.org/spire/agent/join_token/89d6ba5f-ba54-47e7-817c-be019ab74539" SVID does not match expected serial number  subsystem_name=node_api
```

### Discussion

In the common case of a Server restart, we may just need to make sure that all in-flight requests are completed prior to allowing the Server to shut down. This may already be the case - I'll need to investigate more.

In the case of a Server crash, it may be that the Server needs to track both the current Agent SVID and its "prepared" SVID, and only swap when it can confirm that the Agent is in possession of the "prepared" SVID.

**Comment by azdagron** [comment]
The datastore changes required to implement the full fix have been implemented by #1128. After those changes have been included in a release, we can do part two to implement the fix. #1128 commit history contains the summary of the full set of changes.
