### ISSUE TITLE
Agent/Server version compatibility should be asserted with integration tests

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#1038]
Currently we perform compatibility testing by hand when cutting new SPIRE releases. This is error prone and adds significant overhead to the release process. Instead, we should have a test that exercises upgrade paths between compatible versions to ensure that our compatibility guarantees are met as well as speed up the release process.

**Comment by mbyczkowski** [comment]
Would this be a test harness that operates on release artifacts, i.e. there would be some sort of agent/server matrix that would try attestation etc.?

Separately from this, is there a guidance (or promise) for agent/server compatibility? Are newer agents supposed to work with older servers or the other way around (or does it not matter)?

**Comment by evan2645** [comment]
>is there a guidance (or promise) for agent/server compatibility? Are newer agents supposed to work with older servers or the other way around (or does it not matter)?

Yes, we have published documentation on upgrading SPIRE that includes compatibility guarantees: https://github.com/spiffe/spire/blob/master/doc/upgrading.md

We have also merged a new test suite that exercises all upgrade paths in https://github.com/spiffe/spire/pull/1473 🎉 

Marking this as closed. If we want to add additional cases or detection to the above suite, we can do it as part of a new issue.
