### ISSUE TITLE
Healthcheck framework uses a different logger

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#1072]
The healthcheck framework we are using instantiates its own logger, resulting in mis-matched formatting, lost fields and configuration, etc. A brief look at the library makes it seem as if it is possible to provide our own logger, however there may be a slight interface mismatch.

Update the health package to pass our own logger into the go-health library so we get consistent logging.

```
DEBU[0000] Signed X509 SVID                              expiration="2019-08-16T19:17:40Z" spiffe_id="spiffe://example.org/spire/server" subsystem_name=ca
2019/08/16 11:17:40 [DEBUG] Starting checker name=server
DEBU[0000] Initializing API endpoints                    subsystem_name=endpoints
```

**Comment by mcpherrinm** [comment]
Seems like there's a possibility for a meta-task here too:  How can we validate all log messages come from Logrus?  Might be interesting to have some kinda integration test environment to verify.
