### ISSUE TITLE
Safer DB migration strategy in spire server cluster env

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#1083]
Currently if SPIRE Server with DB version X starts up and looks to DB with version < X, SPIRE will auto-migrate the DB to X. Backwards compatibility does not exist.

Problems:
- In a distributed environment this is fatal to the other SPIRE Servers. They will be in a < X DB version and fail to start due to not being able to migrate backwards
- The migration is uncontrolled; in such an environment we not commit to every single Server must upgrade, and hope that the new DB schema is good

Some (non-mutually exclusive) Solutions:
- A flag to pass to Server config to **not** perform auto-migration; without other changes this is fatal to the newer server but lets the older ones continue operations
- Proper semantic versioning of the DB versions; when starting up and the DB is at a later version than the Server expects, if the new version does not indicate a breaking change then the old Server should be able to continue operations (not perform backwards migration)
- A method of rolling back the DB version
- A method of a later Server being backwards compatible for older DB versions

**Comment by ZymoticB** [comment]
To start we should add a flag to disabled auto-migration. It will be a very quick change and will significantly increase maintainability.

A simple requirement which leads to this conclusion, a running build should *always* be able to restart, that is not currently true due to the automigration behaviour.

**Comment by mbyczkowski** [comment]
I think the flag to disable auto-migration would be a good low-hanging fruit (and, incidentally, is already being tracked in #786).

In the future, it would be good to have migrations managed explicitly, through command that takes a list of migration files/statements as inputs (something similar to [Flyway](https://flywaydb.org/) in Java or migrations in Rails). This would still make development easy, but also would be helpful for people that use migration solutions that live outside of their apps, e.g. MySQL users would use [pt-online-schema-change](https://www.percona.com/doc/percona-toolkit/LATEST/pt-online-schema-change.html), [gh-ost](https://github.com/github/gh-ost) or similar tools.

**Comment by evan2645** [comment]
This issue (and much more) is under active scrutiny as part of https://github.com/spiffe/spire/issues/896

We've had a few conversations around how to address this problem in particular. Some observations we've made thus far:
* A great deal of the pain is related to lack of discipline around introducing schema changes and subsequently using them.
  * Schema changes should be both forward and backwards compatible
  * This will move pain from operators to developers (as changes must be planned well in advance), however I don't think it is avoidable
  * Downgrades should be trivial with this approach
* It's not clear (to me yet, at least) that we actually need a facility to disable migration management in SPIRE
  * Migration management with the aforementioned tools are usually required for larger datasets
  * Some back of the envelope numbers suggest that, under some unfavorable conditions, SPIRE db size should not grow more than low single-digit number of GB
    * If anyone has data suggesting otherwise, that would be good to see!
  * At this size, what is the advantage to manually managing migrations?
    * Is this a reaction to _other_ problems that can be addressed by other points noted here?
* We don't yet have a solution for the race-to-migrate problem
  * Could solution to this problem, coupled with more discipline in migration strategy, be wholly sufficient?

**Comment by ZymoticB** [comment]
Our dataset is currently under 100MB

I think opting out of the implicit behaviour is a good short-term low hanging fruit. I don't want to have to educate every single person that may deploy the system that they need to check if they are deploying a build with a DB migration in it and act accordingly.

**Comment by evan2645** [comment]
> I think opting out of the implicit behaviour is a good short-term low hanging fruit.

Mind sharing some of your thoughts around how exactly you'd like to see this work? For instance, disabling auto-migration is fairly straightforward, but then how would you like to actually manage the migration? A new CLI command or utility? We'd need it to somehow consume the migration code/version stuff... We would also need to start now with the more disciplined schema changes, since upgrading server code but not running a required migration implies backwards compatibility.

That last point is related to my earlier question of whether or not this is a reaction to other problems - would starting now on more disciplined schema changes address your particular concern/pain point? Kind of feels like this, and perhaps some small targeted fixes around race-to-migrate specific to SQL is an attractive solution that could suffice until #896 is sorted.

Maybe I am missing something, but disabling migration doesn't seem like a _very_ quick win... and I'd be hesitant to undertake significant work on the current datastore codebase as there's a possibility that we'll rip it all out in the near future. If you have some ideas on how to make this more tenable though, I would love to hear them

**Comment by ZymoticB** [comment]
So the way I see this being safer with the current code (this isn't a reflection on the goal state).

There is a flag that disables automigration, if the DB is not the right version the server will fail to start. With automigration disabled the environment will always be safe for running builds (this doesn't fix the rollback problem). To accomplish a migration a build with automigration enabled would need to be rolled out (or a small CLI to do the migration) followed by an deploy with the new version and automigrate disabled.

This isn't super convenient but at least allows me to opt into safety with minimal changes. I view this as a quick win while acknowledging it doesn't actually solve the problem space being discussed here (ensuring forwards / backwards compatibility in the SQL driver, enabling rollbacks, etc).

**Comment by evan2645** [comment]
I see. @mbyczkowski is this similar to what you had in mind as well?

**Comment by mbyczkowski** [comment]
@evan2645 yes, more or less. E.g. my company uses a central system to manage running all DDL statements, so database migrations are applied separately from deploying code changes. It's on developers to plan database/code changes accordingly. I understand that in smaller environments, it's important for SPIRE to come with complete tooling, so I think having tooling for managing migrations that has an opt-out might be a good solution going forward.

**Comment by mcpherrinm** [comment]
Non-DDL changes are definitely challenging and probably require application code to run them.  Those are the highest risk changes though, and in my experience, the leading cause of outages. 

I would absolutely never want to execute a non-DDL migration automatically as part of a deploy:  Either way it needs to be an explicitly applied step, ideally with controls around velocity of how fast the change iterates over a database to prevent overload, if it's not applied via a binlog filter (ala gh-ost for DDL).

**Comment by amoore877** [comment]
since we are in agreement about this starting point, can we get #1089 reviewed
the only part about that PR that needs some change is I'm not sure exactly on wording that should go into the contributing doc regarding this

**Comment by evan2645** [comment]
> since we are in agreement about this starting point, can we get #1089 reviewed
the only part about that PR that needs some change is I'm not sure exactly on wording that should go into the contributing doc regarding this

I began reviewing #1089 last week but did not finish. I think more is needed (not just the CONTRIBUTING text). Might be easiest to chat about it offline? The biggest thing I see is that there is no facility for stating a required version, and the current PR makes using the feature dangerous - IMO there is room to make the mechanism safe and still meet the needs stated in this issue.

**Comment by mweissbacher** [comment]
Related to this discussion - I added a migration dry run feature that can be used to perform controlled migrations outside of spire-server: https://github.com/spiffe/spire/pull/1110

**Comment by amoore877** [comment]
> When the server starts up, if the SPIRE version number stored is greater than +/- 1 "major" version away from its own version, then it will bail out with an appropriate error. This condition should only be hit if 1) automigration is disabled, AND 2) an operator has upgraded through two "major" versions without performing any migrations.

makes sense

> Upgrading past a "major" version (e.g. 0.6.x to 0.8.x) is not supported in any case.

trying to reconcile with the first statement, particularly the `in any case` part; we have a sequential process for performing DB upgrades from one schema version to the next; in theory shouldn't a user who has deployed the first released version be able to still migrate someday to SPIRE 0.8 or later without special in-between processes? Was `in any case` absolute or just to re-iterating the "disabled migration" scenario?

**Comment by evan2645** [comment]
> Was in any case absolute or just to re-iterating the "disabled migration" scenario?

Sorry for the confusion - I meant that statement to be absolute. I know that we have the migration code to support it, however as a whole we only guarantee SPIRE compatibility +/- 1 version. Things like Node API changes, changes to agent behavior, changes to the server's local state storage and convention etc.

**Comment by evan2645** [comment]
@amoore877 and @mweissbacher how do we feel about this issue? Is it resolved now? The only outstanding thing is https://github.com/spiffe/spire/pull/1110 and I'm not clear on whether that is in scope for this issue or not... judging by the description, it doesn't seem to be.

Perhaps we should open an issue scoped just for providing migration dry run and mark this one as complete?

**Comment by mbyczkowski** [comment]
@evan2645 I'm ok with closing this issue and opening a new one to track the migration dry-run feature (and linking it to #1110) 👍

**Comment by amoore877** [comment]
Sounds good to me
