### ISSUE TITLE
Evaluate logging library, potentially abstract away logging choice

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#1087]
#137 brought on https://github.com/sirupsen/logrus as core logging library. However, logrus is not very performant compared to other options.
- http://hackemist.com/logbench/
- https://github.com/uber-go/zap#performance

As an infrastructure-level system, SPIRE should be optimized where possible for better performance and scalability; time spent in processing overhead things like sending logs and GC is wasted.

A more performant option should be used. A good first step may be to abstract away logging choice in the source code, so that future changes to the actual core logging library do not require refactoring most files in the repo.

**Comment by zmt** [comment]
FWIW, the logrus maintainers now recommend using something like zap as the logrus project is now in maintenance mode. See https://githubhelp.com/sirupsen/logrus.

**Comment by amoore877** [comment]
https://githubhelp.com/sirupsen/logrus
```
Logrus is in maintenance-mode. We will not be introducing new features. It's simply too hard to do in a way that won't break many people's projects, which is the last thing you want from your Logging library (again...).
...
I believe Logrus' biggest contribution is to have played a part in today's widespread use of structured logging in Golang. There doesn't seem to be a reason to do a major, breaking iteration into Logrus V2, since the fantastic Go community has built those independently. Many fantastic alternatives have sprung up. Logrus would look like those, had it been re-designed with what we know about structured logging in Go today. Check out, for example, Zerolog, Zap, and Apex.
```

Possibly this issue should be extended, or replaced with a new one, to use a logging library that is under active usage

**Comment by zmt** [comment]
> Possibly this issue should be extended, or replaced with a new one, to use a logging library that is under active usage

I think migration away from logrus is a giant project worthy of its own issue if there isn't one already.
