### ISSUE TITLE
refactor telemetry package to make label adding internal only

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#1118]
Sub-issue of #1106

Labels should not be optional, and it is tempting to developers to make optional / dynamic labeling in functions with exposed `label_adders` in the `common` telemetry package. Such functionality should instead be in an `internal` directory in the telemetry package, organized in a way to be accessible by the other telemetry functionality (ie, the pre-defined telemetry functions that return `CallCounter` objects).

Alternatively, not much is left in `label_adders` after #1085 (expected merge soon). We may want to remove such functionality entirely.

In the same way, we may want to make the `CallCounter``AddLabel` function unexported; perhaps construction of `CallCounters` can just include the labels? This may be a separate refactoring effort.

**Comment by azdagron** [comment]
This is less problematic now that we have a common way for RPCs to add labels to calls (instead of emitting metrics directly). Closing for now.
