### ISSUE TITLE
Support using multiple k8s clusters in Notifier "k8sbundle"

### ISSUE THREAD

**Issue by ryysud** [spiffe/spire#1119]
Considering a use case of managing multiple k8s clusters with one SPIRE Server, I think that it is useful to be able to push the trust bundle to a configmap of multiple k8s clusters in [Notifier "k8sbundle"](https://github.com/spiffe/spire/blob/master/doc/plugin_server_notifier_k8sbundle.md) .

**Comment by evan2645** [comment]
Thanks for filing this @ryysud!

The current notifier can use in cluster config, which I assume won't be possible in the event that multiple clusters are configured. In moving this issue forward, it would be useful if you could propose one or two suggestions on what the configuration might look like. Perhaps something similar to the k8s node attestor?

Backwards compatibility with the current config structure, simplicity, and consistency with other k8s plugins are some things to keep in mind

**Comment by ryysud** [comment]
> In moving this issue forward, it would be useful if you could propose one or two suggestions on what the configuration might look like. Perhaps something similar to the k8s node attestor?

Yes. I assumed the following configuration similar to the k8s node attestor.

case1: SPIRE Server is running **inside** of k8s cluster and pushes the trust domain to that k8s cluster.

```hcl
    Notifier "k8sbundle" {
        plugin_data {
            clusters = {
                {}
            }
        }
    }
```

case2: SPIRE Server is running **outside** of k8s cluster and pushes the trust domain to multiple k8s cluster.

```hcl
    Notifier "k8sbundle" {
        plugin_data {
            clusters = {
                {
                    namespace = "infra"
                    config_map = "agents"
                    config_map_key = "bootstrap.crt"
                    kube_config_file_path = "/path/to/cluster1-kubeconfig"
                }
                {
                    namespace = "infra"
                    config_map = "agents"
                    config_map_key = "bootstrap.crt"
                    kube_config_file_path = "/path/to/clustrer2-kubeconfig"
                }
            }
        }
    }
```

But, There is a problem that compatibility is broken...

**Comment by evan2645** [comment]
I've been thinking about this lately after someone reminded me of it. Supporting it would greatly ease nested SPIRE deployments in k8s, as well as deployments with a single SPIRE server cluster and multiple k8s clusters.

As for compatibility, I think we can get away by adding only the `clusters` field to the current config, such that the config can be supplied once (top-level) for the in-cluster config, and/or multiple times in the `clusters` field for other clusters. For example, cluster1 is the cluster that the server is in, and cluster2 is another cluster:
```hcl
    Notifier "k8sbundle" {
        plugin_data {
            namespace = "infra"
            config_map = "agents"
            config_map_key = "bootstrap.crt"
            kube_config_file_path = "/path/to/cluster1-kubeconfig"
            
            clusters = {
                {
                    namespace = "infra"
                    config_map = "agents"
                    config_map_key = "bootstrap.crt"
                    kube_config_file_path = "/path/to/clustrer2-kubeconfig"
                }
            }
        }
```

or, we do not update a local cluster at all, and cluster1 and cluster2 are remote:
```hcl
    Notifier "k8sbundle" {
        plugin_data {
            clusters = {
                {
                    namespace = "infra"
                    config_map = "agents"
                    config_map_key = "bootstrap.crt"
                    kube_config_file_path = "/path/to/cluster1-kubeconfig"
                }
                {
                    namespace = "infra"
                    config_map = "agents"
                    config_map_key = "bootstrap.crt"
                    kube_config_file_path = "/path/to/clustrer2-kubeconfig"
                }
            }
        }
    }
```
