### ISSUE TITLE
mock metrics vs fake metrics

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#1121]
Somewhat of an opinion-

A pattern that may be present in other areas of the code is that of mock metrics (such as in agent workload endpoint handler tests). This (or at least present usage of it) is a bit clunky to use as mocks have their own logic on throwing errors; an error saying "missing call to" or "unexpected call to" does not necessarily describe well what one is actually missing.
It is important to note that a `fakemetrics` structure already exists and is in use elsewhere.

Usage of `fakemetrics` does a simple output comparison of metrics, and it can be used in exactly the same way as a metrics object is used in source code. That is, one can create `CallCounters`, and also assign a `fakemetrics` object directly to tested structs. Direct comparison of results shows what is wrong, and usage is mostly about just getting the call orders correct.

Why not only have 1 way of testing metrics? Given gradual efforts of centralizing metrics keys/reporting/names, `fakemetrics` seems like the way to go.

**Comment by azdagron** [comment]
The unit tests have all been transitioned to use the fake metrics for some time now and the mock metrics package has been removed.
