### ISSUE TITLE
Consider deprecating the NodeResolver plugin

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#1127]
The NodeResolver plugin's goal in life is to collect/update node selectors. It was decided early on that this should be done in a dedicated plugin rather than part of the node attestation because we wanted to be able to periodically query for updates, keeping node selectors accurate over time.

Since that decision was made, we discovered that there are some selectors that can only be generated during the attestation process itself (as opposed to trying to discover them after the fact). This led to the extension of the NodeAttestor interface so that it can optionally return node selectors for the agent that has just attested.

The existence and purpose of the NodeResolver plugin has historically been a common point of confusion, and this is exacerbated now that node attestors can generate selectors too. Further, we require that node resolvers be paired 1:1 with node attestors, and their names must match because the resolver needs to know how to pull meaning out of a given agent's SPIFFE ID (which is a function of node attestation). Some of this pain can be felt in #847.

All of this is to say that the NodeResolver has not aged well. IMO we have an opportunity to deprecate it altogether, moving all resolver logic into their respective attestors. The original reasoning for keeping these two things separate doesn't quite hold any longer because 1) we never _actually_ implemented the poll-resolvers-for-updates feature (we only call the resolver once, during attestation), and 2) if we ever _did_ decide we wanted to add such a feature, it could be easily done by extending the NodeAttestor interface to include something like `ReResolve(spiffeID)`.

I've opened this issue to gather thoughts and feedback on the matter. I have heard of some custom node resolver use in the wild, but wonder if there is a better solution for those cases. I find it hard to argue that the current posture of the NodeResolver plugin is a positive one.

**Comment by ZymoticB** [comment]
Deprecating the NodeResolver would mean that any custom selector logic will now require a fork of each Attestor plugin that is used to add the custom behaviour. This could potentially lead to drift in a critical space w.r.t security as the upgrade story will no longer be straight forward.

**Comment by APTy** [comment]
Interesting thoughts. If we remove the idea of NodeResolver altogether, I wonder if there would still be some benefit in a Notifier-style plugin that is invoked post-NodeAttestator that implementors could use as a hook to add custom selectors, log, and/or do lookups to other internal systems if needed.

**Comment by evan2645** [comment]
> Deprecating the NodeResolver would mean that any custom selector logic will now require a fork of each Attestor plugin that is used to add the custom behaviour. This could potentially lead to drift in a critical space w.r.t security as the upgrade story will no longer be straight forward.

This is true, however it is also true in the current state if the custom logic is needed in addition to a built-in resolver's logic. To be clear, I see the need for being able to add node selectors as a result of custom logic, but the current NodeResolver approach seems far from ideal.

> Interesting thoughts. If we remove the idea of NodeResolver altogether, I wonder if there would still be some benefit in a Notifier-style plugin that is invoked post-NodeAttestator that implementors could use as a hook to add custom selectors, log, and/or do lookups to other internal systems if needed. (Kind of like a one-size-fits-all node resolver, rather than one NodeResolver per NodeAttestor)

Yes, I think it is worth exploring alternate options for generation of node selectors (whether they be builtin or custom) and that was my intent in opening this issue.

Further thought on the position of the NodeResolver, and some of the quirks and difficulties we deal with in today's model, leads me to form the belief that node resolution is tightly coupled to a platform... and hence, node attestation. For instance, the 1:1 requirement, and the requirement of passing a SPIFFE ID into a resolver, is effectively a state leak between the attestor and the resolver... the attestor is packing some sort of meaningful information into the SPIFFE ID, and the resolver extracts it for further use. When framed this way, the current positioning of the resolution logic definitely feels smelly.

Continuing on that line of thought, if the resolver requires some (platform-related) information from the attestor, then it would seem that the attestor is in a better spot to emit this information than the resolver is, and the removal of the resolver logic from the attestation process feels strange. Of course, as I mentioned in the original issue text, there continues to be selector information that is not available after-the-fact, so the need for attestors to generate selectors persists.

**Comment by azdagron** [comment]
With #2153 and the advent of the spire-plugin-sdk (currently in progress) we have an opportunity to do something here before 1.0. Don't want to rush anything of course but this is pretty good time for a transition.

**Comment by azdagron** [comment]
Done with #3272. Another issue will be opened to remove the deprecated plugin and interface in 1.5.0.
