### ISSUE TITLE
Improve docker workload attestor config

### ISSUE THREAD

**Issue by APTy** [spiffe/spire#1137]
### Problem Statement

Currently, in order to configure the docker workload attestor, users pass a `cgroup_prefix` and `cgroup_container_index`. For example, the following config allows spire agent to find a container id of `abcdef` out of a cgroup like `10:pids:/my.slice/foo-bar.service/abcdef`:

```
    WorkloadAttestor "docker" {
        plugin_data {
            cgroup_prefix = "/my.slice"
            cgroup_container_index=2
        }
    }
```

This poses a challenge in multi-tenant systems where different cgroup schemas may be used. For example, if you're looking for containers in the `/my.slice` namespace, you can no longer discover workloads in the default `/docker` namespace.

### Option 1

I propose extending the API to allow for multiple container id formats to be passed. Something like the following:

```
    WorkloadAttestor "docker" {
        plugin_data {
            container_id_cgroup_matcher = [
                "/my.slice/.*/(.*)",
                "/docker/(.*)"
            ]
        }
    }
```
This would allow getting a container id from both `10:pids:/my.slice/foo-bar.service/abcdef` _and_ `10:pids:/docker/abcdef`.

### Option 2
I don't really like putting a regex into the config, so we could alternatively just grow the current API, but IMO it lacks a certain clarity of intent:
```
    WorkloadAttestor "docker" {
        plugin_data {
            container_id_cgroup_matcher = [
                {
                    cgroup_prefix = "/my.slice",
                    cgroup_container_index = 2
                },
                {
                    cgroup_prefix = "/docker",
                    cgroup_container_index = 1
                }
            ]
        }
    }
```

**Comment by azdagron** [comment]
I like option 1. Instead of allowing full bore regex syntax there, we could do some sort of simplified grammar that fits the problem domain a little more tightly. Maybe something like:

`/my.slice/*/(*)` - each path segment is either `*` meaning any, `(*)` meaning this is the container id, other otherwise treated as a string literal.

The plugin could then convert that rigid syntax (or something like it) into a regexp for matching purposes.

**Comment by APTy** [comment]
I like the idea of constraining the grammar. What about something like:

```
symbols:
  *    - variable number of any character, except "/"
  <id> - container id, which must not include a "/"

examples:
  "/docker/<id>"
  "/my.slice/*/<id>/*"
```

Then we can do a simple find/replace for `<id>` -> `(.*)`. I figure it makes the config just that much more readable (and more obvious that it's not a straight regex).

**Comment by evan2645** [comment]
I haven't had a look at the docker APIs in a while... perhaps there is something there that can help us? For instance, if we can get the full cgroup membership information from the docker API then maybe we don't have to pick apart the group name (or rely on/hope that container id continues to be present in the future)

**Comment by ZymoticB** [comment]
> I haven't had a look at the docker APIs in a while... perhaps there is something there that can help us? For instance, if we can get the full cgroup membership information from the docker API then maybe we don't have to pick apart the group name (or rely on/hope that container id continues to be present in the future)

Took a peek, looks like yes we can list the containers but no we cannot then generate a cgroup name from that. The container type doesn't have the cgroup parent in it. This would prevent us from mapping the pid to the container ID.
