### ISSUE TITLE
"make functional" fails because the "runner" Docker container doesn't have Go installed, but build.sh expects Go to be installed

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#1141]
`make functional` fails during the "build" target when executing `build.sh setup` in the "runner" container. build.sh is failing during assignment of a variable which is expecting Go to be installed in the container, but it isn't installed yet.

`make functional` relevant output:
```
docker-compose exec runner bash -c 'mkdir -p /go/src/github.com/spiffe/spire/.data && cp -R /spire-orig/* /go/src/github.com/spiffe/spire'
docker-compose exec runner bash -c 'cd /go/src/github.com/spiffe/spire && ./build.sh setup'
make[1]: *** [build] Error 127
make: *** [functional] Error 2
```

It appears [this variable declaration](https://github.com/spiffe/spire/blob/4ae691a53547841f609175fa067cb0d7c0c707a4/build.sh#L16) is failing based on the output I observed from running the `go list` command interactively in the container:

```
root@runner:/go/src/github.com/spiffe/spire# go list ./cmd/... ./pkg/... ./support/...
bash: go: command not found
root@runner:/go/src/github.com/spiffe/spire# echo $?
127
```

[This command](https://github.com/spiffe/spire/blob/4ae691a53547841f609175fa067cb0d7c0c707a4/build.sh#L67) also appears to be problematic if Go is not installed in the container prior to executing build.sh.

* **Version**: 4ae691a53547841f609175fa067cb0d7c0c707a4
* **Platform**: Darwin turner-C02YT63VLVDQ 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
* **Subsystem**: Build scripts

**Comment by azdagron** [comment]
The functional tools (and this rule) have been removed by #1212.
