### ISSUE TITLE
Build a well documented sample to show how SPIRE-issued identities can access AWS resources

### ISSUE THREAD

**Issue by ajessup** [spiffe/spire#1144]
As SPIRE's federation bundle endpoint is compatible with OIDC Federation, it should be possible for Amazon Web Services to retrieve a SPIFFE trust bundle from the endpoint and use this to validate JWT-SVIDs and exchange them for an STS token.

This capability should be documented and demonstrated with a detailed tutorial.

**Comment by evan2645** [comment]
Done, available at https://spiffe.io/spire/try/oidc-federation-aws/
