### ISSUE TITLE
Upstream CA Plugin: AWS Certificate Manager

### ISSUE THREAD

**Issue by bcelenza** [spiffe/spire#1153]
* **Version**: All
* **Platform**: All
* **Subsystem**: Server

I'd like to propose adding a new Upstream CA plugin for integrating Spire Server with an [AWS Certificate Manager Private Certificate Authority](https://docs.aws.amazon.com/acm-pca/latest/userguide/PcaWelcome.html) (ACM-PCA).

The intent behind the proposal is to allow a user to store the root of trust within ACM-PCA, so that spire server never requires the private key of the CA. The integration would instead leverage ACM-PCA's [Issue Certificate API](https://docs.aws.amazon.com/acm-pca/latest/userguide/PcaIssueCert.html) to sign CSRs for Spire Server.

**Comment by evan2645** [comment]
Hello @bcelenza and thank you for opening this. An UpstreamCA plugin for ACM-PCA would absolutely be a welcome addition! I have heard of some folks poking around on this, but am not sure how much progress they made. When ACM-PCA was announced, using it as an UpstreamCA was my first thought :)

For anyone who would like to take a shot at it, you can find an example of how to write an UpstreamCA plugin here: https://github.com/spiffe/spire/blob/master/pkg/server/plugin/upstreamca/disk/disk.go

The plugin then gets hooked into the server's plugin catalog, here: https://github.com/spiffe/spire/blob/7313652bf7d48e2852a6196dcf4f00b248600a20/pkg/server/catalog/catalog.go#L86-L89

Happy to help further any way I can!

**Comment by bcelenza** [comment]
I’m happy to take it on. In fact I have a working version of it locally. 😊 I still need to validate a few scenarios and write unit tests. Expect to have it in the next week or so.

**Comment by evan2645** [comment]
Ooh, awesome! :-D very much looking forward to that, thank you @bcelenza!

**Comment by bcelenza** [comment]
Closing this since the PR has been merged. Opened https://github.com/spiffe/spire/issues/1183 for the root rotation story. Thanks all!
