### ISSUE TITLE
CI job for make/build.sh results discrepancy

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#1159]
Running the various setup `make` and `build.sh` commands against any arbitrary PR should result in no changes to proto files, go.mod / go.sum files, etc.
That is, if a PR is submitted, the author should already have run such commands and included the changes themselves into the PR.

Having a CI job to perform such a check (run all such commands and check `git status` for changes -> should be none) will ensure HEAD is never in an unstable state regarding auto-gen'd elements of the codebase.

**Comment by azdagron** [comment]
Thanks for bringing this up. We should fix this as part of #1155.
