### ISSUE TITLE
Refactor Plugin Catalog

### ISSUE THREAD

**Issue by walmav** [spiffe/spire#116]
- [x] Create Separate Plugin Catalog pkg
- [x] Create PluginCatalog Interface 
- [x] Create PluginCatalog Implementation
- [x] Mock All Plugin Interfaces and add tests
- [x] Refactor to use supported Plugins

**Comment by evan2645** [comment]
Resolved by https://github.com/spiffe/spire/pull/179 and https://github.com/spiffe/spire/pull/196
