### ISSUE TITLE
Use EC P-256 for X509 CA key

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#1167]
We currently use the P-384 curve for the X509 CA key. P-256 is considered stronger than RSA 2048 and therefore strong enough for our purposes.

Additionally, the JWT signing key already uses the P-256 curve. Switching to the same curve provides consistency.

**Comment by ryysud** [comment]
Did I fix this issue with https://github.com/spiffe/spire/pull/1468 ? Does the supported `ca_key_type` need to be changed from the current rsa-2048 or rsa-4096 or ec-p256 and ec-p384?
