### ISSUE TITLE
Curate release tarball contents

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#1180]
The release tarball ships with a bunch of configuration files. It can be confusing to know what to do with these files, if anything.

The release tarball should contain a single example configuration file and necessary supporting files instead of multiple configurations. The website and other supporting documentation/repos can have more elaborate configuration examples.

**Comment by azdagron** [comment]
Here is what currently gets included:

```
spire/LICENSE
spire/spire-server
spire/README.md
spire/spire-agent
spire/conf/agent/agent.conf
spire/conf/agent/dummy_agent_ssh_key
spire/conf/agent/dummy_agent_ssh_key-cert.pub
spire/conf/agent/ha-postgres.conf
spire/conf/agent/dummy_root_ca.crt
spire/conf/server/dummy_upstream_ca.crt
spire/conf/server/server.conf
spire/conf/server/server-mysql.conf
spire/conf/server/server-upstream-false.conf
spire/conf/server/server-postgres.conf
spire/conf/server/dummy_upstream_ca.key
spire/conf/server/ha-postgres.conf
spire/conf/server/dummy_ssh_cert_authority.pub
spire/conf/compose/ha-postgres.yml
```

The README.md is taken verbatim from the repository and is therefore mostly useless (broken links, github badges, etc.). As such, I think we should instead author a distinct README (maybe not even markdown) with a simple description of the files in the tarball.

I think we can trim this list down to: ```
spire/LICENSE
spire/spire-server
spire/README.md
spire/spire-agent
spire/conf/agent/agent.conf
spire/conf/agent/dummy_root_ca.crt
spire/conf/server/dummy_upstream_ca.crt
spire/conf/server/server.conf
spire/conf/server/dummy_upstream_ca.key
```

The benefit of including the dummy certificates is to provide a turn-key way to test out SPIRE without having to get into agent bootstrapping. Alternatively, we could provide a script that generates the example configuration (including the dummy CA) and then there would be reduced risk for people accidentally sharing a "hard-coded" dummy CA...

**Comment by drrt** [comment]
Hey folks, something came up recently that might best relate to this issue...

I'm working on a quick-start doc for SPIRE. I'd like it to not require the user to sudo or be root but the release tarballs re-write the included config files to place all SPIRE-managed files in /opt/spire. The config files as they exist in in the repo work file with ./. Any thoughts on how to support this?

The quickstart is here https://github.com/spiffe/spiffe.io/blob/docs-refactor/content/spire/try/quickstart.md

**Comment by azdagron** [comment]
I think this is already supported. Before the config is stuff into the tarball, "./" is replaced with "/opt/spire/".

That being said, the config files in the repo are intended for developer convenience and have been (ab)used for the release tarball. We plan to stop doing that.

The current thinkings are to have a  `release` directory with the contents of the release tarball other than the SPIRE binaries.

**Comment by azdagron** [comment]
I'm working on this right now, btw. I hope to have a PR up shortly.

**Comment by azdagron** [comment]
> I'd like it to not require the user to sudo or be root but the release tarballs re-write the included config files to place all SPIRE-managed files in /opt/spire.

@drrt, why not require root or sudo to install the tarball? SPIRE itself will need to run with sufficient privileges to write under /opt/spire. Either SPIRE runs as root, or something is going to have to determine the user account SPIRE is going to run under and do the proper mkdir+chown+chmod steps to ensure proper permissions for the data directory. Since that uid/gid can't be known beforehand, the tarball itself couldn't assert those permissions.

We have thought about not including any hard coded configuration, but rather an "install" script that takes a bunch of inputs and prepares directory, but thought it might be overkill.

**Comment by drrt** [comment]
@azdagron the quickstart specifically _doesn't_ require writing outside of your home directory, and the only attestation it does is to the same non-root UID as the agent.

**Comment by azdagron** [comment]
I misunderstood your comment, @drrt. I thought you were asking to for the tarball contents to default to writing to `/opt/spire`. Now I understand better.

**Comment by azdagron** [comment]
I'm all for simplifying the tarball contents to the bare minimum needed to quickly try SPIRE out. I'd rather keep the opinionated parts around how to install SPIRE elsewhere. With that in mind, I think we can have the tarball conf use CWD. I'd also like to make it explicit that the included configuration files are sample files only and certainly require deployment specific changes. Maybe root them under a `./samples` directory or something.
