### ISSUE TITLE
JWT-SVIDs do not act as expected when using Nested SPIRE

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#1190]
Nested SPIRE configurations are accomplished through the use of an `UpstreamCA "spire"` plugin. The UpstreamCA plugin deals with X.509 only, however, and JWT-SVIDs have no concept of key chaining.

The result is that each SPIRE cluster maintains its own JWT-SVID signing keys, meaning JWT-SVIDs cut by cluster A are valid only within cluster A. Instead, JWT-SVIDs should be valid regardless of what cluster minted or is validating them, so long as they're in the same trust domain.

Addressing this will probably involve the dissemination of either each cluster's public keys, or a shared set of private keys. The former provides better security properties but may also prove more challenging.

**Comment by hiyosi** [comment]
This issue seems to be the same when using other UpstreamCA plugins. Is my understanding correct?

**Comment by evan2645** [comment]
Yes @hiyosi that is correct

**Comment by evan2645** [comment]
## Desired Behavior
A JWT-SVID minted in a given trust domain should be valid for the entire trust domain, not just one corner of it. Further, any SPIRE Server cluster in a nested configuration may choose to expose a bundle endpoint for federation. Since this bundle endpoint represents the trust domain of the nested deployment (in its entirety), it is expected that federating with it will enable workloads to validate any JWT-SVID originating from that trust domain.

## Methodology
To accomplish this, it is necessary for all SPIRE Servers participating in a nested topology to have knowledge of the JWT-SVID signing keys of all other SPIRE Servers in the trust domain. This can be done by reporting new JWT-SVID public signing keys to upstream SPIRE Server clusters as they are prepared. Taking this route causes all JWT-SVID public signing keys in the nested topology to accumulate at the root cluster. Since downstream SPIRE Server clusters learn the trust domain bundle from their upstream cluster, this methodology will result in full propagation of all JWT-SVID public signing keys regardless of the complexity or depth of the nested topology.

It should be noted that, unlike X.509, the root cluster MUST be reachable in order to successfully rotate a signing key. This is because JWT lacks the chaining semantics that X.509 has. Where intermediate CA certificates can be managed and rotated without updating the root certificate(s), JWT signing keys must always appear in the root bundle regardless of whether or not the key belongs to a downstream cluster.

## Implementation Options
There are a number of ways that the above methodology may be implemented. Here we explore a few.

### UpstreamCA -> UpstreamAuthority
The UpstreamCA plugin is useful for allowing SPIRE to extend existing PKIs - it is also useful in the nested SPIRE case. Unfortunately, the plugin name and interface is fairly specific to X.509. In this option, we rename the plugin type and extend its interface to support more than just X.509.

The existing UpstreamCA "spire" plugin would then be updated to conform to this new interface, accepting JWT-SVID keys as they're prepared and pushing them to the upstream SPIRE Servers.

It is unclear what other use cases, if any, this option could help to support.

### Special Case the UpstreamCA "spire" Plugin
We can detect when nested SPIRE is in use because the UpstreamCA "spire" plugin will be loaded. This gives us an opportunity to do something a little different. Rather than munging the UpstreamCA plugin interface, SPIRE core can detect this condition and directly report new JWT-SVID signing keys upstream. The upside to this approach is we don't have to change UpstreamCA, but the downside is that the configuration could get ugly (since now both SPIRE core and the UpstreamCA plugin need upstream cluster details) and the maintenance overhead of special casing is non trivial.

### Move Away From UpstreamCA For Nested SPIRE Support
Deprecate the UpstreamCA "spire" plugin, and pull all of its logic into core. Allow core to manage upstream key publishing and CSR fulfillment directly by extending the CA manager logic.

One downside to this approach is increased complexity in the CA manager, which is a critical component. It will require code paths to send CSRs for intermediate CA certificates to either an UpstreamCA plugin or to nested SPIRE logic depending on the configuration.

### Disable JWT-SVIDs When Nested SPIRE is Detected
Another option is to simply not support JWT-SVID when using Nested SPIRE. JWT-SVID signing keys will not be generated, and all JWT-SVID related RPCs would return an error.

## Request for Comments
The methodology described here is likely not the only workable solution. Similarly, there are probably additional implementation options that were overlooked. What we would really like to know is:
* Does this methodology make sense? Or, is there a methodology that might make more sense?
* Which of the implementation options do you find most attractive?
* Are there any other options that you would like to see offered here?

**Comment by APTy** [comment]
To me, changing UpstreamCA to UpstreamAuthority, and updating the "spire" impl to allow the downstream authorities to push their keys upwards, makes a lot of sense.

Still, I wonder if there is an option to apply the federation concept: (1) downstream authorities publish their keys in a JWKS, (2) upstream authority keeps track of all downstream authorities, and (3) upstream authority periodically checks all downstream authority keys and updates the global bundle.

**Comment by evan2645** [comment]
This issue was discussed during today's maintainer call, and the consensus was to introduce an UpstreamAuthority plugin. This plugin will consume a new authenticated RPC for injecting JWKs upstream.

We'll begin creating issues for this work shortly, so if you have any insights/requests/feedback please be sure to share them before Thursday of this week.

**Comment by evan2645** [comment]
This was fixed in https://github.com/spiffe/spire/projects/5
