### ISSUE TITLE
Proposal: support env selectors in the docker workload attestor

### ISSUE THREAD

**Issue by ZymoticB** [spiffe/spire#1198]
In my deployment, we are currently using the docker workload attestor. We have a system which runs docker containers in our fleet and attaches label at launch time which has been effective for workload attestation.

Other workloads in our deployment are managed by mesos. Mesos has support for "labels" as well as docker containers, but the labels are not set on the container they are only available from the mesos slave API. Further to this, we have many different ways of creating a mesos job (aurora, a custom scheduler, multiple orchestration platforms on top of each) and they do not agree about the labels in mesos at all. Additionally, for legacy reasons some of those systems cannot currently be changed.

The lowest common denominator available happens to be a few environment variables that all of our workloads currently depend on, therefore all of these orchestration platforms ensure they are set correctly.

We propose adding support for a env selector to the docker workload attestor. These env variables are the *initial values* attached to the container when it is created in the docker daemon, it is not mutable by the workload. If we instead extended the unix attestor to get data from `/proc/[pid]/environ` then it *would* be mutable by the workload, therefore we think it is best to use the docker workload attestor for this, not the unix workload attestor.

This doesn't change the trust model of the docker attestor, it will increase the number of selectors the agent cache needs to deal with but this will depend on the environment.

**Comment by evan2645** [comment]
> These env variables are the initial values attached to the container when it is created in the docker daemon, it is not mutable by the workload. If we instead extended the unix attestor to get data from /proc/[pid]/environ then it would be mutable by the workload, therefore we think it is best to use the docker workload attestor for this, not the unix workload attestor.

I assume the value of these env vars are coming from the docker api as part of the container config...? If so, SGTM so long as they're the ones set at launch and are not updated afterwards. As you've observed, the unix attestor route won't fly.

Generally speaking, any trustworthy container attribute obtained from the docker api should be fair game

**Comment by ZymoticB** [comment]
```
diff --git a/pkg/agent/plugin/workloadattestor/docker/docker.go b/pkg/agent/plugin/workloadattestor/docker/docker.go
index 949f0bf5..d7697e6b 100644
--- a/pkg/agent/plugin/workloadattestor/docker/docker.go
+++ b/pkg/agent/plugin/workloadattestor/docker/docker.go
@@ -23,6 +23,7 @@ const (
        pluginName          = "docker"
        subselectorLabel    = "label"
        subselectorImageID  = "image_id"
+       subselectorImageID  = "env"
        defaultCgroupPrefix = "/docker"
 )

@@ -138,6 +139,12 @@ func getSelectorsFromConfig(cfg *container.Config) []*common.Selector {
                        Value: fmt.Sprintf("%s:%s:%s", subselectorLabel, label, value),
                })
        }
```

nice and easy :). My understanding is that these are what is set in the container config and they cannot be changed.

**Comment by evan2645** [comment]
Awesome. Probably wanna check our assumptions about the values being stable, otherwise SGTM!

**Comment by ZymoticB** [comment]
Looking at this more, this will be consuming env from the container config and I cannot see any way that is mutable at runtime. I think we're good to move forward with this.
