### ISSUE TITLE
audit logging registrations / bundles

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#1207]
It may be helpful to be able to configure a specific logging on SPIRE Server that is purely for CRUD operations on registrations and trust bundles. This could be at the Server endpoint layer, and for every such call of interest we log information such as caller (as able to determine from gRPC call), operation attempted (delete registration, update bundle...), details of operation (specific registration(s) looks for, selection filter criteria...), and success / failure status of the operation

Having such information in a separate log file, or at least with a very distinct log field (eg. "audit"), would greatly help by

- standardizing how such information is recorded
- allowing easier automated observation into such information
- allowing storing of this specific information as a longer-lasting archive than regular logs, for post-incident investigation

**Comment by amoore877** [comment]
node operations (agent eviction) should also be audited

**Comment by MarcosDY** [comment]
I think that adding a new field like `type=audit` will do the work,
Sample:
```
spire-server_1  | time="2021-03-01T13:36:29Z" level=info msg="Entry created" caller-addr="172.20.0.3:48894" caller-id="spiffe://domain.test/admin" entry_id=bbde054d-3ec6-417d-a37b-dbe36a29f0e0 method=BatchCreateEntry service=entry.v1.Entry spiffe_id="spiffe://domain.test/bar" subsystem_name=api type=audit
```
`caller-addr and caller-id are already in api v2, for calls done from outside.`
 
I think separating api logs (for CRUDs) into different logs will make things harder when configuring (and debuging), but with a field we can easily search for those logs.
Looking for CRUDs logs I figure out that not all RPCs has logs for success calls, and some are `debug` and others are `info`. We may make all fo them `info` and make sure to have logs for each CRUD.

About node operations are you suggesting adding adit to for Attest/Renew too?

`All changes I'm suggesting are  for api v2, because the old API is deprecated.`

**Comment by MarcosDY** [comment]
About `audit` field, in api v2 we have `service` (service=entry.v1.Entry), `subsystem`  (subsystem_name=api), and method (method=BatchCreateEntry) so with that it is possible to filter what we need without new fileld

**Comment by amoore877** [comment]
> I think separating api logs (for CRUDs) into different logs will make things harder when configuring (and debuging), but with a field we can easily search for those logs.
that seems more maintainable to me too

> About node operations are you suggesting adding adit to for Attest/Renew too?
I think that might be helpful. It's not what I was concerned about when writing this issue, but I could see others finding value in it.

> About audit field, in api v2 we have service (service=entry.v1.Entry), subsystem (subsystem_name=api), and method (method=BatchCreateEntry) so with that it is possible to filter what we need without new field.
That would require the operator to always keep or know a list of all service/subsystem/method combinations. There may be cases an operator first just wants to generally look at all auditable entries, and filter down from that on what looks interesting or applicable to a given situation. It would be much easier to do so based on a single field value vs. exhaustively listing all possibilities in a log query.

> but what we must log there? what request detail is relevant and we may log?
I think I want to be able to go back in log history and see exactly everything an admin has done.
This could be for multiple reasons:
- reaction to security incident
- we suspect a service or human messed up, and want to see what exactly they messed up
- anomaly detection of operations against the control plane, or investigation on the detection of an anomaly
The inputs to operations are definitely valuable, though the outputs may be too large to log effectively (for instance on ListRegistrations).

**Comment by MarcosDY** [comment]
Here is a summary of actual APIs that an admin can use to affect database.

**Agent API** (https://github.com/spiffe/spire/blob/master/proto/spire/api/server/agent/v1/agent.proto#L14)
```
DeleteAgent: DeleteAgentRequest{ SPIFFEID }
BanAgent: BanAgentRequest { SPIFFEID }
```

**BundleAPI** (https://github.com/spiffe/spire/blob/master/proto/spire/api/server/bundle/v1/bundle.proto#L8)
```
AppendBundle: AppendBundleRequest{
	repeated spire.types.X509Certificate x509_authorities = 1;
    repeated spire.types.JWTKey jwt_authorities = 2;
}
PublishJWTAuthority: PublishJWTAuthorityRequest { spire.types.JWTKey jwt_authority = 1; }
BatchCreateFederatedBundle: BatchCreateFederatedBundleRequest { repeated spire.types.Bundle bundle = 1; }
BatchUpdateFederatedBundle: BatchUpdateFederatedBundleRequest { repeated spire.types.Bundle bundle = 1; }
BatchSetFederatedBundle: BatchSetFederatedBundleRequest { repeated spire.types.Bundle bundle = 1; }
BatchDeleteFederatedBundle: BatchDeleteFederatedBundleRequest {
	enum Mode {
        RESTRICT = 0;
        DELETE = 1;
        DISSOCIATE = 2;
    }
    repeated string trust_domains = 1;
    Mode mode = 2;
}
```

**EntryAPI** (https://github.com/spiffe/spire/blob/master/proto/spire/api/server/entry/v1/entry.proto#L12)
```
BatchCreateEntry: BatchCreateEntryRequest { repeated spire.types.Entry entries = 1; }
BatchUpdateEntry: BatchUpdateEntryRequest { repeated spire.types.Entry entries = 1; }
BatchDeleteEntry: BatchDeleteEntryRequest { repeated string ids = 1; }
```

In case of Agent RPCs it is easy to provide ids that admin is calling. 
but once we get into Batch functions inputs will be large, for example if we have a batch that updates 1000 entries.
Same happens with bundle where admins can send certificates (that I think we must not send into log) and an ID that we may log.

I think we need consensus about what we really want to log from those requests, and I think that audit may be opcional (a user can set a bool on server config to log them or not) 

About "Get/List" functions do you think there is value adding audit? I think only operations that affect DB may have it.

**Comment by amoore877** [comment]
> In case of Agent RPCs it is easy to provide ids that admin is calling.

I think we want to make sure no matter the RPC, that we are logging who is calling.

> but once we get into Batch functions inputs will be large, for example if we have a batch that updates 1000 entries.

agreed. Batch becomes quite large for loggable results, even trimming to just entry UUIDs. If we want total audit capability though, those would be included. It's this level of detail that made me initially suggest a separate log for audit.

> Same happens with bundle where admins can send certificates (that I think we must not send into log)

What is the risk of logging certificates?

> About "Get/List" functions do you think there is value adding audit? I think only operations that affect DB may have it.

When I think of auditing I think of having full view into actions. However in the case of a malicious actor in SPIRE perhaps this detail is still not intensely helpful since all it would show is the actor's attempts to learn about registrations, how they might be identified/placed, etc. which isn't great to blindly expose but also isn't as critical of a problem as, say, exposing a private key.

**Comment by amoore877** [comment]
so here's a shot at more specific requirements-

As an auditor of SPIRE infrastructure, I should be able to discover the following information in SPIRE Server logs for API requests:
- as a dedicated field, identify the caller as able (SPIFFE ID, IP address, Unix effective user + group, binary path of calling process for Unix domain socket callers)
- log success or failure as a dedicated field; it may be sufficient to rely just on presence or absence of error field
- log the action taken as a dedicated field. prefer the full request, if the request does not contain potentially sensitive data (join token)
- Enough data to uniquely identify the affected records (i.e. item ID for create/update/read, unique attributes of record for delete)
- Affected fields with old vs. new data logged
- bonus points, a unique ID identifying the API event (e.g. UUID), and propagate this ID as able through the logs of this call.

**Comment by MarcosDY** [comment]
I'm start thinking like a separated log (or some tables, but not sure what community will think about adding more tables) will be the correct approach, 
audit logs will add too much noice and I'm worried about providing all request in some apis will result in very extensive log fields.

**Comment by esweiss** [comment]
This is a priority for us.

**Comment by MarcosDY** [comment]
Binary path will require us to specify `hostPID` on Kubernetes (similar we do on agent) we can make that optional, and only set it when that is allowed (it is something to discuss)

**Comment by MarcosDY** [comment]
To unify all ideas, and discuss al together I created a document, with different approaches we can take and things we must take care about. 

Any comment in this document will be appreciated!!!

https://docs.google.com/document/d/1A0z01oj3YmO-3i3J8dgUPNafTawUarFIqKudeqt_fCw/edit?usp=sharing

**Comment by MarcosDY** [comment]
if we add audit logs to all endpoints that changes an entity state, for example calling BanAgent on Agent service, 
may we add audit log events when endpoint fails? it is not really changing anything

**Comment by amoore877** [comment]
> may we add audit log events when endpoint fails? it is not really changing anything

An attempt was still made to perform some privileged action. While ideally any form of permissions check might occur as early in the call stack as possible, I think it is more maintainable to just always log attempt + result (and if failure, possibly failure reason) rather than not log failures or pick and choose failure types to audit.
