### ISSUE TITLE
Add standalone tool for database migration dry run

### ISSUE THREAD

**Issue by mweissbacher** [spiffe/spire#1218]
Currently migrations are automatic on startup unless configured to be disabled, the statements run are not available due to gorm. To support manual migrations it would be great to add a tool that provides the statements to be run. This tool would be run manually, the output can then be either run directly against the database or plugged into a database migration tool like gh-ost. Modifications to spire-proper should be limited to an export of functions from the datastore package. The standalone tool should reside in the support folder. This issue is related to https://github.com/spiffe/spire/issues/1083. I started work on this, will open a PR when ready.

**Comment by azdagron** [comment]
I think we're still open to having this kind of tool. However, it's been a few years a while and we've had no asks from the community for it. I'm going to close this for the time being.
