### ISSUE TITLE
Avoid need to create configuration directory for first time installation

### ISSUE THREAD

**Issue by ajessup** [spiffe/spire#1237]
An annoying, but common gotcha when installing SPIRE server for the first time is the need to create a directory for server data. By SPIRE expects this to be `/opt/spire/.data` which requires the user to create it, and on many systems requires root privileges to do so. It must be then created with sufficient privileges to be visible to whatever user then actually starts `spire-server`. While this is desirable for production deployments to facilitate upgrades and backups, for inexperienced users evaluating the tool for the first time it leads to a lot of chmodding and scratching before getting the satisfaction of actually seeing software run.

A related gotcha is that all paths in the `server.conf` file need to be complete filepaths, since if they are expressed as relative paths they are evaluated as relative to the _current working directory of the terminal_ rather than relative to the location of the binary or configuration file. This is probably not the expected behavior for most users.

This issues argues for three changes to improve this experience.

(1) Paths in configuration files should either be relative to the location of the configuration file itself, or to the path of the binary that is evaluating the file, not to the CWD the binary is executed from.

(2) Make the default path for `data_dir` to be `.data` within the spire directory itself, the sql datastore `connection_string` to be `.data/datastore.sqlite3`. The user who created this directory is likely to be the same user whom the `spire-server` binary is first run as.

(3) Detect and emit on startup a warning when the `data_dir` is under the same directory of the SPIRE installation itself, and that a user should consider specifying a common directory outside the SPIRE installation for production use.

Making these changes remove a whole set of tedious steps from early SPIRE evaluations - as it would mean that SPIRE server will automatically create an appropriate data directory, specific to that installation, and under the same user that the `spire-server` is first run as (which is likely ideal for most early evaluation scenarios).

* **Version**: 0.8.4
* **Platform**: Linux vagrant-ubuntu-trusty-64 3.13.0-112-generic #159-Ubuntu SMP Fri Mar 3 15:26:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**: Server

**Comment by azdagron** [comment]
SPIRE has created the data directory if it doesn't exist for quite some time.
