### ISSUE TITLE
MySQL read / write connection strings

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#1239]
To take advantage of read replicas, MySQL plugin should allow configuring a Read-only connection string.

- Write connection string is mandatory, and if no Read-only is set then the Write string is used for Read as well
- If Read is set, use for Read ops

**Comment by APTy** [comment]
Strawman config option for [plugin_server_datastore_sql](https://github.com/spiffe/spire/blob/master/doc/plugin_server_datastore_sql.md) proposed in bold:

| Configuration     | Description                                                                |
| ------------------| -------------------------------------------------------------------------- |
| database_type     | database type                                                              |
| connection_string | connection string                                                          |
| **ro_connection_string** | **read-only connection string, used for read-only queries if set**                                                         |

**Comment by evan2645** [comment]
> Strawman config option for plugin_server_datastore_sql proposed in bold:

👍 that looks about right!

There are some features in SPIRE that depend on datastore consistency for security - join tokens (race to use) come to mind, as does node attestor TOFU.

IME read replicas are usually async and can fall behind. We will probably need to revisit some security-sensitive spots to make sure that the guarantees remain the same if an async read replica is in use.

I think there is an assumption that the SPIRE dataset is 1) relatively small and 2) not very demanding. It leads me to wonder how much gain we can really make by supporting read replicas. Are there aspects beyond performance that drive folks in this direction? Curious to hear thoughts on this and the above

**Comment by kirutthika** [comment]
Thanks for the feedback above. The direction that led us to this change was the idea of having HA server clusters that connect to the database with high throughput, which could be benefitted by having read-only replica for some operations. As an example, AWS clusters support read-only replicas for high throughput workloads and we could benefit by having this change. Having said that, I agree with your point on concerns related to read-after-write consistency. In those cases, we can resort to reading from main DB, otherwise we should be having an option to spread out the load and read from one of the read replicas. If this sounds good, I could work on identifying operations that are not critical to have read-after-write consistency guarantees and have it rely on RO connection string with a fallback to default RW connection string.

**Comment by kirutthika** [comment]
On taking a look at the SPIRE codebase, operations such as ListBundles, ListAttestedNodes, ListRegistrationEntries can perhaps live with eventual consistency guarantees with the tradeoff for scalability while using read-only replicas. While there is currently no existing patterns for read-after-write for these operations yet, we could add documentation that states that these operations will be eventually consistent with the usage of read-only replicas. Thoughts around this proposal?

As for my other comment on falling back to readonly replica for primary operations, I think we could live with having this managed outside SPIRE for now.

**Comment by kirutthika** [comment]
@evan2645, would appreciate your thoughts on this.

**Comment by evan2645** [comment]
Hi @kirutthika - thanks for your patience here.

I discussed this on the SPIRE maintainers call today, and we think there's a lot to consider around the implications of allowing potentially stale reads that would probably need to be assessed on a case-by-case basis... so, limiting the number of cases that we introduce the behavior will probably ease the conversation quite a bit.

ListRegistrationEntries and GetNodeSelectors are two of the highest rate reads that we do, so we think it will make sense to start with just those two. What do you think?

**Comment by kirutthika** [comment]
Hi @evan2645 - thanks for coming back.

Agreed with your top two read operations of ListRegistrationEntries and GetNodeSelectors. We did a recent analysis in a cluster of 3 DB servers - with one primary write instance and 2 read replicas and the results look very promising. This will help consumers to improve the DB performance of read heavy operations by horizontally scaling the read instances.

<img width="683" alt="Screen Shot 2020-01-30 at 2 35 50 PM" src="https://user-images.githubusercontent.com/57149250/73496803-3d2c5300-436e-11ea-9870-e247993d5521.png">

**Comment by evan2645** [comment]
Done in https://github.com/spiffe/spire/pull/1363 , closing this out
