### ISSUE TITLE
agent request backoff

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#1241]
Related area as #1240 

On sync / fetch failure agent should gradually backoff requests. This avoids continuous doomed retries

**Comment by amoore877** [comment]
May want to take configured / remaining TTL into account for backup logic; ie, probably shouldn't back off past SVID expiration?

**Comment by APTy** [comment]
Good point on taking TTL into account. IMHO we should have a sane upper bound on the backoff of like a few minutes, in addition to the configured TTL.
