### ISSUE TITLE
tpm-based key manager

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#1242]
It would be nice to have a TPM-based key manager that Agent and Server could use, as an alternative to in-memory and disk-based.
Actual usage would obviously depend upon the deployment environment having access to TPMs or similar implementation

**Comment by zmt** [comment]
Some overlap server-side with HSM support: #525

**Comment by udf2457** [comment]
Honestly I'm surprised there's no PIV /  PKCS#11 support in SPIRE, let alone TPM support.  Would have thought it would be an obvious necessity to acheive hardware-backed node attestation and cert issuance ?

**Comment by bnevis-i** [comment]
Also be aware that there is a DevID provisioning tool that probably needs a bit of work before it can be made production-worthy.  https://github.com/HewlettPackard/devid-provisioning-tool
