### ISSUE TITLE
undocumented options in the k8s workload attestor

### ISSUE THREAD

**Issue by bobo333** [spiffe/spire#1245]
* **Version**: 0.8.3
* **Platform**: kubernetes
* **Subsystem**: agent

There are undocumented options in the k8s workload attestor. Specifically `max_poll_attempts` and `poll_retry_interval`. These are useful for dealing with pod deletion race conditions. As mentioned in https://github.com/spiffe/spire/issues/1230 and https://github.com/spiffe/spire/pull/1216

**Comment by evan2645** [comment]
Hey @bobo333 I left a small comment on your PR, please let me know what you think... thanks again!

**Comment by bobo333** [comment]
closed the PR as the new defaults cover my use case, thanks!
