### ISSUE TITLE
Agents should re-attest if its current SVID is invalid

### ISSUE THREAD

**Issue by APTy** [spiffe/spire#1257]
I couldn't find an existing issue for this, but I know I've talked about it with some people before. Currently, agent attestation logic is fairly simple:

1. If a cached SVID/key pair exists and is not expired, use it.
2. Else, do node attestation

As a result, the agent fails permanently in the case of a `spire-server agent evict`. The current mitigation is to manually delete the agent's `.data` dir and then restart it. The agent could be more robust and automatically re-attest in these cases.

**Comment by ZymoticB** [comment]
I intend to pick this up next week while everyone else is at kubecon :)

**Comment by evan2645** [comment]
Thoughts on how to detect this condition? The unauthenticated error code comes to mind but I think that we might use that in some other spots as well.

**Comment by ZymoticB** [comment]
The plan was permission denied on fetchx509svids

**Comment by evan2645** [comment]
Copy/pasting some chatter from #sig-integration-aws slack channel as fodder for thought:

> Jonathan Oddy:  Does anyone know why the iid node attestor rejects attestation if the IID has already been used to attest a node before? (https://github.com/spiffe/spire/blob/master/pkg/server/plugin/nodeattestor/aws/iid.go#L173-L179)
> 
> Evan Gilman:  IID (and all other methods in that family like GCP IIT etc) are all trust on first use because anything running on the host can fetch it... Without special non-SPIRE configuration, it poses a problem for deployments with multiple workloads on a single host as any of them can fetch the document and masquerade as the agent (thereby obtaining SVIDs for colocated workloads) (edited) 
> 
> With TOFU, the window is reduced to racing the agent, and at least you'll get to know if you lost
> 
> ...
> 
> Jonathan Oddy: In our particular case we're not really that worried about other workloads masquerading as the agent, so perhaps the quick fix is a config option to disable that guard. (On a related note, we've also been tempted to add a noop workload attestor that'll attest any workload on a given host with a fixed selector)
> 
> These nodes all run a single workload and nothing else, so we aren't worried if anything on the node can attest as that node
> 
> Evan Gilman: Thinking further on this one... I guess another concern of allowing re-attestation using an IID is that it could become possible for someone to exfiltrate the IID and use it to obtain agent credentials (similar to capital one, via SSRF or otherwise). When coupled with the issue 1257, it gets worse because the "good" agent would simply think that it was evicted and proceed to re-attest, allowing the attacker to renew the agent credentials in perpetuity and weakening the signal that would otherwise be thrown off by the agent that got booted offline.

I think the key insight here is that the agent being denied access to FetchX509SVID could be relied upon as an indicator of compromise. If an attestor is TOFU, then you should still get a signal because the agent will fail to re-attest also... but the signal could be lost if the attestation method is repeatable.

**Comment by APTy** [comment]
I don't think disabling TOFU is the right way to go. If an agent has been offline long enough that its SVID expires, that is (1) probably not a supported use case, and (2) should require operator intervention to fix. That said, if there are problems in SPIRE that prevent an agent from maintaining high uptime, those should be fixed at the source.

The main point here is that if an operator wants //does// want to fix this issue, it should be relatively easy. Running `agent evict <spiffe-id>` should be enough to induce the agent to re-attest.

**Comment by JonathanO** [comment]
Hi,
I think maybe the comments from me are unrelated to this bug, and should be in another issue.
I think there are three separate issues covered in Slack conversations:
* An evicted agent does not re-attest (this issue)
* An agent with an expired SVID does not re-attest until it is restarted (probably a bug?)
* If one of the node attestors with TOFU is in use a manual evict is required if an agent's SVID expires (the more contentious issue, with some discussion required)

**Comment by rturner3** [comment]
This appears to be resolved by #1710 and #2065, and also appears to be a partial duplicate of #2061.

@APTy Can we close this issue?
