### ISSUE TITLE
Feature Request: IP restricted agents

### ISSUE THREAD

**Issue by mcpherrinm** [spiffe/spire#1273]
# IP Restricted Agents
## Background
The SPIRE server has pluggable attestations for nodes.  The attestation plugin in the server receives data sent from the spire agent, but does not easily have access to the network context of an incoming request.

## Ideas for how this could work
Some rough ideas for things that could be done here.

1. Restrict join tokens to an IP range.  Eg, `spire-server token generate --spiffeID spiffe://example.org/agent1 --ip 10.0.100.0/24`.
Since join tokens and the above CLI are already implemented as a special-case in the server, it could be expanded to support IP restricted join tokens without touching other methods of agent attestation.

2. Provide node attestation plugins with an API for network location and to add restrictions to the registered agent.  That would imply two additions to the node attestor protos:
 a. spire.agent.nodeattestor.AttestRequest includes the network address that the incoming request is from
 b. spire.agent.nodeattestor.AttestResponse includes range(s) of network addresses the agent may use.  The SPIRE server would then enforce these ranges for any authenticated calls from the agent in the future.

3. Some sort of additional configuration, policy language, or plugin interface to control network access control.  By providing a mechanism orthogonal of the node attestors, they can be used independently of them, however, that may remove some interesting possibilities (such as a plugin uses signed metadata which contains the node's IP address).

## Security Benefits
One of the goals of SPIRE is of course, zero-trust networking.  In some ways, this feels like it's not quite in tune with that, however, I feel it's still an effective defense-in-depth mechanism given that modern networks, especially in datacenter and cloud environments, do have relatively difficult to overcome network controls.

One potential attack this may help mitigate is a host-level compromise where an agent's SVID is exfiltrated.  A shared SPIRE server may be reachable from multiple networks (for example, if it's used for both datacenter workloads as well as workloads located remotely on the internet).  By restricting which subnets an agent may communicate to the server from, we can effectively ensure the internet-facing side of the SPIRE server is not abused to use exfiltrated agent SVIDs.

Another potential use is to mitigate theft of join tokens which are sent through intermediate systems (such as a host imaging configuration management system).  By preventing those systems from using the tokens directly (via these network restrictions), an attacker is required to take additional steps to abuse those tokens.

**Comment by mcpherrinm** [comment]
Though I specified layer 3 (IP address) restrictions,  if SPIRE is used on the same subnet as its agents, layer 2 restrictions (MAC address) may be interesting as well, though those are often easier to spoof.

**Comment by hiyosi** [comment]
We're interested in this feature. Have you discussed this issue ?
