### ISSUE TITLE
Configuration validator option?

### ISSUE THREAD

**Issue by mcpherrinm** [spiffe/spire#1280]
We have our server and agent configs checked into git, and we'd like a way to validate they seem sensible at CI time.  It would be good to have a flag for spire-server and spire-agent that loads and validates the configuration in a way we can use in CI (ie, shouldn't require the DB, upstream CA, or make network connections)

At least I'd like to know:
 - Does it parse?
 - Are all the configuration options known?
 - Are any of them deprecated?

This came up due to a typo when I moved to default_svid_ttl from svid_ttl.

**Comment by evan2645** [comment]
Related to https://github.com/spiffe/spire/issues/1101

**Comment by ryysud** [comment]
I will fix this issue.

What do you think of the following specifications? Please give feedback.

- Add `-dry-run` flag (type: bool, default: false) to` spire-server run` and `spire-agent run` subcommands
  - [Question] If `-dry-run` is not good, `-check` , `-validateConfig` and other name?
- If `-dry-run` is true, print a message after executing [newServerConfig (...)](https://github.com/spiffe/spire/blob/546ed8c4f6161a03da1342dca6a0b979c4a101f9/cmd/spire-server/cli/run/run.go#L158-L162) and exit
  - e.g.
    - If the validation is OK, print a success message and exit 0
    - If the validation is NG, print a failure message and exit 1
  - [Question] Is it better not to print a message?

**Comment by evan2645** [comment]
>Add -dry-run flag (type: bool, default: false) to spire-server run and spire-agent run subcommands
[Question] If -dry-run is not good, -check , -validateConfig and other name?

Validation feels like an independent "mode" of the CLI tool, so IMO it feels natural to have it as a standalone command e.g. `spire-server validate` or something similar

>[Question] Is it better not to print a message?

I'm actually not sure on this one... I think @mcpherrinm might have an opinion though since he's the one that bumped into this. Certainly, failure should exit non-zero. Another question probably is stderr vs stdout.

**Comment by ryysud** [comment]
Thanks for the quick feedback.

> so IMO it feels natural to have it as a standalone command e.g. spire-server validate or something similar

I also feel that providing this feature as a standalone command is natural.

> I think @mcpherrinm might have an opinion though since he's the one that bumped into this.

OK. I wait for his opinion.

**Comment by ryysud** [comment]
@mcpherrinm I would like to hear your opinion on this issue.

**Comment by mcpherrinm** [comment]
I am fine with any of the options discussed.

`spire-server validate -config file.conf` seems natural to me.

**Comment by ryysud** [comment]
Thanks for the quick reply.

>  but a -dry-run flag to run would be fine too (and may have a more straightforward implementation, if it just adds an early-return in Run()

I think so. But `spire-server validate` seems natural to me,
So I will implement it as an independent "mode" of the CLI tool and create a PR.

**Comment by ryysud** [comment]
Since I implemented `spire-server validate` and `spire-agent validate` commands, Is this issue closed?

**Comment by evan2645** [comment]
Yes!! Thanks @ryysud it's great to see this get in! I've been asked a few times about it

Closing this out now
