### ISSUE TITLE
upsert/put API for registration entries

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#1301]
Proposing a new API for registration entries:
- If given entry (by key) does not already exist, insert as per `Create`
- If given entry does exist, update as per `Update`

Use cases:
- a registrant periodically wants to just make sure its registrations exist, would rather just make a single API call that handles read/create/update all in one go, rather than separate Read (or `AlreadyExists`-returning Create) followed by Insert/Update call
- a registrant wants to make sure its most up-to-date versions of registrations exist, would rather just make a single API call
- a registrant taking advantage of the `EntryExpiry` field wants to periodically refresh this expiry time, such that
-- the registrant does not have to do separate read/update as above, on some strict cadence such that entries (and thus the resulting SVIDs) do not get too close to expiration
-- and the registrant does not necessarily have to be relied upon to delete old registrations, it will simply stop updating the `EntryExpiry` and in the worst case the automatic registration pruning logic will take care of this

**Comment by amoore877** [comment]
A `RenewEntry` API could also be viable, but Upsert/Put would be a superset of this functionality

**Comment by evan2645** [comment]
A new set of APIs for SPIRE Server is currently in the works, so this could be addressed as part of that work. I think it makes sense, but I wonder about entry ID.

Currently, consumers "can't" provide a custom entry ID when creating a new one. SPIRE generates its own and overwrites whatever was supplied. Overall, I think that's probably the behavior we want? What does that mean for this operation?

**Comment by evan2645** [comment]
@amoore877 would something like this suffice? It won't alter an existing entry, but it will suppress an error in that event as well as return the existing entry (along with its ID) https://github.com/spiffe/spire/pull/1464

**Comment by amoore877** [comment]
#1464 is definitely a big step forward with this
I can understand not having a blanket `upsert` API, since it may add unneeded complexity.
However I think a `renew` API would be beneficial still, considering the `EntryExpiry` field. Today if a registrant sets some entry with expiration and wants to update it, they have to:
- know the entry ID (or query with a fetch to get it) and call `UpdateRegistration`, which is a more dangerous API than needed if just wanting to update the expiration.
- OR delete the entry and start fresh (on error the entry is gone; the opposite intent)
- OR wait for pruning and re-create (but SVIDs from it will have less and less TTL, ping-ponging at the end with renewal requests)

Perhaps having to know the Entry ID is a separate problem, but I would like to see a more trimmed down `Update` API that just gets sent the new TTL and updates it. Existing `Update` call:
- leaves too much open to be messed up by caller for a simple need. expiration is not an "identifying" part of the registration, if that makes sense, but rather a meta/management attribute. being able to update just that without risk of breaking the registration would be helpful.
- has a far larger request definition than needed (minor network load concern)

**Comment by azdagron** [comment]
The API refactor (in progress) update API allows for updating an individual field on the entry via an input mask.

You still need to know the entry ID, but I don't see a way around that considering that is the "primary key".

Will that be sufficient?

**Comment by amoore877** [comment]
I think that sounds good. The caller will just have to know the ID, which they should if they are the ones that made it or can query for it on startup.
Further enhancement would be something like deterministic entry IDs as in #1008, but that's it's own issue.

**Comment by azdagron** [comment]
Yeah, we've discussed pros and cons of allowing callers to "choose" their entry ID at time of creation to help with some of this but haven't landed at a spot where everybody is comfortable with it yet.

**Comment by amoore877** [comment]
To me, this issue can be closed.
