### ISSUE TITLE
Wire up benchmarks into CI/CD

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#1302]
We have a few benchmark tests in the codebase. It would be nice to have CI/CD run them and report abnormal changes (using [benchstat](https://godoc.org/golang.org/x/perf/cmd/benchstat) or something).

**Comment by evan2645** [comment]
>It would be nice to have CI/CD run them and report abnormal changes
Will the results be stable in case we have noisy neighbor or similar performance volatility in our CI/CD pipeline?
