### ISSUE TITLE
feature request: spire-agent join token from environment variable or file

### ISSUE THREAD

**Issue by mcpherrinm** [spiffe/spire#1303]
Spire Agent current accepts join tokens on the command line, via the -joinToken flag.

It would be good if it could accept a file argument instead.  Join tokens are relatively sensitive (even if they are 1-time-use) so it would help me sleep better at night if they weren't getting into process command line logs and/or being shown to other processes in the same process namespace.

It also allows join tokens to be placed in a secrets management system or host imaging system which supports exposing secrets as files or environment variables.

If file support is added, env var support is trivially added via a wrapper script.

**Comment by mcpherrinm** [comment]
Maybe the most versatile thing here is way to provide any agent config as environment variable, and then merge it in, similar to what's done with merging defaults, config file, and command line arguments today.

**Comment by ryysud** [comment]
I will fix this issue.

What do you think of the following specifications? Please give feedback.

- Add `-joinTokenFile` flag (type: string, default: empty string) to `spire-agent run` subcommand to accept a file
- Add `-envJoinToken` flag (type: bool, default: false) to `spire-agent run` subcommand to accept environment variables
  - If `-envJoinToken` is true, read a join token from `SPIRE_JOIN_TOKEN` environment variable
- User can only choose one from `-joinToken`, `-joinTokenFile` and `-envJoinToken`

**Comment by evan2645** [comment]
>If file support is added, env var support is trivially added via a wrapper script.

I believe that join token is currently configurable via agent config file option `join_token`

>Add -joinTokenFile flag (type: string, default: empty string) to spire-agent run subcommand to accept a file

I think this sounds pretty reasonable! does it trim newlines and/or spaces in the file?

>Add -envJoinToken flag (type: bool, default: false) to spire-agent run subcommand to accept environment variables
If -envJoinToken is true, read a join token from SPIRE_JOIN_TOKEN environment variable

This also sounds OK to me. Most projects I've seen declare static env var names like this, and making it configurable feels a little overkill.

>User can only choose one from -joinToken, -joinTokenFile and -envJoinToken

Yes I think these things should be mutually exclusive

I'll again defer to @mcpherrinm as to whether the above is enough to solve it for him

**Comment by ryysud** [comment]
Thanks for the quick feedback.

> does it trim newlines and/or spaces in the file?

I have not thought about it. But I think the trimming feature is very useful.

> I'll again defer to @mcpherrinm as to whether the above is enough to solve it for him

OK. I wait for his opinion.

**Comment by mcpherrinm** [comment]
I think a more generic feature could be used here, since the join token could be specified in the configuration: https://github.com/spiffe/spire/pull/1453

**Comment by mcpherrinm** [comment]
I think #1453 supports this.

For supporting tokens from a file, something like this can be done:

```
AGENT_JOIN_TOKEN=$(cat file)
spire-agent -expandEnv ....
```
