### ISSUE TITLE
Registration API should validate selectors

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#1314]
Selectors are mostly free form. However, the presence of a colon (`:`) in the type field is a pretty good indication of a misconfiguration since the type field is usually set to the plugin that sources the selector (by convention).

This would prevent accidental misconfigurations like:
```
type="unix:user" value="root"
```

Whereas the unix selector produces:
```
type="unix" value"user:root"
```

**Comment by ryysud** [comment]
@azdagron 
I created a PR (https://github.com/spiffe/spire/pull/1919) to validate that the Type in selector contains a colon.
If the PR looks good, I will make it ready-for-review.

**Comment by ryysud** [comment]
I have made the PR ready-for-review.
