### ISSUE TITLE
Add metadata/labels/attributes in registration entry

### ISSUE THREAD

**Issue by rbkumar88** [spiffe/spire#1336]
Would be nice to have some key/value metadata for each registration entry which is visible when listing later (and support in cli too).

**Comment by evan2645** [comment]
Thank you for opening this @rbkumar88 

Could you help me understand some use cases for this? How do you envision it being useful? Would the metadata be used for anything beyond administrative annotation?

**Comment by rbkumar88** [comment]
@evan2645  I could see these attributes being used to filter/group the registration entries for a particular group/org/application within a company or any other way we want to group/query on the registration entries.

**Comment by rturner3** [comment]
@rbkumar88 Would the new [hint](https://github.com/spiffe/spiffe/blob/1b1c383c3ec4757f320ed63f842de136d65ae98f/standards/workloadapi.proto#L78-L82) property that can be associated to an SVID potentially meet the use case you had in mind? Presumably once that field is added to SPIRE, it will somehow need to be associated to registration entries.

**Comment by azdagron** [comment]
This should be more or less be covered by #2588, which adds the hint field.
