### ISSUE TITLE
spire agent log message not clear when spire-server service name is missconfigured

### ISSUE THREAD

**Issue by vbotez** [spiffe/spire#1339]
* **Version**: a211e075c1f44026efdeb89e9a9081e1898d5214
* **Platform**: kubernetes cluster
* **Subsystem**: agent

spire-agents restarting with`level=error msg="agent crashed" error="opening stream for attestation: rpc error: code = Canceled desc = context canceled"`

This was due to having miss-configured the spire-server service name in my spire-agent config.

Log message is not clear with regards to issue. Maybe this could be improved.

**Comment by evan2645** [comment]
To add a little more detail here, I think that this message is the result of the agent being unable to reach the server (in this case because of a misconfiguration). It is not clear from reading the logged error that this is any kind of timeout trying to reach the server.
