### ISSUE TITLE
Reduce data transmission in Agent FetchX509SVID sync with Server

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#1361]
There are several opportunities to optimize the FetchX509SVID sync operation that the SPIRE Agent regularly performs to update its registration entry cache and request SVIDs. I've attached a document below which examines data transmission rates between SPIRE Agent and SPIRE Server for the FetchX509SVID RPC and proposes possible solutions for optimizing the existing Agent -> Server synchronization process.

I'd appreciate feedback on the proposals. After the document is reviewed, I can create separate issues for any specific proposals which we might want to realize.

[Reducing Data Transmission in Agent FetchX509SVID Sync.pdf](https://github.com/spiffe/spire/files/4136183/Reducing.Data.Transmission.in.Agent.FetchX509SVID.Sync.pdf)

**Comment by azdagron** [comment]
Nice report, @rturner3! Thanks for putting in the time to prepare this!

Relatedly, there has been some recent work to reduce database load for FetchX509SVID
- #1350 (cache bundles in the node handler)
- #1355 (prepare statements for optimized queries)
Still awaiting review:
- #1357 (reduces the number of database queries)

The bandwidth requirements for FetchX509SVID at-scale surprised me. I do have a local commit prepared but not yet a PR which elides node registration entries from the response to the agent that would help both in terms of # of entries in each response and # of SVID signing requests from agents. However, we aren't sure if we want to take something like that yet.

In terms of the options you laid out:
- Option 1: This has already been added as an experimental feature. I'm interested to know what real world impact that is having for those who are using it.
- Option 2: This seems like a significant increase in complexity around sync management. I'd be hesitant to use this option, except as a last resort.
- Option 3: I think there is probably potential here. Certainly not all fields in the registration entry would be useful to the agent and could potentially be culled. We're currently going through a design phase for a server API refactor and this is an excellent consideration.
- Option 4: From what I can tell this is mostly just Option 1 with the added benefit of being able to reduce entry churn responsiveness without impacting rotation responsiveness?

**Comment by rturner3** [comment]
Glad to hear we're already taking steps to improve the database queries! Thanks for the efforts there, @azdagron !

> * Option 1: This has already been added as an experimental feature. I'm interested to know what real world impact that is having for those who are using it.

I'm hoping to experiment with the Agent sync interval configuration soon. On paper, this should be a significant improvement if the sync interval is bumped up at least 2x+.

> * Option 2: This seems like a significant increase in complexity around sync management. I'd be hesitant to use this option, except as a last resort.

I agree. Syncing just the deltas would lead to a greater chance that the Agent misses some data from the Server due to clock skew. Even if you rely on Server timestamps, if you're operating the Server in an HA deployment, Server clocks have the possibility of being out of sync with each other. You can intentionally account for some degree of clock skew in the implementation, but it's still not perfect.

> * Option 4: From what I can tell this is mostly just Option 1 with the added benefit of being able to reduce entry churn responsiveness without impacting rotation responsiveness?

Correct. Given that SVID TTLs are configurable, it may also be useful to provide corresponding configuration in the Agent to sync on some cadence which is based on minimum expected SVID TTL values.

Another idea, which it appears might be already considered in #1057, is to separate the operations of fetching registration entries from sending CSRs into separate RPCs altogether. FetchX509SVID feels a bit overloaded today and has quite different operative modes based on request parameters.

**Comment by evan2645** [comment]
As we work on #1057, we consider adding a mask to API requests which allows the caller to specify the fields they are interested in. This should help to cut down on the size of the response, but I'm not sure if it is "enough"

One interesting thing that @azdagron pointed out to me is that the agent doesn't technically need the dns information, however it uses it to notice changes that indicate that it should re-request related SVIDs (see https://github.com/spiffe/spire/issues/1425 for more information). We may be in need of a more formal solution for detecting these kinds of conditions, such as the addition of a `generation` attribute.

On option number 1 (and by extension number 4), IMO tradeoff between propagation delay and network consumption is one I'd prefer not to make. If the addition of something like `generation` is palatable, I'd much prefer to see that.

**Comment by azdagron** [comment]
The new API surface (under development) provides a way for callers to filter out which information is returned in registration entries. The agent can leverage this to only ask for things it needs, while relying on the newly introduced `generation` field to know when an entry has changed.

**Comment by azdagron** [comment]
This has been fixed in #1786.

**Comment by rturner3** [comment]
It looks like this fix was accidentally dropped before the 0.11.0 release in this commit: https://github.com/spiffe/spire/commit/373868ed66fbcec0825be3f665dd22c150937b15
