### ISSUE TITLE
Support environment variable expansion within configuration files.

### ISSUE THREAD

**Issue by joshua-rutherford** [spiffe/spire#1364]
* **Version**: NONE
* **Platform**: ALL
* **Subsystem**: SERVER, AGENT, PLUGIN

At present, it seems I need to provide sensitive information (e.g., database passwords) within my configuration files.  I want my environment under configuration control and that is a bit problematic in a Kubernetes environment when using the instructions provided.  If I used a ConfigMap as described, I would have the ConfigMap in plain text in my repository.  

I can use a Secret instead and then something like Kubeseal to encrypt the value before checking it into my repository but then I have a bunch of much less sensitive information controlled within a secret and so changing something trivial (i.e., log level) requires I grab the decrypted secret from Kubernetes, decode the config file, make my change, re-encode the config file, re-encrypt the config file and push.

It seems to me that a much more robust solution would be to support environment variable expansion within the configuration file.  Almost all Hashicorp products using HCL support this in one form or another so it is a thing.

I think there are a few approaches that would work (in order of simplicity):

1. Simply perform variable expansion on the configuration file before actually parsing.
2. Provide an interpolation syntax that is processed after parsing (e.g., `"${env SECRET}"`)

**Comment by joshua-rutherford** [comment]
A quick dine in packer’s source shows they just assume the file is. A go template, and render it before reading.  I’ll spike this if you’d like, but would want to know if you think it could be considered a breaking change and therefore should include a cli flag to render, otherwise just read as a regular config?

**Comment by mcpherrinm** [comment]
FWIW, my team has a tool we use to render templated JSON into the final one we feed to SPIRE to solve this.

First-class support would be nice to avoid needing to write out the evaluated config in a separate process.

**Comment by joshua-rutherford** [comment]
Yeah, I realize there is an easy win via an init container or repackaging with a custom entry point script but this could be pretty clean and I think #1366 gets us largely there.

**Comment by azdagron** [comment]
I have a few concerns with a Go template based approach in general:
1) I don't know that we need or want the full power of templating. It seems that there are already many existing tools for munging configuration. Unless we can come up with some additional use cases, it seems like overkill just to support ingesting config from the environment.
2) There are already existing (albeit undocumented) configurables that take Go template values (e.g. `agent_path_template` in the sshpop, x509pop. aws_iid, gcp_iit plugins). Those existing values would need to be escaped in order to not be processed by the code introduced in this PR. It would be difficult to roll this out with backwards compatibility.

In the absence of other practical use cases that would merit the flexibility and complexity introduced by full templating, I think I'd personally rather see a more targeted approach (.e.g. expanding ${} patterns in string values).

**Comment by joshua-rutherford** [comment]
Given you already "support" templating in specific variables, would targeting other values be a reasonable approach.  I'm really mostly concerned about database connection information at this point.

**Comment by evan2645** [comment]
>FWIW, my team has a tool we use to render templated JSON into the final one we feed to SPIRE to solve this.

@mcpherrinm For secrets exclusively? Or for other non-secret things too? In plugins only or also in core config? It would be useful to know a little more about your use

>I have a few concerns with a Go template based approach in general:
I share these concerns. It would be nice if the use was targeted - for instance, AWS has standardized environment variable names for its API client secrets, and their SDKs all use them be default if set (as does SPIRE by extension). Similarly, MySQL has a standardized environment variable name for passwords. Whether or not something like this would satisfy the use cases is why I ask the question above.

If there are strong opinions that the config file in its entirety should be templatized, I think @azdagron's suggestion of expanding `${}` string values (or something similar) is the safest approach. I do have to admit though that, personally, it doesn't feel great write in (and support/maintain) new features for things that are already well solved by other tools/utilities.

**Comment by joshua-rutherford** [comment]
I don’t have @mcpherrinm’s tool but have plenty of entry point scripts in bash and ruby that handle this.  I think I’ll just build a stand alone container for this if there is not a lot of interest.  I’m not a fan of init containers if avoidable but the truth is we already have to use one for the agents so it’s not that big a step for the server too.

**Comment by mcpherrinm** [comment]
Our config interpolation script replaces all values which differ by environment and region.  Currently those values are:

1. Database Configuration:  Username, Hostname, DB Name
mysql client_cert_path & client_key_path or password (mTLS in DC, password for RDS in AWS)

2. trust_domain and ca_subject

3. Upstream CA configuration values; we use an internal upstream CA currently which requires specifying what HSM cluster and which key/cert to use.

**Comment by joshua-rutherford** [comment]
For what it's worth, I went ahead and implemented a simple command line utility to do this so I can standardize how we do this across all things we deploy and manage.  Open sourced it too incase anyone wants a non-SPIRE specific solution.  https://github.com/greymatter-io/templar

**Comment by mcpherrinm** [comment]
Environment variable interpolation is now supported in SPIRE via #1453
