### ISSUE TITLE
Add SPIRE Server Node API RPC to inject JWKs into the bundle from Downstream servers

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#1372]
As downstream SPIRE Servers generate new JWKs to be used for signing JWT-SVIDs, they need to be communicated upstream so that the public keys can be present in the bundle of all other SPIRE Servers. Since all nested SPIRE Servers inherit their bundle from the root SPIRE Servers, by pushing new JWKs upstream we can ensure that they propagate downwards throughout the entire topology.

We will need a new RPC on the SPIRE Server Node API in order to do this. Only identities which can be authenticated as "downstream" identities should be allowed to call it.

One catch to this is that the new JWK needs to reach the root SPIRE Servers. This means that if there are more than two levels in the nested topology, then the key needs to be passed upwards (rather than stored in the local bundle). So, if a SPIRE Server receives a JWK via this RPC, it needs to first check whether or not it itself has an UpstreamAuthority configured. If it does, then we need to pass the JWK to it, and pass its response back to our caller. If it _doesn't_ have an UpstreamAuthority configured, then this is a root SPIRE Server, and we should instead append the key to our local bundle.

It could be the case that an UpstreamAuthority plugin is loaded, however the UpstreamAuthority does not support JWK. In this case, we should receive a gRPC NotImplemented error code from the plugin when we attempt to pass it the JWK. When that happens, we want to append the JWK to our local bundle instead of worrying about continuing to pass it upstream. A warning should also be logged in this event, something like "UpstreamAuthority \"foo\" does not support JWT-SVIDs. Workloads managed by this server or downstream servers may have trouble communicating with workloads outside this zone when using JWT-SVIDs." The warning should be logged just once, perhaps guarded by something like sync.Once.

The response emitted by this RPC should include an up-to-date copy of the JWKS bundle, including the newly-appended JWK.

Please see #1190 for more information.

* Ensure that only "downstream" workloads are authorized to call this new RPC
* When called, pass the received JWK to the UpstreamAuthority plugin (if present)
* If UpstreamAuthority is not present, or NotImplemented error is returned, append the received JWK to the local bundle
* The downstream server should receive an up-to-date bundle in the response

Blocked on #1371

**Comment by martincapello** [comment]
Hi @evan2645, I have a question about this. Let's say that some intermediate SPIRE server receives a call to this new RPC, and it has an UpstreamAuthority plugin that supports JWT-SVIDs. According to the description it must pass the JWK to the plugin and then send the response back to the caller. So, if I understood well, the intermediate SPIRE server won't have an updated bundle after returning the response to the caller. Is this intentional? Or should the intermediate server update the bundle before sending the response to the caller?

**Comment by evan2645** [comment]
Ooh... This is a very good question @martincap

You are right about point 1, at this time the intermediate server would have an outdated bundle... The problem is larger than that though, because it might be that there multiple intermediate clusters at the same level, and only the cluster through which the request path passed would receive that update.

This was discussed at length during our maintainer sync today (thanks again for bringing this up!) and we have some ideas on how to solve it but are not exactly sure just yet.

I'd say that for now though, do not worry about updating the bundle when we pass an RPC call from the handler to upstream. We will come up with a solution for the larger problem and slide it into the end of the backlog so it gets fixed prior to the release of this feature.

**Comment by martincapello** [comment]
Cool, got it. Thank you @evan2645 !
However, I believe that point 2 is still relevant in the case of a root SPIRE server (in which case the rpc is not passed because there is no upstream for it, and the bundle has to be updated). What do you think? Or should I skip bundle update for this case too?

**Comment by evan2645** [comment]
Yes, 2 is still relevant for the root servers. Your line of thinking sounds about right to me (let the CA handle the bundle update), especially when considering the notifications that will need to get sent.

Maybe @azdagron has some further thoughts on this
