### ISSUE TITLE
Light up support for JWT-SVIDs in a nested topology

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#1380]
To finally solve #1190, light up and verify all the pathways for supporting JWT-SVIDs in nested topologies. Doing this will involve a few steps.

First, SPIRE Server's CA manager needs to be updated to call the UpstreamAuthority plugin whenever it prepares a new JWK. Any error encountered while calling UpstreamAuthority (_other_ than NotImplemented) should result in a failure to prepare the new key. We should also be careful to apply a deadline/timeout to the context of this request, as we don't want to wait around forever.

If a gRPC NotImplemented error is encountered, then we should continue as if we didn't have an UpstreamAuthority configured. In other words, we should inject the new key into the local bundle and succeed in preparing the key. At this time, we should also log a warning, something like "UpstreamAuthority \"foo\" does not support JWT-SVIDs. Workloads managed by this server may have trouble communicating with workloads outside this cluster when using JWT-SVIDs." This warning should be logged only once, perhaps using something like sync.Once.

The error handling for preparation of a new X.509 CA key/certificate should also be updated to mirror the above behavior. The gRPC NotImplemented error code should be detected, and a warning should be issued if it's received. Similarly to JWKs, if this error code is encountered while preparing an X.509 CA key/certificate, we should fall back to the behavior that would otherwise be present if no UpstreamAuthority was configured (i.e. we should inject the new CA certificate into our local bundle and succeed the key preparation, while logging a warning). Any other (non-NotImplemented error) should result in an error preparing the key.

Second, we'll need an integration test to cover the nested SPIRE topology. One option is to extend the existing rotation test suite to leverage a nested deployment - in this case, we can exercise and validate rotation at all levels. We want to ensure that both X.509 _and_ JWK rotation is occurring as expected, and that X509-SVIDs and JWT-SVIDs can both be minted/updated/validated before and after intermediate and root rotations. This test suite will help us build confidence that JWT-SVIDs are behaving as expected in nested topologies.

Finally, bugs may (will?) be encountered while building up the test suite. Any bugs encountered during this process should be raised as separate bugfix PRs such that everything is known to be working prior to merging the PR that fixes this issue. We should ensure that all bugfix PRs that are raised during this stage include regression tests.

Please see #1190 for more information.

* Update CA manager to call UpstreamAuthority when new JWKs are prepared, and handle error vs NotImplemented appropriately
* Update CA manager to handle error vs NotImplemented appropriately when preparing new X.509 CAs
* Introduce functional/integration tests that fully exercise rotation in nested topologies for both X509-SVIDs and JWT-SVIDs
* Fix any/all bugs encountered in dedicated PRs that include regression tests

Blocked on #1379 
Blocked on #1452

**Comment by martincapello** [comment]
Hi @evan2645, I started working on some of this, and I think I need a bit more light :grimacing: 
What should the manager do with the JWKs bundle when a call to the UpstreamAuthority plugin succeeds? Should it update the bundle with all the JWKs received from upstream?

**Comment by evan2645** [comment]
>Hi @evan2645, I started working on some of this, and I think I need a bit more light 😬
What should the manager do with the JWKs bundle when a call to the UpstreamAuthority plugin succeeds? Should it update the bundle with all the JWKs received from upstream?

Hah! I was so worried about covering the failure cases that I didn't talk about the happy path 😆 

Yes, in case of success for JWK preparation with UpstreamAuthority, we should use the JWKs in the returned bundle to update our local bundle. You can see similar behavior for X.509 currently: https://github.com/spiffe/spire/blob/57bbecdb83800b5cb1768eda7b09ea9ca7d15b4f/pkg/server/ca/manager.go#L208-L224

That being said, this issue is blocked on #1379, which is in turn blocked on #1372 and #1378. I think we'll need to complete those three issues before we are in a position to tackle this one

**Comment by MarcosDY** [comment]
about integration test,   I was thiinking in create something like:
![nested integration test](https://user-images.githubusercontent.com/3899789/75571164-6a385800-5a37-11ea-9853-bd7ab78f07d4.png)

where we'll validate svid rotations

make this sense? it will be all in separated containers (docker for now)

**Comment by anvega** [comment]
@MarcosDY In regards to the integration testing, it may be better to add an additional layer of downstream servers for a total of three, one top and two downstream. That way all code paths will be exercised.

**Comment by evan2645** [comment]
Yes I think that makes sense... though I also agree with @anvega - there is a code path that relays keys from downstream to upstream, so having three layers of servers will ensure all are exercised.

What I'm not sure of is whether it is best to have a dedicated test suite for this, or if our existing rotation suite should be updated to use a nested topology. Kind of feels like the latter since I can't think of a non-nested rotation problem that a nested rotation test _wouldnt_ detect. I'll defer to @azdagron on that though

**Comment by MarcosDY** [comment]
Thanks  @anvega  and @evan2645 for your feedback!! 
I already implemented previous image I'll update that integration test to:
![x509 nested integration test](https://user-images.githubusercontent.com/3899789/76763955-cbb83080-6772-11ea-9345-402bf503ffda.png)

About keeping or not  `non-nested` integration test, actual it only fetch for x509, I was thinking in update it to fetch jwt too, and I prefer to keep both just to have a case where we dont use `upstream spire`

**Comment by azdagron** [comment]
> I prefer to keep both just to have a case where we dont use upstreamAuthority spire
I think I'd probably agree. The current rotation test does not use an UpstreamCA, which I think is meaningful to test in isolation from a rotation perspective.

**Comment by evan2645** [comment]
>I prefer to keep both just to have a case where we dont use upstreamAuthority spire

Yes that makes sense

I don't think that "Downstream 2.2" is strictly needed as we exercise the full three levels on the left hand side. May be some small benefit to exercising an uneven topology, but I'm having a hard time coming up with anything realistic we might be able to catch that way

**Comment by MarcosDY** [comment]
my intention with  "Downstream 2.1" (than I renamed to IntermediateB) was to have a separated tree, 
so now I'm validating a workload svid from "Downstream 1.1" agains  "Downstream 2.1".
and doing the same with  "Downstream 1.2" (now called leafA), fetching svids from it and validating it against "Downstream2.2" 
with that we validate than intermediate servers have valid keys too

**Comment by evan2645** [comment]
I have updated this issue to reflect that it is now blocked by #1452

It will be a little while until that issue is resolved. If this test suite is functioning properly, you should see the suite fail prior to the resolution of #1452. That being said, it will also take some time to review, so please feel free to open the PR for this issue prior to it being unblocked by the above work.

Sorry for the disruption @MarcosDY
