### ISSUE TITLE
Review documentation for accuracy with regards to JWT-SVIDs in nested topologies

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#1381]
We need to do a final sweep of all the documentation to make sure that the text reflects reality with regards to JWT-SVID support in nested topologies. Some areas that come to mind are: spiffe.io, UpstreamAuthority "spire" config reference, the SPIRE readme, and spire_server.md.

If there are any questions about what the "reality" is, or how something works, please feel free to ping back on Slack or in this issue.

Blocked on #1380

**Comment by azdagron** [comment]
This is complete.
