### ISSUE TITLE
AWS KMS Upstream Authority

### ISSUE THREAD

**Issue by mcpherrinm** [spiffe/spire#1382]
AWS KMS has added asynchronous signing, so it's now (likely) suitable for use backing a CA.

This could be a better alternative to the Secrets Manager plugin that currently exists, or a cheaper option than using Private CA.  I suspect we could even deprecate the SM plugin if there aren't users.

**Comment by evan2645** [comment]
Is this better modeled as an Upstream Authority or as a Key Manager? Kind of feels like the latter, where SPIRE Server handles the CA certificates etc, and KMS is used purely for key persistence and signing operations

**Comment by evan2645** [comment]
Support for AWS KMS has been released as a KeyManager plugin with SPIRE 0.12.2
