### ISSUE TITLE
Support Namespace, Type, Name and Container K8S Workload Registrar

### ISSUE THREAD

**Issue by joshua-rutherford** [spiffe/spire#1393]
* **Version**: All
* **Platform**: Kubernetes
* **Subsystem**: Kubernetes Workload Registrar

At present, the Kubernetes Workload Registrar only supports registration based upon Service Account, Labels and Annotations.  In practice, I'm resistant to the idea that labels or annotations can be used to uniquely identify a workload as these can be added to any resource at any time.  

Service account is better as that is unique in a namespace, but I wonder if it's not possible to uniquely identify every workload by it's namespace, type, name and container.  Has this been ruled out as an option?

**Comment by evan2645** [comment]
>I'm resistant to the idea that labels or annotations can be used to uniquely identify a workload as these can be added to any resource at any time

I didn't write the registrar, but I think the idea was that there should be other controls in place if this is important to you.

>Service account is better as that is unique in a namespace, but I wonder if it's not possible to uniquely identify every workload by it's namespace, type, name and container. Has this been ruled out as an option?

We wanted to be sure that registrar users had two options: first, the ability to specify a SPIFFE ID for a deployment, and second, the ability to have a default name assigned if the first option was too onerous. The default name does not require any annotations or labels, and generates SPIFFE IDs that include both the namespace and service account of the deployment.

So, I think that's most of the way to what you're describing? Yes, container name/image/etc could have also been part of this default SPIFFE ID, however the existing default ID format was meant to adopt the same format that Istio uses (Istio does not allow custom SPIFFE IDs).

If you want to identify by an ID other than the default, I think you can specify that via annotation/label

**Comment by joshua-rutherford** [comment]
Maybe I missed something, but is there a way to prevent arbitrary annotations from being set by anyone who can launch a pod?  If so, that would be fine.

In the past month though I've decided the current behavior is sufficient for my needs and provides a logical implementation.  I'm fine closing this issue after further thought (had forgotten I opened it).
