### ISSUE TITLE
Agent should detect updates to its cache and push them out

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#1425]
Changes to registration entries should be detected by the agent and the cache should be updated so the changes are reflected without having to wait a full rotation period.

**Comment by evan2645** [comment]
Some additional context, pasted from a slack conversation with @faisal-memon 

> Faisal Memon: If a spire entry is updated, is the new svid pushed out?
> Agustín Martínez Fayó: hi Faisal :wave: updating a SPIRE entry does not push a new SVID
> Faisal Memon: Thanks for the reply Augustin. Is there any way to push a new SVID? My use case is that when a service is created, I want to add the name of the service as a dns name for all the endpoints of the service.
