### ISSUE TITLE
spiffe_id fields in SQL database tables have incorrect maximum length constraint

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#1446]
The `spiffe_id` field in the following SQL database tables resorts to the default maximum length used by gorm of 255 characters, a type of `varchar(255)`:

- `attested_node_entries`
- `node_resolver_map_entries`
- `registered_entries`

The SPIFFE Specification says that SPIFFE implementations MUST support SPIFFE URIs up to 2048 bytes in length. See [SPIFFE ID Section 2.3](https://github.com/spiffe/spiffe/blob/master/standards/SPIFFE-ID.md#23-maximum-spiffe-id-length) for reference.

See [gorm documentation](https://gorm.io/docs/models.html) of `size` struct tag for default size of `varchar` fields.

**Comment by evan2645** [comment]
Thank you for reporting this @rturner3, it is definitely something we need to address.

Would be great to get a patch in for the next release, which is coming in the next 2-3 weeks.

Are there any compatibility concerns with this kind of migration?

**Comment by rturner3** [comment]
To my knowledge, increasing the size of a `varchar` field in SQL shouldn't impact any existing data. And 2048 bytes is well within the range of maximum sizes allowed for `varchar` fields in some of the most popular SQL databases:

```
| Database   | Max varchar size (bytes) |
|------------|--------------------------|
| MySQL      |                   65,535 |
| PostgreSQL |               10,485,760 |
| sqlite     |            2,147,483,647 |
| Oracle     |                    4,000 |
```

References:
[MySQL 5.6 limits](https://dev.mysql.com/doc/refman/5.6/en/char.html)
[PostgreSQL limits](https://github.com/postgres/postgres/blob/fe604800681aed8228fbe67d2e175d6822c66ea2/src/include/access/htup_details.h#L578) (not documented explicitly anywhere, but is derived from this value in the code)
[SQLite limits](https://www.sqlite.org/limits.html)
[Oracle limits](https://docs.oracle.com/cd/B28359_01/server.111/b28320/limits001.htm#i287903)

**Comment by rturner3** [comment]
After looking more deeply into this, I found that bumping the size of the SPIFFE ID fields in the SQL tables is actually problematic for MySQL because it causes some indexes on SPIFFE ID fields to exceed the maximum allowable index prefix length allowed by InnoDB. The SPIRE database is using the `utf8` [character set](https://dev.mysql.com/doc/refman/8.0/en/charset-mysql.html) for MySQL, which requires up to 3 bytes per character. It is also using the `DYNAMIC` row format.

These are the maximum index prefix lengths for InnoDB across recent versions of MySQL for the character set and row format used in the SPIRE database:
```
| MySQL version | Max index prefix length |
|---------------|-------------------------|
| 5.6           | 767 bytes               |
| 5.7           | 3072 bytes              |
| 8.0           | 3072 bytes              |
```

InnoDB has to budget for any particular `utf8` character occupying 3 bytes of space, so this effectively reduces the maximum index prefix length to `N / 3`, resulting in the following maximum index sizes for `varchar` types:
```
| MySQL version | Max index character length |
|---------------|----------------------------|
| 5.6           | 255                        |
| 5.7           | 1024                       |
| 8.0           | 1024                       |
```

This means that supporting the maximum SPIFFE ID length in the specification would require removal of any indexes on any SPIFFE ID fields.

**Comment by rturner3** [comment]
The only feasible solution I've found for this so far is to diverge the schemas for different SQL databases. MySQL would get a version of the `registered_entries` and `node_resolver_map_entries` tables that doesn't index on `spiffe_id`, and PostgreSQL and SQLite would get a version of those tables with the `spiffe_id` indexes.

This is an unfortunate limitation for MySQL users. I hope it is less consequential now that most of the frequently accessed data is served from an in-memory cache.

**Comment by evan2645** [comment]
After conversation with the SPIRE maintainers, I've removed this issue from the 1.0 milestone as we haven't yet identified a clear solution.

**Comment by rturner3** [comment]
This issue is still relevant, although there is still not a clear solution.
