### ISSUE TITLE
Initial support for revision number in the Registration Entry

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#1459]
We need a good way for agents to recognize when a workload X509-SVID should be renewed outside of the normal rotation schedule (e.g. DNS names on the registration entry for the workload changed).

#1447 introduced a few proposals. Consensus was achieved to add a revision number to the registration entry that is bumped whenever the entry is changed. The agent can respond to a change in revision number by renewing the X509-SVID.

The first step to enable revision number support is to add a migration to the SQL datastore for a new revision number column on the registration entry. This should go in before 0.10.0 is released.

**Updated:** renamed to `revision number` instead of `generation number` based on the conversation below.

**Comment by evan2645** [comment]
I wonder if the term `generation` will be confusing to new users. Personally, I like it and think it's a good fit, but I could see how something like `serial number` would better communicate its function.

I only raise this now as the column will need a name :). Curious to hear your thoughts

**Comment by azdagron** [comment]
Hmm, how about `revision`?

**Comment by evan2645** [comment]
Much better!

How about `revision_number`?

**Comment by azdagron** [comment]
Even more better! I'll re-title the issues.
