### ISSUE TITLE
UpdateRegistration DB call should be atomic

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#1465]
Today the `UpdateRegistration` call in SQL first deletes some information and then calls `update`.
In case of error, between the deletions and updates, the registration is neither the old nor desired state.

The entirety of operations for this should be in a single atomic transaction.

**Comment by azdagron** [comment]
I believe it is already performed under a single transaction.

https://github.com/spiffe/spire/blob/52c0ab63920bb26c6fa20772555143f066f5062a/pkg/server/plugin/datastore/sql/sql.go#L412

**Comment by amoore877** [comment]
ah, missed that one magic line of logic :)
the support function called gives the appearance of independent executions
