### ISSUE TITLE
SPIRE should support SPIFFE Bundle sequence number

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#1495]
The SPIFFE bundle specification allows for an optional sequence number to be set, which allows consumers to understand which bundles are "newer" or "older", and also allows them to measure propagation.

SPIRE does not currently support setting a sequence number on its bundles, but it should!

This issue is done when the SPIFFE bundle published by the federation api has a sequence number included, and when servers and agents log updates to the bundle by sequence number.

**Comment by mchurichi** [comment]
doesn't SPIRE support sequence numbers in the Bundle yet?

**Comment by azdagron** [comment]
It doesn't yet. It doesn't persist them nor increment them when the bundle is appended during rotation.
