### ISSUE TITLE
Agent feature to download the bundle from a URL.

### ISSUE THREAD

**Issue by esweiss** [spiffe/spire#1507]
As an alternative to putting the SPIRE server bundle on disk using the "trust_bundle_path", allow the agent to fetch it from a URL (maybe "trust_bundle_url").

**Comment by dfeldman** [comment]
Hi all,
Here is what I'm planning for this issue. 
I'll add a new trust_bundle_url config, which will allow referring to a remote URL to get the root bundle in PEM format.
We'll allow either HTTP or HTTPS fetching. If it's set to HTTPS, it'll use the system default CA store to authenticate the server for downloading the root bundle. 
If both trust_bundle_path and trust_bundle_url are set, the two bundles will be concatenated. 
If there's a failure to fetch the URL, and there are no other trust bundles available, the agent will fail to start up. 
If the contents of the URL are not parseable, the agent will fail to start up.
We won't cache the bundle locally in any way. The expected use case is for ephemeral nodes in the cloud that will download the bundle from S3 (or equivalent). If there is a use case for long-lived nodes with less reliable access to the trust bundle URL, we might have to cache it in case of a download failure.
We may want to send a no-cache header in case the user is using Cloudfront or something in front of their S3 bucket (since the trust bundle changes frequently).

**Comment by azdagron** [comment]
Thanks for putting this together, @dfeldman! This is looking pretty good. I have a few open ended questions...

> get the root bundle in PEM format
Wonder if we should also support a SPIFFE bundle? If so, how would we determine the encoding? Maybe the `Content-Type` header (i.e. `application/x-pem-file` and `application/json`)?

> We'll allow either HTTP or HTTPS fetching
If we do allow `HTTP` we should be loud about it not being ideal (i.e. emit a warning in the log)

> If both trust_bundle_path and trust_bundle_url are set, the two bundles will be concatenated.
That's an interesting idea! What use case are you thinking of here? Unless there is a clear use case, I wonder if we should start with making the two configurables mutually exclusive? We could always open it up later.

> We may want to send a no-cache header....
Yeah this is an interesting point. I'd personally probably lean towards leave the caching strategy up to the server. The agent isn't going to be do any caching client-side so it's going to hit the endpoint regardless. If the agent sends the header, we may unintentionally subvert the server from employing the caching strategy they want for their deployment.

**Comment by evan2645** [comment]
> We'll allow either HTTP or HTTPS fetching

Is it possible to use whatever schemes are registered with the system to identify a handler, thus supporting arbitrary protocols?

If we wanted to support a new protocol in the future, how might that look?

> HTTP is obviously not ideal but it may be useful for testing and such.

IMO it's worse than "not ideal". There are similar concerns when considering my above comment - it could be hard for us to assert that the requested transport type is authenticated (perhaps that alone is a reason to not do that).

We should either avoid HTTP support entirely, or be very loud when configured about this being a terrible idea either via `insecure` configurable naming, log message warning, or both. A breach using this vector would effectively result in an "authentication bypass" vuln of sorts for any workload running on that host... And the attacker could maintain this presence indefinitely, perhaps even undetected.... It's pretty bad. Security here is very important.

> If both trust_bundle_path and trust_bundle_url are set, the two bundles will be concatenated.

What is the use case for this? Feels a little dangerous to me... Could they be mutually exclusive?

> We may want to send a no-cache header as part of the request

:+1: that sounds like a very good idea, if/when the protocol is HTTPS

A final note on security - normally, this only happens at boot, making the window of opportunity relatively small. However, changes of behavior are being discussed that involve pulling this bundle again in certain cases, widening the window and possibly even allowing an attacker to induce the condition (e.g. by interfering with agent -> server communication).

**Comment by azdagron** [comment]
> Is it possible to use whatever schemes are registered with the system to identify a handler, thus supporting arbitrary protocols?
@evan2645, I'm not sure I grok that. Are you expecting the agent to shell out to some system utility for handling the URL?

**Comment by azdagron** [comment]
Re: `HTTP` URLs, maybe we make them explicitly opt-in to insecure behavior by making that scheme available only if they configure something like `insecure_allow_http_trust_bundle_url = true`, or having an `insecure_trust_bundle_url` configurable alongside `trust_bundle_url`?

**Comment by esweiss** [comment]
If we only want http support for testing, perhaps it could be restricted to 127.x.x.x?

**Comment by evan2645** [comment]
> @evan2645, I'm not sure I grok that. Are you expecting the agent to shell out to some system utility for handling the URL?

Most operating systems have a way to register URL scheme/protocol handlers such that the right thing is invoked when trying to access a URL (e.g. open)... Though thinking more about it now it's probably not appropriate since I think all it does is open the registered app and pass the URL to it.

**Comment by evan2645** [comment]
> Re: `HTTP` URLs, maybe we make them explicitly opt-in to insecure behavior by making that scheme available only if they configure something like `insecure_allow_http_trust_bundle_url = true`, or having an `insecure_trust_bundle_url` configurable alongside `trust_bundle_url`? 

One option here could be to only allow HTTP if insecure_bootstrap is set to true.

What is the testing use case we have in mind here? Functional testing, testing the integration, or something else? The former could probably be accomplished some other way, and I might suggest that the latter doesn't actually work until TLS does. If there are no other use cases, I wonder if the existing insecure_bootstrap configurable is enough on its own.

**Comment by azdagron** [comment]
> One option here could be to only allow HTTP if insecure_bootstrap is set to true.
I like that. I like that a lot.

**Comment by evan2645** [comment]
> If we only want http support for testing, perhaps it could be restricted to 127.x.x.x?

This could also be an option depending on the use case in mind - it's not clear to me exactly what that would be at the moment.

**Comment by azdagron** [comment]
Right now we ignore the `trust_bundle_path` completely if `insecure_bootstrap` is set, since we skip server verification entirely. It would be a _little_ inconsistent to have `trust_bundle_url` still be meaningful but maybe that is just a documentation thing.

**Comment by evan2645** [comment]
> Right now we ignore the `trust_bundle_path` completely if `insecure_bootstrap` is set, since we skip server verification entirely. It would be a _little_ inconsistent to have `trust_bundle_url` still be meaningful but maybe that is just a documentation thing.

Agreed, I had the same thought. That  configurable feels like the "right" place for this, but consistency would be ideal.

Maybe we could have a change in behavior with bundle path... If set and also insecure_bootstrap, _try_ to authenticate but log a warning if we can't...? And still permit bundle path and URL to be empty? :shrug: food for thought

**Comment by dfeldman** [comment]
Ok, you guys have me convinced:
* no HTTP unless insecure_bootstrap is set. We really don't want someone to use HTTP by accident, and there's no reason to have a bootstrap bundle at all if you can't trust where it's coming from.
* no concatenating bundles. Either the bundle comes from a URL or from disk, but not both.
