### ISSUE TITLE
Improved Error Messages For JWT-SVID Fetch Failure

### ISSUE THREAD

**Issue by elee** [spiffe/spire#1508]
This Issue is feedback on error messages from Spire Agents and a suggestion to make them more descriptive for users and operators.

Recently on a host running a spire-agent that was unable to connect to Spire Server we observed the following error message in the logs trying to mint a JWT:

```
nagios@hubbernetes-node-385b248:~$ spire-agent api fetch jwt -audience spiffe://iad.github.net/moda-app-controller-productio
rpc error: code = Unavailable desc = could not fetch JWT-SVID: unable to get a stream
```

Peeking into the code and strace-ing the process revealed that this was retrying the configured Spire Server hostname a few times and eventually giving up. The message is seemingly emitted here: https://github.com/spiffe/spire/blob/7224db779e9fd994318f4791fe210652862cbb5f/pkg/agent/client/client.go#L175

if this were to read:

- failed to connect to $SERVER after $N attempts
- server at $SERVER unavailable
- unable to connect to spire-server

This would be more descriptive.

* **Version**: 0.9.1
* **Platform**: Debian
* **Subsystem**: agent

**Comment by rturner3** [comment]
The behavior of FetchJWTSVID has changed since this issue was originally reported, and the error message cited in the issue description is no longer used. Closing this, please open another issue if you find any other improvements to error reporting.
