### ISSUE TITLE
Document Federation configuration options

### ISSUE THREAD

**Issue by esweiss** [spiffe/spire#1514]
Update SPIRE Server documentation to include federation options.

**Comment by evan2645** [comment]
I think we probably need an issue that precedes this one, along the lines
of "Determine the most appropriate way to configure and interact with
SPIRE's federation features".

E.g. should we even allow file-driven configuration, or allow both file and
API, what is the behavior in that case, etc

--
evan

**Comment by azdagron** [comment]
The solution we land on will also need to consider how servers coordinate updates to the federated trust domain bundle when running in HA.

**Comment by martincapello** [comment]
If nobody is against, am going to start documenting what we already have for this, and then when we implement an appropriate solution, we can update it. This way anyone that wants to try **today** how federation works, can use this documentation to have some guidance in setting the current experimental configuration, without having to wait for a better configuration experience.

**Comment by martincapello** [comment]
Alright, just saw https://github.com/spiffe/spire/issues/1619, I will document the options according to what that issue specifies.

**Comment by evan2645** [comment]
Done, available at https://github.com/spiffe/spire/blob/master/doc/spire_server.md#federation-configuration
