### ISSUE TITLE
Investigate a notifier plugin for Puppet

### ISSUE THREAD

**Issue by drrt** [spiffe/spire#1521]
This issue exists to discuss the feasibility and possible implementation of a bundle notifier for Puppet.

Users who deploy SPIRE agents via Puppet need a current copy of the trust bundle. A notifier plugin, akin to k8sbundle, would make this process simpler.

A Puppet-native notifier might be difficult to implement. The Puppet HTTP API provides some mechanisms for updating both files in buckets and facts, but the API is not terribly stable nor designed with non-Puppet access in mind. Authenticating to it may also require impersonating a Puppet agent.

Another option could be to install a Puppet agent on the SPIRE server and write a module to back up the trust bundle from a file on disk to the Puppet master.

Other options undoubtedly exist.

**Comment by evan2645** [comment]
> Another option could be to install a Puppet agent on the SPIRE server and write a module to back up the trust bundle from a file on disk to the Puppet master.

That is interesting. I suppose this solution would involve publishing some puppet bits rather than a new plugin. I would imagine that the HA semantics in this case may be challenging. I further wonder if similar - options are available for chef e.g. a SPIRE recipe that knows how to update a data bag with the local bundle retrieved from spire-server during a chef run

**Comment by drrt** [comment]
> > Another option could be to install a Puppet agent on the SPIRE server and write a module to back up the trust bundle from a file on disk to the Puppet master.
> 
> That is interesting. I suppose this solution would involve publishing some puppet bits rather than a new plugin. I would imagine that the HA semantics in this case may be challenging. I further wonder if similar - options are available for chef e.g. a SPIRE recipe that knows how to update a data bag with the local bundle retrieved from spire-server during a chef run

Oh right, that file on disk would need to be created by executing a spire-server command. That's certainly a puppety thing to do.

**Comment by drrt** [comment]
@elee @Sambao21 @joewilliams  - @anvega mentioned to me that you may have some thoughts on this work?

**Comment by elee** [comment]
@drrt thanks for the ping, we may have an interest. What challenges do you expect the plugin to solve for teams using puppet?

**Comment by rturner3** [comment]
Closing this issue as no one has asked for this in several years.
