### ISSUE TITLE
Server log message "join token has already been used" needs more information

### ISSUE THREAD

**Issue by mcpherrinm** [spiffe/spire#1523]
* **Version**: v0.10.0
* **Platform**: Linux
* **Subsystem**: node_api

SPIRE emits the error "join token has already been used" but doesn't include any further information.

This is difficult to debug; requiring cross-referencing agent logs to figure out which agent is trying to reuse a join token.

It would be better if the message also included some more information about the agent, and who had previously used the join token.

**Comment by evan2645** [comment]
What kind of information would be useful here? IP address of the agent trying to attest? Something else?

I'll note that the result of an attestation is always a SPIFFE ID in the reserved namespace that has been generated by the attestor. Given a join token, the SPIFFE ID of the related agent is derivable. I don't think we currently store the IP of the caller on successful attestation, though we certainly could.

**Comment by mcpherrinm** [comment]
the IP address would be helpful.

Really what I'd like is the aliased agent spiffe ID that's set up, but that might need extra DB lookups to fetch, since that'll let me figure out what server is unhappy.

**Comment by azdagron** [comment]
Looks like we add the IP field to the logger, but at a much later point in the Attest call.

**Comment by azdagron** [comment]
These log messages are now embellished with locator information. Further, the alias concept is a little hacky and may or may not exist, and in any case would require an additional lookup. We'll go ahead and close this for now.
