### ISSUE TITLE
Consider removing auto-generated markdown for protocol buffer and service definitions

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#1541]
We've maintained auto-generated markdown documetation against the protocol buffer and service definitions for some time now. Specifically, these are the `README_pb.md` files under the github.com/spiffe/spire/proto/* subdirectories. There is added complexity to our tooling and Makefiles for generating the documentation.

Is this markdown something that people find useful?

Alternatively, are the `.proto` files themselves easy enough to consume?

Considering the content between the .proto and the generated markdown is the same, this seems mostly to be a question of which has the most convenient formatting.

Unless anybody has strong feelings against this, I'd argue that the .proto files themselves are sufficiently understandable and that the autogenerated markdown is largely repetitive and unhelpful and that we should rip it out.

**Comment by drrt** [comment]
Related but not necessarily a blocker - there's some work underway to automatically pull some documentation from various repos into the spiffe.io website, and the documentation in the .protos is on the short list. Using the existing, pre-generated .md would be pretty simple, but the work of generating the .md could be moved to that process though and out of the SPIRE build itself without much effort

**Comment by azdagron** [comment]
That's good to know, @drrt. Unless we want to use it for in-repo documentation I'd probably vote on the side of generating the markdown into a separate repo.
