### ISSUE TITLE
SDS API should be enabled by default

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#1544]
The SDS API has been opt-in for a long time now. There are many people using it successfully, and I feel it's pretty clear that there's no adverse effect to having it enabled. Further, I can't think of any reason why one would want to _disable_ it.

Consider enabling the SDS API by default, and deprecating the `enable_sds` configurable.

**Comment by azdagron** [comment]
I agree. I think it is time.

**Comment by azdagron** [comment]
I think we can go two ways deprecating this:
1. Unilaterally enable SDS and warn if the configurable is set that it is unused and will be removed at a later time
2. Enable SDS if the configurable isn't set, but still honor the configurable when set (and warn that SDS will be enabled unilaterally and the configurable will go away at a future date). This allows folks to disable SDS if wanted until we remove the configurable.

Like you said, there isn't really a risk to enabling it so the first might be ok. In any case either approach will have the same deprecation timeline (pull the configurable in 0.12.0).

**Comment by azdagron** [comment]
We should revise the documentation at the same time to reflect that SDS is no longer considered 
"beta".

**Comment by mcpherrinm** [comment]
I think it makes sense to just unilaterally enable it.
I can't imagine that would break anything for anyone.

**Comment by amartinezfayo** [comment]
>Unilaterally enable SDS and warn if the configurable is set that it is unused and will be removed at a later time.

I think that we should do that.
