### ISSUE TITLE
API Refactor: Implement Bundle.AppendBundle RPC

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#1550]
AppendBundle appends items from the request bundle to the bundle for the trust
domain of the server. If appending JWT keys, and an UpstreamAuthority is
configured, it should also publish those keys upstream.

The caller must be local or present an admin or downstream X509-SVID.

Acceptance Criteria:
- Callers are properly authenticated
- Bundle is rejected with INVALID_ARGUMENT if not for the server trust domain
- Incoming bundle contents are appended to the existing bundle
- The fields that are appended are filtered against the input mask
- Appended JWT keys are pushed upstream if an UpstreamAuthority is configured
- Resulting bundle is returned, filtered against the output mask.

**Comment by azdagron** [comment]
I'm having second thoughts about this RPC, as currently described, particularly in its interactions with Nested SPIRE.

At first glance, it feels flexible to be able to update the bundle with extra X.509 roots or JWT keys. One intent of this RPC was to facilitate the downstream SPIRE server publishing JWT keys upstream (i.e. a replacement for the current Node.PublishJWTKey RPC). However, in Nested SPIRE, we don't currently have (or need) a way to push an X.509 root upstream.

Presumably an admin would add a one-off X.509 root because it intended to have trust domain workloads trust identities minted by that root. By not publishing upstream, that root wouldn't propagate to the rest of the nested structure. This means that the admin would need to call AppendBundle on all SPIRE servers or risk not having that root trusted everywhere.

It's just feeling a bit clunky to me.

**Comment by evan2645** [comment]
> Presumably an admin would add a one-off X.509 root because it intended to have trust domain workloads trust identities minted by that root. By not publishing upstream, that root wouldn't propagate to the rest of the nested structure. This means that the admin would need to call AppendBundle on all SPIRE servers or risk not having that root trusted everywhere.

Would X.509 bundle additions propagate downwards? If so, that seems pretty reasonable? If I want it in the whole TD, I add it at the root level.

There's also the non-nested case to weigh which is probably more commonly deployed. I think the argument there becomes "should we allow administrative bundle additions at all?". Since admins could always inject something into the bundle at the datastore layer, Im leaning towards "yes".

**Comment by azdagron** [comment]
I agree that downward propogation feels good and natural with this API.

Propogating JWT upward while not doing the same with X.509 is what feels clunky.

What if AppendBundle was reserved for administrative bundle additions and we introduced a new API just for the purpose of publishing (jwt keys) upstream?

**Comment by azdagron** [comment]
Maybe something like `PublishDownstreamJWTAuthority` to make it clear that it is specific to the downstream use case (similar to the SVID.NewDownstreamCA` RPC)? If at some point we allow publishing X.509 upstream we could add a similar RPC.

**Comment by azdagron** [comment]
We discussed this a bit today on a call with maintainers. The broad consensus was that we should keep AppendBundle as an administrative RPC to append bundle contents (without upstream propagation) and introduce a new RPC for publishing downstream JWT authorities upstream.
