### ISSUE TITLE
API Refactor: Implement Bundle.BatchUpdateFederatedBundle RPC

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#1554]
BatchUpdateFederatedBundle updates one or more bundles for federated trust
domains. If a given bundle does not already exist, the result code for that
bundle is set to NOT_FOUND. The updated bundle is returned.

The caller must be local or present an admin X509-SVID.

This RPC cannot be used to updated the bundle of the server trust domain.

Acceptance Criteria:

- Callers are properly authenticated.
- Results for requests to update the bundle for the server trust domain are rejected with INVALID_ARGUMENT.
- Bundles that already exist are updated based on the input mask. The result is appended to the response, properly filtered by the output mask.
- Bundles that don't already exist result in a result code of NOT_FOUND being appended to the response.

**Comment by esweiss** [comment]
BatchCreateFederatedBundle creates one or more bundles for federated trust
domains. If a given bundle already exists, the result code for that bundle is
set to ALREADY_EXISTS. The created bundle is returned.

The caller must be local or present an admin X509-SVID.

This RPC cannot be used to updated the bundle of the server trust domain.

Acceptance Criteria:

Callers are properly authenticated.
Results for requests to create the bundle for the server trust domain are rejected with INVALID_ARGUMENT.
Bundles that don't already exist are created and the result is appended to the response, properly filtered by the output mask.
Bundles that already exist remain unchanged and the result code of ALREADY_EXISTS is appended to the response.
