### ISSUE TITLE
Use SPIFFE bundle endpoint as bootstrap bundle

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#1572]
SPIRE Agent recently gained the ability to download the bootstrap bundle from an HTTPS endpoint (#1526) in lieu of loading it from disk. The agent expects the endoint to serve PEM-encoded X.509 certificates.

This functionality very closely resembles a federation client downloading a SPIFFE bundle. Since the SPIFFE bundle contains the X.509 authorities for the trust domain, there seems to be no reason it couldn't be a source for the bootstrap bundle.

Since the whole purpose of the  bootstrap bundle is to enable the agent to authenticate identities from the trust domain, it only makes sense for the agent to support web-PKI authenticated bundle endpoints, since the material needed to authenticate a SPIFFE authenticated bundle endpoint would be the same material the agent would need to bootstrap trust with the server.

An open question is how the agent determines what content to expect to receive over the HTTPS endpoint, as the SPIFFE bundle is a JWKS document which is different from PEM-encoded X.509 certificates. A few options:
1) The agent relies on the HTTP `Content-Type` header. At the time of writing, there is no `Content-Type` header requirement on SPIFFE bundle endpoints, so this may not be possible or desired.
2) The agent relies on explicit configuration to determine what to expect (i.e. another configurable in the agent configuration).
3) The agent determines the content heuristically. This might be difficult to debug.

**Comment by amartinezfayo** [comment]
>The agent relies on explicit configuration to determine what to expect (i.e. another configurable in the agent configuration).

I'm inclined to this option. IMO seems to be the most simple and less error prone solution.

**Comment by mcpherrinm** [comment]
I worry option 3 is potentially confusing or hard to debug if it doesn't work right.

Option 2 seems best to me.

**Comment by azdagron** [comment]
I brought this up with SIG-SPEC and was reminded of a discussion we had while drafting the endpoint specification:

> We generally assume that the ability to have a server serve a trust bundle from a specific URL does not imply that an operator has the ability to configure HTTP response parameters and headers

So that rules out option 1.

I also agree that option 3 could get gross and has bad diagnostics if we get it wrong.

I'm ok with option 2, especially if we name the configurable something like `trust_bundle_url_content_type` or something like that to keep it grouped closely to `trust_bundle_url`.

**Comment by azdagron** [comment]
Of course, if we support SPIFFE bundle content at the URL, we could presumably also support loading a SPIFFE bundle from disk, so maybe the configurable should just be
```
trust_bundle_content_type = <PEM,SPIFFE>
```
It could default to PEM.

**Comment by evan2645** [comment]
One option could be to move the agent to use SPIFFE bundle for bootstrapping exclusively by introducing new config names and deprecating the old ones. The URL feature could then take SPIFFE bundle only

**Comment by azdagron** [comment]
Deprecating the old config might have implications for current bundle notifiers, which push up the PEM-encoded X.509 authority material from the bundles.

**Comment by amoore877** [comment]
Bumping on this as I recently noticed this (to me) odd non-reuse of existing SPIFFE concepts and was about to file an issue.

If operators of SPIRE in an organization have already set up a SPIFFE Bundle endpoint for consumers, it would be an extra burden on them to set up yet another endpoint that may be serving precisely the same content but in a different format.
