### ISSUE TITLE
Support additional roots in upstream CA bundles

### ISSUE THREAD

**Issue by mcpherrinm** [spiffe/spire#1573]
I'm using the AWS PCA upstream authority.

One issue with the current plugin for me is that I can't add additional CAs to the bundle of roots. 
Unfortunately there's no way to add them together right now:  The current PCA plugin only returns the root which signed the intermediate.

AWS PCA is per-region, so I'd like to have at least two PCAs in different regions. 
As well, rotating to a new root would require a period where both the new and old roots are trusted.

One option would be to add a bundle_file_path to the PCA plugin for the upstream bundle which works the same as the disk CA does today.

Or this could be a feature supported directly by SPIRE, instead of requiring re-implementation in each plugin.  It is unclear if this is required in other cases though:  This is possibly just a shortcoming of PCA in that the upstream can't provide additional roots.

**Comment by mcpherrinm** [comment]
https://github.com/spiffe/spire/pull/1574 is a rough sketch of how it might be implemented in the PCA plugin

**Comment by mcpherrinm** [comment]
This might actually be solved by #1550, by just using the administrative AppendBundle.

**Comment by evan2645** [comment]
> This might actually be solved by #1550, by just using the administrative AppendBundle.

I think this is the right way forward in the long term. What wasn't clear to me was whether or not it's valuable to have a static on-disk file that can be configured (vs having to make an interaction). My hunch is that if something is dropping a file, it can call a command whenever the resource changes... either way, I've gone ahead and picked up #1574 in the interest of getting a solution in.

I'd be interested to hear if the existing functionality exposed by AppendBundle is good enough for you. Of course, we'll need to add it to the CLI utilities.

**Comment by evan2645** [comment]
#1574 and #1550 have both been addressed. An API is now available for adding certificates to the bundle, and the aws_pca upstream authority plugin now supports `supplemental_bundle_path` configurable.

Closing this as fixed
