### ISSUE TITLE
Race condition in SPIRE Agent

### ISSUE THREAD

**Issue by faisal-memon** [spiffe/spire#1610]
There is a small window where a race condition might be happening in the SPIRE Agent after this [PR](https://github.com/spiffe/spire/pull/1477/files). In sync.go both `fetchEntries()` and `fetchSvids()` call `m.client.FetchUpdates()` and an update might happen in between the two calls. So lets say the following sequence happens:

1. DNS Names updated to `A, B`
2. `fetchEntries()` called
3. DNS Names updated to `A`
4. `fetchSvids()` called
5. DNS Names updated to `A,B`
6. `fetchEntries()` called (next loop)

The update adding B would be lost in this scenario. This is because `record.svid` will only have `A` but `record.entry` will have `A,B` due to the update coming in between the two calls to `m.client.FetchUpdates()`. The next time through the synchronization loop the `checkSvid()` test will see nothing has changed because `record.entry` will still be the same `A.B`.

`m.client.FetchUpdates()` should only be called once per synchronization loop.

* **Version**: 0.10.0
* **Platform**: all
* **Subsystem**: agent

**Comment by azdagron** [comment]
I think the key takeaway here is that the agent needs to look at the entry returned by the server when doing the fetchSvids() call and only remove the "staleness" marker in the cache if the entry is unchanged.

**Comment by azdagron** [comment]
I believe this will be fixed by #1720. When step 6 happens, instead of observing the same DNS Names that it saw in step 2, the code will notice a revision number change (due to both step 3 and 5) and will re-fetch the SVID.

**Comment by azdagron** [comment]
I'm going to close this for now (since I believe it to be fixed by #1720). Please re-open if you have evidence otherwise. Thanks for bringing this to our attention!

**Comment by faisal-memon** [comment]
Thanks, seems like that will fix the race issue. If you don't mind me asking though, what is the reason for calling m.client.FetchUpdates() twice in the same synchronization loop?

**Comment by azdagron** [comment]
`FetchUpdates` (and the RPC it uses under the covers) is dual purpose. The first call is used to get the updated registration entries, the second (and optional) call is used to obtain or renew the X509-SVIDs. The new APIs have distinct RPCs for these operations so when they are ready, the agent code can be refactored and clarified.
