### ISSUE TITLE
more descriptive spire agent comm errors

### ISSUE THREAD

**Issue by ryancnelson** [spiffe/spire#1627]
in discussion with a community member, this came up:  @ryancnelson capturing the note, but it's not my idea:

it is highly inconvenient to often get generic errors back from the server on agent-side. 
Agent should receive more specific errors (which get logged on its side), for the variety of issues that can occur, such as (but not necessarily limited to):

- Already attested
- Invalid attestation data
- Internal error to Server

**Comment by azdagron** [comment]
Thanks! We should certainly handle the first two cases above. The 3rd case may require some scrutiny.... internal details aren't always appropriate to share. In any case, I'm sure there are definite places we can improve here.

If there are any specific error messages as examples, that would help us scope this work.

**Comment by amoore877** [comment]
it may be good to combine with https://github.com/spiffe/spire/issues/1508, which has one specific example. I believe a meeting is going to be set by @esweiss or @ryancnelson for us to sync up on more specifics. It may be as simple as walking through the returns together to see what's appropriate and what can be expanded.
