### ISSUE TITLE
API Refactor: Implement Agent.BanAgent RPC

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#1637]
BanAgent bans an agent.

The caller must be local or present an admin X509-SVID.

Implementing this will require changing some of the semantics around the
attested node entry for the agent. Specifically, there is no "banned" column
in the datastore. Instead of adding a distinct column for this purpose, the
serial number field should be repurposed, where an empty serial number indicates
that the agent is "banned". This may require some careful auditing of existing
code, particularly in the node handler that this condition is detected and
treated properly:

Acceptance criteria:

- Callers are properly authenticated (middleware should handle this)
- Returns NOT_FOUND if the agent does not exist
- If the agent does exist, resets the serial number to empty to indicate the "banned" status.
- Node handler code is audited and modified to properly handle the new semantics of an empty serial number. This includes authorization checks for agents as well as modifying the `Attest()` flow to check for banned state using the agent SPIFFE ID returned from the node attestor.

**Comment by APTy** [comment]
One note: I _believe_ SPIRE only behaves as expected for node attestation plugins that enforce TOFU. For node attestors that allow re-attestation, then a banned agent can just re-attest and skip the server logic that checks for serial number parity. Perhaps this only needs to be documented in the ban-agent RPC and CLI docs, but longer-term we may want to address it.

**Comment by azdagron** [comment]
I updated the description to include the modification to the Attest flow. This should work for all attestors except `k8s_sat`, which generates a unique agent SPIFFE ID for every attestation attempt.
