### ISSUE TITLE
Agents should re-attest if evicted

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#1644]
Following on from #1257,
If a SPIRE agent has previously attested and still has a valid SVID, but then gets evicted, it will fail all subsequent calls to the SPIRE Server due to having an SVID not recognized by the Server. When the SVID's validity finally runs out, the agent will crash and finally re-attest. Workaround is to delete the agent's `.data` contents, which is not maintainable at scale.
Given the agent will eventually attempt attestation anyway, it should know it has been evicted and re-attest automatically rather than waiting for an arbitrary countdown of its own SVID validity.

**Comment by zmt** [comment]
What if the eviction is intended to disable identity for a compromised host? How could we distinguish between a node we are trying to recover and one we are trying to block by evicting? I think we would we need some additional semantic like "allow re-attest" vs. "block attestation" vs. simply "evicting".

**Comment by azdagron** [comment]
The refactored APIs introduce the concept of "banning" an agent. The attest RPC will return with PermissionDenied if the agent is banned. However, I think we need to think carefully how an agent responds to that status code.

**Comment by azdagron** [comment]
Maybe we can differentiate by providing extra information in the gRPC footer?

**Comment by azdagron** [comment]
Ah, see https://grpc.io/docs/guides/error/#richer-error-model.

**Comment by azdagron** [comment]
We can use the `details` available on the gRPC status. The status.Status type is a type alias for the internal status struct, which has the `Details` method (https://github.com/grpc/grpc-go/blob/7a808837ae926d5e44454a9a34af1d92cafeea10/internal/status/status.go#L123)

**Comment by azdagron** [comment]
I've implemented returning the details that we can use to switch on the permission denied reason in #1710.
