### ISSUE TITLE
CreateEntryIfNotExists has misleading output

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#1645]
`CreateEntryIfNotExists` naming implies "create this entry, if this entry does not already exist"
However the logic behind it only checks if any entries already exist with the same:
- SPIFFE ID
- Parent SPIFFE ID
- Selectors

If at least one match comes back, return the first one retrieved (non-deterministic) to the caller.
There are many more fields beyond IDs and Selectors to check. The returned entry is not necessarily the entry the caller wanted to actually create, and it is very possible that the desired entry does not exist in the DB at all. This is:
- a misleading success message (the desired entry may not actually exist)
- a confusing return (the returned entry may not match what the caller desired)

ref.
https://github.com/spiffe/spire/blob/9f967fdb69ec755c5ba427f1975087823bdf7342/pkg/server/endpoints/registration/handler.go#L75
https://github.com/spiffe/spire/blob/9f967fdb69ec755c5ba427f1975087823bdf7342/pkg/server/endpoints/registration/handler.go#L757

**Comment by azdagron** [comment]
This RPC has a specific purpose (see #1464). The criteria for what is considered a "similar entry" is very clear (the three bullet points above). This RPC was not intended as a mechanism for doingg an upsert.

That being said, the semantics are atypical and a little confusing at first glance. I'd be happy to see some more clarifying documentation in the registration.proto. These semantics are clearly documented in Entry.BatchCreateEntry RPC in the the server API refactor.

**Comment by amoore877** [comment]
This issue should be moved to focus on updating documentation to make the intent more clear.
#namingishard

**Comment by azdagron** [comment]
Is the documentation in Entry.BatchCreateEntry clear enough? If so, it may not be worth the effort to improve the Registration API docs.... it is being deprecated in 0.12.0 (which will go out this month). Code should be migrating to the new APIs.

**Comment by amoore877** [comment]
The BatchCreateEntryResponse doc is probably clear enough.
