### ISSUE TITLE
[RFC] Deprecate SPIRE DataStore pluggability

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#1650]
# Introduction

The intent of this RFC is to discuss deprecation of the current DataStore plugin interface.

# Background
The DataStore plugin interface is large and complex. It frequently requires changes to support new behavior. Even though SPIRE has done well to maintain compatibility guarantees with other plugin types, it has not done so with the DataStore plugin.

For the aforementioned reasons, even though the DataStore has been theoretically pluggable, it has not been practically pluggable. 

A lot of work has gone in to rethink what pluggable storage could look like (#896). Ideally we have a plugin interface that is relatively easy to implement and that does not require revision whenever a new feature with a storage need is introduced. However, we are not close to any final solution.

In the meantime, the DataStore interface continues to grow in both surface area and complexity.

# Proposed Action

I propose that we remove pluggability of the DataStore interface, restricting use to the current built-in `sql` plugin, with the hope that at some point in the (near?) future, we have a more palatable pluggable storage interface.

The most cautious route, that also follows our compatability guidelines, would be to deprecate on the next major release and remove pluggability on the release after. I do think there is some merit to the argument that we could deprecate and remove pluggability immediately since it is rather unlikely that there is an existing implementation out there that has managed to track all of the backwards-incompatible changes in master and stay up-to-date. The argument to deprecate sooner is that our next major release is probably going to be 1.0 and the optics seem a little funny to have deprecation warnings on a 1.0 release, but that is likely just semantics.

There exists one (public) implementation of the DataStore on github (https://github.com/summerwind/spire-plugin-datastore-k8s) but it has not received updates in a while and is certainly out-of-date at this point.

# Request for comments

1. Do you use a custom DataStore implementation?
2. Do you foresee ever wanting something other than a SQL backend for storage needs?

**Comment by APTy** [comment]
A big +1 on this.

Realistically, I think we can deprecate immediately and remove pluggability entirely in the next release. Agreed we'll want to wait some time to make sure anyone with custom implementations has had time to see this and speak their mind.

Regarding (2) I've always hoped for the ability to use a distributed K/V store like ZooKeeper or Etcd :D

**Comment by hiyosi** [comment]
> Regarding (2) I've always hoped for the ability to use a distributed K/V store like ZooKeeper or Etcd :D

+1
