### ISSUE TITLE
Attest Unix workloads by user groups

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#1657]
The SPIRE Agent `unix` workload attestation plugin today can attest workloads based on the process's user ID/name and group ID/name. However, it cannot attest workloads based on supplementary groups for which the user that spawned the process is a member of.

Say for example that a user `bob` is a member of two groups named `broad` and `narrow`, where `broad` is a large group of users and `narrow` is a more scoped set of users. Say that `broad` has a group ID of `1001` and `narrow` has a group ID of `1002`.

In this example, say that `bob`'s effective group is `broad`. Example output from a Linux system would be:

```bash
$ id -g
1001
$ id -G
1001 1002
```

Because `bob`'s effective group is `broad`, any processes `bob` spawns will be assigned the group ID `1001`. Thus when using Unix group-based selectors in workload registrations, the SPIRE Agent `unix` workload attestation plugin will only ever attest processes spawned by `bob` for the group ID `1001`. There is currently no way to declare a workload registration with Unix group selectors for the group name `narrow` or group ID `1002` that will successfully attest for processes spawned by `bob`.

The use case I have in mind for this at the moment is when a user wants to interactively launch an administrative CLI as their user and receive an admin identity to manage registrations in SPIRE Server. In this case, creating the workload registration to match against the group `broad` is not acceptable, because that group contains members who are not SPIRE administrators. Creating registrations based on `bob`'s user name is also tedious, since it requires creating individual registrations for every member of the `narrow` group and maintaining these individual registrations over time.

For reference:
In Linux, supplementary group information is available in [procfs](https://man7.org/linux/man-pages/man5/proc.5.html) in the `Groups` field of `/proc/[pid]/status`.

**Comment by azdagron** [comment]
This seems like a reasonable attribute to want to select on.

Should these groups to be surfaced under a distinct selector so they aren't confused with the effective gid?

**Comment by rturner3** [comment]
That sounds like a good idea so that the existing group selectors can function as is, and so that the user has an option to differentiate between the different type of group selectors (effective vs. any mapped to the user).
