### ISSUE TITLE
Server should cache FetchBundle response in TLS handshake

### ISSUE THREAD

**Issue by APTy** [spiffe/spire#1669]
Currently, in the TLS handshake, a FetchBundle call to the datastore is required. (see https://github.com/spiffe/spire/blob/65ed6b831cd40c033c169adfbb67a937fbe98e7d/pkg/server/endpoints/endpoints.go#L244)

If the server comes under high pressure from new TLS connections, this can cause undue load on the system. Even a cache policy of 1 second would significantly reduce query load.

**Comment by azdagron** [comment]
This was tackled as part of #1768.
