### ISSUE TITLE
Upgrade hashicorp/go-hclog and hashicorp/go-plugin

### ISSUE THREAD

**Issue by yurishkuro** [spiffe/spire#1686]
Is it possible to upgrade this repo to these deps?

  * github.com/hashicorp/go-hclog v0.14.0
  * github.com/hashicorp/go-plugin v1.3.0

**Comment by yurishkuro** [comment]
#1687 includes necessary upgrade of HCLogAdapter to conform to hclog.Loggerr interface as of 0.13.1

**Comment by zmt** [comment]
My testing indicated that #1687 should be sufficient to unblock us. I did note that in our codebase, the github.com/hashicorp/go-plugin was also updated to v1.3.0 when updating github.com/jaegertracing/jaeger on top of #1687.

**Comment by azdagron** [comment]
I'm not opposed to updating this deps in general. go-plugin specifically has had some (announced) breaking changes between minor versions in the past so before we do so, I'll need to take a gander at the changelog. Alternatively, another thing that would bring piece of mind is building an external plugin with the old version and making sure it still works when SPIRE is running the new version.

**Comment by zmt** [comment]
> Alternatively, another thing that would bring [peace] of mind is building an external plugin with the old version and making sure it still works when SPIRE is running the new version.

You just put old/new plugin vs old/new binary on my radar as a dimension for matrix testing of old/new version compatibility. Great suggestion. Thanks.

**Comment by azdagron** [comment]
Hmm, the PR auto-closed. Reopening to cover the go-plugin dependency update.

**Comment by azdagron** [comment]
I've reviewed the changelist for go-plugin. I'm ok bumping the dependency.
