### ISSUE TITLE
Suggestion: make pull request template more friendly to new contributors

### ISSUE THREAD

**Issue by yurishkuro** [spiffe/spire#1688]
Pull request template contains a question "does the PR conform with two CONTRIBUTING docs". Those docs are quite long, and it's not clear what "conforms" means. I recommend adding specific questions of what you're looking for.

**Comment by azdagron** [comment]
This is a good suggestion. Thanks @yurishkuro!

**Comment by anvega** [comment]
Template has been modified to read as:
