### ISSUE TITLE
API Refactor: integration tests for common flows

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#1718]
We should write up some integration tests for common flows across the new APIs, such as:
1. Agent attestation, renewal, deletion, and banning
2. Registering admin workloads, fetching admin SVIDs and using them to call admin-permitted RPCs
3. Registering downstream workloads, fetching downstream SVIDs, and using them to call downstream-permitted RPCs
4. Others??

These tests should mostly exist to make sure that supported flows work as expected. They shouldn't try and exercise failure scenarios so much. The unit-tests are pretty exhaustive there already.

Considering there is no CLI support for the new APIs, this will likely require writing some go code that the integration test framework can exercise.

**Comment by APTy** [comment]
Another common flow to consider is the hierarchy of registrations that users are likely to have, aliases, child entries, etc. If we have solid integration tests for this flow, we'll have more confidence when making changes to FetchX509SVID logic.

**Comment by amartinezfayo** [comment]
Integration tests implemented in #1730, #1753 and #1779.

Created #1817 to add integration tests for hierarchical registrations.
