### ISSUE TITLE
Federation Graduation (the missing bits)

### ISSUE THREAD

**Issue by martincapello** [spiffe/spire#1743]
The work done in #1619 was focused in federation configuration, but one piece of the puzzle have been overlooked: the experimental SPIRE Server's commands.
These commands are needed to get a trust bundle as a JWKS document for a determined trust domain. In order to bootstrap federation the servers need the trust bundles of the trust domains to which they want to federate with.
Currently these commands are:
`experimental bundle show`:   
&nbsp;&nbsp;&nbsp;&nbsp;Shows the SPIRE server bundle as a JWKS document.
`experimental bundle set -id <trust domain SPIFFE ID> [-path <path to bundle data>]`
&nbsp;&nbsp;&nbsp;&nbsp;Creates or Updates the federated bundle for the specified trust domain ID. If `-path` is specified the bundle is created/updated from the content of the file, otherwise it reads the content from the standard input.
`experimental bundle list [-id <trust domain SPIFFE ID>]`
&nbsp;&nbsp;&nbsp;&nbsp; If `-id` is not specified, shows the list of all federated bundles per trust domain ID, otherwise it shows the federated bundle for the specified trust domain ID, if any.

This issue is to reach consensus on a solution to graduate the above commands.

The proposed changes go like this:
1) Log a "This command will be deprecated in a future release, please use...." warning when any of the experimental commands are run.
2) Modify the current `bundle show`, `bundle list` and `bundle set` to accept an optional flag to indicate the output/input format of the given command. For instance: 
`bundle show` and `bundle show -as=X.509_PEM` would do the same.
`bundle show -as=JWKS` would do what `experimental bundle show` does right now.

Thanks @azdagron to propose the use of a flag, hopefully something like this was what you had in mind. 

All feedback is appreciated, so feel free to make any comment!

**Comment by azdagron** [comment]
I think this approach sounds reasonable. If you want to put up a PR, we can work through the details. Thanks @martincapello !

**Comment by amartinezfayo** [comment]
I discussed offline with @martincapello that I'll be taking care of this.
