### ISSUE TITLE
SPIRE sql datastore plugin fails to initialize when using ro_connection_string and new database cluster

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#1746]
* **Version**: c0acffac052d404d889db1afa5de4b5a67e8c979
* **Platform**: N/A
* **Subsystem**: `sql` datastore plugin

Reproduce steps:
1. Create new database cluster with replication
2. Configure SPIRE Server to use the `sql` datastore plugin with the `connection_string` property pointing to the address of the read-write replica and the `ro_connection_string` property pointing to the address of a read-only replica.
3. Start SPIRE Server.

SPIRE Server fails to start up with these logs coming from the `sql` plugin, in this case configured for MySQL:
```
time="2020-07-23T14:38:41-07:00" level=info msg="Opening SQL database" db_type=mysql subsystem_name=built-in_plugin.sql
time="2020-07-23T14:38:41-07:00" level=info msg="Initializing new database." subsystem_name=built-in_plugin.sql
time="2020-07-23T14:38:44-07:00" level=info msg="Connected to SQL database" read_only=false subsystem_name=built-in_plugin.sql type=mysql version=5.7.31-log
time="2020-07-23T14:38:44-07:00" level=info msg="Opening SQL database" db_type=mysql subsystem_name=built-in_plugin.sql
time="2020-07-23T14:38:44-07:00" level=info msg="errorexternal/com_github_jinzhu_gorm/scope.go:85Error 1290: The MySQL server is running with the --read-only option so it cannot execute this statement" subsystem_name=built-in_plugin.sql.gorm
time="2020-07-23T14:38:44-07:00" level=error msg="Failed to configure plugin." built-in_plugin=true error="rpc error: code = Unknown desc = datastore-sql: Error 1290: The MySQL server is running with the --read-only option so it cannot execute this statement" plugin_name=sql plugin_type=DataStore subsystem_name=catalog
time="2020-07-23T14:38:44-07:00" level=error msg="fatal run error" error="unable to configure plugin \"sql\": rpc error: code = Unknown desc = datastore-sql: Error 1290: The MySQL server is running with the --read-only option so it cannot execute this statement"
time="2020-07-23T14:38:44-07:00" level=error msg="server crashed" error="unable to configure plugin \"sql\": rpc error: code = Unknown desc = datastore-sql: Error 1290: The MySQL server is running with the --read-only option so it cannot execute this statement"
```

The issue here appears to be that the `sql` datastore plugin will attempt to create the database tables on connection to the read-only replica if the tables don't exist. With a fresh database cluster, the SPIRE database does not exist yet.

The `sql` plugin will first create the database and its tables using the read-write connection. It then performs the same check of whether the database tables exist in the read-only replica. On initial startup, there may be some replication delay between the read-write and read-only replicas, such that at the time that the `sql` plugin checks for existence of the SPIRE database in the read-only replica, it does not exist yet.

SPIRE should not attempt to perform write operations on read-only database replicas since such operations will always fail.

**Comment by azdagron** [comment]
Great catch, @rturner3. That whole bit of database setup code is in sore need of a refactor. It is very crufty and hasn't grown very well.
