### ISSUE TITLE
Vault as UpstreamProvider: no such UpstreamAuthority error

### ISSUE THREAD

**Issue by Taranasaur** [spiffe/spire#1755]
Hi, I have deployed a spire-server on Kubernetes and have issues getting it to start when given HashiCorp Vault as an upstreamProvider. 

Here are the startup logs for the pod:

> #### spire                    spire-server-0                                                0/1     CrashLoopBackOff        8          17m #### spire-server ##################
> spire-server#####
> time="2020-07-28T14:45:32Z" level=info msg="data directory: \"/run/spire/data\""
> time="2020-07-28T14:45:32Z" level=info msg="Plugin loaded." built-in_plugin=true plugin_name=disk plugin_services="[]" plugin_type=KeyManager subsystem_name=catalog
> time="2020-07-28T14:45:32Z" level=info msg="Plugin loaded." built-in_plugin=true plugin_name=k8sbundle plugin_services="[]" plugin_type=Notifier subsystem_name=catalog
> time="2020-07-28T14:45:32Z" level=info msg="Opening SQL database" db_type=sqlite3 subsystem_name=built-in_plugin.sql
> time="2020-07-28T14:45:32Z" level=debug msg="Code and DB schema versions are the same. No migration needed." schema=14 subsystem_name=built-in_plugin.sql version_info=0.10.0
> time="2020-07-28T14:45:32Z" level=info msg="Connected to SQL database" read_only=false subsystem_name=built-in_plugin.sql type=sqlite3 version=3.25.2
> time="2020-07-28T14:45:32Z" level=info msg="Plugin loaded." built-in_plugin=true plugin_name=sql plugin_services="[]" plugin_type=DataStore subsystem_name=catalog
> time="2020-07-28T14:45:32Z" level=info msg="Plugin loaded." built-in_plugin=true plugin_name=k8s_sat plugin_services="[]" plugin_type=NodeAttestor subsystem_name=catalog
> time="2020-07-28T14:45:32Z" level=error msg="fatal run error" error="no such UpstreamAuthority builtin \"vault\""
> time="2020-07-28T14:45:32Z" level=error msg="server crashed" error="no such UpstreamAuthority builtin \"vault\""
> 

* **Version**: gcr.io/spiffe-io/spire-server:0.10.0
* **Platform**: Kubernetes Atomic-Centos
* **Subsystem**: UpstreamAuthority

Section of configuration added under plugin section inside spire-server configmap:

      UpstreamAuthority "vault" {
        plugin_data {
            vault_addr = "http://vault.default.svc.cluster.local:8200/"
            pki_mount_point = "pki"
            ca_cert_path = "/run/spire/ca/ca.pem"
            token_auth {
               token = "s.bkhum1mAqeF0Mf66hKGNWXAP"
            }
        }
      }

Checked the token works against the vault outside the instance and the ca.pem file is present at the mount point

**Comment by azdagron** [comment]
It appears you are using spire 0.10.0? The `vault` UpstreamAuthority plugin did not land until 0.10.1.

**Comment by azdagron** [comment]
Considering the above, I'll close the issue. Please feel free to re-open if it does not identify the plugin with 0.10.1.

**Comment by Taranasaur** [comment]
Thanks, now working. That was the issue
