### ISSUE TITLE
Use T.TempDir for temporary directory creation in tests

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#1758]
Go 1.15 includes a convenience method for creating a temporary directory in tests that is automatically cleaned up:

https://tip.golang.org/pkg/testing/#T.TempDir

We have our own facilities for this. It would be nice once go1.15 is adopted in the project to leverage this feature.

**Comment by SilvaMatteus** [comment]
Hello @azdagron. Should this issue be closed? I was looking for good first issues, but this issue seems to be resolved.

Issue #835 seems to be resolved too.

**Comment by azdagron** [comment]
Hi @SilvaMatteus!

> I was looking for good first issues
:heart: 

>  but this issue seems to be resolved.

We have our own helper right now (`spiretest.TempDir`). Go1.15 added a `TempDir` method to `testing.T` and `testing.B` that we'd rather use instead. As a project, we haven't yet moved to Go1.15. However, it has been out long enough that we're probably ok doing so.

**Comment by azdagron** [comment]
I'll comment on #835, I think there is an opportunity for a quick win there to close that out.

**Comment by evan2645** [comment]
> As a project, we haven't yet moved to Go1.15. However, it has been out long enough that we're probably ok doing so.

@SilvaMatteus if you're looking to pick this up, please feel free to bump the project to 1.15. You should be able to find how to do that by looking at the git history as well as grepping the repo for the current version number (1.14.6). You can address this issue (moving to the upstream TempDir helper) at the same time if you like. These are both things we've been meaning to do but haven't got around to yet.

Thanks in advance! And please let us know if you have any questions along the way

**Comment by sachinkumarsingh092** [comment]
Hi @azdagron @evan2645, can we close this issue now?
