### ISSUE TITLE
SPIRE Server cli default TTL entry creation should use actual config

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#1759]
https://github.com/spiffe/spire/blob/master/cmd/spire-server/cli/entry/create.go#L234

If TTL is not set in the command, it defaults to 1 hour. It would be more convenient to operators if the default was whatever SPIRE Server happened to be configured for the `default_svid_ttl` setting. This would mimic closer what the RPC-version of the command does.

**Comment by azdagron** [comment]
I agree that getting the default SVID ttl is the least surprising. I've been bitten by the CLI default before. That being said, if we change this behavior, we may need to do it across two releases so we can inform people of the upcoming change in behavior.

**Comment by mcpherrinm** [comment]
I think this makes a lot of sense.  We should make sure to put a note in the release notes that this is changing, as it is a user-visible change, even if it's not likely to break anything for anyone.

**Comment by azdagron** [comment]
The default value for the `default_svid_ttl` is the same as the CLI (one hour) and our example configs also specify one hour so I think the risk to backcompat is low.

**Comment by amartinezfayo** [comment]
>I think this makes a lot of sense. We should make sure to put a note in the release notes that this is changing, as it is a user-visible change, even if it's not likely to break anything for anyone.

I'll make sure to include this change in the CHANGELOG for the release. Since the default value for the `default_svid_ttl` is the same as the CLI I think that the risk of breaking something is really low.

**Comment by azdagron** [comment]
Since the risk is so low is it overkill going with the deprecation route? The downside I think is that unless folks specify a TTL, we'll be printing a warning message on every entry creation, which could smell a little.

Thoughts @mcpherrinm and @amartinezfayo?

**Comment by amartinezfayo** [comment]
I think that it would be overkill to go with the deprecation route here. It would affect the experience with no benefit in the vast majority of cases. I'm ok with just changing the behavior.
