### ISSUE TITLE
logging traceability of Server API callers

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#1776]
It would be helpful to log available information about the caller such as the address from the calling context (ex. https://godoc.org/google.golang.org/grpc/peer#Peer).
In a large deployment environment, being able to have additional information to track down poorly/oddly behaving callers would go a long way towards maintaining operations at scale.

I encountered this need while triaging server error logs for failed attestations, and noticed there is a lack of information about the caller. This means that combined logs/metrics of agents must be combed through, assuming it was an agent calling at all. Having at least caller's address would be a good start, and if needed we could always extend later to add more information.
While this was encountered for node attestation, it's likely the solution could be applied as a common feature of all/most endpoints.

**Comment by azdagron** [comment]
Thanks for bringing this up! The new server APIs have this already. The logger passed into each handler is already adorned with the caller address and (if available) SPIFFE ID. We'll be cutting agents over to the new API before our next release. Considering that, I'm not sure if it is worth going back and fixing up the old API but I wouldn't balk at a PR that introduced it, since the old APIs are not going to be deprecated any time soon.

**Comment by amoore877** [comment]
> Thanks for bringing this up! The new server APIs have this already. The logger passed into each handler is already adorned with the caller address and (if available) SPIFFE ID.

excellent :)

> We'll be cutting agents over to the new API before our next release. Considering that, I'm not sure if it is worth going back and fixing up the old API

If agents are moving over soon-ish, then yeah probably not worth it IMO. Maybe a nice-to-have if anyone is calling server with their own custom agent implementation.

I'd be fine having this issue closed, though maybe there's some value in keeping it open in case someone decides they want to pick up doing such a fix on the old APIs before they are removed? Either way.

**Comment by azdagron** [comment]
I think we'll close this for now. If folks using the old APIs bring this up, it will be a good opportunity to promote usage of the new APIs.
