### ISSUE TITLE
Add AttestLimit configurable for agent IP throttling/rate limiting

### ISSUE THREAD

**Issue by scotte** [spiffe/spire#1778]
Currently, AttestLimit is hardcoded in https://github.com/spiffe/spire/blob/master/proto/spire/api/node/limits.go#L7 but when using a load balancer this will pose a problem when there are a large number of agents. It would be useful to expose this as a configurable in the spire-server configuration.

Loosely related: #753

**Comment by azdagron** [comment]
Seems reasonable considering there is no real workaround.

**Comment by evan2645** [comment]
> when using a load balancer this will pose a problem when there are a large number of agents

I'd love to hear more about the reasons for putting a load balancer between agents and servers. There is a lot of client-side load balancing logic built into the agent (and a lot of work has been done on that front), and I'd imagine the most efficient setup would be to lean on that logic and leave intermediary load balancers out of the picture. Personally, I've been discouraging LB use between agents and servers.

**Comment by scotte** [comment]
In the current case I'm working on, SPIRE servers are in a control plane running inside an Istio mesh, agents are outside, with an ingress gateway as the only public access point into the control plane. You can personally discourage it all you want :-). The reality is that it is an extremely common and well understood topology, and unfortunately puts an unnecessary limitation on SPIRE. SPIRE doesn't get to choose the network topology of deployment. In many cases the network is already built out, and given the choice of adopting SPIRE or changing the network topology means SPIRE doesn't get adopted.

**Comment by evan2645** [comment]
> SPIRE doesn't get to choose the network topology of deployment

Fair enough!
--
evan
