### ISSUE TITLE
Make sure we have testing for all proto buffer interfaces

### ISSUE THREAD

**Issue by drrt** [spiffe/spire#18]
_From @kunzimariano on August 7, 2017 21:11_

**NodeAgent**
Plugins 
- [ ] Workload Attester 
- [ ] Key Manager 
- [ ] Node Attester 

API 

- [ ]  Workload API 

_Copied from original issue: spiffe/node-agent#36_

**Comment by walmav** [comment]
Decided to close it and make sure our test coverage handles this.
