### ISSUE TITLE
Minting SVID cannot accept asterisk(*) as a DNS label.

### ISSUE THREAD

**Issue by dr-shim** [spiffe/spire#1809]
* **Version**:  v0.10.1
* **Platform**: linux/amd64
* **Subsystem**: server

I've already posted this issue on the Slack channel, but I think I need to post it on this issue page either.

I found a problem while minting SVID by using Spire server UDS.

```bash
/opt/spire/bin #  ./spire-server x509 mint -spiffeID spiffe://infra.samecloud.com/aa/aa -dns "*.infra.samecloud.com"
error: unable to mint SVID: rpc error: code = InvalidArgument desc = invalid DNS name: label does not match regex: *
```

It seems minting SVID cannot accept `*` as a DNS label even though `*.infra.samecloud.com` is a valid SAN for a certificate. 

This seems to be caused by this codes,

https://github.com/spiffe/spire/blob/368ceb58356c42454a65d9fb937d62e68a90ebba/pkg/server/endpoints/registration/handler.go#L984

https://github.com/spiffe/spire/blob/368ceb58356c42454a65d9fb937d62e68a90ebba/pkg/server/endpoints/registration/handler.go#L33

Is it an error? Or, did I make any mistake?

**Comment by azdagron** [comment]
Hi @dr-shim ! Thanks for bringing this up. Support for wildcard DNS names were intentionally excluded from the DNSNames feature. Can you elaborate on your use case?

**Comment by dr-shim** [comment]
> Hi @dr-shim ! Thanks for bringing this up. Support for wildcard DNS names were intentionally excluded from the DNSNames feature. Can you elaborate on your use case?

I'm going to mint a x509 SVID and use it on my web server. You know, a web server domain might have many sub domains and I want to use a single certificate for those sub domains.

**Comment by 0123hoang** [comment]
I'm struggling with same issue, how can I do that?

**Comment by cb-troydai** [comment]
I have needs for this feature, and I'm happy to write down my scenario. Shall I start a new issue or reopen this one. @evan2645

**Comment by evan2645** [comment]
Hi @cb-troydai really appreciate the use case contribution - a new issue that references this one is best ☺️ thank you!

**Comment by cb-troydai** [comment]
Opened. And I cross referenced this issue. Happy to chat more deep into this on the new thread. My team operates both service mesh and SPIFFE/SPIRE infrastructure, I believe there is a good case to make to improve this integration.
