### ISSUE TITLE
Question-  How to create automatic registration entries for workloads

### ISSUE THREAD

**Issue by PriyaKatkade** [spiffe/spire#1810]
I just have started reading SPIFFE/SPIRE. Its looks really amazing. I am totally new to this but whatever I have gone through I see creating workload registration entry process is manual. I gone through different examples where services are started first. Once all services are started, there is script which connects to container(spire-server) and then execute **spire-server entry create** command in it. And so after executing the script, registration entries get created for workloads.

This is okay for development environment but what about production environment? So unlike development environment we can't execute commands by connecting to spire-server container. Also there is chance of container restart, so do I need to register workloads again and again.

There must be some way to automatically create registration entries for workloads while starting up the workload.

Will you please tell me, is there any automatic way to create registration entries for workload? It will be really helpful for me as  stuck there.

Thanks

**Comment by martincapello** [comment]
Hi! As far as I can tell, you don't need to create the registration entries every time your SPIRE Server is restarted, this is due to the fact that they are stored in the Datastore (if you look at the picture here https://spiffe.io/docs/latest/spire/understand/concepts/#all-about-the-server you can see that the server has an internal component called Datastore).

**Comment by ajessup** [comment]
Hi Priya, is your challenge that you need to re-register workloads each time your SPIRE server starts up? Or that after the server has started developers might deploy new workloads to k8s that need to be registered?

**Comment by PriyaKatkade** [comment]
> Hi! As far as I can tell, you don't need to create the registration entries every time your SPIRE Server is restarted, this is due to the fact that they are stored in the Datastore (if you look at the picture here https://spiffe.io/docs/latest/spire/understand/concepts/#all-about-the-server you can see that the server has an internal component called Datastore).

Thank you @martincapello. Yeah, I know there is Datastore which keeps entry details in it. But for the first time I need to create registration entries manually. So, I am talking about that first time registration process.

**Comment by PriyaKatkade** [comment]
> Hi Priya, is your challenge that you need to re-register workloads each time your SPIRE server starts up? Or that after the server has started developers might deploy new workloads to k8s that need to be registered?

Hi @ajessup ,
My challenge is that after the server has started developers might deploy new workloads to k8s that need to be registered. Also how to create registration entries for the first time when SPIRE server starts-up.

I came through k8s-workload-registrar which facilitates automatic workload registration within Kubernetes. But I didn't find any working example for that. Will you please help me if you have any?

Thanks

**Comment by ajessup** [comment]
k8s-workload-registrar is definitely the right place to be looking to automate this problem. There's no tutorial currently that I'm aware of, but developing one would be a good idea. I've filed https://github.com/spiffe/spire/issues/1812 to track this.
