### ISSUE TITLE
Question- Configuration for "k8s-workload-registrar". 

### ISSUE THREAD

**Issue by PriyaKatkade** [spiffe/spire#1811]
I am referring https://github.com/spiffe/spire/tree/master/support/k8s/k8s-workload-registrar for "k8s-workload-registrar".

I have provided below configuration:
   ```
 server_address = "spire-server"
    server_socket_path = "/run/spire/sockets/registration.sock"
    trust_domain = "example.org"
    log_level = "DEBUG"
    cluster = "demo-cluster"
    cert_path = "/run/registrar/certs/server-cert.pem"
    key_path = "/run/registrar/secret/server-key.pem"
    cacert_path = "/run/registrar/certs/cacert.pem"
```
And I am deploying it as a container in SPIRE server pod. As per the documentation I have shared volume for socket file between SPIRE server and k8s-workload-registrar. But when I use this configuration, I am getting below errors:

**SPIRE-server**
`time="2020-08-31T07:33:58Z" level=warning msg="Connection failed during accept." error="could not resolve caller information" subsystem_name=endpoints`

**k8s-workload-registrar**
```
time="2020-08-31T07:29:40Z" level=info msg="Dialing server" socket_path=/run/spire/sockets/registration.sock
time="2020-08-31T07:29:40Z" level=info msg="Initializing registrar"
rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection closed
	main.(*Controller).createEntry:227
	main.(*Controller).Initialize:44
	main.run:56
	main.main:21
	runtime.main:203
time="2020-08-31T07:29:40Z" level=error msg="Failed to create pod entry" error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection closed" parent_id="spiffe://example.org/spire/server" selectors="k8s_psat:cluster:demo-cluster" spiffe_id="spiffe://example.org/k8s-workload-registrar/demo-cluster/node"

```

will anyone please help me to get out of this. It will be good If anyone have the demo example for k8s-workload-registrar.

**Comment by azdagron** [comment]
SPIRE server, until recently, required that processes connecting to it over a unix domain socket be in the same process namespace. That restriction has been lifted (https://github.com/spiffe/spire/pull/1660) but hasn't quite made it into a release yet. Luckily, we've been preparing for a new release this last week.

You have a few options:

1. wait for the 0.11.0 release (this will probably release today or tomorrow)
2. use a SPIRE image from a recent commit (these are available in the gcr.io/spiffe-io registry)
3. configure your Pod spec to share a process namespace between the SPIRE server and k8s-workload-registrar container (i.e. `shareProcessNamespace: true`)

**Comment by azdagron** [comment]
I'll close this for now. Please let me know if one of the above options does not work out for you.
