### ISSUE TITLE
Document a tutorial for the Kubernetes registrar

### ISSUE THREAD

**Issue by ajessup** [spiffe/spire#1812]
While the k8s-registrar (https://github.com/spiffe/spire/tree/master/support/k8s/k8s-workload-registrar) is internally well documented, it is not easy to discover, nor is there any tutorial on how to configure it. Setting this up would be a good "201" style tutorial to follow on from the "101" tutorial of getting SPIRE up and running in Kubernetes.

**Comment by azdagron** [comment]
Thanks for opening this @ajessup. Since the k8s-workload-registrar is being deprecated, I'll go ahead and close this out.
