### ISSUE TITLE
Envoy TLS Certificates not picking up on removed trust bundles from SPIRE / SPIFFE

### ISSUE THREAD

**Issue by cyt3ea** [spiffe/spire#1816]
Also posted on slack here: https://spiffe.slack.com/archives/CBNCC2V17/p1598559156057500

I've configured using Envoy with SPIRE / SPIFFE and check that TLS certificates are set in Envoy correctly by going to `localhost:9901/certs` after doing a port forward for the envoy gateway. The behavior I'm currently seeing is when I update a spire-server registration entry with a new federation using `entry update`, the Envoy TLS certs will be up to date. However, when I update a spire-server registration entry by removing a federation also using `entry update`, the TLS certs in Envoy are not updated until I completely restart the Envoy gateway.

I think since the Envoy gateway in a production environment will be serving traffic, it seems like having to completely restart Envoy is undesired and given that Envoy will update correctly when adding but not removing a federation also seems like this might be a bug.

Not sure if this is caused by any sort of misconfiguration, but would love some help troubleshooting or finding a workaround / solution for this. Thank you!!

**Comment by azdagron** [comment]
I've confirmed that SPIRE's SDS implementation returns a response with an empty resource set to Envoy when the federation  relationship is removed on the entry. From an envoy/xDS standpoint, i'm not sure this kind of "revocation" action is possible. It is likely holding onto the previously returned certificate. I'll dig in and see what I can find.

**Comment by azdagron** [comment]
From my reading of https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#deleting-resources, I think we need to implement the incremental protocol (i.e. DeltaSecrets RPC) in order to get Envoy to recognize the removal.

**Comment by evan2645** [comment]
Hmm I'm not sure of any workaround with the current codebase other than restarting Envoy. There's some work involved in implementing the new RPC that would allow us to properly remove the resource from Envoy, and it could take some time. Any chance you'd be willing to make such a contribution? We'd be happy to show you a detailed way forward on that if so.

Otherwise, I wonder if rather than return an empty resource, we should return one with bogus data, and/or a cert that we know won't work? I'm not sure how much validation Envoy does on what we send it. That change would be less involved and likely to ship sooner rather than later...

@azdagron any further ideas on how folks might be able to work around this issue given the current state of the world?

**Comment by azdagron** [comment]
> we should return one with bogus data, and/or a cert that we know won't work
That is thinking outside of the box :) I'm pretty confident that would work. It would certainly span the gap until somebody got around to implementing `DeltaSecrets`...

**Comment by JonathanO** [comment]
The SDS protocol doesn't seem to support removal of secrets at all, even with the delta protocol.

If you check sds_api.cc you can see that the SDS implementation assumes that all updates, whether SoTW or delta, contain exactly 1 secret in resources/added_resources and throws an exception if not. The delta version of the onConfigUpdate method ignores the removed_resources argument completely.

**Comment by azdagron** [comment]
Boy, that is unfortunate. Considering that, I think Evan's suggestion about about returning a bogus CA certificate seems to get us the desired functionality even if a little hard to debug/reason about.

**Comment by evan2645** [comment]
Do we need an issue in Envoy? Or it is a wontfix? Maybe @lizan has an opinion, he has been working on envoy support for spiffe federation

**Comment by azdagron** [comment]
I believe that this now works fine with the SPIFFEValidator support in Envoy. Please re-open if that isn't the case.
