### ISSUE TITLE
Confirm the behaviour of spire-agent, spire-server and spire-registrar

### ISSUE THREAD

**Issue by PriyaKatkade** [spiffe/spire#1822]
I am using Minikube for deployment.
Minikube version: v1.12.3
Kubernetes version: v1.18.3

I am using below helm chart for spire deployment.
https://github.com/DecipherNow/helm-charts/tree/release-2.3/spire

PSAT plugin is used for node attestation and k8s plugin for workload attestation. Also I have configured the Minikube as per guidelines.
https://spiffe.io/docs/latest/spire/installing/getting-started-k8s/#considerations-when-using-minikube

Along with this chart I am deploying demo application with two micro-services/workloads (frontend, backend). Envoy SDS is configured in this micro-services.

**Expectation behaviour**
As per reading, as soon as spire-agent get starts, it will establish trust with spire-server and after successful authentication between spire-agent and spire-server, and node attestation process gets completed, the spire-server should issue identity to agent in the form SVID. And so, the registrar should use this identity as a parenID while creating entries for workloads.

**Actual behaviour**
After deploying helm chart, two pods are created for agent and server.
Below logs are there-
**Server**
```
time="2020-09-04T07:02:05Z" level=warning msg="Current umask 0022 is too permissive; setting umask 0027."
time="2020-09-04T07:02:05Z" level=info msg="data directory: \"/run/spire/data\""
time="2020-09-04T07:02:05Z" level=info msg="Plugin loaded." built-in_plugin=true plugin_name=k8s_psat plugin_services="[]" plugin_type=NodeAttestor subsystem_name=catalog
time="2020-09-04T07:02:05Z" level=info msg="Plugin loaded." built-in_plugin=true plugin_name=noop plugin_services="[]" plugin_type=NodeResolver subsystem_name=catalog
time="2020-09-04T07:02:05Z" level=info msg="Plugin loaded." built-in_plugin=true plugin_name=disk plugin_services="[]" plugin_type=KeyManager subsystem_name=catalog
time="2020-09-04T07:02:05Z" level=info msg="Plugin loaded." built-in_plugin=true plugin_name=k8sbundle plugin_services="[]" plugin_type=Notifier subsystem_name=catalog
time="2020-09-04T07:02:05Z" level=info msg="Plugin loaded." built-in_plugin=true plugin_name=disk plugin_services="[]" plugin_type=UpstreamCA subsystem_name=catalog
time="2020-09-04T07:02:05Z" level=info msg="Opening SQL database" db_type=sqlite3 subsystem_name=built-in_plugin.sql
time="2020-09-04T07:02:05Z" level=info msg="Initializing new database." subsystem_name=built-in_plugin.sql
time="2020-09-04T07:02:05Z" level=info msg="Connected to SQL database" read_only=false subsystem_name=built-in_plugin.sql type=sqlite3 version=3.25.2
time="2020-09-04T07:02:05Z" level=info msg="Plugin loaded." built-in_plugin=true plugin_name=sql plugin_services="[]" plugin_type=DataStore subsystem_name=catalog
time="2020-09-04T07:02:05Z" level=info msg="plugins started"
time="2020-09-04T07:02:05Z" level=info msg="Journal loaded" jwt_keys=0 subsystem_name=ca_manager x509_cas=0
time="2020-09-04T07:02:05Z" level=info msg="X509 CA prepared" expiration="2020-09-05T07:02:05Z" issued_at="2020-09-04T07:02:05Z" self_signed=false slot=A subsystem_name=ca_manager upstream_bundle=true
time="2020-09-04T07:02:05Z" level=info msg="X509 CA activated" expiration="2020-09-05T07:02:05Z" issued_at="2020-09-04T07:02:05Z" slot=A subsystem_name=ca_manager
time="2020-09-04T07:02:05Z" level=info msg="JWT key prepared" expiration="2020-09-05T07:02:05Z" issued_at="2020-09-04T07:02:05Z" slot=A subsystem_name=ca_manager
time="2020-09-04T07:02:05Z" level=info msg="JWT key activated" expiration="2020-09-05T07:02:05Z" issued_at="2020-09-04T07:02:05Z" slot=A subsystem_name=ca_manager
time="2020-09-04T07:02:05Z" level=info msg="Starting UDS server" address=/run/spire/socket/registration.sock subsystem_name=endpoints
time="2020-09-04T07:02:05Z" level=info msg="Starting TCP server" address="[::]:8443" subsystem_name=endpoints
time="2020-09-04T07:02:13Z" level=info msg="Node attestation request completed" address="172.17.0.2:39654" attestor=k8s_psat method=node_api spiffe_id="spiffe://example.org/spire/agent/k8s_psat/example/5f97c121-8ad5-408f-8874-13367e028910" subsystem_name=node_api
```

**Registrar**
```
time="2020-09-04T07:02:06Z" level=info msg="Dialing server" socket_path=/run/spire/socket/registration.sock
time="2020-09-04T07:02:06Z" level=info msg="Initializing registrar"
time="2020-09-04T07:02:06Z" level=info msg="Created pod entry" parent_id="spiffe://example.org/spire/server" selectors="k8s_psat:cluster:example" spiffe_id="spiffe://example.org/k8s-workload-registrar/example/node"
time="2020-09-04T07:02:06Z" level=info msg="Serving HTTPS" addr="[::]:8444" skip_client_verification=true
2020/09/04 07:02:12 http: TLS handshake error from 172.17.0.2:46775: EOF
```

**Agent**
```
time="2020-09-04T07:05:47Z" level=warning msg="Current umask 0022 is too permissive; setting umask 0027."
time="2020-09-04T07:05:47Z" level=info msg="Starting agent with data directory: \"/run/spire\""
time="2020-09-04T07:05:47Z" level=info msg="Plugin loaded." built-in_plugin=true plugin_name=memory plugin_services="[]" plugin_type=KeyManager subsystem_name=catalog
time="2020-09-04T07:05:47Z" level=info msg="Plugin loaded." built-in_plugin=true plugin_name=k8s plugin_services="[]" plugin_type=WorkloadAttestor subsystem_name=catalog
time="2020-09-04T07:05:47Z" level=info msg="Plugin loaded." built-in_plugin=true plugin_name=unix plugin_services="[]" plugin_type=WorkloadAttestor subsystem_name=catalog
time="2020-09-04T07:05:47Z" level=info msg="Plugin loaded." built-in_plugin=true plugin_name=k8s_psat plugin_services="[]" plugin_type=NodeAttestor subsystem_name=catalog
time="2020-09-04T07:05:48Z" level=info msg="Renewing X509-SVID" spiffe_id="spiffe://example.org/k8s-workload-registrar/example/node" subsystem_name=manager
time="2020-09-04T07:05:48Z" level=info msg="Starting workload API" subsystem_name=endpoints
```

So after deploying my application, two pods created and registrar creates registration entries for that pods. 
For command **agent list**, following output is there.
```
Found 1 attested agent:

Spiffe ID         : spiffe://example.org/spire/agent/k8s_psat/example/5f97c121-8ad5-408f-8874-13367e028910
Attestation type  : k8s_psat
Expiration time   : 2020-09-04 08:05:48 +0000 UTC
Serial number     : 4253764676667946721233694556574268225
```
If I execute `entry show` in spire-server container it gives below list of entries:
```
Entry ID      : e03eeb68-c958-4747-b7e1-b393c01ac900
SPIFFE ID     : spiffe://example.org/backend
Parent ID     : spiffe://example.org/k8s-workload-registrar/example/node
TTL           : default
Selector      : k8s:ns:default
Selector      : k8s:pod-name:spire-helm-backend-6dcd58475d-9p9xv

Entry ID      : 85cd1201-021c-46e0-9a88-46c96fcbd106
SPIFFE ID     : spiffe://example.org/frontend
Parent ID     : spiffe://example.org/k8s-workload-registrar/example/node
TTL           : default
Selector      : k8s:ns:default
Selector      : k8s:pod-name:spire-helm-frontend-58c85b64bf-twmlh

Entry ID      : 8b44d589-2c49-4335-ac64-86ddbb392423
SPIFFE ID     : spiffe://example.org/k8s-workload-registrar/example/node
Parent ID     : spiffe://example.org/spire/server
TTL           : default
Selector      : k8s_psat:cluster:example
```

So here if we observed parentID, its different than agent's SPIFFEID. So here I am getting confused whether this behaviour is right or wrong?
Also if I execute **api fetch** in agent container, it gives below error:
`rpc error: code = PermissionDenied desc = no identity issued`

Also after deploying my application agent shows below logs:
```
time="2020-09-04T07:45:00Z" level=error msg="No identity issued" error="<nil>" registered=false subsystem_name=workload_api
time="2020-09-04T07:45:12Z" level=info msg="Renewing X509-SVID" spiffe_id="spiffe://example.org/backend" subsystem_name=manager
time="2020-09-04T07:45:12Z" level=info msg="Renewing X509-SVID" spiffe_id="spiffe://example.org/frontend" subsystem_name=manager
```

So here I am getting confused about its behaviour. Because parentID for pod entries is different then agent SPIFFEID but workloads are getting their identity and workloads can communicate each other over mTLS.

So whats wrong here? Or this is right behaviour.

**Comment by azdagron** [comment]
This behavior is in line with the webhook mode of the registrar (the default). The parent ID of the workload entries is `spiffe://example.org/k8s-workload-registrar/example/node`, which is a cluster-wide ID given to all agents belonging to that cluster. The registration entry that provides that is the following node registration entry:

```
Entry ID      : 8b44d589-2c49-4335-ac64-86ddbb392423
SPIFFE ID     : spiffe://example.org/k8s-workload-registrar/example/node
Parent ID     : spiffe://example.org/spire/server
TTL           : default
Selector      : k8s_psat:cluster:example
```

Any agent that is attested via `k8s_psat` belonging to the `example` cluster is given the ID `spiffe://example.org/k8s-workload-registrar/example/node`. This means that your two workload registrations are registered to run on any agent in that cluster.

The reason for such a broad registration (i.e. any workload can run on any agent) is because when the admission controller webhook is invoked, it does not have any insight into which node the pod will be scheduled, so it does not have the information it would need to make a more granular, scoped registration.

The newer registrar modes (e.g. `reconcile` and `CRD`) DO know what node the pod is being scheduled on, and therefore scope a workload registration to the specific node the pod for the workload is being scheduled on.

As far as the `api fetch` command failing to return an identity, you've run that in the agent container. There is no workload registration set up that would match a "workload" running in that container. However, i imagine if you did an `exec` in the `spire-helm-backend-6dcd58475d-9p9xv` or `spire-helm-frontend-58c85b64bf-twmlh` pods, that it would be able to return an identity (based on the workload registrations above).

**Comment by PriyaKatkade** [comment]
Thanks @azdagron 
I got it. I gone through the document again and understand the working of webhook.

So what mode do you recommend to use? As per document, webhook mode has some issues which are not there in reconcile and crd mode. So which mode will you recommend to use?

**Comment by azdagron** [comment]
Both the CRD and reconcile modes offer different benefits. That being said, the CRD mode is more complicated to use and deploy so unless you have a specific use case that drives CRD-based registration, I'd probably try out the `reconcile` mode first.

**Comment by azdagron** [comment]
I'll close this issue for now. Please re-open if you feel the need!
