### ISSUE TITLE
Update `spire-server` CLI utility to use the refactored APIs

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#1826]
SPIRE Server has a [new suite of APIs](https://github.com/spiffe/spire/tree/master/proto/spire/api/server), but the CLI utility still uses the legacy registration API. Update it to consume the new APIs

**Comment by amartinezfayo** [comment]
Created sub-tasks (#1850, #1851, #1852, #1853, #1854, #1855, #1856, #1857) for this and a [project](https://github.com/spiffe/spire/projects/7) to track the progress.

Closing this issue, as it is covered by the created issues.
