### ISSUE TITLE
Determine how long k8s_sat node attestor should be supported for

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#1827]
There has been some desire to deprecate the `k8s_sat` node attestor in favor of the `k8s_psat` attestor (see [security considerations note](https://github.com/spiffe/spire/blob/master/doc/plugin_server_nodeattestor_k8s_sat.md#security-considerations)), however we held off as a number of cloud providers had yet to implement the projected token feature needed for `k8s_psat` to work.

Determine a timeline for `k8s_sat` deprecation based on the state of public support for projected service account tokens.

**Comment by srwaggon** [comment]
(with @adobley)

We looked at the major Cloud Providers to determine when they introduced the projected token feature needed for the `k8s_psat` node attestor.

Are there others that we would want to investigate as part of this issue?

Here were our findings:

## [Service Account Token Volume Projection](https://v1-19.docs.kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection)
- Beta in Kubernetes 1.12
- Stable in Kubernetes 1.20

## Amazon Elastic Kubernetes Service (EKS)
- Introduced support for SATVP in [2019 September](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/)
- Oldest currently supported EKS version was released in [March 2020](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar)
- **Conclusion:** We believe that SATVP is fully supported presently in EKS.

## Google Kubernetes Engine (GKE)
- A set of Google Employees [published an article](https://cloud.google.com/community/tutorials/gke-workload-id-clientserver) detailing usage of the SATVP feature being available to GKE as early as Kubernetes 1.12.
- GKE [currently supports](https://cloud.google.com/kuberun/docs/cluster-versions) versions 1.20 - 1.15 of the GKE control plane. We assume that the GKE control plane versions map to the releases of Kubernetes but are lacking evidence.
- **Conclusion:** Uncertain. SATVP seems to be currently supported across all currently supported versions of GKE, but we have not found hard evidence yet.

## Azure Kubernetes Service (AKS)
- Introduced support for SATVP in [2020 February](https://github.com/Azure/AKS/blob/master/CHANGELOG.md#release-2020-02-24)
- Oldest currently supported AKS version was released in [2020 July](https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions#aks-kubernetes-release-calendar)
- **Conclusion:** We believe that SATVP is fully supported presently in AKS.

For each of these cloud providers, it was difficult to find concrete evidence for when support for Service Account Token Volume Projection became available, such a release notes or a change log.

For further exploration, an alternative approach would be to setup respective Kubernetes clusters for each cloud provider and manually test for the feature.

**Comment by azdagron** [comment]
We've opened #3495 to deprecate the SAT attestor. Thank you so much @srwaggon and @adobley for doing the initial research on this.
