### ISSUE TITLE
Use go-spiffe v2 types

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#1828]
The go-spiffe v2 library introduced strong types for SPIFFE IDs, trust domains, and bundles. Using these types across the SPIRE codebase would provide uniformity and reduce opportunity for bugs and mishandling.

This work should probably be bitten off in small chunks in order to keep things scoped and auditable.

**Comment by azdagron** [comment]
I've tackled most of the agent side while I've been working through #1847. There are a LOT of side effects to changing these types over, particularly in the boundary between units and often more significantly, unit tests. I'd suggest this work be tackled unit-by-unit, otherwise it will be quite hard to review :)

**Comment by maxlambrecht** [comment]
I'm tackling the server units `ca` and `endpoints` and probably will need to tackle some side-effects on related units.

**Comment by bri365** [comment]
Closing #2232 Clarify type and usage by using the appropriate spiffeid types (e.g. spiffeid.TrustDomain and spiffeid.ID) in favor of tracking here.

**Comment by azdagron** [comment]
I think most of the server code is done. We still need to go through the agent side, particularly the use of the bundleutil package.

**Comment by guilhermocc** [comment]
Hey there, I would like to contribute by continuing to resolve this issue, could it be assigned to me, please?

**Comment by azdagron** [comment]
Awesome! There are bound to be a lot of changes. Where possible, in order to prevent review fatigue, I suggest sending a PR for  one unit at a time.

**Comment by guilhermocc** [comment]
So far, I've mapped the following agent units that need to be updated to use go-spiffe types:
- api [✔️]
- attestor [🎯] 
	- node: using bundleutil.Bundle in `AttestationResult` struct
	- workload [✔️]
- catalog [✔️]
- client [🎯]: Use custom types X509SVID and JWTSVID; check if we need/can replace them with go-spiffe types.
- common [✔️]
- endpoints [❓] 
- manager [❓] 
- plugin [❓]
- storage [❓]
- svid [❓]
- workloadkey [❓]
