### ISSUE TITLE
Investigate data storage using Cayley

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#1830]
Cayley (https://github.com/cayleygraph/cayley) is an interesting option to explore for storage pluggability in SPIRE with a reduced/simplified interface.

This issue tracks the work prototyping datastore support with cayley.

I've started the work. I'll be updating this issue with my results, including benchmarking. If it pans out, there would likely still need to be additional work implementing various interesting backends for cayley (e.g. etcd). However, it would mean a more low-level granular interface for plugin authors to conform to. SPIRE core could then contain all of the query logic and any necessary data migration mechanics.

**Comment by evan2645** [comment]
Hey @azdagron mind leaving a quick update here?

I think what we found is that the Cayley project is effectively on life support - there is little recent activity and the maintainers have vanished. Is that an accurate assessment?

**Comment by azdagron** [comment]
Yes. The project is more or less inactive. I'd hesitate building a solution leveraging cayley without being without to either fork and strip, or otherwise maintain these portions of the project we'd leverage, which is probably too much to take on.

I think it would be prudent to look in a different direction. If anybody has knowledge of a library that can act as an overlay on a simple storage inferface (e.g. K/V) that allows for a BYODB (bring-your-own-database) approach, feel free to speak up.
