### ISSUE TITLE
Enable CA rotation

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#185]
The CA certificate in spire server should be easily rotated. This has implications on distribution of CA certificate, as well as possible cross-signing since workloads in the trust domain will see this as a root cert rotation. This issue is done when the rotation of the CA certificate is fully automated

**Comment by evan2645** [comment]
There are a number of concerns I would try to keep in mind when working on this... one is, how do workloads with certs minted from the "new" CA trust certs minted by the "old" CA and vice versa?

How do the new CA certificates get propagated, and how long does that take? What implications does this have on both CA and SVID expiration timing? And finally, will the proposed scheme work with the current instantiation of the Workload API?

Another thing to think about is, would it be possible to use the Federation mechanisms in the Workload API to introduce the new (or old) CA certificates?

Some reading:
https://en.wikipedia.org/wiki/X.509#Certificate_chains_and_cross-certification
https://tools.ietf.org/html/rfc5280#section-6
http://www.oasis-pki.org/pdfs/Understanding_Path_construction-DS2.pdf

**Comment by y2bishop2y** [comment]
Need to take into account all the feedback. Opens up the different federation use cases.

Feel that we will move this issue to next Milestone as we research all the different implications.

**Comment by evan2645** [comment]
CA rotation is in and supported for some time now. Workload API now supports push. Closing this out
