### ISSUE TITLE
Update `spire-server bundle` subcommands to consume the refactored server APIs

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#1850]
SPIRE Server has a new suite of APIs, but the CLI commands still use the legacy registration API.
The `spire-server bundle` subcommands are:
- `delete`
- `list`
- `set`
- `show`

Update these subcommands to consume the [new APIs](https://github.com/spiffe/spire/tree/master/proto/spire/api/server).

**Comment by MarcosDY** [comment]
When working on delete federated bundle cmd, I found that we used to have a `delete mode` on delete federated bundle: https://github.com/spiffe/spire/blob/master/proto/spire/api/registration/registration.proto#L75
but actual endpoint does not provide it: https://github.com/spiffe/spire/blob/master/proto/spire/api/server/bundle/v1/bundle.proto#L187
And in implementation we made all deletes to be `RESTRICT `

may I just remove that option from cmd? https://github.com/spiffe/spire/blob/master/cmd/spire-server/cli/bundle/delete.go#L47

What do you think @evan2645 & @azdagron ?
