### ISSUE TITLE
Enable go-plugin checksum

### ISSUE THREAD

**Issue by walmav** [spiffe/spire#187]
Only allow plugins with configured checksum to run

**Comment by y2bishop2y** [comment]
Implement a flag for development. Insecure mode

**Comment by drrt** [comment]
Related #231

**Comment by azdagron** [comment]
The current warning seems sufficient. If an attacker has the ability to overwrite a plugin, they probably have sufficient permissions to mutate config. Plugins should have file system permissions that prevent tampering.
