### ISSUE TITLE
Detect when the codebase version is not bumped following a release

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#1887]
One problem we stumble over occasionally is that it's easy to forget to bump the codebase version number following a release. We should be able to detect this by extending the upgrade compatibility test suite to assert that the current version of the codebase is ahead of the latest version that it's testing against

**Comment by marcosy** [comment]
I think that will tackle the case of someone updating the [version.txt](https://github.com/spiffe/spire/blob/master/test/integration/suites/upgrade/versions.txt) file but forgetting to update the version value in [version.go](https://github.com/spiffe/spire/blob/master/pkg/common/version/version.go)?

I believe, ideally, we want to complement the above with some git verifications that ensure that the nearest preceding tag is lower than the current codebase value in "version.go". 

Does that sound logical/correct?

**Comment by amartinezfayo** [comment]
I think that the approach taken in #1978 is good, thanks @marcosy!
