### ISSUE TITLE
Add integration tests to exercise spire-server CLI commands

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#1889]
We don't really have integration tests that exercise the spire-server CLI commands. Add integration tests for them.

**Comment by lsantire** [comment]
Hello @amartinezfayo . I've implemented the changes to add tests for the _entry_ cli server command into the spire-server-cli test suite. You can find the diff here: [master...lsantire:server-cli-test-entry](https://github.com/spiffe/spire/compare/master...lsantire:server-cli-test-entry).

If it seems like a good solution, I will create a PR.

**Comment by amartinezfayo** [comment]
Hi @lsantire, thanks for this contribution!
That looks good to me. If you open the PR we can discuss from there any implementation detail.
