### ISSUE TITLE
The entry API should allow me to filter entries by federates with

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#1894]
As an operator, I would like to see all the entries that federate with a particular trust domain. This is particularly necessary when trying to delete or remove a trust bundle - are there any entries currently using it? The only way to do this today is to list _all_ entries, then iterate through them looking for the target trust domain name.

https://github.com/spiffe/spire/blob/bda8803756b29428506e66b20b12a65c58817ea0/proto/spire/api/server/entry/v1/entry.proto#L45-L49

**Comment by lsantire** [comment]
Hi, I've been doing some tutorials and working around SPIFFE and SPIRE recently, and I would really like to work on this issue. I have already pictured the solution, but I haven't implemented it yet.

For example, the changes in the proto files I am thinking about are the following ones:

Add _by_federates_with_ field in [spire/proto/spire/api/server/entry/v1/entry.proto](https://github.com/spiffe/spire/blob/bda8803756b29428506e66b20b12a65c58817ea0/proto/spire/api/server/entry/v1/entry.proto#L45-L49)
```proto
 message Filter { 
     spire.types.SPIFFEID by_spiffe_id = 1; 
     spire.types.SPIFFEID by_parent_id = 2; 
     spire.types.SelectorMatch by_selectors = 3; 
     google.protobuf.StringValue by_federates_with = 4; 
 } 
```
Add _by_federates_with_ field in [spire/proto/spire/server/datastore/datastore.proto](https://github.com/spiffe/spire/blob/db11d23501cdb472bed559d2e696bbf0e3a0232c/proto/spire/server/datastore/datastore.proto#L250-L257)
```proto
 message Filter { 
    message ListRegistrationEntriesRequest {
    google.protobuf.StringValue by_parent_id = 1;
    BySelectors by_selectors = 2;
    google.protobuf.StringValue by_spiffe_id = 3;
    Pagination pagination = 4;
    // When enabled, read-only connection will be used to connect to database read instances. Some staleness of data will be observed.
    bool tolerate_stale = 5;
    google.protobuf.StringValue by_federates_with = 6;
}
```
I can share more details about my approach here to discuss about them if needed, or I could just start working on the implementation and open a PR when finished if I am welcome.

Thanks in advance!

**Comment by amartinezfayo** [comment]
Thank you @lsantire for looking into this issue!
We discussed the proposed changes in today's maintainer's call, and we think that it would be good if the filtering by "federates with" is implemented in the same way that is implemented the filtering by selectors.

This would involve having a message `spire.types.FederatesWithMatch` similar to `spire.types.SelectorMatch` in the `Filter` message (entry.proto) and having a message `ByFederatesWith` in the `ListRegistrationEntriesRequest` message similar to the `BySelectors` message (datastore.proto).

What do you think?

**Comment by lsantire** [comment]
Thanks @amartinezfayo, I agree, it seems better to keep this consistent with the way BySelector is implemented, and I guess it won't be much harder to do it this way if I use the selectors filter implementation as guidance.

I'll start working on it, and we can keep discussing about this once I open the PR, but let me know if you have any other comments.
