### ISSUE TITLE
Agent's confusing metrics

### ISSUE THREAD

**Issue by mchurichi** [spiffe/spire#1903]
While documenting metrics, I noticed that there are two metrics being emitted by the SPIRE Agent that can be a little bit confusing.

1. the counter [`workload_api.validate_jwt_svid` ](https://github.com/spiffe/spire/blob/52e9456394f1d85032fb497522ce449ceb8e916e/pkg/common/telemetry/agent/workloadapi/workload.go#L89) is being emitted when [there's an error while validating a JWT SVID](https://github.com/spiffe/spire/blob/52e9456394f1d85032fb497522ce449ceb8e916e/pkg/agent/endpoints/workload/handler.go#L170), but the naming of this metric can be confusing since **the key set isn't declaring that this is an error**, and [the same key set + some labels](https://github.com/spiffe/spire/blob/52e9456394f1d85032fb497522ce449ceb8e916e/pkg/common/telemetry/agent/workloadapi/workload.go#L80) are also being emitted [when the JWT validation is successful](https://github.com/spiffe/spire/blob/52e9456394f1d85032fb497522ce449ceb8e916e/pkg/agent/endpoints/workload/handler.go#L178).
Since this is the only metric I found being emitted to report an error I'm not sure what would be a proper key set, but probably adding an extra `error` key or replacing it with something like `workload_api.validate_jwt_svid_error` could be more accurate.

2. the counter [`sds_api.connections`](https://github.com/spiffe/spire/blob/a9a909a063b7220ca61a6047e60ceadd6cf72ec0/pkg/common/telemetry/agent/sdsapi.go#L14) is being emitted to count the total number of active connections, but I think this needs to be a Gauge instead, since the number of connections can go up and down, and counters shouldn't go down AFAIK. There was a change in https://github.com/spiffe/spire/commit/a9a909a063b7220ca61a6047e60ceadd6cf72ec0 some time ago but it seems like [it was missing the change from Counter to Gauge](https://github.com/spiffe/spire/commit/a9a909a063b7220ca61a6047e60ceadd6cf72ec0#diff-9bfbcb8388909a13d9a9242434fa21eaR15).

* **Version**: 0.11.1
* **Platform**: all
* **Subsystem**: telemetry

**Comment by azdagron** [comment]
I think you are right on both counts. I think adding an explicit metric for failure is probably easier to latch onto if you wanted to build a dashboard around error rates (rather than keying off labels).

Good catch on the failure to switch to a gauge.

Are these things you are willing to open a PR for?

**Comment by mchurichi** [comment]
Hey @azdagron, thanks for looking at this, I will open a PR.
