### ISSUE TITLE
V2 sql datastore migration uses incorrect version of models

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#1922]
https://github.com/spiffe/spire/blob/b35581f3cf2ee41e95c38062b663b8b6007e5bcb/pkg/server/plugin/datastore/sql/migration.go#L289

The V2 migration is using the latest version of the models when it should use the V1 models. This might result in some upgrade migration failures for any existing users on the V2 migration attempting to upgrade to a recent version of SPIRE.

* **Version**: b35581f3cf2ee41e95c38062b663b8b6007e5bcb
* **Platform**: N/A
* **Subsystem**: Server

**Comment by azdagron** [comment]
SPIRE has since moved away from keeping old migration code around, since we require upgrading through all minor releases. In other words, SPIRE no longer has this code in place.
