### ISSUE TITLE
Context (metadata) reset before reaching Workload Attestor Plugins

### ISSUE THREAD

**Issue by SilvaMatteus** [spiffe/spire#1924]
# Summary

Cannot get context's metadata in the plugin's code in the implementation of  the following interface:
- `func (p *Plugin) Attest(ctx context.Context, req *workloadattestor.AttestRequest) (*workloadattestor.AttestResponse, error)`.

* **Version**: b35581f3cf2ee41e95c38062b663b8b6007e5bcb
* **Platform**: any
* **Subsystem**: agent (communication with plugins)

# Detailing

I noticed that the context passed to the `Attest` interface is reset, and in the implementation of a new Workload Attestor Plugin, I can't get metadata sent via Workload API (https://github.com/SilvaMatteus/spire/blob/master/pkg/agent/attestor/workload/workload.go#L84). I need to send some additional metadata to be handled by my custom plugin, in order to attest the workload properly. I found that the context seems to be reset before I handle it in my implementation.

Maybe it is a bug. Someone can let me know if it is the intended behavior?

I made some smalls changes in the SPIRE Agent code (https://github.com/SilvaMatteus/spire/tree/bug-ctx-metadata), in order to clarify where the problem is, and the steps to reproduce are detailed below.

The changes are:

1. New dummy plugin (https://github.com/SilvaMatteus/spire/blob/bug-ctx-metadata/pkg/agent/plugin/workloadattestor/dummy/dummy.go)
2. Small change in `workload.go` to print out the metadata (https://github.com/SilvaMatteus/spire/blob/bug-ctx-metadata/pkg/agent/attestor/workload/workload.go#L85)
3. Small change in `common.go` to add a new example of metadata (https://github.com/SilvaMatteus/spire/blob/bug-ctx-metadata/cmd/spire-agent/cli/api/common.go#L39) (in fact, this metadata in a real scenario should be passed by a library that requests an SVID)

# Steps to reproduce

1 - clone the implementation of the dummy plugin

`git clone https://github.com/silvamatteus/spire -b bug-ctx-metadata && cd spire`

2 - Build SPIRE Server

`go build ./cmd/spire-server/`

3 - Run SPIRE Server

`./spire-server run -config conf/server/server.conf` 

4 - Build and run SPIRE Agent

`./rebuild-and-run-agent.sh`

5 - Register a workload and try the fetch the X.509 SVID to activate the code we want to inspect

```bash
./register-dummy-workload.sh
./spire-agent api fetch x509
```

In the agent's log, it is expected to see some messages like the following:

```
DEBU[0003] New active connection to workload API         subsystem_name=workload_api
[workload.go] SHOW METADATA (1/2): map[:authority:[/tmp/agent.sock] content-type:[application/grpc] dummy-metadata-key:[dummy-metadata-value] user-agent:[grpc-go/1.30.0] workload.spiffe.io:[true]]
[DUMMY WORKLOAD ATTESTOR] Starting Attest Func
[DUMMY WORKLOAD ATTESTOR] SHOW METADATA (2/2): map[:authority:[builtin] content-type:[application/grpc] user-agent:[grpc-go/1.30.0]]
DEBU[0003] PID attested to have selectors                pid=205872 selectors="[type:\"dummy\" value:\"dummy_selector:dummy_value\" ]" subsystem_name=workload_api
DEBU[0003] Fetched X.509 SVID                            count=1 registered=true spiffe_id="spiffe://example.org/scone-workload" subsystem_name=workload_api ttl=116.439134664
DEBU[0003] Closing connection to workload API            subsystem_name=workload_api
```
I expected to see the same value in `workload.go` (SHOW METADATA (1/2)) and in my dummy plugin (SHOW METADATA (2/2)), but it's not the case.

If we uncomment line 90 of `workload.go`, the code works as intended. Uncomment the line and repeat `./rebuild-and-run-agent.sh` and `./spire-agent api fetch x509`. You should see a log like this:

```
INFO[0000] Starting workload API                         subsystem_name=endpoints
DEBU[0004] New active connection to workload API         subsystem_name=workload_api
[workload.go] SHOW METADATA (1/2): map[:authority:[/tmp/agent.sock] content-type:[application/grpc] dummy-metadata-key:[dummy-metadata-value] user-agent:[grpc-go/1.30.0] workload.spiffe.io:[true]]
[DUMMY WORKLOAD ATTESTOR] Starting Attest Func
[DUMMY WORKLOAD ATTESTOR] SHOW METADATA (2/2): map[:authority:[builtin] content-type:[application/grpc] dummy-metadata-key:[dummy-metadata-value] user-agent:[grpc-go/1.30.0] workload.spiffe.io:[true]]
DEBU[0004] PID attested to have selectors                pid=208790 selectors="[type:\"dummy\" value:\"dummy_selector:dummy_value\" ]" subsystem_name=workload_api
DEBU[0004] Fetched X.509 SVID                            count=1 registered=true spiffe_id="spiffe://example.org/scone-workload" subsystem_name=workload_api ttl=115.73704815400001
DEBU[0004] Closing connection to workload API            subsystem_name=workload_api
```

Now, SHOW METADATA (1/2) and SHOW METADATA (2/2) print the same value.

Thanks for reading until here.

Should  I submit a new pull request?

**Comment by evan2645** [comment]
Hello @SilvaMatteus, and thank you for opening this.

I'm curious what you're trying to accomplish by using gRPC context metadata?

The SPIFFE Workload Endpoint spec disallows authentication of its callers, which is why we don't pass this information through (or accept any other kind of information from Workload API callers). Perhaps you can share more about what you're trying to do, and we can see if there are any other solutions?

**Comment by SilvaMatteus** [comment]
Hello @evan2645.

My plugin needs to receive a challenge to verify the workload's properties. This challenge is something that only a trusted workload could have. With this challenge, the plugin can verify if the workload is not lying.

**Comment by evan2645** [comment]
Ah, I see... may I ask the nature of this challenge? What is the workload presenting? Usually challenge/response requires bidirectional communication.

> This challenge is something that only a trusted workload could have.

The SPIFFE/SPIRE threat model considers workloads fully untrusted. This is one reason that we don't generally accept input from the workload. SPIFFE/SPIRE also aim to solve the "secret zero" problem - as such, there is no need for the workload to be in possession of any information (secret or otherwise) prior to contacting the workload API.

I am curious to learn more about your use case. Do the built-in workload attestors not meet your security requirements? Perhaps there is another mechanism we can use to mitigate the threat(s) you have in mind?

**Comment by SilvaMatteus** [comment]
We are considering enclaved applications (Intel SGX), and it simple for them to get something related to their natural identity (which depends on the hash on the application itself). I will consider the out-of-band authenticity check a bit more and detail the pros and cons.

**Comment by evan2645** [comment]
Let's continue the discussion in SIG-SPIRE and on https://github.com/spiffe/spire/issues/1989 which I think more accurately captures what we're trying to accomplish. Since it seems like this issue is no longer relevant, I'm going to go ahead and close it. Thanks again for opening it @SilvaMatteus
