### ISSUE TITLE
Document security disclosure responsibilities in MAINTAINERS.md

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#1927]
SPIRE maintainers receive security disclosures, however the responsibility placed on them in the handling of these disclosures is not documented in MAINTAINERS.md.

Document maintainer responsibility as it relates to security response procedures, including confidentiality and response time requirements.

**Comment by amoore877** [comment]
This seems straightforward to do; is the missing piece a discussion on what the complete list of procedures and requirements should be?
