### ISSUE TITLE
generate_dummy_ca.sh fails with error

### ISSUE THREAD

**Issue by gcohler** [spiffe/spire#1929]
When I run subject script, the key creation succeeds, but the cert creation fails (and hence the rest of the script).

I get the following error:

```
problems making Certificate Request
140582273925568:error:0D07A098:asn1 encoding routines:ASN1_mbstring_ncopy:string too short:../crypto/asn1/a_mbstr.c:100:minsize=1
cp: cannot stat 'dummy_upstream_ca.crt': No such file or directory
mv: cannot stat 'dummy_upstream_ca.crt': No such file or directory
mv: cannot move 'dummy_upstream_ca.key' to '../conf/server': No such file or directory
```
* **Version**: 59deea68
* **Platform**: Linux 5.4.0-52-generic #57~18.04.1-Ubuntu SMP Thu Oct 15 14:04:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**:

**Comment by azdagron** [comment]
Thanks for opening this, @gcohler! The broken behavior may have to do with a difference in OpenSSL version or something. Before we invest time fixing it, I was hoping you could share the circumstances that led you to run it to regenerate the dummy CA certificate? This isn't something most of us run, so I was curious what prompted you to run it (e.g., a set of instructions somewhere that we could re-evaluate). We've considered pulling this script before, but don't want to do that if it is serving a purpose.

**Comment by gcohler** [comment]
I was going to attempt to learn how to create our own root certificate for our Spire trust domain.  I thought I'd try the script to see how it worked.  We have folks who are more knowledgeable than I am on this subject.  I'm sure that when we need to, we'll be able to generate a workable root cert for ourselves.  The script seemed nice because it called out the special fields that need to be set for Spiffe/Spire (i.e. those above and beyond a standard certificate).  I'll let you folks decide how to proceed.  Just wanted to let you know that it didn't work.  Thanks for responding.

**Comment by gcohler** [comment]
I was able to get it to work by executing inside the docker.  So I'm closing this issue.

**Comment by evan2645** [comment]
Glad to hear you got it working @gcohler 

Just wanted to note that an "upstream root" isn't strictly required to run SPIRE. If an UpstreamAuthority plugin is not configured, SPIRE will create and manage its own root. The script in question is mostly used for development and testing purposes, and the shape of the certificate it generates is mostly arbitrary - I don't think we have any requirements of the upstream CA cert.

**Comment by gcohler** [comment]
Thank you @evan2645
