### ISSUE TITLE
Document security considerations for node attestors that leverage node-scoped tokens

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#1930]
Cloud-based node attestors that leverage node-scoped tokens all require TOFU semantics, and most of the tokens in question are relatively long-lived. These attestors should include a Security Considerations section in their documentation that explains the nature of this behavior, and the risks associated with their use.

At a minimum, the following node attestor documentations should be updated:
* aws_iid
* gcp_iid
* azure_msi

**Comment by jheiss** [comment]
I'm curious how these tokens require trust-on-first-use. Are the tokens not validated by the server? I'm mostly familiar with GCP, where the host identity is a JWT token signed by Google. Is the server not validating that Google signed the JWT?

Somewhat related question: at least on GCP the instance identity token is accessible by any user on the instance. This would seem to allow anyone with access to the instance to pretend to be the agent and attest any user. Is spire making the assumption that GCP instances are single user?

**Comment by evan2645** [comment]
> I'm curious how these tokens require trust-on-first-use. Are the tokens not validated by the server? I'm mostly familiar with GCP, where the host identity is a JWT token signed by Google. Is the server not validating that Google signed the JWT?

I think you may have meant "I'm curious _why_ these tokens require ..."?

The token signature is validated by the server, here is where you can find the relevant code for that: https://github.com/spiffe/spire/blob/master/pkg/server/plugin/nodeattestor/gcp/iit.go

> Somewhat related question: at least on GCP the instance identity token is accessible by any user on the instance. This would seem to allow anyone with access to the instance to pretend to be the agent and attest any user. Is spire making the assumption that GCP instances are single user?

This is exactly the reason that we treat the tokens as trust on first use. Many users choose to block access to the metadata API(s) with custom tooling to prevent non-agent software from being able to access the identity token... but the SPIRE project is not able to ensure that these kinds of protection mechanisms have been installed. Instead, we choose to trust the token only once to mitigate the risk.
