### ISSUE TITLE
Consider deprecating `k8s:node-name` workload selector

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#1955]
The kubernetes workload attestor emits a selector named `k8s:node-name`, whose value is the name of the node that the agent is running on. The primary use case of this selector is to limit the nodes on which a certain identity may be issued, however this use case is poorly solved by a workload selector - agents on other nodes with different names could still have access to the identity, as agent authorization is a function of parent_id and node selectors.

Consider deprecating this selector in favor of the (already existing) node selector generated by the k8s_psat attestor.

**Comment by azdagron** [comment]
We're in favor of removing this selector from the K8s workload attestor. This would be the first time that we've removed a workload selector so there are backwards compatibility concerns that we need to navigate. The "unscoped" part of this work is figuring out the plan for that.
