### ISSUE TITLE
Investigate retries and backoff for server keymager plugin

### ISSUE THREAD

**Issue by kunzimariano** [spiffe/spire#1964]
Based on what was discussed on https://github.com/spiffe/spire/issues/1941 we need to elaborate how to approach retries and backoff for each scenario. In some cases the server needs to retry, while in others it is the agent. We also need to define the returned error. That could allow us to properly identify the situation, so we can act accordingly.

**Comment by kunzimariano** [comment]
There are two main topics to consider here. 

## Error type and propagation

In order to know how to act, we need to consider the error  we want to return from the plugin. Given that gRPC already has a set of status codes, we could start returning them instead of just plain errors. This would also align properly with the errors produced by timeout additions (DEADLINE_EXCEEDED), and allow us to act based on them (whether to retry or not).

We need to pay close attention to the status codes returned by the plugin, and whether we should propagate them to the server clients. Just to name one case, if we get DEADLINE_EXCEEDED when calling the plugin, it might be better to return INTERNAL instead.

## Different scenarios and how to handle them

There are different scenarios to consider, and they don't necessarily require the same approach.

I will try to explain each one, and how we could approach them.

### Server internals

The functionalities for this scenario are:
 
- Initialize server CA and JWT key
- Initialize Server X509-SVID
- Rotate server CA and JWT key
- Rotate server X509-SVID

This is internal Spire server code that makes use of the plugin, without exposing it through an endpoint to a client. It already has a fixed retry for the rotations. The question is whether to add a backoff or not.

### Server endpoints with agent client

The functionalities for this scenario are:
 
- Attest agent and get X509-SVID
- Renew agent X509-SVID
- Sign workloads X509-SVID
- Sign JWT-SVID

These are  server endpoints that have  agents as a client. As far as I know we haven't defined retry policies[1](https://github.com/grpc/grpc-go/tree/master/examples/features/retry#usage) [2](https://github.com/grpc/proposal/blob/master/A6-client-retries.md) for the client. We will also need to verify the server endpoint is returning the right status code.

### Server endpoints with any client

The functionalities for this scenario are:
 
- MintX509SVID
- MintJWTSVID

We don't necessarily control the clients for those functionalities, hence we can't control the retry policies. We do need to be sure we are returning the right status codes.

### Server endpoint with another server as client

The functionalities for this scenario are:

- Create downstream CA

This is called by the Spire upstream authority plugin. We could also add the retry configuration to the client, and verify the server endpoint returns the right status code.

**Comment by evan2645** [comment]
> This is internal Spire server code that makes use of the plugin, without exposing it through an endpoint to a client. It already has a fixed retry for the rotations. The question is whether to add a backoff or not.

There might be some nuance here depending on the operation. For example, we probably don't want to backoff if we're initializing, but maybe we do if we're just rotating? The more I think about it, the more it feels appropriate to avoid backoff even in the rotation logic... things can get complicated fast - for example, we'd probably need to cap the backoff somehow since if we don't rotate, we die. We can always add backoff later if it becomes problematic

> These are server endpoints that have agents as a client. As far as I know we haven't defined retry policies1 2 for the client. We will also need to verify the server endpoint is returning the right status code.

I think this is ok? And yes, we'll definitely want to make sure that we're returning the right code from the handler. Exactly which code we return can probably be debated in PR? I'm not sure what would be best, honestly... deadline exceeded doesn't sound _too_ unreasonable

**Comment by kunzimariano** [comment]
I would like to propose to not make any of the mentioned changes, aside from the timeouts added in [PR#2044](https://github.com/spiffe/spire/pull/2044).

I believe the current thinking is to not change our clients. They already have retry intervals. Adding backoff becomes complicated quickly, and could put us into a place of no recovery.  There is also an argument for letting each plugin handle this since "they know better". Even more, some SDKs from external services, like AWS, already come with this built-in.

When it comes to error propagation from the plugin to the server endpoints, I think that returning internal error, as we currently do, with details coming from the plugin should suffice. Making the endpoints check if they got an status code, and decide whether to propagate it to the client, or return a generic internal error might add unnecessary complexity.

**Comment by kunzimariano** [comment]
Yesterday at the SIG-SPIRE meeting we agreed to not do any of this. Closing this issue.
