### ISSUE TITLE
TLS Config for Client is missing NextProtos 

### ISSUE THREAD

**Issue by maxlambrecht** [spiffe/spire#1966]
The TCP Server endpoint is created with a TLSConfig that doesn't get appended the `NextProtos`. This causes a funny issue with clients that expect "h2" during the ALPN protocol negotiation.  

* **Version**: 0.11.2
* **Platform**: 
* **Subsystem**: Server

**Comment by azdagron** [comment]
grpc-go normally handles this by appending `h2` to the `NextProtos` field during the call to `credentials.NewTLS`. However, SPIRE server is passing a tls.Config that does per-client TLS config as a way to get (relatively) fresh bundle content for each handshake. However, this means that the config returned by `GetConfigForClient` does not have the `h2` protocol appended. This is apparently causing problems for non-go languages.

In the short term, we can probably just append `h2` to the NextProtos on the config returned by `GetConfigForClient`. At some point we can probably start leveraging go-spiffe v2's TLS configurations to use (relatively) fresh bundles without having to use  the `GetConfigForClient` hook.
