### ISSUE TITLE
SRI architecture doc restricted

### ISSUE THREAD

**Issue by krockpot** [spiffe/spire#1974]
SRI architecture doc appears to have been restricted, I don't have view access;
https://docs.google.com/document/d/1nV8ZbYEATycdFhgjTB619pwIvamzOjU6l0SyBGbzbo4/edit#heading=h.kvr446y4phyy

**Comment by amartinezfayo** [comment]
Hi @krockpot we have some references to this old document that should be removed. This is an outdated document that we don't actively maintain anymore. Please go to spiffe.io for the most updated documentation.
