### ISSUE TITLE
Option to use TLS 1.3 only

### ISSUE THREAD

**Issue by bt-nia** [spiffe/spire#1976]
* **Version**: 
* **Platform**: 
* **Subsystem**: 

Due to the rise of attacks against TLS 1.2 (https://www.thesslstore.com/blog/raccoon-attack-researchers-find-a-vulnerability-in-tls-1-2/#:~:text=The%20Raccoon%20attack%20is%20a,between%20the%20server%20and%20client.&text=Connection%20must%20use%20Diffie%2DHellman%20key%20exchange), I was wondering if a configuration feature to use TLS 1.3 would be sensible. 
Is there a way with the methods in place right now to set TLS 1.3? Looking at the code min TLS 1.2 seems hard coded at: https://github.com/spiffe/spire/blob/master/pkg/server/endpoints/endpoints.go#L272

**Comment by evan2645** [comment]
Hmm that is a good question @bt-nia 

> Is there a way with the methods in place right now to set TLS 1.3? Looking at the code min TLS 1.2 seems hard coded

There is no way to disable TLS 1.2 at the moment, no. That said, SPIRE should negotiate TLS 1.3 without a problem.

> I was wondering if a configuration feature to use TLS 1.3 would be sensible.

The raccoon attack is fairly impractical, and from my understanding is not really seen in the wild as a result. It's also not clear to me if Go's TLS implementation is vulnerable at all. In my opinion, TLS 1.2 is still a fairly safe bet (of course, maybe I am the minority...)

All of that said, I think we'd be willing to make this change if/when the time is right. More community demand (perhaps via this issue), and better TLS 1.3 support penetration are probably the two main things we'd want to see. If/when there is sufficient motivation for this, then perhaps we want to move away from TLS 1.2 altogether.

**Comment by bt-nia** [comment]
Hey @evan2645 
Thanks for your view on this. Indeed, the raccoon attack requires a specific scenario to be successful and I agree that enforcing TLS 1.3 is not always the best solution. But for high-security applications and future flexibility, it is beneficial to have a way to control this without changing the source code. This is especially helpful when all negotiating parties are in our control and there's no need to support older, vulnerable versions of TLS - it completely eliminates the risk of being exposed to some vulnerabilities.

**Comment by evan2645** [comment]
Yes, I see - thank you again for bringing this up @bt-nia. We will keep this issue open and under consideration. My vote would be that when the time is right, we move away from 1.2 entirely

**Comment by evan2645** [comment]
After 5 months, we have not heard any other requests for this, even in high security environments. We're going to close this out for now, and will revisit in the future when demand is greater. Thanks again for opening this @bt-nia!
