### ISSUE TITLE
Entry create command fails but exit status is 0

### ISSUE THREAD

**Issue by lsantire** [spiffe/spire#1977]
* **Version**: 
* **Platform**: 
* **Subsystem**:  server CLI

When trying to create new entries using the server CLI command _entry create_, if the arguments validation doesn't fail, but then every entry fails to be created, the corresponding errors are shown in the log, but the exit status of the command execution is 0.

I understand and I agree that if some entries are created correctly and some other fail, it's okay to show the failed ones in the log and exit with status 0. But I think that if every entry fails to be created, then the exit status shouldn't be 0.

You can see this behavior directly in the code: [https://github.com/spiffe/spire/cmd/spire-server/cli/entry/create.go](https://github.com/spiffe/spire/blob/a348c5edada1c320d8238f87fca39aeaa7df83b0/cmd/spire-server/cli/entry/create.go#L102-L121)
```go
        succeeded, failed, err := createEntries(ctx, serverClient.NewEntryClient(), entries)
	if err != nil {
		return err
	}

	// Print entries that succeeded to be created
	for _, r := range succeeded {
		printEntry(r.Entry, env)
	}

	// Print entries that failed to be created
	if len(failed) > 0 {
		env.Printf("FAILED to create the following %s:\n", util.Pluralizer("", "entry", "entries", len(failed)))
	}
	for _, r := range failed {
		printEntry(r.Entry, env)
		env.Printf("%s\n", r.Status.Message)
	}

	return nil
```

I would be happy to contribute with this small change if you think is a good idea to change this behavior.

P.S. I know that this is a nit-picky issue, but I think it would be useful, and the implicated changes seem really easy to implement.

**Comment by evan2645** [comment]
Thank you very much for opening this @lsantire 

> P.S. I know that this is a nit-picky issue

It is not nit-picky :) it is important for people who are automating the invocation of this command.

Seems to me that moving the for loop into the if statement, and adding a new return statement in there, would do the trick. This does change the behavior of the CLI though, so we'll probably want to release it starting in 0.12.0. I'd be happy to see a PR for it

I also wonder if this command should be idempotent... feels like it probably should be, but that is beyond the scope of this issue. I'd be interested to hear thoughts/feedbacks on that point though.

**Comment by lsantire** [comment]
Thanks @evan2645 for your response.

> Seems to me that moving the for loop into the if statement, and adding a new return statement in there, would do the trick. This does change the behavior of the CLI though, so we'll probably want to release it starting in 0.12.0. I'd be happy to see a PR for it

Great, I will work on these changes and I will also add the corresponding tests for it.

> I also wonder if this command should be idempotent... feels like it probably should be, but that is beyond the scope of this issue. I'd be interested to hear thoughts/feedbacks on that point though.

I agree that this command being idempotent could be useful for automated invocations of it, but seeing that right now is possible to create entries with exactly the same data (spiffeID, selectors, etc.), it may happen that a repeated invocation of the command is done with the intention of creating a repeated entry, and I don't know if there is a friendly way to make the command invocation idempotent taking this possible use in consideration.

However, I think that adding a new parameter to allow users to specify the way to handle failures could be useful. For example, this parameter could be used to choose one of the following possible behaviors:
1) "All-or-none": if at least one entry fails to be created, then do not create any of them and fail.
2) "Best-effort": try to create the entries independently and use log messages to inform which ones failed and which ones succeeded (this is how it works now).

Just to make it clear, I am not requesting this feature, I am just thinking out loud.

**Comment by azdagron** [comment]
The exit code on a failed creation changed (unintentionally?) as part of #1913. There function that creates the entries was changed to use naked returns that unfortunately do not set the named `err` return value (since `err` ended up being aliased). I don't think this change in behavior has made it into a release, so we're probably ok just fixing that code?

The (first) naked return that needs to be fixed:
https://github.com/spiffe/spire/blob/master/cmd/spire-server/cli/entry/create.go#L215

**Comment by azdagron** [comment]
Oh I guess, beyond fixing the naked returns, we need to return an error from `Run()` if `len(failed) > 1`...

**Comment by marcosy** [comment]
Good catch! The original behaviour was to stop creating entries if an error was encountered. This changed with the introduction of the new API (which creates entries in batch mode). 
We also have to fix the ["update"](https://github.com/spiffe/spire/blob/master/cmd/spire-server/cli/entry/update.go#L213) command (I made the same mistake).

**Comment by azdagron** [comment]
Unrelatedly I'm fixing up the output of those commands (based on some confusion shared in slack about the formatting). I'm also moving the error printing to stderr, but the way the unit-tests are written, if anything is written to stderr, it expects a non-zero exit code, which of course won't happen with the way the code is currently structured. @lsantire if you are close on putting up a PR for this, I'm more than happy to wait and put my changes on top. I don't want to step on any toes!! If not, I'm happy to fix it while I'm in there. No pressure either way!

**Comment by lsantire** [comment]
Oh, I see, I thought that it was changed intentionally.
 
> Unrelatedly I'm fixing up the output of those commands (based on some confusion shared in slack about the formatting). I'm also moving the error printing to stderr, but the way the unit-tests are written, if anything is written to stderr, it expects a non-zero exit code, which of course won't happen with the way the code is currently structured. @lsantire if you are close on putting up a PR for this, I'm more than happy to wait and put my changes on top. I don't want to step on any toes!! If not, I'm happy to fix it while I'm in there. No pressure either way!

@azdagron, I haven't started to code the changes yet, so go ahead and work on them yourself, to avoid stepping on each other toes!

By the way, I think is a good moment to mention that I was working on the integration tests for this command (#1889). I will wait for this fix, and then I will make the corresponding changes in this new test.
