### ISSUE TITLE
Audit SPIRE for SPIFFE-compliance

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#1995]
SPIRE is known to deviate from the SPIFFE specification in several ways:

- #1446 
- #1495 
- #2103
- #2288
- #4106

SPIRE should be audited to identify and address any further discrepancies from the SPIFFE specification.

**Comment by rturner3** [comment]
As I start to look into this, I'm thinking that a potentially useful artifact to produce as part of this effort is an integration test that validates SPIFFE compliance based on today's version of the specification. The test may not be able to completely validate SPIFFE compliance in an automated way, but it would at least provide a repeatable way to measure aspects of compliance. That will help us track any drift between SPIRE and today's version of the specification.

I'll contemplate the scope of such a test as I continue to compile the specification requirements from its prosaic format into a more tabular one. I'm planning to post the table of specification requirements here for reference.

**Comment by rturner3** [comment]
SPIFFE is pretty explicit about defining conformance to the specification as just adhering to the requirements in SPIFFE-ID.md:
https://github.com/spiffe/spiffe/blob/master/standards/SPIFFE-ID.md#4-conclusion

Given that SPIRE is the current de-facto reference implementation of SPIFFE, is this level of adherence to the spec good enough for claiming compliance, or should the requirements specified in the remaining supporting documents ([X509-SVID.md](https://github.com/spiffe/spiffe/blob/master/standards/X509-SVID.md), [JWT-SVID.md](https://github.com/spiffe/spiffe/blob/master/standards/JWT-SVID.md), etc.) also be taken into consideration? It seems like SPIRE should try to implement the specification as closely as possible, but perhaps the remaining requirements are outside the scope of this issue of auditing for "compliance"?

**Comment by rturner3** [comment]
I've taken a first stab at capturing the current state of SPIRE's compliance with SPIFFE in this [Google Sheet](https://docs.google.com/spreadsheets/d/19SZ-6OWy7rJU24imK3ncDNU7dIfbiHsHLLhiB1s-fhE/edit#gid=1500648620). I tried to provide evidence in the form of code references and a short explanation of SPIRE's implementation regarding each element of the specification, where relevant. I hope this will slightly ease the burden of doing such audits in the future.

I found a few places along the way where SPIRE was not conforming to SPIFFE as well as some suggested improvement opportunities where SPIRE could add more explicit or defensive checks to prove conformance. In most cases, I filed issues in SPIRE for these gaps. There were some components of the spec on which it was rather difficult to definitively assert conformance, particularly the SPIFFE ID and Workload API sections. I would appreciate feedback on some of the improvement opportunities I identified, and issues can be created for them later if deemed to be valuable.

The SPIFFE ID section affects _many, many_ places in the code base, and there were numerous changes around handling of SPIFFE IDs introduced in recent SPIRE security releases. An effort was made to incorporate those changes into the audit since the security patches were introduced in the middle of the audit process.

I also found that proving conformance of parts of the Workload API section of the specification requires plumbing through many areas of the code base (e.g. proving that a bundle is non-empty). Detailed notes were added into the audit results where I saw room for improvement in simplifying the ability to audit such requirements.

Another note worth mentioning that I included plugin implementations out of scope of this audit for a few reasons:
- Third-party plugins can be configured in SPIRE. These plugins are not centrally registered or managed anywhere, so we cannot definitively assert conformance in all plugins.
- SPIRE core should generally be able to validate the responses it receives from plugins for validity w.r.t. SPIFFE.
- From a practical perspective, the cost of auditing all plugin implementations, even only including builtin plugins, was simply too high for me to do it on my own.

**Comment by azdagron** [comment]
How are you feeling about this now ryan? Would you consider the audit complete? We have open issues for the known problems. Anything else to do here?

**Comment by rturner3** [comment]
I've linked issues related to all the aspects of the SPIFFE specs where SPIRE was found to be non-compliant into the description of this issue. I think we are good to close this now since all the follow-ups are being tracked with individual issues.
