### ISSUE TITLE
Implement CP DataStore Sqlite plugin

### ISSUE THREAD

**Issue by drrt** [spiffe/spire#20]
_From @walmav on August 7, 2017 20:58_

 Seed initial testing with a CSV data file that is loaded into SQLite

_Copied from original issue: spiffe/node-agent#34_

 * [x] `CreateFederatedEntry()`
 * [x] `ListFederatedEntry()`
 * [x] `UpdateFederatedEntry()`
 * [x] `DeleteFederatedEntry()`
 * [x] `CreateAttestedNodeEntry()`
 * [x] `FetchAttestedNodeEntry()`
 * [x] `FetchStaleNodeEntries()`
 * [x] `UpdateAttestedNodeEntry()`
 * [x] `DeleteAttestedNodeEntry()`
 * [x] `CreateNodeResolverMapEntry()`
 * [x] `FetchNodeResolverMapEntry()`
 * [x] `DeleteNodeResolverMapEntry()`
 * [ ] `RectifyNodeResolverMapEntries()`
 * [x] `CreateRegistrationEntry()`
 * [x] `FetchRegistrationEntry()`
 * [ ] `UpdateRegistrationEntry()`
 * [ ] `DeleteRegistrationEntry()`
 * [ ] `ListParentIDEntries()`
 * [ ] `ListSelectorEntries()`
 * [ ] `ListSpiffeEntries()`
 * [ ] `Configure()`
 * [x] `GetPluginInfo()` (minimal stub exists)

**Comment by evan2645** [comment]
This is done
