### ISSUE TITLE
Formalize policy and removal of exclusionary language in SPIRE

### ISSUE THREAD

**Issue by anvega** [spiffe/spire#2003]
We bounced the idea during today's maintainer's sync-up to formalize our policy around exclusionary language in the SPIRE project. 

It should make it explicit in the contributor guidelines. This includes not allowing the following phrases:

master/slave (use primary/replica instead)
blacklist (use deny list instead)
whitelist (use allow list instead)

There are some usages of the above terms in the repo that can be easily cleaned while others like renaming master to main might involve additional work on certain tools in use. We can use this as a tracking issue for that.

There is a [whole list](https://inclusivenaming.org/language/word-list/) of other language that we should move away from.

**Comment by evan2645** [comment]
Thank you for opening this @anvega, I believe we've got it all now
