### ISSUE TITLE
Hardened Docker Images - Non-Root User

### ISSUE THREAD

**Issue by jkevlin** [spiffe/spire#2009]
* **Version**: all
* **Platform**: docker images
* **Subsystem**: all

**Use best practices when running containers.**
One best practice when running a container is to launch the process with a non root user.  By default, root in a container is the same root (uid 0) as on the host machine. If a user manages to break out of an application running as root in a container, he may be able to gain access to the host with the same root user.

Currently all spire containers are created without specifying a non-root user, this means that by default they will run as root.

**Comment by azdagron** [comment]
Thank you for opening this, @jkevlin! This is definitely something we are interested in exploring. A conversation for this is already under way in #1862. I'll close this issue as a duplicate.
