### ISSUE TITLE
Is not support reloading the configuration at runtime?

### ISSUE THREAD

**Issue by ryysud** [spiffe/spire#2016]
* **Version**: v0.11.2
* **Platform**: All
* **Subsystem**: server and agent

Out of curiosity,
I understood that reloading the configuration at runtime is not supported in SPIRE after reading the code.
Do you have a plan to support this? Please let me know if you have considered it before.

**Comment by azdagron** [comment]
Hi, @ryysud! We have imagined that one SPIRE might gain support for hot-reload of the configuration and as such, try to keep at least the plugin code ready for such a feature (e.g. ensure plugins will behave properly if `Configure` can be called at any time).

However, SPIRE does not currently support hot-reload. This would be a significant engineering effort and there are some design considerations that there aren't clear answers on yet.

So the short answer is SPIRE does not currently support it, and probably won't anytime in the near to mid-term future, but the idea is certainly interesting and something it might gain support for in the future.

Is there a particular use-case impacting your deployment that would be solved by hot-reload that we should consider?

**Comment by ryysud** [comment]
> So the short answer is SPIRE does not currently support it, and probably won't anytime in the near to mid-term future, but the idea is certainly interesting and something it might gain support for in the future.

Thank you for your reply, I really understood the background and the plan for this feature.

> Is there a particular use-case impacting your deployment that would be solved by hot-reload that we should consider?

No, this issue was a simple question. Thanks.
