### ISSUE TITLE
k8s Workload Attestor Image Selectors are Inconsistent

### ISSUE THREAD

**Issue by caleblloyd** [spiffe/spire#2026]
## Inconsistency

In Agent plugin: WorkloadAttestor "k8s", the following labels are Inconsistent:

Selector | Value
-- | --
k8s:container-image|The image of the workload's container
k8s:pod-image | An image of a container in workload's pod
k8s:pod-init-image | An image of an init container in workload's pod

(https://github.com/spiffe/spire/blob/7dd2d015070505243af2d7c6165a3cce7b29a429/doc/plugin_agent_workloadattestor_k8s.md)

Looking at the code - it appears that

- `k8s:container-image`
  - queries Kube API for `.status.containerStatuses[requesting container].image || .status.initContainerStatuses[requesting container].image`
  - this field can contain a tag, such as: `docker.io/envoyproxy/envoy-alpine:v1.16.0`
- `k8s:pod-image`
  - queries Kube API for `.status.containerStatuses[].imageID`
  - this field contains a resolved SHA256 digest, such as `docker.io/envoyproxy/envoy-alpine@sha256:bf862e5f5eca0a73e7e538224578c5cf867ce2be91b5eaed22afc153c00363eb`
- `k8s:pod-init-image`
  - queries Kube API for `.status.initContainerStatuses[].imageID`
  - this field contains a resolved SHA256 digest, such as `docker.io/envoyproxy/envoy-alpine@sha256:bf862e5f5eca0a73e7e538224578c5cf867ce2be91b5eaed22afc153c00363eb`

https://github.com/spiffe/spire/blob/a90c73d26fd37de47dc20c461f38eed92df5a3c1/pkg/agent/plugin/workloadattestor/k8s/k8s.go#L631-L672

## Example

Take the following example:

```
Pod with 2 containers
1. docker.io/envoyproxy/envoy-alpine:v1.16.0  <- uses SDS API to get the certs
2. docker.io/nginx:alpine
```

I would expect the following labels to work:

```
k8s:container-image:docker.io/envoyproxy/envoy-alpine:v1.16.0
k8s:pod-image:docker.io/envoyproxy/envoy-alpine:v1.16.0
k8s:pod-image:docker.io/nginx:alpine
k8s:pod-image-count:2
```

However, they will not work because the `pod-image` is expecting an image ID based off a Sha256 digest.  So the actual selector would need to be:

```
k8s:container-image:docker.io/envoyproxy/envoy-alpine:v1.16.0
k8s:pod-image:docker.io/envoyproxy/envoy-alpine@sha256:bf862e5f5eca0a73e7e538224578c5cf867ce2be91b5eaed22afc153c00363eb
k8s:pod-image:docker.io/nginx@sha256:c2ce58e024275728b00a554ac25628af25c54782865b3487b11c21cafb7fabda
k8s:pod-image-count:2
```

These Sha256 digests change every time a new tag is pushed.  So now you have to write a synchronization mechanism to fetch the Sha256 digest and keep it in sync.

## Potential Fixes

**1. Not BC Breaking, Consider image or imageID in Existing Labels**

- Allow labels to match either `image` or `ImageID`: 
  - `k8s:container-image`: add logic to match against `.status.containerStatuses[requesting container].image`, `.status.containerStatuses[requesting container].imageID`, `.status.initContainerStatuses[].image`, and `.status.initContainerStatuses[].imageID`
  - `k8s:pod-image-id`: add logic to match against both `.status.containerStatuses[].image` and `.status.containerStatuses[].imageID`
  - `k8s:pod-init-image-id`: add logic to match against both `.status.initContainerStatuses[].image` and `.status.initContainerStatuses[].imageID`

**2. BC Breaking, Add New Labels and make Consistent**

- Change `k8s:pod-image` to match against `.status.containerStatuses[].image` instead of `.status.containerStatuses[].imageID`
- Change `k8s:pod-init-image` to match against `.status.initContainerStatuses[].image` instead of `.status.initContainerStatuses[].imageID`

- Add 3 new labels: 
  - `k8s:container-image-id`: match against `.status.containerStatuses[requesting container].imageID || .status.initContainerStatuses[requesting container].imageID`
  - `k8s:pod-image-id`: match against `.status.containerStatuses[].imageID`
  - `k8s:pod-init-image-id`: match against `.status.initContainerStatuses[].imageID`

**3. Not BC Breaking, Add New Labels but leave existing Inconsistent ones**

- Add 3 new labels: 
  - `k8s:container-image-id`: match against `.status.containerStatuses[requesting container].imageID || .status.initContainerStatuses[requesting container].imageID`
  - `k8s:pod-image-name`: match against `.status.containerStatuses[].image`
  - `k8s:pod-init-image-name`: match against `.status.initContainerStatuses[].image`

## Documentation

The documentation should be improved to show which Kube API fields are being queried for these labels.  Most folks probably expect it to query `.spec.containers[].image`, which could be something like `envoyproxy/envoy-alpine:v1.16.0` (without the leading `docker.io`)

## Contribution

Given some guidance on which approach to take, I am happy to open the PR

## Info

* **Version**:0.11.2
* **Platform**: linux/amd64
* **Subsystem**: k8s workload attestor

**Comment by evan2645** [comment]
Hmm this is unfortunate... Thank you @caleblloyd for reporting, and sorry for the delay.

I'm not sure how option 1 would work. Selector matching occurs in SPIRE core, so assuming I understand your proposal correctly, we'd have to teach core to understand this selector type and know that it is interchangeable with some other (new?) selector.

Option 2 is out due to compatibility problems even though the naming is corrected, so I think we're (unfortunately) left with option 3. It's certainly a mess... but right now, we don't have a good way to deprecate selectors or otherwise change their names or values.

any other thoughts or ideas @rturner3 @azdagron?

**Comment by azdagron** [comment]
I think maybe Option 1 is talking about emitting the currently selector labels for both the image and imageID, if so that seems viable to me?

In the illustrated case, it would produce a "merge" of the expected and current behavior:
```
k8s:container-image:docker.io/envoyproxy/envoy-alpine:v1.16.0
k8s:pod-image:docker.io/envoyproxy/envoy-alpine:v1.16.0
k8s:pod-image:docker.io/nginx:alpine
k8s:pod-image:docker.io/envoyproxy/envoy-alpine@sha256:bf862e5f5eca0a73e7e538224578c5cf867ce2be91b5eaed22afc153c00363eb
k8s:pod-image:docker.io/nginx@sha256:c2ce58e024275728b00a554ac25628af25c54782865b3487b11c21cafb7fabda
k8s:pod-image-count:2
```

Registration entries could then either use the image name or ID with the selector and get it to match without breaking existing compatability.

**Comment by caleblloyd** [comment]
@azdagron that is correct, that's what I had in mind for Option 1

**Comment by evan2645** [comment]
Aah gotcha, thanks for that clarification and sorry for the confusion. Now that I understand, option 1 sounds good to me too.

**Comment by caleblloyd** [comment]
Great, I will work up a PR!

**Comment by bleggett** [comment]
I currently have an issue where I create SPIRE registrations before the Pod is created, and need the (Istio/envoy-aware) `k8s:pod-image` behavior - but since the Pod isn't created, I can't know the `sha256` of the container yet (`status` isn't populated), and I can't build a pod-aware selector that works.

Option 1 would solve it for me, so that sounds good.

**Comment by narg95** [comment]
Hi, I would love to have this change, that gives consistency to k8 selectors and makes the `pod:image` selector easier to maintain.
The SHA256 is stronger, but it is not human readable, there is no way to anticipate his value and it is more difficult to maintain. Having the image tag as in option 1) would be great!

**Comment by caleblloyd** [comment]
I still plan to send a PR for this, but it may be ~1-2 months before I will have time.  If anyone else would like to try a PR for it before then please feel free

**Comment by bleggett** [comment]
@caleblloyd Thanks for updating - PR incoming with your suggested approach, because I find myself in need of it.

**Comment by bleggett** [comment]
PR created - thanks @caleblloyd, it was relatively simple to implement the behavior you described.
