### ISSUE TITLE
Missing definition of MSITokenClaims.Subject?

### ISSUE THREAD

**Issue by gcohler** [spiffe/spire#2030]
In pkg/common/plugin/azure/msi.go, the AgentId method references `c.Subject` -- where no Subject property is defined in the MSITokenClaims type definition.  I'm not sure what the intent is here.

```
type MSITokenClaims struct {
	jwt.Claims
	TenantID string `json:"tid,omitempty"`
}

func (c *MSITokenClaims) AgentID(trustDomain string) string {
	u := url.URL{
		Scheme: "spiffe",
		Host:   trustDomain,
		Path:   path.Join("spire", "agent", "azure_msi", c.TenantID, c.Subject),
	}
	return u.String()
}
```

**Comment by azdagron** [comment]
The `Subject` field is part of the `jwt.Claims` struct that is embedded into the `MSITokenClaims` struct. `jwt.Claims` contains fields for standard JWT claims, including the `sub` claim (parsed into the `Subject` field). In this instance, the `sub` claim contains the principal ID for the managed service identity granted to the instance.

See https://golang.org/doc/effective_go.html#embedding for more information on embedding.

I'll close this issue for now. If I misconstrued your question or didn't answer it satisfactorily, please re-open the issue!

**Comment by gcohler** [comment]
Thank you.  Closing is fine.  It turned out that when I copied the code into my plugin, my IDE had imported the wrong jwt package (that didn't have a Subject property).  All is well.  Thank you for your prompt response.
