### ISSUE TITLE
Plugin-info seems to be busted on spire-agent and spire-server

### ISSUE THREAD

**Issue by ajessup** [spiffe/spire#206]
The plugin-info command on the `spire-agent` and `spire-server` binary seems to be broken. I get this `2017/09/21 21:47:45 error: rpc error: code = Unavailable desc = grpc: the connection is unavailable` on both binaries.

It's not clear to me if this is a bug in the code, or a configuration error. If the former, it should be fixed, if the latter, this error needs to be more clear. 

It's not entirely clear to me what the use-case of this subcommand is. Perhaps we do away with this command altogether and just have similar output emitted when `run` is invoked?

**Comment by evan2645** [comment]
Fixed in https://github.com/spiffe/spire/pull/221

**Comment by evan2645** [comment]
To further clarify, the endpoint powering the `plugin-info` subcommand was removed some weeks ago. The subcommand lingered. The "fix" was to simply remove it. If we need functionality like this in the future, we can add it back in a different way

**Comment by ajessup** [comment]
Killing the command outright seems like the right move to me.
