### ISSUE TITLE
NodeAttestor sshpop does not return any selectors

### ISSUE THREAD

**Issue by alchen99** [spiffe/spire#2060]
Currently the NodeAttestor sshpop returns a SPIFFE ID in the form of `spiffe://<trust-domain>/spire/agent/sshpop/<fingerprint>` e.g.: `spiffe://example.org/spire/agent/sshpop/21Aic_muK032oJMhLfU1_CMNcGmfAnvESeuH5zyFw_`. However, the plugin does not return any selectors. 

It would be nice if it could return selectors similar to what is returned for the x509 plugin. More specifically, it would be nice if it could return the fingerprint and principal(s) as selectors.

**Comment by tyler-at-fast** [comment]
This seems reasonable for `sshpop` to provide.

In the meantime, depending on your needs, you may get some value out of using the [`agent_path_template`](https://github.com/spiffe/spire/blob/master/doc/plugin_server_nodeattestor_sshpop.md) config to create a custom SPIFFE ID using the `ValidPrincipals` from the ssh cert.

The data available in the template is in [sshpop.agentPathTemplateData](https://github.com/spiffe/spire/blob/63db998a37b48abef6ba4a3cab2dd838955961a2/pkg/common/plugin/sshpop/sshpop.go#L34) and includes all the data from the ssh cert
