### ISSUE TITLE
Revisit server and agent socket paths and CLI flags

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#2064]
The SPIRE server socket flag is named `registrationUDSPath`, which is a poor name considering there are more than one APIs hosted on the server UDS and the Registration API is now deprecated.

Similarly, the default socket path value is `/tmp/spire-registration.sock`.

Additionally, the default socket path for both server and agent is under `/tmp`. While convenient for development, `/tmp` is NOT appropriate in production use, since it is typically world writable.

We should update the server CLI flag for the socket to be the same as the agent (i.e. `socketPath`) and change the defaults for both to no longer place the socket in /tmp.

**Comment by azdagron** [comment]
I propose the following for the server socket:
```
/run/spire/server/api/api.sock
```
And the agent:
```
/run/spire/agent/api/api.sock
```

The reason for the directory structure is to prevent accidental sharing of other sockets. For example, the SPIRE agent supports a "debug" socket, which should not be located in the same directory (or a child of the directory) that holds the Workload API socket, since a volume mount to share the Workload API socket would accidentally share the debug socket.

**Comment by amartinezfayo** [comment]
Thank you @azdagron for looking for a solution for this.
I think that having an homogeneous flag named `socketPath` is very good.
Regarding the default paths, `/run/spire/server/api/api.sock` and `/run/spire/agent/api/api.sock` look good to me and is a step forward having SPIRE secure "by default". The only thing that I'm thinking is the best way to communicate the impact of the change. I think that it would be good to make sure that this is properly documented in the CHANGELOG for the release, pointing specifically that new default paths are not writable by unprivileged users.

**Comment by evan2645** [comment]
> The reason for the directory structure is to prevent accidental sharing of other sockets. For example, the SPIRE agent supports a "debug" socket, which should not be located in the same directory (or a child of the directory) that holds the Workload API socket, since a volume mount to share the Workload API socket would accidentally share the debug socket.

Debug "API" ,,, does that suggest that the debug api socket would not live in the `api/` directory?

Frankly, I think these suggestions are much better than our current posture, so I would not block at all on them... though I also wonder if something like `public/` and `private/` would be better e.g. `/run/spire/agent/public/workload_api.sock` and `/run/spire/agent/private/mgmt.sock` ... and similarly `/run/spire/server/private/mgmt.sock`... or we can assume that all SPIRE Server sockets are private and shorten to `/run/spire/server/api.sock`

Again, not blocking, just some stray thoughts.

> The only thing that I'm thinking is the best way to communicate the impact of the change. I think that it would be good to make sure that this is properly documented in the CHANGELOG for the release, pointing specifically that new default paths are not writable by unprivileged users.

I agree with @amartinezfayo we would absolutely need to communicate the change in CHANGELOG ... but I also worry about choosing a path that largely requires elevated permissions. We have spent at least _some_ effort allowing SPIRE Agent to run as an unprivileged user, and we are trending more in that direction currently, so this seems a little counterproductive. Are there any other "standard" paths we may be able to use for this, caveated by the fact that we can always create our own directory with our own permissions within it?

**Comment by azdagron** [comment]
> Debug "API" ,,, does that suggest that the debug api socket would not live in the api/ directory?
Sorry, it's actually called the "admin" socket... and yes, it shouldn't live under the `api/` directory.

> something like public/ and private/ would be better
I'm keen on this. I'm also having a hard time of thinking of a situation where SPIRE server would need a distinction (or even have more than one socket).

>  /run/spire/agent/public/workload_api.sock
The agent socket serves three services on it. I'm a little hesitant to name it workload_api.sock, since it is also used for SDS and (now) the health service.

> I also worry about choosing a path that largely requires elevated permissions... Are there any other "standard" paths we may be able to use
https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s15.html says the following:

```
System programs that maintain transient UNIX-domain sockets must place them in this directory or an appropriate subdirectory as outlined above.
```

I feel pretty strongly that `/run` is the right place for this. Ultimately, unless we want to rely on the home directory for the service account (which is horrible IMO), we need to put it in some directory that will require root access at least once during the install (e.g. to create the subdirectory under /run and chmod it to whatever account SPIRE runs as).

>  We have spent at least some effort allowing SPIRE Agent to run as an unprivileged user, and we are trending more in that direction currently, so this seems a little counterproductive

Placing sockets under /run only requires privileged access at install time. It doesn't impact SPIRE's ability to run as an unprivileged user.

**Comment by rturner3** [comment]
`/run` seems like the appropriate place for Unix sockets on Linux. The main concern I have with using `/run` as the default however is that it will break compatibility with macOS, since macOS does not have any directory named `/run`.

For this reason, using `/var/run` may be preferable since it maintains compatibility across both macOS and Linux. In many Linux distros, `/var/run` should itself be a symlink to `/run` anyway.

**Comment by evan2645** [comment]
> Sorry, it's actually called the "admin" socket... and yes, it shouldn't live under the api/ directory.

It feels like the `api` directory name is ambiguous. They're all APIs. Why is one in a different directory?

> I'm keen on this. I'm also having a hard time of thinking of a situation where SPIRE server would need a distinction (or even have more than one socket).

Not that I'm suggesting this, but we have considered bundle api being public... what about federation api. The safe bet is to just stick everything in `private` for now I think, assuming the public/private thing is what we want to do. There are probably alternatives to the `public` `private` terminology e.g. admin etc

> The agent socket serves three services on it. I'm a little hesitant to name it workload_api.sock, since it is also used for SDS and (now) the health service.

Fair point

> transient UNIX-domain sockets

I wonder what that means... is ours a "transient" socket?

> Placing sockets under /run only requires privileged access at install time. It doesn't impact SPIRE's ability to run as an unprivileged user.

It does mean that anyone attempting to run SPIRE for the first time without elevated privileges will encounter an error. Do the dev configs use an alternate location? Does that mean that every time a dev invokes a CLI utility that they have to specify a long argument?

There is also the compat concern of folks running the agent today without elevated privileges - those people will fail to upgrade without a config change, and without warning (other than the CHANGELOG) ... though I suppose if we're going to do that, now is the time

**Comment by azdagron** [comment]
> the api directory name is ambiguous
I agree. I think you're on to something with the public/private thing (conceptually, I'm happy if somebody has a better pair)

> I wonder what that means... is ours a "transient" socket?
Hmm. Not sure!

I think we have some options for reconciling the dev experience. For example, we could conditionally inject a different default path for "dev" builds (via a special Makefile target). In the end though, I think secure-by-default should trump developer convenience.

Yeah, the backcompat story isn't that great. We have good reasons to want to steer clear of `/tmp` though.

@rturner3 brings a good point about macOS not having /run. We could do OS dependent defaults pretty trivially (which would set us up for future windows support) or just use /var/run for now.

**Comment by azdagron** [comment]
Ok, @evan2645 did some discussion offline and dug into whether or not `/tmp` is really that bad. Turns out, I _think_ we are ok. `/tmp` is set to permissions `1777`, which means with the sticky bit on only root or someone sharing the SPIRE user or group can remove the socket (to attempt a MitM). This reduces the risk to somebody racing with SPIRE on startup to create the socket first, a problem that will result in SPIRE failing to start when it fails to bind its socket (since the socket has already been created and can't be unlinked by SPIRE).

Another realization is that we have times when we want to run SPIRE agent and server side-by-side (i.e. nested SPIRE), in which case, we don't want both server and agent sharing a directory, since they could stomp on each other to create it and may be running under different accounts.

So here is what I propose:

```
/tmp/spire-agent/public/api.sock
/tmp/spire-server/private/api.sock`
```

Thoughts?
