### ISSUE TITLE
Improve packaging of SPIRE under Linux

### ISSUE THREAD

**Issue by ajessup** [spiffe/spire#207]
There is a lot we could do to improve the packaging of SPIRE to make it more convenient for installation under Linux.

* Binaries should be pre-built, so that a prospective user doesn't have to install go tooling
* Binaries should be automatically installed in an appropriate location on the user's path (eg. `/usr/local/bin/spire-agent`. 
* Configuration should be placed somewhere appropriate for configuration (such as `/etc/spire/agent.conf`)
* Both the `spire-server` and `spire-agent` should be run as daemons automatically on startup.

**Comment by drrt** [comment]
We are now creating binary releases (Linux, amd64, glibc) for distribution via GitHub releases. 

Automatic installation will require creating .deb and .rpm.

spire-agent can not be started (or restarted) automatically at this time, it's necessary to provide a new join token every time it launches.

**Comment by ajessup** [comment]
Thanks, this is a great start.

Would it be helpful to create separate specific issues for a deamonizable spire-agent (even when a join token is used) and specific packaging options? We can then close this issue.

**Comment by y2bishop2y** [comment]
@ajessup  we need more detail here.  Can you verify how other projects distribute their agent and server
