### ISSUE TITLE
Serverless support: Azure plugin

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#2072]
Implement a plugin that provides support to store issued identities in Azure Key Vault.

**Comment by jonas-weismueller-by** [comment]
Does this mean to implement a KeyManager for Azure Key Vault?

**Comment by amartinezfayo** [comment]
>Does this mean to implement a KeyManager for Azure Key Vault?

Hi @jonas-weismueller-by!
Serverless support is implemented through a new plugin type that is the [SVIDStore](https://github.com/spiffe/spire/blob/main/proto/spire/plugin/agent/svidstore/v1/svidstore.proto) agent plugin type. It's not implemented through a KeyManager.
This issue is to implement a plugin of SVIDStore type that would implement the logic to store issued SVIDs and keys in Azure Key Vault.
You can refer to the [RFC issue](https://github.com/spiffe/spire/issues/1843#issuecomment-754275015) for more details about how an SVIDStore plugin interacts with serverless architectures.

**Comment by jonas-weismueller-by** [comment]
@amartinezfayo Thanks for the explanation. We are looking for a Azure Key Vault KeyManger and I was wondering if there is any overlap with this implementation. But it does not seem to. Thanks.
