### ISSUE TITLE
Admin authentication mechanisms for the SPIRE server

### ISSUE THREAD

**Issue by lumjjb** [spiffe/spire#2099]
Following up on a conversation with @evan2645 @dfeldman and @mrsabath.

We discussed authentication methods for administering a SPIRE server. The main focus was around the ability to manage a SPIRE server without running into the bootstrap problem (i.e. today, in order to administer the SPIRE server, an identity has to be created within the trust domain). 

Doing this bases the administrative trust around a set of processes that is not easily extended from other forms of trust that may already be established. For example, @evan2645 mentioned the ability to authenticate a SPIFFE ID from a different trust domain. 

The discussion brought about additional thoughts on other forms of trust establishment. One use case would be based in user management. Exploring the administrators of identities may be based around privileged users as well. For example, to be able to configure an OIDC or LDAP provider to authenticate.

This issue is to discuss further possibilities and proposals for authentication mechanisms for the administrative interface of SPIRE servers.

**Comment by rturner3** [comment]
Closing due to staleness.
