### ISSUE TITLE
go get github.com/spiffe/spire/… only builds server nodeattestor-jointoken plugin 

### ISSUE THREAD

**Issue by ajessup** [spiffe/spire#210]
When running `go get github.com/spiffe/spire/…` (the recommended way to install SPIRE), this will build every binary in the project and make them available under $GOPATH/bin. Unfortunately we have two binaries with the same name (`nodeattestor-jointoken`) for the server and agent, and so only one of these is actually available.

For folks who want to use `go get` it would be helpful if we gave these binaries unambiguous name, or otherwise ensure they both get built.

**Comment by drrt** [comment]
We are not going to support go get ...
