### ISSUE TITLE
Add "count" Server CLI subcommands for entities with "list" / "show" subcommands

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#2129]
In larger deployments of SPIRE, it can be useful to understand the count of certain SPIRE entities. As of today, there are three entities that provide "list" operations in the Server CLI:

- Registration entries (`entry show` subcommand)
- Attested agents (`agent list` subcommand)
- Bundles (`bundle list` subcommand)

The current implementations of these commands do not use pagination, so they may fail when there are larger counts of these entities. Additionally, querying for all the records for a particular entity can be expensive.

In order to determine the count of these entities, it would be useful to have `count` CLI subcommands for all the entities mentioned above. The Server should have corresponding `Count` RPCs for these commands which only query for the number of records rather than selecting the data from each record.

Additionally, each of these `Count` RPCs as well as the CLI commands should accept all the filters available in the list operation for the entity.

**Comment by bri365** [comment]
In the interest of reducing backend load, we can create new "count" commands that call the datastore count RPCs.

**Comment by bri365** [comment]
PR is updated with expanded scope for this issue. I added count to server API and CLI, but not the registration API, as it didn't seem necessary or valuable.

**Comment by bri365** [comment]
Can this issue be closed as we have #2137 to track the next step?

**Comment by azdagron** [comment]
Yep. Thanks.
