### ISSUE TITLE
feat: Provide entries and selectors in a declarative way

### ISSUE THREAD

**Issue by narg95** [spiffe/spire#2134]
Hi all,

thanks for the amazing job with Spire!

See, currently I have Spire Server running inside kubernetes.
It is deployed in a GitOps fashion using a Git Repo with the k8 manifests.
When a workload/pod is updated with a new image tag, Spire Server needs to be updated in order to provide new identities.
For that, I have created a k8 Job, as a workaround, which is triggered on deployment with a script updating/creating entries with the new pod:image selector, something like this:

``` sh
kubectl exec -n spire spire-server-0 -- \
    /opt/spire/bin/spire-server entry create \
    -parentID spiffe://$parentID \
    -spiffeID spiffe://$spiffeID \
    -selector k8s:ns:spire \
    -selector k8s:container-name:spire-agent \
    -selector k8s:container-image:gcr.io/spiffe-io/spire-agent:0.12.0 \
    ...  # redacted
```
That is quite cumbersome, error prone and not easy to update/maintain. 
It requires bash script, setup RBAC access for the Job to execute `kubectl exec`, use `sed -i` to update script etc. 

It would be great to be able to provide SPIFFE entries in a declarative way using e.g. a YAML file from a ConfigMap which is updated on new changes and the spire-server is either, redeployed to read it at bootstrap time, or signaled somehow to reload the file without redeployment. 

Going one step ahead, this goes in the direction of making Spire somehow more kubernetish and db-less by using resources like k8 configmaps and secrets as a storage mechanism, it will required very likely a custom k8 spire controller. But this is not what I am requesting here, just to be clear :)

What do you think?

Best,
Nestor

**Comment by rturner3** [comment]
It should be possible to provide a more declarative experience for registering entries statically once there is a solution for #2626. How this would be done in Kubernetes probably needs some more thought.
