### ISSUE TITLE
[RFE] SPIRE agent to support root ca fingerprint

### ISSUE THREAD

**Issue by elinesterov** [spiffe/spire#2136]
To establish trust between agent and spire server currently, we use trust_bundle which could be loaded by an agent from the file path or URL. We even support insecure bootstrap. The current design limited in the way that the SPIRE agent should be distributed with trust_bundle.
The proposal is to add the fingerprint of the trusted root as a part of the agent configuration. 
So the operator can put it as a part of the config. If trusted_bundle is used it could be optional or as a way to enforce additional check.

**Comment by evan2645** [comment]
This would be awesome to support, but I'm having hard coming up with an approach in which it will work in all cases.

SPIRE Server could transmit the root as part of its TLS handshake, but many deployments have more than one root cert (basically any time the root level is managed by SPIRE and there is more than one SPIRE Server).

We're definitely interested in making bootstrap easier... I have been thinking about bundle notifications, and left some thoughts here that I think may lead to a simpler solution when combined with agent url-based bundle fetching: https://github.com/spiffe/spire/issues/1512

Any further ideas on how to make this better are definitely welcome! @elinesterov do you think there is a path forward with fingerprint that could support the multiple roots case?

**Comment by elinesterov** [comment]
>SPIRE Server could transmit the root as part of its TLS handshake, but many deployments have more than one root cert (basically any time the root level is managed by SPIRE and there is more than one SPIRE Server).

Do you mean when you have multiple SPIRE servers each of them is root and they all federated? Or that is about the case when you have chained SPIRE where the SPIRE server is a root?
Nevertheless, I think it could be supported with the list of fingerprints. The analogy here is the initial trust bundle for the SPIRE agent: how do you solve that? You have an initial trust bundle with all roots agents should trust, instead of shipping agents with the trust bundle user would have an option to specify a list of trusted roots fingerprints.

**Comment by rturner3** [comment]
Hey @elinesterov, it wasn't quite clear how this would simplify the bootstrapping process since the fingerprints are derived from the CA data. If you feel this is still important to address, it would be helpful to understand the benefits you see with this method of bootstrap.

Since there hasn't been movement on this issue in a while, we are going to close this for now and will consider reopening if there is some good benefits we can identify for this proposal.
