### ISSUE TITLE
Add list-style filtering to agent and entry server CLI count commands

### ISSUE THREAD

**Issue by bri365** [spiffe/spire#2137]
For server CLI agent count and entry count commands ([Issue 2129](https://github.com/spiffe/spire/issues/2129)), it would be helpful if the count would be filtered the same way as the respective list commands, allowing users to count specific subsets of items rather than just the totals.

**Comment by FedeNQ** [comment]
I can take this one :)

**Comment by amartinezfayo** [comment]
Thank you @FedeNQ!
