### ISSUE TITLE
Shouldn't node attestation strategy be specified in Node Agent config file?

### ISSUE THREAD

**Issue by ajessup** [spiffe/spire#214]
To see which Node Attestation strategy the agent was going to use, I had to go through all the agent plugin config files to see which were enabled. This is (a) cumbersome, and (b) feels a little unintuitive. What happens if two Node Attestation plugins are enabled for the agent?

Intuitively the node attestation strategy to use would be a configuration setting in the agent's config file, rather than the config file of a plugin.

**Comment by y2bishop2y** [comment]
Config refactor

**Comment by ajessup** [comment]
@y2bishop2y what does this mean?

**Comment by y2bishop2y** [comment]
Might be solved by agustin work.  @amartinezfayo  can you link to your work in a comment.
