### ISSUE TITLE
ListEntries RPC: consider adding MATCH_SUPERSET and MATCH_ANY match behaviors when filtering

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#2141]
The `SelectorMatch` and `FederatesWithMatch` messages support only the `MATCH_EXACT` and `MATCH_SUBSET` match behaviors.

Although those behaviors may be used in some circumstances, they don't seem to be the most useful ones.
When filtering by selectors, a common situation is that you know one of the selectors but not all the selectors. In that case, having a `MATCH_SUPERSET` behavior would be useful.

When filtering by federated trust domain, one important use case to support is when you want to know all workloads that federate with a trust domain because you may want to delete that trust domain. In this case, `MATCH_SUPERSET` could be useful, but also `MATCH_ANY`.
Let's say that you federate with four trust domains: W, X, Y and Z. If Y and Z have been compromised and you want to delete them, you want to identify all the entries that federates with Y _or_ Z. In that case, the `MATCH_ANY` behavior would be useful.

Look at the discussion in #2053 for more context about the different behaviors, their meaning and possible use.

**Comment by amartinezfayo** [comment]
Once we have figured out the match behaviors that we need to support the CLI use cases, we need to update the "spire-server entry show" command to consume the updated RPC and update the command to provide a consistent experience where the user can specify the match behavior.

**Comment by evan2645** [comment]
From conversation in #2053 (https://github.com/spiffe/spire/pull/2053#discussion_r589743239) I think we have some rough consensus that superset match is most natural for CLI interaction, and should probably be the default behavior. Changing CLI defaults is pretty tough deprecation-wise, so I think swapping this behavior in 1.0 might be a reasonable compromise.

**Comment by MarcosDY** [comment]
It is suggested to add a single `-matchOn` for federatesWith and selector.  But must we add two matchON? one for `-matchFederatesWithOn` and another for `-matchSelectorsOn`?

Actual Matcher for federatesWith is `any` (it was filtered in code) may we keep any as default for it? 

And `Agent list` command is not providing a way to filter agents, must we add a `-selector` & `-matchOn` as filters?

**Comment by amartinezfayo** [comment]
>It is suggested to add a single `-matchOn` for federatesWith and selector. But must we add two matchON? one for `-matchFederatesWithOn` and another for `-matchSelectorsOn`?

I think that adding different flags for the different properties would provide a great flexibility. IMO we can have `-matchFederatesWithOn` and `-matchSelectorsOn` for this.

>Actual Matcher for federatesWith is `any` (it was filtered in code) may we keep any as default for it?

I'm not sure to change the behavior without a deprecation path. I'm more inclined now to perhaps include some warning if a specific match strategy is not specified, where we make a note about what behavior is assumed now and the planned future behavior.

>And `Agent list` command is not providing a way to filter agents, must we add a `-selector` & `-matchOn` as filters?

I think that it would be great to provide filtering functionality here, having a consistent experience across CLI commands.
The `ListAgents` RPC allows filtering by attestation type, selectors and banned status. It would be nice to expose those filters in the CLI.

**Comment by MarcosDY** [comment]
I'm not sure about 'byBanned', we are not allowing ban agents using CMD, maybe we can avoid it for now until we allow it?

**Comment by azdagron** [comment]
This issue was completed some time ago (#2467 for the API, #2478 for CLI).
