### ISSUE TITLE
We should document a worked example of how someone actually performs workload attestation

### ISSUE THREAD

**Issue by ajessup** [spiffe/spire#215]
In the SPIRE documentation, nowhere do we describe how to use the registration API to register a workload for attestation, or how to use the workload API to retrieve it. A tutorial showing this would be a useful addition to our documentation.

**Comment by evan2645** [comment]
The SPIRE readme now includes an example of registering a workload, as well as retrieving the SVID through the workload API. Please re-open this if the current documentation is insufficient.
