### ISSUE TITLE
Plugin Versioning Support

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#2153]
## Introduction

This issue tracks proposed work for bringing plugin versioning support into SPIRE. The main motivation for this work is to provide the groundwork that supports the introduction of a more robust Agent KeyManager (#670). We'll need to support two very different KeyManager plugin interfaces for a deprecation period. The current catalog code and the way plugins are consumed in SPIRE in general does not make this easy.

## Facade Interfaces

The bulk of this change will involve writing facades around each plugin type. As new plugin versions are introduced, all that will be required is to write a shim to adapt the gRPC interface to the facade interface. When the way of interacting with the two versions diverges too much, this is a sign that we're changing something architecturally, and there might be a need to introduce another facade interface for a deprecation period and have forked code to handle either, e.g. an agent KeyManager that supports multiple keys (the new one), or one that supports a single key provided by the caller (the old one).

Additionally facade interfaces provide these additional benefits and possibilities:

- Decouples plugin consumer code from the specific gRPC plugin interface for that plugin type. This drastically cleans up the code and removes a bunch of protobuf construction and handling.
- Provides consistency around how the plugin is used and how errors are handled
- Provides an easy place to embellish errors coming out of plugins with the plugin name so each plugin author doesn't have to write their own and can just return normal gRPC statuses without prefixing the plugin name, which is what we currently advocate.
- Provides a uniform interface that can be used to write generic plugin-agnostic tests for builtins. This can cut down on unit-test code drastically, since each plugin doesn't have to repeat (i.e. copy-and-paste) test cases from other built-ins, and is a stronger guarantee that all of our built-ins behave the same.

## Catalog Changes

The catalog currently infers the main plugin _type_ (i.e. KeyManager). Further, the exchange of what _services_ and _hostservices_ are supported by the plugin and SPIRE is  done by the _type_ (i.e. MetricsService). What we need is for the plugin subsystem to support the exchange of which gRPC service names are provided by the plugin or SPIRE (e.g. `spire.plugin.server.keymanager.v1.KeyManager`).

SPIRE already has a stage where this information can be provided, through the `Init` service that is implicitly implemented by all plugins. The gRPC reflection service was also considered and is supported by go-plugin, but was not chosen because 1) the `Init` service already does something like this and is required for other reasons (it kicks off the brokering process and wires up the logger, etc), and 2) we don't want to accidentally try and handle services that are provided by go-plugin (e.g., gRPC health).

## Plugin Interface

The plugin Configure RPC is currently baked into the interface for each plugin type. This coupling makes it so that the interface for how  SPIRE configures a plugin, and the primary function of that plugin, cannot be revised separately. This change would decouple those interfaces, creating a new SPIRE configuration service.

There is a consequence to separating this out now; each plugin type would need a new version, which could be mostly the same except small parts we can clean up some small things that we've intended to for a long time (which I think is worth doing while introducing a new version).

## Plugin SDK Repo

While we're shaking things up, this seems like an opportune time to consider creating a separate repository for SPIRE plugin authors. This repo would contain the gRPC service definitions for all supported plugin, service, and hostservice types and versions. It would additionally contain the _bare minimum_ scaffolding necessary for SPIRE to consume these plugins as well as some convenience packages around unit-testing plugin implementations.

The intent here is to provide a one-stop shop for plugin authors and to also keep the internals of how plugins are loaded, initialized, managed, etc., either within SPIRE or unexported from this module.

### Layout

I propose the following repository layout under the `github.com/spiffe/spire-plugin-sdk` repository:

| package | description |
| ---------- | ---------- |
| `/proto/spire/plugin/*` | proto's and generated stub code, organized by `(server,agent)/<type>/<version>` |
| `/plugin` | generic interface definitions and exported helpers needed by both SPIRE and this code |
| `/pluginmain` | contains a turnkey method to serve a plugin from main() |
| `/plugintest` | contains a turnkey method to load a plugin for unit-testing |
| `/internal` | internal details, unexported by the module |
| `/examples` | contains convenient scaffolding for the latest version of each plugin type

### Initial Plugin Interface Versions

If we decide to decouple the configuration and primary plugin interfaces, I suggest that we do the following to make it easier to deprecate the existing interfaces and know that all plugins written with the SDK are configured with the decoupled service, _which makes some of the catalog code cleaner_:
- maintain the current interfaces _in SPIRE only_ as the `v0` interfaces
- Plugin SDK gets the new `v1` interfaces only. 

### Keeping SPIRE In Sync

An unfortunate consequence of having a separate repository is that we have some additional overhead in terms of consuming and keeping the SDK and SPIRE in sync.

Here is what I propose:
- SPIRE `master` always relies on some `next` tag (e.g. `github.com/spiffe/spire-plugin-sdk@next`)
- When introducing a new plugin version, we update the `next` tag and then re-run `go get github.com/spiffe/spire-plugin-sdk@next` in SPIRE. This will grab the new code and update `go.sum`. You should then be able to use the new changes.
- When we cut a release for SPIRE, we tag `github.com/spiffe/spire-plugin-sdk` with that same version. We update `go.mod` in the release branch to track this specific version. This step can be added to our checklist.

This keeps in-progress changes in the SDK from breaking SPIRE until SPIRE is ready to consume them (by updating its hash for the `next` version). It also keeps the number of PRs that update go.mod for this dependency down to once per release.

## Backwards Compatibility

This proposal should be doable without impacting runtime backwards compatibility with existing external plugins. However, since we're shaking up the SPIRE catalog and plugin interface code, plugins that pull in the latest SPIRE code will suffer a build break and no longer compile. However, transitioning to the new plugin SDK should be very mechanical, probably entirely a shuffling of one or two imports and renaming a few catalog-related types. We can provide a simple migration doc.

## The Work

I have done a good deal of prototyping here and have good grasp on the necessary changes and if accepted, plan on completing this feature by myself. 

Here is an itemized list of the work, in rough order, along with a status:

### Introduce Facade Interfaces and V0 Shims

This will result in some cruft in the server/agent catalog code, but that will be removed when those packages are refactored to consume the new catalog code.

- [x] Server KeyManager Facade interface with v0 shim
- [x] Server NodeAttestor Facade interface with v0 shim
- [x] Server NodeResolver Facade interface with v0 shim
- [x] Server Notifier Facade interface with v0 shim
- [x] Server UpstreamAuthority Facade interface with v0 shim
- [x] Agent KeyManager Facade interface with v0 shim
- [x] Agent NodeAttestor Facade interface with v0 shim
- [x] Agent WorkloadAttestor Facade interface with v0 shim

### Prepare SDK with Interfaces and Support Code

This does not include the v1 interfaces, which will be defined later after SPIRE is consuming the new SDK in the catalog system

- [x] Plugin SDK interfaces, plugin loading, plugin testing
- [x] Provide example plugin implementation scaffolding

### Consume SDK in SPIRE

- [x] Refactor common catalog code to consume the new Plugin SDK interfaces, versioning support, initialization, etc.
- [x] Refactor server catalog code to use new common catalog code
- [x] Refactor agent catalog code to use new common catalog code

### Transition to V1 Interfaces

- [x] Plugin SDK Server KeyManager v1 interface
- [x] Plugin SDK Server NodeAttestor v1 interface
- [x] Plugin SDK Server NodeResolver v1 interface
- [x] Plugin SDK Server Notifier v1 interface
- [x] Plugin SDK Server UpstreamAuthority v1 interface
- [x] Plugin SDK Agent KeyManager v1 interface
- [x] Plugin SDK Agent NodeAttestor v1 interface
- [x] Plugin SDK Agent WorkloadAttestor v1 interface
- [x] Server KeyManager Facade v1 shim
- [x] Server NodeAttestor Facade v1 shim
- [x] Server NodeResolver Facade v1 shim
- [x] Server Notifier Facade v1 shim
- [x] Server UpstreamAuthority Facade v1 shim
- [x] Agent KeyManager Facade v1 shim
- [x] Agent NodeAttestor Facade v1 shim
- [x] Agent WorkloadAttestor Facade v1 shim
- [x] Migrate Server KeyManager awskms built-in to v1
- [x] Migrate Server KeyManager disk built-in to v1
- [x] Migrate Server KeyManager memory built-in to v1
- [x] Migrate Server NodeAttestor sshpop built-in to v1
- [x] Migrate Server NodeAttestor jointoken built-in to v1
- [x] Migrate Server NodeAttestor aws_iid built-in to v1
- [x] Migrate Server NodeAttestor x509pop built-in to v1
- [x] Migrate Server NodeAttestor k8s_sat built-in to v1
- [x] Migrate Server NodeAttestor k8s_psat built-in to v1
- [x] Migrate Server NodeAttestor gcp_iit built-in to v1
- [x] Migrate Server NodeAttestor azure_msi built-in to v1
- [x] Migrate Server UpstreamAuthority awssecret built-in to v1
- [x] Migrate Server UpstreamAuthority vault built-in to v1
- [x] Migrate Server UpstreamAuthority spire built-in to v1
- [x] Migrate Server UpstreamAuthority disk built-in to v1
- [x] Migrate Server UpstreamAuthority awspca built-in to v1
- [x] Migrate Server UpstreamAuthority gcpcas built-in to v1
- [x] Migrate Server Notifier k8sbundle built-in to v1
- [x] Migrate Server Notifier gcsbundle built-in to v1
- [x] Migrate Server NodeResolver azure_msi built-in to v1
- [x] Migrate Agent KeyManager disk built-in to v1
- [x] Migrate Agent KeyManager memory built-in to v1
- [x] Migrate Agent NodeAttestor sshpop built-in to v1
- [x] Migrate Agent NodeAttestor jointoken built-in to v1
- [x] Migrate Agent NodeAttestor aws_iid built-in to v1
- [x] Migrate Agent NodeAttestor x509pop built-in to v1
- [x] Migrate Agent NodeAttestor k8s_sat built-in to v1
- [x] Migrate Agent NodeAttestor k8s_psat built-in to v1
- [x] Migrate Agent NodeAttestor gcp_iit built-in to v1
- [x] Migrate Agent NodeAttestor azure_msi built-in to v1
- [x] Migrate Agent WorkloadAttestor unix built-in to v1
- [x] Migrate Agent WorkloadAttestor k8s built-in to v1
- [x] Migrate Agent WorkloadAttestor docker built-in to v1
- [x] V1 Metrics Host Service implementation
- [x] V1 AgentStore Host Service implementation
- [x] V1 IdentityProvider Host Service implementation

Noticeably absent is the Agent SVIDStore interface. It is not yet finalized and yet to be consumed so isn't included until then. Since it is a new interface, the changes to fix it up should be minimal.

## When Do We Bump Versions?

We need a good rubric to know when or when not to introduce a new version for a plugin/service/hostservice. When a new feature comes along, the following should be considered in order.

1. Introduce a new field to an existing RPC.
    This can only be considered if the newly introduced field is _completely optional_, since existing plugins won't have any knowledge of it. An example of this kind of change is when we added the ability for server NodeAttestor plugins to optionally return a set of node selectors.
2. Introduce a new RPC to an existing plugin/service/hostservice version.
    This can only be considered if the newly introduced RPC is _completely optional_, since existing plugins won't have any knowledge of it.
3. Introduce a new version to an existing plugin/service/hostservice.
    This option should be considered when the conceptual role of the plugin has not changed. An example of this kind of change is the new Agent KeyManager.
4. Introduce a new plugin/service/hostservice.
    This option is the very last resort. Introducing a new plugin type has sprawling impact on documentation, examples, coding effort, etc. and should only be considered if the conceptual role of the existing plugin/service/hostservice is changing. An example of this kind of change is when we introduced the UpstreamAuthority plugin to replace the UpstreamCA plugin.

## Conclusion

All of this, so that at the end of the day, we can version plugin types, independent from configuration, in a way that makes introducing a new version, in the majority of cases, as simple as:
- defining the new service definition
- writing a version shim (generally with a high degree of code re-use)
- adding the new version to the list of supported versions for that plugin type to the server/agent catalog

**Comment by rturner3** [comment]
This sounds like a welcome improvement to me!

**Comment by amartinezfayo** [comment]
Thank you @azdagron for putting this together! I see a lot of benefit coming from this.

**Comment by azdagron** [comment]
For the layout of the various interface service definitions in the plugin SDK, I was thinking of the following:

```
spire/plugin       - plugins (e.g. KeyManager)
spire/service      - general services provided by plugins
spire/hostservice  - general services provided by the host (i.e. SPIRE)
```

Within each of these namespaces we have the following to break down which
interfaces are specific to a SPIRE component, or common. The `common` thing
kinda bugs me because if we ever introduced a 3rd component, then common
becomes a little ambiguous. I was also thinking of a name like `core` instead
of `common`, but I haven't thought that through really.
```
agent
server
common
```

For the current definitions, this looks like:
```
proto/spire/plugin/agent/keymanager
proto/spire/plugin/agent/nodeattestor
proto/spire/plugin/agent/svidstore
proto/spire/plugin/agent/workloadattestor

proto/spire/plugin/server/keymanager
proto/spire/plugin/server/nodeattestor
proto/spire/plugin/server/noderesolver
proto/spire/plugin/server/notifier
proto/spire/plugin/server/upstreamauthority

proto/spire/service/common/config                   (this is the new service through which SPIRE configures plugins)

proto/spire/hostservice/server/identityprovider
proto/spire/hostservice/server/agentstore

proto/spire/hostservice/common/metrics              (renamed from the curent metricsservice, which felt redundant)
```

**Comment by azdagron** [comment]
This is done.
