### ISSUE TITLE
Agent should emit network-related metrics in telemetry

### ISSUE THREAD

**Issue by GuoqiangZ** [spiffe/spire#2154]
* **Version**: 
* **Platform**: 
* **Subsystem**: agent

Currently there is a lack of metrics telling status of network between spire-agent and spire-server. We would like to emit some metrics in spire-agent telemetry to improve monitoring and alerting.

The first metric is the time of spire-agent initiating gRPC connection with spire-server. 
[pkg/agent/client/dial.go#L68-L80](https://github.com/GuoqiangZ/spire/blob/9a1b81a8351bf16bb5e9e3999c660b8fb3e94281/pkg/agent/client/dial.go#L68-L80)
![image](https://user-images.githubusercontent.com/44148177/111193861-df5dc900-8577-11eb-8e57-64628265d30c.png)

The second one is the time of spire-agent initiating TCP connection with spire-server.
[pkg/agent/client/dial.go#L91-L98](https://github.com/GuoqiangZ/spire/blob/9a1b81a8351bf16bb5e9e3999c660b8fb3e94281/pkg/agent/client/dial.go#L91-L98)
![image](https://user-images.githubusercontent.com/44148177/111193924-ef75a880-8577-11eb-8876-715cfadc0bc6.png)

The third one is the elapsed time of spire-agent gRPC unary call.
[pkg/agent/client/dial.go#L100-L109](https://github.com/GuoqiangZ/spire/blob/9a1b81a8351bf16bb5e9e3999c660b8fb3e94281/pkg/agent/client/dial.go#L100-L109)
![image](https://user-images.githubusercontent.com/44148177/111194104-1633df00-8578-11eb-8a39-a26ec5e0c6ee.png)

**Comment by evan2645** [comment]
I don't see any reason why we wouldn't want to expose this as telemetry data.

I think the next step here is to document (in this issue) exactly the data we want to collect. Is it limited to the three examples you provided? Let's figure out what the types and names of those metrics will be, and what labels they should have. Ideally, each metric and label have an associated use case

**Comment by amoore877** [comment]
Bump on this issue. I definitely think @GuoqiangZ 's branch is at least a good start to have but don't yet know what else we might want. Have there been discussion elsewhere regarding this?

**Comment by rturner3** [comment]
@GuoqiangZ Just checking in since this issue has been around for a little while, are you still interested in having these metrics?

**Comment by IvMdlc** [comment]
Hi, went through the docs looking for network metrics but couldn't find anything, then bumped into this issue which has exactly what we are interested in: `time of spire-agent initiating TCP connection with spire-server`. Thanks.
