### ISSUE TITLE
Document optionality of ACME for federation

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#2197]
The spire-server docs don't state that the ACME configuration is optional when turning on the bundle endpoint.

Update the docs to reflect the optionality of ACME, and add a short blurb about the implications of not using it

**Comment by mjptree** [comment]
@evan2645 I wouldn't mind working on this. Do I understand correctly that this refers primarily to [doc/spire_server.md](https://github.com/spiffe/spire/blob/main/doc/spire_server.md) or did you have also other places in mind?
