### ISSUE TITLE
Agents using non-TOFU node attestors should not rotate their SVIDs in place

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#2203]
Agents currently rotate their SVIDs "in place", by authenticating to SPIRE Server with the SVID they want to rotate/renew. This is necessary because many node attestors require trust on first use (or TOFU), but agents using such attestors still need a way to securely renew their own SVID.

The downside to this is that securing this process is non-trivial. Not only do we need to assert that we are rotating the exact same identity as is being presented, but we also need to ensure that it is a true agent identity, AND that it is the exact same cert we gave the agent last time (in order to mitigate agent credential exfiltration).

Ideally, an agent must prove its identity every time it needs a new SVID, rather than simply presenting its old SVID. This has added benefit of continuous assurance (e.g. the TPM is measured every time the agent identity is rotated), and is decidedly simpler than the rotation-in-place scheme.

To do this though, the node attestor in question must not be restricted by TOFU semantics. Since the server is the one that authorizes rotate-in-place operations (which will still be required for TOFU attestors), core will need to have some knowledge of which agents need to rotate-in-place and which don't.

**Comment by azdagron** [comment]
Related to #1847
