### ISSUE TITLE
BatchCreateEntry API may return the 'Table tmp/xxx doesn't exist' in high load.

### ISSUE THREAD

**Issue by hiyosi** [spiffe/spire#2209]
* **Version**: 0.12.1
* **Platform**: x86_64 GNU/Linux
* **Subsystem**: spire-server

When executing a large number of concurrent requests to BatchCreateEntry API, I get some errors as follow.

```
failed to list entries: datastore-sql: Error 1146: Table './tmp/#sql1e435_6613_0' doesn't exist
```

e.g. 
10,000 request to 8 servers. 

```
        plugin_data {
            database_type = "mysql"
            max_open_conns = 1000
            max_idle_conns = 1000
            connection_string = "spire:xxx@tcp(my-db)/spire?parseTime=true"
        }
```

In case of 10,000 request to 2 servers, it does not occur.

I'm not sure the cause of this, so it may be a MySQL problem.
However, there does not seem to be anything abnormal as far as the MySQL logs and metrics I can see.

**Comment by evan2645** [comment]
Thank you very much for opening this @hiyosi!

Do you know by any chance if this is a new problem with 0.12.1?

**Comment by hiyosi** [comment]
@evan2645 

Thank you for replying!
My environment, I get the same error with v0.12.0 and v0.12.2.

**Comment by hiyosi** [comment]
After changing the MySQL parameters, sometimes suppresses the error.
So I suspect that the error is probably caused by MySQL tuning issue.

I will close this issue.
If I find out other causes, I will re-open this or create new issue.

Thanks you.
