### ISSUE TITLE
Server API authorization result metrics

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#2223]
#825 introduced authorization result metrics for the Node and Registration APIs. Similar metrics were not included for the v1 server APIs. It is useful to have metrics for authorization results to get better visibility into whether or not callers of SPIRE are failing due to invalid credentials.

**Comment by azdagron** [comment]
The API middleware should emit call metrics for authorization failures produced by the authorization middleware. I can understand why it may not be as convenient as a single metric for a given service like we had before (e.g. authorize_call metrics for both node and registration), but is the per-rpc metric sufficient?

**Comment by azdagron** [comment]
I guess it probably isn't very convenient. We could have the authorization middleware emit a metric with the RPC name as a label...

**Comment by evan2645** [comment]
Even though the docs don't reflect it, we emit a label with the call status with each rpc counter
```
| Call Counter | `rpc`, `<service>`, `<method>` | | Call counters over the SPIRE Agent RPCs
|
```

I think you should be able to visualize this by using a wildcard on service and/or method, and group by status label. Assuming that works, we should be able to see all calls by status, as well as broken down by specific RPCs if necessary.

For what it's worth, this is a pattern I have observed in the past (per-RPC count metrics with status tags)

**Comment by rturner3** [comment]
I missed this, thanks for pointing it out. I think this should be adequate for this use case. Closing for now, will re-open if I run into any issues with it.
