### ISSUE TITLE
use spiffeid types throughout datastore

### ISSUE THREAD

**Issue by bri365** [spiffe/spire#2232]
Clarify type and usage by using the appropriate spiffeid types (e.g. spiffeid.TrustDomain and spiffeid.ID).

**Comment by azdagron** [comment]
Just a note that we shouldn't try and tackle this until SIG-SPEC has finalized updates to the specification related to ID and Trust Domain encoding and character sets and go-spiffe v2 has been updated to take them into consideration.

We'll need a strong audit of all go-spiffe v2 type usage after that takes effect to ensure any behavior changes are well understood taken into consideration.

**Comment by maxlambrecht** [comment]
Related to #1828

**Comment by bri365** [comment]
Will track in #1828
