### ISSUE TITLE
Provide telemetry dashboard templates

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#2233]
In order to effectively operate SPIRE in a production environment, users need to develop visualization of SPIRE telemetry to have adequate observability into the system. These dashboards can be time-consuming and tedious to develop, so it may be helpful to users to provide dashboard templates for common open-source observability dashboard systems like [Grafana](https://grafana.com/). Metrics dashboards also provide a way for newer users to quickly familiarize themselves with frequently exercised RPCs in the SPIRE control plane.

SPIRE supports emission of metrics to several metrics systems, such as Prometheus, statsd, and M3. Given that dashboards are powered by metrics queries whose query languages differ by observability system, it may make sense to have separate dashboards for different supported query languages (e.g. PromQL, M3QL).

**Comment by FedeNQ** [comment]
We're working in something related to this and we'll happy to contribute here.

**Comment by FedeNQ** [comment]
We are planning to add a .JSON file to be used for generating the dashboards. Does anyone have suggestions on where we should place it within our project structure?
