### ISSUE TITLE
Federation Management API: define a protobuf

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#2250]
Create a protobuf definition for an API that manages the federation relationships with other trust domains.

**Comment by evan2645** [comment]
Progress on this has fallen victim to the 1.0 release crunch. We've determined that finalization of the proto doesn't technically block 1.0. The PR has been up for a while and is generally well-received, it should be merged soon ... untagging from the 1.0 milestone in the meantime so we can get unblocked.
