### ISSUE TITLE
slight mismatch on caller ID logging field

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#2254]
For logging a caller ID as a log field, generally we should be using https://github.com/spiffe/spire/blob/73f660bee008e1e4f8d310158c1258b65b53f959/pkg/common/telemetry/names.go#L130 which is a constant equal to `caller_id`

Noticed in our production logs there were instances of `caller-id` (hyphen instead of underscore), and traced this to https://github.com/spiffe/spire/blob/04bee9741ac3b8c4b204e6367d0bd6146f78a8c7/pkg/server/api/middleware/authorization.go#L47

For consistency I think this should just use the existing value, if not directly importing the constant.

The same code also has  `caller-addr` as a logging field. A minor nit, but I think this should be made consistent and also use an underscore like the other fields, and should be moved into a constant in the telemetry package.

**Comment by azdagron** [comment]
Seems like a reasonable thing to fix.
