### ISSUE TITLE
Error in documentation with AWS Node Resolver on defining the spiffe id of the agent page.

### ISSUE THREAD

**Issue by caleygoff-invitae** [spiffe/spire#2259]
https://spiffe.io/docs/latest/deploying/registering/#1-defining-the-spiffe-id-of-the-agent has the following llink on it which leads to nowhere. Can this be updated or removed to reduce confusion? Thanks! 

AWS | [The configuration reference page for the AWS Node Resolver](https://github.com/spiffe/spire/blob/master/doc/plugin_server_noderesolver_aws_iid.md)
-- | --

**Comment by asjoyner** [comment]
I stumbled on this broken link today... and still can't find where that page should point.

**Comment by asjoyner** [comment]
Is it this page, perhaps?
https://github.com/spiffe/spire/blob/v1.0.2/doc/plugin_server_nodeattestor_aws_iid.md

**Comment by azdagron** [comment]
@sanderson042, can you fix the AWS IID nodeattestor link on this page? @asjoyner has posted the correct link.

**Comment by azdagron** [comment]
Actually, I'll close this and open it on the spiffe.io repository.

**Comment by azdagron** [comment]
https://github.com/spiffe/spiffe.io/issues/229 has been filed for this. Thanks @caleygoff-invitae and @asjoyner !
