### ISSUE TITLE
AWS KMS keymanager issues when used with ACME bundle endpoint

### ISSUE THREAD

**Issue by kunzimariano** [spiffe/spire#2302]
There are currently 3 issues when using the AWS KMS keymanager plugin, in conjunction with the ACME bundle endpoint:

- Keys used by ACME contain characters not supported by KMS aliases. This allows the creation of keys in KMS, but fails when trying to assign an alias to them. Alias names should match this pattern: `alias/^[a-zA-Z0-9/_-]+$` from  [Create Alias Docs](https://docs.aws.amazon.com/kms/latest/APIReference/API_CreateAlias.html).
- When acme_auth tries to retrieve an already existing key, it fails since it's not making proper use of status codes.
- When hitting the bundle endpoint we could get the next error: 
`http: TLS handshake error from 10.0.0.1:59534: tls: failed to sign ECDHE parameters: rpc error: code = InvalidArgument desc = unsupported combination of keytype: EC_P256 and hashing algorithm: SHA512`. This only seem to happen with curl built with LibreSSL. *Not* with  OpenSSL (or curl built with it), wget, browsers or another SPIRE server. As the error says, KMS does not support that combination of curve and hashing algorithm.

* **Version**:  890012d886deed20d701974f2793bd5bb1c3e20a
* **Subsystem**: server and aws kms

**Comment by evan2645** [comment]
@kunzimariano do you know if this is issue can be closed? I see some of the things here have been addressed already

**Comment by kunzimariano** [comment]
💯 this was also addressed by https://github.com/spiffe/spire/pull/2390. 
Closing it 🚢
