### ISSUE TITLE
SPIRE FetchX509Bundles RPC does not match Workload API specification in SPIFFE

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#2325]
SPIRE's Workload API handler implements the Workload API proto definition in go-spiffe v2. The version of the Workload API proto in go-spiffe v2 does not match the RPC definition for FetchX509Bundles in SPIFFE, see https://github.com/spiffe/go-spiffe/issues/162.

The differences from SPIFFE are:

- Missing the `crl` field in the `X509BundlesResponse` type
- The field number of `X509BundlesResponse.bundles` is `1` in the go-spiffe proto, but `2` in SPIFFE.

**Comment by azdagron** [comment]
So glad you caught this Ryan. Fortunately, SPIRE hasn't released that feature yet, and go-spiffe v2 doesn't use it internally. So we should be safe to just patch go-spiffe v2 and update our dependency.

**Comment by azdagron** [comment]
https://github.com/spiffe/go-spiffe/pull/164
