### ISSUE TITLE
Helper utility/binary to exercise SPIRE APIs

### ISSUE THREAD

**Issue by lumjjb** [spiffe/spire#2347]
Provide a way to exercise SPIRE apis for development, debugging and exploration kind of like a "Swiss-army knife" type tool.

Usecase for this stemmed from when I was trying to exercise the spire-server gRPC proto over HTTP, but the `spire-server` binary only allowed talking to the socket. 

Quoting the originating idea from @evan2645 on slack:

>I have this vision of eventually building a spiffe CLI utility that does a bunch of SPIFFE-related stuff, and the helper functionality is one of those things. The hard part though is that these other APIs are SPIRE and not SPIFFE APIs ...
Maybe we can have a spire-cli binary, that implements SPIRE-related functionality, and also pulls in all the SPIFFE functionality from the other (yet-to-be-developed) utility

**Comment by evan2645** [comment]
Small bit of additional context from the slack conversation, occurring prior to the text @lumjjb has quoted:

> I have a hard time coming up with a good answer. We can extend SPIRE Server CLI to do this, but there are a lot of other related configurables that then become necessary (workload api socket path? cert/key path if no workload api? and what if there's more than one SPIFFE ID on the workload api response?)

**Comment by azdagron** [comment]
When I was doing a bunch of automated testing as part of auditing our behavior in regards to the recent CVE, I wrote up with a general purpose tool, `spire-pipe` that could invoke any SPIRE APIs, taking JSON input and doing JSON output. The experience for streaming RPCs isn't very ergonomic (of which we have one RPC, `Agent.AttestAgent`, but other than that the experience was pretty good overall.

It had a few other helpers baked in to do base64 and PEM conversions and the like:

For example, to get a JSON formatted list of all agents, you could run something like this:
```
jq -n '{}' | spire-pipe rpc agent list-agents
```

**Comment by rturner3** [comment]
Closing since there is no momentum behind this issue. @azdagron has a minimal tool called `spire-pipe` that may be sufficient for now until there is a more concrete proposal laid down for a general purpose CLI.
