### ISSUE TITLE
Vault UpstreamAuthority: Support kubernetes authentication to Vault

### ISSUE THREAD

**Issue by bjencks** [spiffe/spire#2348]
Feature request: The Vault UpstreamAuthority plugin should support using kubernetes authentication, specifically with a PSAT. The benefits of PSATs over long-term stable credentials are well documented in the PSAT node attestor plugin, it should be supported for Vault auth too.

**Comment by evan2645** [comment]
This would be awesome. Thanks for opening the issue @bjencks 

Having a look at the [vault plugin config](https://github.com/spiffe/spire/blob/main/doc/plugin_server_upstreamauthority_vault.md#configuration), this can be easily slipped in e.g. `k8s_psat_auth`.

Any chance you'd be up for contributing it @bjencks?
