### ISSUE TITLE
Improve K8s integration test coverage

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#2350]
In terms of K8s test coverage, we currently test against, and a have a client dependency set to our lowest supported version (1.18). The client dependency prevents us from making calls that aren't supported by the 1.18 APIs but doesn't actually give us assurance that the code still works on the latest K8s releases.

Further, since our test coverage only covers our minimum version, we wouldn't discover any such breaks even with integration testing.

What we really need is a series of integration tests that can run against all supported kubernetes versions, or at a minimum, the lowest and the greatest. This would give us flexibility to change our client deps and reap those benefits (better interfaces, code fixes, etc) without sacrificing compatibility guarantees. The hidden requirement would be, of course, that any new code that invokes kubernetes APIs is also covered by the integration tests.

**Comment by evan2645** [comment]
It would be great if we could automate our tracking of the k8s versions, perhaps using GitHub Actions to open a PR against us with version bumps any time k8s releases. Something like that would be ideal - I fear any solution that involves manually tracking these versions will ultimately fall behind
