### ISSUE TITLE
Feature Request: Filter ListAgent using the value of X509SvidExpiresAt

### ISSUE THREAD

**Issue by hiyosi** [spiffe/spire#2367]
e.g.
If we fetch an agent list for the purpose of cleaning some data associated with expired Agent, It is useful to be able to use the value of 'X509SvidExiresAt' in Filter.

Currently, we need to fetch all data and extract them by myself.

**Comment by hiyosi** [comment]
datastore has `ByExpiresBefore` fieled in `ListAttestedNodesRequest`
https://github.com/spiffe/spire/blob/main/pkg/server/datastore/datastore.go#L123

**Comment by rturner3** [comment]
Hi @hiyosi, we recently added support for purging expired agent data in https://github.com/spiffe/spire/issues/1836. Does this meet your needs or is there something not covered by the agent purge CLI that you might still need this filter for?

**Comment by hiyosi** [comment]
@rturner3  
Thank you for comment.

This request is about efficiency.
It seems inefficient to fetch and compare all records, so we would like to be able to filter.  
I think if it could be filtered, the purge command would be more efficient.

**Comment by evan2645** [comment]
Hi @hiyosi, thank you for the clarification.

I agree that the prune logic is best handled server-side. I opened this issue on the API SDK to introduce a new prune RPC so that this filtering can be done server-side: https://github.com/spiffe/spire-api-sdk/issues/41

Does this address your concern?

**Comment by hiyosi** [comment]
@evan2645 

Yes, it is better.
Thank you for opening the issue.

**Comment by evan2645** [comment]
Great, thank you @hiyosi! Going to go ahead and close this one out
