### ISSUE TITLE
log/return caller information from peer trackers

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#2412]
It would be helpful for triage if the various peer tracker errors gave information about the caller (ex. [linux tracker: caller no longer being watched](https://sourcegraph.com/github.com/spiffe/spire@9951ef97a87288b823d6b80e2b4a62e4aaf06bcc/-/blob/pkg/common/peertracker/tracker_linux.go?L84)). The additional information could help narrow down misbehavior or other troublesome processes, at a fairly low cost of additional log field(s) by peer tracker type.

**Comment by amartinezfayo** [comment]
Fixed in #2469.
