### ISSUE TITLE
introduce soft deletion of registration entries

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#2431]
It may be the case that registrations:
- are deleted in error, and need to be re-created by operators
- are pruned due to expiry, and the related registrant in error was failing to renew the entry
- should be temporarily "turned off" for debugging, mitigations, or migrations:
-- mitigate accidental overlap of SVID selectors
-- be a record of an error, to better determine in post-mortem what went wrong for entry definition
-- convenience operator method; if the entry is determined to be needed, it can be reinstated without full entry definition (just entry ID)
-- carefully migrate workloads to new SPIFFE IDs or selector sets, being able to independently flip old and new entry statuses independently and easily "rollback" by soft deleting the new entry and reinstating the old one.

Introduce the concept of `soft deletion` of registration entries.

#### Pros
Handle cases listed above as a quick convenience to SPIRE operators for reinstating a deleted registrations, reducing human or process error for registration re-creation.
Give finer, less dangerous control to SPIRE operators when performing triage related to the list of registrations.

#### Cons
Forgetting to `hard delete` entries over time could:
- cause the SPIRE DB to grow very large
- introduce significant cruft/noise when SPIRE operators are attempting to triage an error
Increased complexity of DB model.
Possible footgun in source code and test coverage of queries. It is easy to miss adding `isActive/Deleted = [true|false]`.
Can't "cascade" a `soft delete` to the joined tables used to form a full entry object. From a SPIRE perspective this is probably fine; from a human perspective it may look odd that (for instance) a registration entry is `soft deleted` but the related entries in the tables of `selector` or `dnsname` rows are not.

#### Notes
Not to get too far into implementation on proposal phase, but initial thoughts would be:
- Likely this would be some `deleted` or `active` boolean flag on the entry model
- Registration List API and CLI would add a filter for looking for de-activated entries, defaulting to active-only
- SPIRE Agents would only receive SVIDs for active registrations
- A new API for de-activating/activating entries by ID would probably be needed
- Registration Delete API, or a new API, would need to handle `hard delete` (today's behavior)
- Would it be helpful to expose `soft deleted` time, for determining eventual cleanup? Exaggerated example: if an entry has been `soft deleted` for a year, probably we don't need it anymore.

Right now it's possible to restrict deleting a bundle if there are associated entries. Do `soft deleted` entries count in the consideration here? Probably the answer is yes, but this and any similar scenarios need to be called out to ensure consistent behavior and proper documentation of that behavior.

**Comment by rturner3** [comment]
Hi @amoore877, the maintainers discussed this and felt in cases where an operator or job is managing deletion of entries, the caller should be able to keep the entry data locally before deletion. With that data, it should be able to re-create the entries if something goes wrong during the deletion. We feel this is a simpler solution than adding this capability into SPIRE because the implementation to support soft deletion would be complex and span across subsystems.

Given that, we are closing this issue for now.
