### ISSUE TITLE
add clarity in `AgentAuthorizer` middleware switch default

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#2432]
Ref [Agent Authorizer](https://github.com/spiffe/spire/blob/19719d954a9c01aaa94608e9d76b7ca46d3d8799/pkg/server/endpoints/middleware.go#L110)

In the [default case for handling FetchAttestedNode returns](https://github.com/spiffe/spire/blob/19719d954a9c01aaa94608e9d76b7ca46d3d8799/pkg/server/endpoints/middleware.go#L161), the code assumes that the only possible issue at this point is a mismatch of cert serial number between the agent's data in the database and the calling agent's certificate.
```
		default:
			log.WithFields(logrus.Fields{
				telemetry.SVIDSerialNumber: agentSVID.SerialNumber.String(),
				telemetry.SerialNumber:     attestedNode.CertSerialNumber,
			}).Error("Agent SVID is not active")
			return permissionDenied(types.PermissionDeniedDetails_AGENT_NOT_ACTIVE, "agent %q expected to have serial number %q; has %q", id, attestedNode.CertSerialNumber, agentSVID.SerialNumber.String())
		}
```

This seems to be based on the previous cases:
```
                 case err != nil:
...
		case attestedNode.CertSerialNumber == "":
...
		case attestedNode.CertSerialNumber == agentSVID.SerialNumber.String():
...
		case attestedNode.NewCertSerialNumber == agentSVID.SerialNumber.String():
...
```
and so, if only considering cert serial numbers, it would seem the final case left would be that there is a serial number mismatch (the `default`) today.

However:
- this is unintuitive based solely on having called `FetchAttestedNode`. A reader must inspect each of the listed cases and assume that the code is doing the right thing (ie, there are no missed validity checks, and no other validity errors possible beyond mismatched serial number). we at least need a comment here
- this will become more unintuitive in the future, potentially leading to the bug, if further validity checks are added in this switch case

Proposal if we want to go beyond adding a comment:
either
- change `default` case to instead be the "OK" case. Today, this is `case attestedNode.CertSerialNumber == agentSVID.SerialNumber.String():`, which takes no action.
-- `attestedNode.NewCertSerialNumber == agentSVID.SerialNumber.String():` is also "OK" but does some work, so it is not suitable as `default` IMO
-- if/when more cases are added here, especially more "OK cases with more work", this will become complex

and/or

- create a separate block/function for `checkSerialNumberValidity`, which specifically handles the serial number logic in switch-case. The initial error check would be its own pre-check before validity checks. Future classes of validity check could be other blocks/functions

**Comment by vaibhavkoshti7** [comment]
hello @evan2645 . I want to work on this issue. Could you asign this to me.

**Comment by vaibhavkoshti7** [comment]
hello @evan2645 . I want to work on this issue. Can you please assign it to me.

**Comment by evan2645** [comment]
Thanks @MarcosDY for assigning - @vaibhavkoshti7 you are now assigned!
