### ISSUE TITLE
Investigate options for propagation delay measurement

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#245]
In order to effectively rotate CA certificates, we need to understand how long it takes for the new certs to propagate. Investigate options for measuring propagation delay of CA certs across a single SPIRE trust domain. This issue is done when there is at least one method for reliably determining how long it takes for a new CA cert to fully propagate.

**Comment by y2bishop2y** [comment]
This might not be an issue if we change the Workload API to a PUSH instead of a Poll. 
open issue.

**Comment by walmav** [comment]
This might be not necessary depending on the workload api spec, if the workload api would be determined being a push with a bi-directional stream, then this will not be any delay. cc: @evan2645
