### ISSUE TITLE
error 20 at 0 depth lookup: unable to get local issuer certificate

### ISSUE THREAD

**Issue by thiagosantosleite** [spiffe/spire#2455]
Why the verify does not work? there are any intermediate generated that I didnt found.

```
openssl verify -CAfile /tmp/bundle.0.pem /tmp/svid.0.pem 
C = US, O = SPIRE
error 20 at 0 depth lookup: unable to get local issuer certificate
error /tmp/svid.0.pem: verification failed
```

Workload certificate:

```
openssl x509 -in /tmp/svid.0.pem -text | grep -A2 "Authority Key Identifier"
            X509v3 Authority Key Identifier: 
                keyid:52:A3:90:03:8B:FF:A6:B6:9A:18:D9:E8:1D:A6:0C:C9:C2:36:0F:D5
```

CA Certificate:

```
openssl x509 -in /tmp/bundle.0.pem -text | grep -A2 "Subject Key Identifier"
            X509v3 Subject Key Identifier: 
                87:A5:F3:57:A2:F0:35:AC:C0:F8:64:C4:54:E7:6E:D3:BA:39:C8:E8
            X509v3 Basic Constraints: critical
```

I didnt found who is "keyid:52:A3:90:03:8B:FF:A6:B6:9A:18:D9:E8:1D:A6:0C:C9:C2:36:0F:D5".

I'm following this example:
https://spiffe.io/docs/latest/try/spire101/

**Comment by azdagron** [comment]
The intermediate should be located in the svid.0.pem (first CERTIFICATE block is the SVID, the second is the intermediate). However, the `verify` command will only look at the first certificate present in the file. If you want to verify using openssl, you need to first copy the intermediate from svid.0.pem into a separate file (e.g. intermediates.pem). You can use the `-untrusted` flag to indicate the file containing the intermediates.

```
openssl x509 verify -CAfile /tmp/bundle.0.pem -untrusted intermediates.pem /tmp/svid.0.pem
```

**Comment by thiagosantosleite** [comment]
thanks @azdagron !
