### ISSUE TITLE
Implement -matchSelectorsOn in agent list CLI

### ISSUE THREAD

**Issue by MarcosDY** [spiffe/spire#2466]
Add  `-matchSelectorsOn` and `-selector` when listing agents on Server CLI
Make MATCH_SUPERSET default for `-matchSelectorsOn`

**Comment by evan2645** [comment]
Since we don't already have support for `-selector` on the agent list CLI, I think we could technically release this sooner than 1.1 but thought it would make sense to hold back for consistency since we can't release https://github.com/spiffe/spire/issues/2465 until 1.1 anyway

**Comment by evan2645** [comment]
Depends on https://github.com/spiffe/spire/issues/2464
