### ISSUE TITLE
k8s-workload-registrar support "k8s.io/api/admission/v1" version due to API removal of "k8s.io/api/admission/v1beta1" in Kubernetes version v1.22

### ISSUE THREAD

**Issue by developer-guy** [spiffe/spire#2470]
Due to [API Removals in Kubernetes v1.22](https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes), I think we have to support or at least do a workaround for converting "k8s.io/api/admission/v1beta1" requests to "k8s.io/api/admission/v1" like the code available in the official [Kubernetes example webhook(agnhost)](https://github.com/kubernetes/kubernetes/blob/175776d25a5cf007c1fe1294097a8bf8e8b90e28/test/images/agnhost/webhook/main.go#L65-L89)

**Comment by developer-guy** [comment]
we (w/@Dentrax) are the volunteers for doing this issue, we would like to help 🤝🙋🏻‍♂️

**Comment by azdagron** [comment]
That would be great @developer-guy! I believe we can just move to `k8s.io/api/admission/v1` since it was introduced in Kubernetes 1.16. We support 1.18+.

**Comment by faisal-memon** [comment]
Nice. I was planning to look into this fairly soon because its a problem for us too. LMK if you all need help or want to collaborate.

**Comment by faisal-memon** [comment]
I believe this will require us to update controller-runtime to at least 0.7.0 to get the v1 webhook types. Bullet 1 under "High-Impact": https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.7.0

**Comment by faisal-memon** [comment]
@developer-guy How is this coming along?

**Comment by developer-guy** [comment]
Hello @faisal-memon thanks for asking, I couldn't find time to look at it but I will do it ASAP, but if you want to work on it, please go ahead 🙋🏻‍♂️🤝

**Comment by faisal-memon** [comment]
Thanks for checking in @developer-guy and I appreciate you volunteering to work on this. I would like to get this into the [SPIRE 1.1.0](https://github.com/spiffe/spire/milestone/7) release, which means we would need a PR before the end of the month. Is that doable for you?

**Comment by developer-guy** [comment]
yeah, deadline is ok for me @faisal-memon
