### ISSUE TITLE
Library to parse SPIFFE ID out of a cert

### ISSUE THREAD

**Issue by drrt** [spiffe/spire#25]
_From @evan2645 on July 18, 2017 19:32_

In order to do any of the authentication we want, we need to be able to pull a SPIFFE ID out of a certificate. In practice, this is poorly supported due to the use of the URI SAN type. Additionally, this action will be performed in many places, by us and by others, so it makes sense to build a shared library.

We can use the `go-spiffe` repo for this. The lib should provide at least two helper methods:
1. Given a cert or TLS connection, give me the SPIFFE ID of the client
1. Given a cert or TLS connection, assert that the client matches SPIFFE ID `foo`

_Copied from original issue: spiffe/node-agent#3_

**Comment by evan2645** [comment]
This is done. Go 1.10 also makes this trivial
