### ISSUE TITLE
Lack of DNSName/CN configuration for Server's SVID

### ISSUE THREAD

**Issue by SilvaMatteus** [spiffe/spire#2500]
* **Version**: latest
* **Platform**: any
* **Subsystem**: server/svid/rotator

Hi everyone,

Recently I needed to communicate with the Server's registration API via a Python client.

If I am not missing something, there is no way to configure a DNSName or CN for the Server SVID (presented in the registration API connections).  It makes clients abort the connections with errors like `Peer name example.org is not in peer certificate`.

We have the option to configure `ca_subject` for the bundle. How about having an option to also configure the Server's SVID? We have [this configuration](https://github.com/spiffe/spire/blob/main/pkg/server/api/svid/v1/service.go#L105) for other SVIDs.
It may be a parameter added to `ca.X509SVIDParams` in the [Server's rotator](https://github.com/spiffe/spire/blob/main/pkg/server/svid/rotator.go#L89).

**Comment by azdagron** [comment]
Hi Matteus! The option to configure DNS SANs/CN for workload registrations is principally motivated to allow legacy, SPIFFE-unaware workloads to do traditional hostname validation of the certificates. In this case, we're talking about the SPIRE server, which seems less likely to be need to interface with SPIFFE-unaware workloads. The strong preference is for new software to perform SPIFFE authentication of X509-SVIDs. Which library are you using to do the TLS? Can you hook the validation path?

> I needed to communicate with the Server's registration API
Just a heads up that the Registration API is deprecated and will be removed in 1.1. You should prefer the other APIs.

**Comment by SilvaMatteus** [comment]
I see. I'll look for a way to hook the validation path.

> Just a heads up that the Registration API is deprecated and will be removed in 1.1. You should prefer the other APIs.

Yeah, I  was talking about `spire.api.server.entry.v1`. I wrote the wrong name :P

Since changing the SPIRE code is not what we want, I'm closing this issue.

Thank you, @azdagron.
