### ISSUE TITLE
Federation Management API: Implement DataStore support for DeleteFederationRelationship

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#2507]
The implementation should be a fairly simple CRUD operation.

**Comment by marcosy** [comment]
While working on this issue I started wondering whether this method should delete the bundle associated to that trust domain in addition to the federation relationship? I was thinking about it considering that the CreateFederationRelationship datastore method creates/updates the bundle if provided.

**Comment by azdagron** [comment]
We discussed this on slack. The consensus was that this API should not remove the bundle.
