### ISSUE TITLE
Federation Management API: Implement the TrustDomain.RefreshBundle RPC

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#2513]
The implementation for this may be a little tricky if we try and interface with the bundle manager directly. To simplify things and provide for an easy test experience, then handler should receive an interface like the following:

```
type BundleRefresher interface {
    // RefreshBundleFor refreshes the bundle for the given trust domain. If the 
    // trust domain is not known, false is returned. Otherwise true is returned along
    // with the result of the refresh operation.
    RefreshBundleFor(ctx context.Context, td spiffeid.TrustDomain) (bool, error)  
}
```

We can implement that interface when we add support to the bundle manager.

**Comment by azdagron** [comment]
@SilvaMatteus has raised his hand to tackle this. Thanks!

**Comment by azdagron** [comment]
I'm going to assign it to me so somebody else doesn't try and claim it.

**Comment by SilvaMatteus** [comment]
Good. Just waiting for the PR from Marcos.
