### ISSUE TITLE
Release SPIRE 1.1

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#2584]
Tracking issue for SPIRE 1.1 release

Release commit: ~009aaef~ f632710

* Updated to include the SDK v1.1.0 dep bump

**Comment by Mixaster995** [comment]
Will you update CRD in Quickstart for spire-registrator (https://github.com/spiffe/spire/blob/main/support/k8s/k8s-workload-registrar/mode-crd/README.md#configuration)? 
It is required for correct work on kubernetes >=1.22

**Comment by azdagron** [comment]
@Mixaster995 , we talked about this elsewhere, but just to make sure everybody sees the answer, but 1.1.0 will  include support for the v1 webhooks. The quickstart will be updated after release to document this and bump the image version in the example to the 1.1.0 image.
