### ISSUE TITLE
Update CustomResourceDefinition and ValidatingWebhookConfiguration for spire-registrator

### ISSUE THREAD

**Issue by Mixaster995** [spiffe/spire#2586]
## Issue
Quickstart for SPIRE Kubernetes Workload Registrar (CRD Mode) not working with kubernetes 1.22 because of old api version in CustomResourceDefinition and ValidatingWebhookConfiguration
https://github.com/spiffe/spire/blob/main/support/k8s/k8s-workload-registrar/mode-crd/README.md#configuration

Output:
`unable to recognize "https://raw.githubusercontent.com/spiffe/spire/main/support/k8s/k8s-workload-registrar/mode-crd/config/spiffeid.spiffe.io_spiffeids.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "https://raw.githubusercontent.com/spiffe/spire/main/support/k8s/k8s-workload-registrar/mode-crd/config/spire-server-registrar.yaml": no matches for kind "ValidatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1"`

## Root cause
Kubernetes drops support for v1beta1 for CRD in 1.22 version

## Expected behaviour
Everything should work

## Possible solution
Update CustomResourceDefinition and ValidatingWebhookConfiguration from version v1beta1 to version v1

* **Version**: 1.0.2 spire-agent, 1.0.2 spire-server, 1.0.2 spire-registrator
* **Platform**: kind cluster with 1.22 kubernetes version

**Comment by azdagron** [comment]
The 1.1 release (happening EOW) includes support for the v1 webhook but 1.0.2 does not. @faisal-memon will be fixing up the quickstart right after the release to 1) use the v1 webhook and 2) update the image to 1.1.

**Comment by azdagron** [comment]
Good idea :)
