### ISSUE TITLE
Implement SVID labels in SPIRE

### ISSUE THREAD

**Issue by dfeldman** [spiffe/spire#2588]
This is a tracking issue to implement SVID labels in SPIRE. The feature has already been discussed and approved in [SPIFFE #179](https://github.com/spiffe/spiffe/pull/179), but it needs to be implemented in SPIRE.

**Comment by dfeldman** [comment]
Hint is now in the datastore schema. 
I have the needed change in go-spiffe here: https://github.com/spiffe/go-spiffe/pull/179. 
I'm working on step 2, adding it to the API. This might require a feature flag -- not sure.

**Comment by guilhermocc** [comment]
Hey there, I would like to contribute by continuing to resolve this issue, but first, I need to know what is left to be done, could someone help me with that?

**Comment by evan2645** [comment]
Hey @guilhermocc - thank you for this! @dfeldman was working on Step 2 above, but I'm not sure how far he got. I'll go ahead and assign this issue to you

**Comment by rturner3** [comment]
@guilhermocc We will also want to update the [java-spiffe](https://github.com/spiffe/java-spiffe) Workload API client for feature parity in both Go and Java client libraries.

**Comment by guilhermocc** [comment]
@rturner3 ok, I'm going to create a sub-task for it 👍
