### ISSUE TITLE
Heavily exercise SVID update

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#260]
Run agent for 1-4 hours while continuously creating registration entries and pulling SVIDs from workload API. The goal is to exercise the fetching and generation of new SVIDs (newly merged cache manager code) so that we know it's stable before demoing it.

- [x] Create initial framework
- [x] Improve final report
- [ ] Add different scenarios
- [x] [Integrate to our CI system](https://github.com/spiffe/spire/issues/285)

**Comment by evan2645** [comment]
A good test might be to set SVID ttl to 5s and watch the agent create new CSRs and SVIDs as the old one rapidly expires (in addition to creating new registration entries etc).

It would great if this was scripted so we can use it in the future

**Comment by kunzimariano** [comment]
We should also consider setting the base SVID TTL as low as possible so we can see both base and regular SVIDs expiring at the same time.

**Comment by evan2645** [comment]
Other things to track/measure:
memory consumption of the agent/server
make sure we get the same number of SVIDs (no duplication or missing SVIDs)
workload API response time
make sure SVIDs are not expired

**Comment by y2bishop2y** [comment]
I think we will have to break out this issue into multiple issues.

**Comment by walmav** [comment]
Add [leaktest](https://github.com/fortytw2/leaktest) 
Additional test cases with variations in SVID expiration times:
 1. Stress test with short SVID ttl
 2. Stress test by injecting multiple expiring cache entries

Workload socket connection stress testing: Bring up multiple workloads and connect to the same socketPath, monitor I/O latency.

**Comment by kunzimariano** [comment]
We could start by classifying the type of tests or what we want to achieve, for example:
- Resource usage (we should consider what makes sense to measure here). 
- Responsiveness or reliability under certain load.
- Finding the upper limit. In other words, how many requests/CSR can we handle? Which frequency?
- Functional tests, are the results we are getting what we are supposed to get?

**Comment by evan2645** [comment]
We have basic functional tests in place. We also have blackbox tests in place for rotation. Closing this issue for now
