### ISSUE TITLE
Node attestation failure with k8 configuration

### ISSUE THREAD

**Issue by shaaaarpy** [spiffe/spire#2608]
* **Version**: 
* **Platform**: 
* **Subsystem**: 

Hi
I have deployed my agent on k8 and spifee server is running on an azure VM. I am getting the following error
`➜ 
time="2021-10-29T13:47:01Z" level=warning msg="Current umask 0022 is too permissive; setting umask 0027."
time="2021-10-29T13:47:01Z" level=info msg="Starting agent with data directory: \"/myntra/data/agent\""
time="2021-10-29T13:47:01Z" level=info msg="Plugin loaded." built-in_plugin=true plugin_name=k8s_sat plugin_services="[]" plugin_type=NodeAttestor subsystem_name=catalog
time="2021-10-29T13:47:01Z" level=info msg="Plugin loaded." built-in_plugin=true plugin_name=memory plugin_services="[]" plugin_type=KeyManager subsystem_name=catalog
time="2021-10-29T13:47:01Z" level=info msg="Plugin loaded." built-in_plugin=true plugin_name=k8s plugin_services="[]" plugin_type=WorkloadAttestor subsystem_name=catalog
time="2021-10-29T13:47:01Z" level=info msg="Plugin loaded." built-in_plugin=true plugin_name=unix plugin_services="[]" plugin_type=WorkloadAttestor subsystem_name=catalog
time="2021-10-29T13:47:01Z" level=info msg="Bundle is not found" subsystem_name=attestor
time="2021-10-29T13:47:02Z" level=debug msg="No pre-existing agent SVID found. Will perform node attestation" path=/myntra/data/agent/agent_svid.der subsystem_name=attestor
time="2021-10-29T13:47:02Z" level=info msg="SVID is not found. Starting node attestation" subsystem_name=attestor
time="2021-10-29T13:47:02Z" level=warning msg="Insecure bootstrap enabled; skipping server certificate verification" subsystem_name=attestor
time="2021-10-29T13:47:02Z" level=warning msg="Insecure bootstrap enabled; skipping server certificate verification" subsystem_name=attestor
time="2021-10-29T13:47:02Z" level=warning msg="Insecure bootstrap enabled; skipping server certificate verification" subsystem_name=attestor
time="2021-10-29T13:47:02Z" level=warning msg="Insecure bootstrap enabled; skipping server certificate verification" subsystem_name=attestor
time="2021-10-29T13:47:02Z" level=warning msg="Insecure bootstrap enabled; skipping server certificate verification" subsystem_name=attestor
time="2021-10-29T13:47:02Z" level=error msg="agent crashed" error="failed to get SVID: error getting attestation response from SPIRE server: rpc error: code = FailedPrecondition desc = could not find node attestor type"`

I am also attaching my server conf for your reference
`
server {
    bind_address = "0.0.0.0"
    bind_port = "8081"
    trust_domain = "hello.com"
    data_dir = "/hello/data/server"
    log_level = "DEBUG"
    ca_ttl = "168h"
    log_file = "/hello/log/spire/server.log"
    default_svid_ttl = "15m"
}

telemetry {
    Statsd = [
	{address = "statsd.hello.com:8125"},
]
}

plugins {
    DataStore "sql" {
    	    plugin_data {
           	 database_type = "mysql"
		connection_string = ""
           }
    }

    KeyManager "disk" {
        plugin_data {
            keys_path = "/hello/data/server/keys.json"
        }
    }

    NodeAttestor "azure_msi" {

	plugin_data {
	tenants = {
        "" = {}
        }
	}
   }

    NodeAttestor "k8s_sat" {
        plugin_data {
          clusters = {
            # NOTE: Change this to your cluster name
            "aksmlpprodcluster01" = {
              use_token_review_api_validation = true
              service_account_whitelist = ["spire:spire-agent"]
            }
          }
        }
      }

   NodeResolver "azure_msi" {
        enabled = true
        plugin_data {
            use_msi = true
            tenants={}
        }
        }
   Notifier "k8sbundle" {
        plugin_data {
            namespace = "spire"
            config_map = "spire-bundle"
            config_map_key = "bundle.crt"
            kube_config_file_path = "/etc/spire/conf/server/kubeconfig"
        }
    }
}`

Can you look what is missing in the conf. Thank you!!

**Comment by azdagron** [comment]
Can you provide your agent configuration?

**Comment by shaaaarpy** [comment]
yes my agent conf is 
`agent {
      data_dir = "/hello/data/agent"
      log_level = "DEBUG"
      server_address = "spire-server.myntra.com"
      server_port = "8081"
      socket_path = "/run/spire/sockets/agent.sock"
      insecure_bootstrap = true
      trust_domain = "hello.com"
    }
    telemetry {
    Statsd = [
        {address = "statsd.hello.com:8125"},
      ]
    }
    plugins {
      NodeAttestor "k8s_sat" {
        plugin_data {
          cluster = "aksmlpprodcluster01"
        }
      }

      KeyManager "memory" {
        plugin_data {
        }
      }

      WorkloadAttestor "k8s" {
        plugin_data {
          skip_kubelet_verification = true
        }
      }

      WorkloadAttestor "unix" {
          plugin_data {
          }
      }
    }`

Thank you

**Comment by azdagron** [comment]
Hi @shaaaarpy, did this get resolved? Can we close the issue?

**Comment by azdagron** [comment]
I _think_ we resolved this in our slack conversation? If I am mistaken, please feel free to re-open!
