### ISSUE TITLE
unix selectors that exclude containerized workload

### ISSUE THREAD

**Issue by kfox1111** [spiffe/spire#2610]
* **Version**: 1.1.0
* **Platform**: Linux
* **Subsystem**: unix workload plugin

I have some systems that have some underlying services running on them, such as sshd that need identities. On the same system, there are containers managed though either Kubernetes or Docker.

The unix workload plugin currently only lets you select via uid/gid/etc that will also match containerized workload. This would allow a container to get access to the identity of the underlying hosts sshd.

Root on the host is not the same as root within a container. Containerized workload often has extra protections in place such as dropping most Linux Capabilities(https://man7.org/linux/man-pages/man7/capabilities.7.html) so a "root" user in a container often behaves much more like a regular user. Containerization allows it to have essentially a different identity as the user on the host.

So, its important that there is a way to be able to target workload specifically on the host vs running in a container.

Some additional selectors like cname attributes, selinux contexts, seccomp profiles, etc might be useful to allow a workload selector to be specific enough to target only the right workload.

**Comment by kfox1111** [comment]
Looks like including selectors for the contents of:
```
cat /proc/<pid>/cgroup
```
would be very interesting. For sshd on my systems it looks like:
```
12:perf_event:/
11:blkio:/system.slice
10:hugetlb:/
9:devices:/system.slice
8:memory:/system.slice/sshd.service
7:rdma:/
6:freezer:/
5:cpuset:/
4:net_cls,net_prio:/
3:pids:/system.slice/sshd.service
2:cpu,cpuacct:/system.slice
1:name=systemd:/system.slice/sshd.service
```

Just the name alone there is interesting and seems to distinguish from containers and includes that its systemd service sshd and not some other systemd service.

Perhaps though for unix identity the pids one is relevant.

**Comment by evan2645** [comment]
Hey @kfox1111 - we discussed this issue today, trying to figure out what is needed in order to satisfy the use case. Sounds like using add'l selectors to sharp shoot the workload(s) you care about is the easiest path forward? The unix attestor has path and sha256 selectors that you might be able to use .. would that suffice? There is also a [new systemd attestor](https://github.com/spiffe/spire/pull/4058/files) that might be relevant

Alternatively, we could consider including some additional selector data like cgroup information, but I'm not quite sure what the usability would/could look like there.

**Comment by kfox1111** [comment]
Yeah, a new selector just stating it isn't in a cgroup might be enough. But not sure how systemd plays in with things there. sha256 is hard to use. software updates could break it easily if its not well controlled. Path could work, provided the paths are not relative to a namespace like inside a container?

The systemd one looks interesting too. Can you use both unix and systemd together or are they separate?

Less sure about the other cgroup properties as selectors too.

**Comment by evan2645** [comment]
> sha256 is hard to use. software updates could break it easily if its not well controlled.

Yea, agreed.

> The systemd one looks interesting too. Can you use both unix and systemd together or are they separate?

Yes you can use them together. We can also extend the systemd attestor to emit add'l selectors if it helps this use case. I think it would be better than cgroup-centric selectors

**Comment by kfox1111** [comment]
Ok, I'll play around with the systemd one a little bit and see what it looks like in certain scenarios.

**Comment by evan2645** [comment]
Sounds good - let us know!

**Comment by evan2645** [comment]
The systemd plugin shipped with a bug unfortunately, and there is an open PR to fix it. Once the PR is merged, you should be able to test it using the nightlies

We're going to go ahead and close this out for now. If it doesn't solve your use case, please let us know and we can re-open
