### ISSUE TITLE
Windows support: building the tpm_devid agent plugin

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#2615]
The tpm_devid agent plugin does not currently build on Windows. The problem is that the Windows version of the [OpenTPM](https://github.com/google/go-tpm/blob/master/tpm2/open_windows.go#L26) function does not allow a path argument as it does for [other platforms](https://github.com/google/go-tpm/blob/master/tpm2/open_other.go#L34).

In Windows, a path cannot be supplied.

**Comment by colek42** [comment]
https://github.com/testifysec/spire-tpm-plugin is based on the https://github.com/google/go-attestation library and has windows support.

@azdagron was kind enough to upgrade it to the current API.  I'm adding PCR support and will be opening an upstream PR in about a week.

**Comment by MarcosDY** [comment]
[EmulatorReadWriteCloser](https://github.com/spiffe/spire/blob/main/pkg/agent/plugin/nodeattestor/tpmdevid/tpmutil/session.go#L160) is no present in [run_windows.go](https://github.com/google/go-tpm/blob/master/tpmutil/run_windows.go) but it is on [run_other.go](https://github.com/google/go-tpm/blob/master/tpmutil/run_other.go#L61), so we must take care of it too
