### ISSUE TITLE
Need an automated mechanism to track linked OSS code within SPIRE

### ISSUE THREAD

**Issue by suniljames** [spiffe/spire#262]
_[Assigning to drrt@ as per y2bishop2y]_

We need an automated to understand - at any given moment - what linked OSS (or otherwise) code exists within the SPIRE codebase. For each bit of linked code, we need to be able to answer the following questions (and have said answers exportable into a spreadsheet):

1) What is the name of the linked code?
2) From which URL was said linked code downloaded from and included in SPIRE?
3) On what date/time was said linked code downloaded from aforementioned URL?
4) What were the license terms of the code when downloaded?
5) What are the license terms of the code as of now (as detailed from the URL where it was first downloaded)?
6) What SPIRE codebases have linked to this code?

**Comment by suniljames** [comment]
We should evaluate https://fossa.io/ here.

**Comment by anvega** [comment]
FOSSA has been used for quite some time.

https://github.com/spiffe/assets/tree/master/fossa

The latest report is publicly downloadable here:
https://app.fossa.com/attribution/c27aa038-b826-4dac-91eb-076d3ea63c03
