### ISSUE TITLE
oidc-discovery-provider 'use' property

### ISSUE THREAD

**Issue by kfox1111** [spiffe/spire#2623]
I've been trying to get Spire and Strimzi deployed Kafka to work together. I deployed the oidc-discovery-provider and connected Kafka to it. It almost works but apparently the Kafka plugin is expecting the JWKS to have the 'use' property specified. It appears optional in the spec so its arguably a Kafka plugin bug. But, there could be other oidc/oauth2 clients that have similar expectations so for compatibility reasons, the ability to have oidc-discovery-provider allow force setting the 'use' property might be useful. Perhaps a command line flag to force set the 'use' property to 'sig'?

**Comment by azdagron** [comment]
I think this sounds reasonable. I am tempted to just add "use" to the JWKs across the board but I am not super confident that it won't break some esoteric existing deployment. It WOULD be surprising if an implementation couldn't handle the parameter but we've seem some crazy stuff.

> command line flag

The project does not use flags except to direct the application to a config file. I could see us growing a new `jwks` section in the config file for controlling rendering (assumes that we may have other properties to tweak in the future).

Maybe something like:

```
jwks {
    set_use_parameter = true
}
```

**Comment by azdagron** [comment]
If we got enough signal that "use" was safe across the board, we could always migrate the default to true (following our backcompat guidelines).

**Comment by azdagron** [comment]
Fixed by #2634.
