### ISSUE TITLE
Feature Request: make configurable of specifying selectors while deploying k8s-workload-registrar

### ISSUE THREAD

**Issue by developer-guy** [spiffe/spire#2658]
There are a bunch of selectors in the [Workload K8S Attestator](https://github.com/spiffe/spire/blob/v1.1.1/doc/plugin_agent_workloadattestor_k8s.md), but there is no way of specifying which one of them do I want to use while deploying the `k8s-workload-registrar` webhook because by default, it uses `k8s:pod-name` and `k8s:ns:` selectors.

So, what we (w/@dentrax) are proposing is that make them configurable while deploying the `k8s-workload-registrar`.

> please feel free to assign it to us, we would love to take care of that. 🤝

**Comment by evan2645** [comment]
Hi @developer-guy, thank you for opening this issue.

I'd love to learn a little more about what you're trying to accomplish. What kind of selectors would you prefer to use and why?

Alternatively, you can try giving the spire-controller-manager a look. It is still in the early stages and not production ready, but it already has something like what you're asking here: https://github.com/spiffe/spire-controller-manager/blob/main/api/v1alpha1/clusterspiffeid_types.go

**Comment by developer-guy** [comment]
Hello @evan2645, thank you for the response!
> I'd love to learn a little more about what you're trying to accomplish. What kind of selectors would you prefer to use and why?

There are no specific selectors that I would prefer but we thought that if we make them configurable, it can add more flexibility to the webhook.

> Alternatively, you can try giving the spire-controller-manager a look. It is still in the early stages and not production ready, but it already has something like what you're asking here: spiffe/spire-controller-manager@main/api/v1alpha1/clusterspiffeid_types.go

Ah, it seems so if I can specify the selector types for my Pods(workloads) while registering them.

**Comment by rturner3** [comment]
Closing this since k8s-workload-registrar is now deprecated, and this feature should be available in [spire-controller-manager](https://github.com/spiffe/spire-controller-manager). Let us know if there is anything else we may have missed here.
