### ISSUE TITLE
Provide installation steps for the k8s-workload-registrar (+ webhook example in quick start)

### ISSUE THREAD

**Issue by Dentrax** [spiffe/spire#2659]
It had better to provide some quick start navigation the [README.md](https://github.com/spiffe/spire/blob/main/support/k8s/k8s-workload-registrar/README.md). We had to find the [mode-crd](https://github.com/spiffe/spire/tree/main/support/k8s/k8s-workload-registrar/mode-crd#quick-start) folder, which is a bit hard to figure it out at the beginning.

Furthermore, we can add webhook example in the [spire-tutorials/k8s/quickstart](https://github.com/spiffe/spire-tutorials/tree/master/k8s/quickstart).

What do you think?

@developer-guy

**Comment by evan2645** [comment]
> It had better to provide some quick start navigation the README.md. We had to find the mode-crd folder, which is a bit hard to figure it out at the beginning.

We have some links to the quickstarts on the website currently, but the k8s quickstart doesn't use the registrar 🤔 @sanderson042 I thought I recall someone working on adding that?

We should really just have one quickstart for k8s 😬

> Furthermore, we can add webhook example in the spire-tutorials/k8s/quickstart.

We've been discouraging folks from using webhook mode for some time now. CRD mode is the one we recommend, and the whole mode situation in general is a legacy soup that we're trying to clean up. Please have a look at the new spire-controller-manager ... it's still very early but we'd love your feedback 

https://github.com/spiffe/spire-controller-manager

**Comment by Dentrax** [comment]
Thanks for the clarification @evan2645! I didn't notice spire-controller-manager. Definitely look into it!

To summarize up, how should we proceed here? Should we write some documentation about the webhook and contoller-manager to clarify the installation process?

**Comment by sanderson042** [comment]
Hi all,

Evan, I think you are referring to the PR below from @lucianozablocki . The last I remember, you had a phone call with him and he agreed to make some changes based on that conversation. I don't think the doc is intended as a standalone k8s tutorial but rather as a complement to the existing k8s tutorial (but it sounds like that is what is needed...). I've pinged him and will let you know if he's still working on it.

PR:
https://github.com/spiffe/spire-tutorials/pull/59

Doc for PR:
https://github.com/spiffe/spire-tutorials/blob/76a63685beac1e7f48ad3b2ee40374f206bab34c/k8s/k8s-workload-registrar/README.md

**Comment by sanderson042** [comment]
Update: Luciano is on vacation now but hopes to resume work on the k8s workload registrar tutorial after his vacation.

**Comment by rturner3** [comment]
Closing this since k8s-workload-registrar is now deprecated.
