### ISSUE TITLE
discussion: tlog: push entries/type(s) to rekor: convert types/entry object to rekor schema(s)

### ISSUE THREAD

**Issue by Dentrax** [spiffe/spire#2660]
As we all know that Spire API uses a [types/entry/v1](https://github.com/spiffe/spire-api-sdk/blob/4735c1b6518e55c14b671164231c02a92de8e83c/proto/spire/api/types/entry.proto#L8-L56) (and [other types](https://github.com/spiffe/spire-api-sdk/tree/main/proto/spire/api/types)) model - _A registration entry maps an identity – in the form of a SPIFFE ID – to a set of properties known as selectors that the workload must possess in order to be issued a particular identity._ [^2]

---

[rekor](https://github.com/sigstore/rekor)'s goals are to provide an immutable tamper resistant ledger of metadata generated within a software projects supply chain. Rekor will enable software maintainers and build systems to record signed metadata to an immutable record.

There is an [Attestation Transparency](https://docs.google.com/document/d/18vejheS6HPos-G6ZEjLekXuvIEsWDPywts-DKuxyzco/edit?resourcekey=0-os1n7gVr6AjIAKSGTXvGpA#heading=h.ramqb693vq3c) system, allowing for the storage and retrieval of rich In-Toto attestations that contain the full build history of any given artifact, including the exact tools, source code and build system that was used. [^3]

See the similar implementation how we create [hashedrekord_v001.V001Entry](https://github.com/sigstore/rekor/blob/main/pkg/types/hashedrekord/v0.0.1/hashedrekord_v0_0_1_schema.json) in the [rekorEntry](https://github.com/sigstore/cosign/blob/1feacab43fb01662ff372ab58e4186cf7da8ffcb/pkg/cosign/tlog.go#L111-L132) function in cosign. [^1] I'm not so sure whether it would fit in this use-case, so we thought (@developer-guy) that dropping the idea here to make further discussion on this topic.

We probably have to create custom schema(s) in the rekor for specific types that defined in the API.

@dlorenc @bobcallaway @lukehinds would have better thoughts on this. Could you please enlighten us?

[^1]: https://github.com/sigstore/cosign
[^2]: https://spiffe.io/docs/latest/deploying/registering/
[^3]: https://dlorenc.medium.com/zero-trust-supply-chain-security-e3fb8b6973b8

**Comment by lukehinds** [comment]
Sounds like an interesting proposal. Would the entry be signed? Rekor likes a pub key, sig so it gets non repudiation around whomever makes the entry?

**Comment by evan2645** [comment]
There is a lot of interest in this, from myself included :)

There are many potential applications .. but personally, I think the most valuable use case is recording node and workload attestation results for audit and forensic purposes.

> Would the entry be signed?

If we send attestation data, I think it should be signed by the entity making the attestation (i.e. either SPIRE Server or a SPIRE Agent).

What kind of use cases do you see around having entry data in rekor too?

Finally, I've been given the impression that performance may be a big concern as SPIRE attestation velocity may outpace rekor, how much rekor do you want to throw at this problem, etc ..
