### ISSUE TITLE
Detect and warn when an incorrect profile is configured for a remote bundle endpoint

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#2668]
When a SPIRE Server bundle endpoint is configured without ACME, it serves the `https_spiffe` profile by default. Aside from this being poorly documented, when the profile is misconfigured on the bundle endpoint client in SPIRE Server, we return errors relating to name validation. For example, the following is logged when a client configured for `https_web` connects to an endpoint using the `https_spiffe` profile:
```
time=2022-06-01T05:45:00Z level=error msg="Error updating bundle" error="Failed to fetch federated bundle from endpoint: failed to fetch bundle: Get \"https://my-cluster-domain:8443\": x509: certificate is not valid for any names, but wanted to match my-ingress-url" subsystem_name=bundle_client trust_domain=domain2.example
```

I think we can probably detect this condition .. if we are using https_web and we fail on name validation, we should check the server certificate for a SPIFFE ID. If present, we can warn and/or include an indicator of the misconfiguration in the error message.

Other misconfiguration combinations are unfortunately harder to detect with any certainty, but at least we can help out on this one.

**Comment by ryysud** [comment]
@evan2645 Is this issue fixed in https://github.com/spiffe/spire/pull/3395?

**Comment by evan2645** [comment]
Yes! Thank you so much @ryysud ❤️
