### ISSUE TITLE
spire-agent fails to fetch authorized entries for very large entry sets

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#2675]
The gRPC Entry API client used in spire-agent uses the default maximum gRPC response message size of 4 MB. When a `GetAuthorizedEntriesResponse` message exceeds 4 MB in its protobuf serialized form, spire-agent will continuously fail to update its entries from the server:
```
ERRO[0025] Synchronize failed                            error="failed to fetch authorized entries: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (5404085 vs. 4194304)" subsystem_name=manager
ERRO[0041] Failed to fetch authorized entries            error="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (5404085 vs. 4194304)" subsystem_name=manager
```

**Comment by rturner3** [comment]
A few options that come to mind about how this could be addressed:

1. We could override the default gRPC max response message size in SPIRE Agent to something larger. It will probably remove this problem for most larger-scale users, but it doesn't really solve the underlying scaling bottleneck.
1. We make changes to the `GetAuthorizedEntries` method to use some form of pagination and rework the Agent code to use that pagination. This could be tough to implement though since there is currently no cache coherence between in-memory server entry caches in an HA deployment.
1. We introduce a new server streaming method in the Entry API that eventually replaces `GetAuthorizedEntries`. This method could split the response into batches that will definitely not exceed 4 MB. Probably the most straightforward solution but is a bigger change.

**Comment by esweiss** [comment]
Approximately 30,000 entries triggers this

**Comment by rturner3** [comment]
Actually looks like closer to 17k entries will cause this issue. Example code to estimate `GetAuthorizedEntriesResponse` size:
```go
package main

import (
    "fmt"

    entryv1 "github.com/spiffe/spire-api-sdk/proto/spire/api/server/entry/v1"
    "github.com/spiffe/spire-api-sdk/proto/spire/api/types"
    "google.golang.org/protobuf/proto"
)

const (
    numEntries = 17000
)

func main() {
    resp := &entryv1.GetAuthorizedEntriesResponse{
        Entries: generateEntries(),
    }

    numMbOfResp := float64(proto.Size(resp)) / 1024.0 / 1024.0
    fmt.Printf("%f MB\n", numMbOfResp)
}

func generateEntries() []*types.Entry {
    entries := make([]*types.Entry, 0, numEntries)
    for i := 0; i < numEntries; i++ {
        entry := &types.Entry{
            SpiffeId: &types.SPIFFEID{
                TrustDomain: "example.org",
                Path:        fmt.Sprintf("/reasonably/long/spiffeid/like/in/production/%d", i),
            },
            ParentId: &types.SPIFFEID{
                TrustDomain: "example.org",
                Path:        "/spire/agent/foobar-host",
            },
            Selectors: []*types.Selector{
                {
                    Type:  "docker",
                    Value: "label:org.example.some.docker.label:somedockerlabelvalue",
                },
                {
                    Type:  "docker",
                    Value: "label:org.example.some.docker.label:somedockerlabelvalue",
                },
            },
        }

        entries = append(entries, entry)
    }

    return entries
}
```

```
$ go run .
3.993883 MB
```

**Comment by zmt** [comment]
What about implementing registration synchronization as a Merkle tree?

**Comment by azdagron** [comment]
I'm closing this issue in lieu of #3496. If that proposal is rejected, we can reopen this issue to explore alternatives.
