### ISSUE TITLE
race detector makes TestRotator flaky in pkg/agent/svid

### ISSUE THREAD

**Issue by zmt** [spiffe/spire#2713]
* **Version**: 20671191f75e52f3f698377dcca12325af87e6b3
* **Platform**: `Linux [redacted] 5.4.129+ #1 SMP Wed Aug 18 19:58:18 PDT 2021 x86_64 GNU/Linux`
* **Subsystem**: Agent

The `TestRotator` in `pkg/agent/svid` fails at an unacceptable frequency when run under the race detector. No specific data race is detected, but the additional overhead of enabling the race detector seems to trigger failures in some time-dependent tests. It tends to fail in one of 2 ways:

Example 1:
```
% go test -race -count 25 -failfast -run TestRotator ./pkg/agent/svid
--- FAIL: TestRotator (60.03s)
    --- FAIL: TestRotator/expires_after_startup (60.01s)
        rotator_test.go:113: timed out waiting for rotation check to finish after clock adjustment
FAIL
FAIL	github.com/spiffe/spire/pkg/agent/svid	60.486s
FAIL
```

Example 2:
```
% go test -race -count 25 -failfast -run TestRotator ./pkg/agent/svid
--- FAIL: TestRotator (0.07s)
    --- FAIL: TestRotator/expires_after_startup (0.03s)
        rotator_test.go:130:
            	Error Trace:	rotator_test.go:130
            	Error:      	Should be true
            	Test:       	TestRotator/expires_after_startup
            	Messages:   	SVID stream should have changes
FAIL
FAIL	github.com/spiffe/spire/pkg/agent/svid	0.135s
FAIL
```

These do not occur when race detector is not enabled:
```
% for i in $(seq 4)
do
    go test -count 25 -failfast -run TestRotator ./pkg/agent/svid
done
ok  	github.com/spiffe/spire/pkg/agent/svid	0.852s
ok  	github.com/spiffe/spire/pkg/agent/svid	0.850s
ok  	github.com/spiffe/spire/pkg/agent/svid	0.834s
ok  	github.com/spiffe/spire/pkg/agent/svid	0.880s
```

**Comment by zmt** [comment]
Also see #2379 & #2705.

**Comment by zmt** [comment]
Per discussion in con tributor sync, we should probably just migrate this to mock clock entirely to make it less flaky.

**Comment by mjlshen** [comment]
Adding a third way this fails - curiously this test does seem to be using the mock clock though
```
--- FAIL: TestRotator (0.00s)
    --- FAIL: TestRotator/not_expired_at_startup (0.00s)
        rotator_test.go:124: 
            	Error Trace:	rotator_test.go:124
            	Error:      	Should be true
            	Test:       	TestRotator/not_expired_at_startup
            	Messages:   	expected context canceled, not <nil>
FAIL
FAIL	github.com/spiffe/spire/pkg/agent/svid	0.606s
FAIL
```

**Comment by zmt** [comment]
> Adding a third way this fails - curiously this test does seem to be using the mock clock though

I think I saw that one last week also. They are mostly using the mock clock and I think that is the problem. The places it is failing, it is selecting on a real `time.After` channel. For example: https://github.com/spiffe/spire/blob/main/pkg/agent/svid/rotator_test.go#L112-L113
