### ISSUE TITLE
Consistency delay between entry creation and SVID readiness

### ISSUE THREAD

**Issue by lumjjb** [spiffe/spire#2760]
I have a question about the consistency model for entries. I'm having the following series of events happening which is causing problems. What are some of the considerations of consistency model

22:31:28: Entry created
22:31:30: Workload queries agent socket fetching SVID, gets "PermissionDenied desc = no identity issued", fails...
22:31:35: SVID signed (SPIRE server logs)

(Moving conversation from Slack for documentation purposes.)

**Comment by evan2645** [comment]
Copied the rest here for posterity


[Evan Gilman](https://app.slack.com/team/U5QR1EDJQ)  [23 minutes ago](https://spiffe.slack.com/archives/C7XDP01HB/p1644360430355099?thread_ts=1644359857.487869&cid=C7XDP01HB)
consistency is dictated by datastore, however agent poll frequency is by default 5s, so it is "normal" to have up to 5s or so delay between registration and availability on the workload api (agent needs to sign csr, server needs to sign new certs, etc)
[Evan Gilman](https://app.slack.com/team/U5QR1EDJQ)  [22 minutes ago](https://spiffe.slack.com/archives/C7XDP01HB/p1644360493960109?thread_ts=1644359857.487869&cid=C7XDP01HB)
people deal with the delay in a number of ways ... but the easiest thing to do is retry with a backoff when you encounter permission denied, and this is noted in the spec (and I believe the go sdk does this)
[Evan Gilman](https://app.slack.com/team/U5QR1EDJQ)  [22 minutes ago](https://spiffe.slack.com/archives/C7XDP01HB/p1644360520353699?thread_ts=1644359857.487869&cid=C7XDP01HB)
Some other folks use init container .. etc
[Evan Gilman](https://app.slack.com/team/U5QR1EDJQ)  [18 minutes ago](https://spiffe.slack.com/archives/C7XDP01HB/p1644360714211599?thread_ts=1644359857.487869&cid=C7XDP01HB)
agent poll frequency is by default 5s
Cycle is, agent polls, asks for what identities it should have, compare list against local cache, reconcile, repeat
[Andrew Harding](https://app.slack.com/team/UA4C7Q74L)  [15 minutes ago](https://spiffe.slack.com/archives/C7XDP01HB/p1644360884685239?thread_ts=1644359857.487869&cid=C7XDP01HB)
Authorized entry latency is also introduced by the authorized entry cache, which refreshes every 10 seconds.
:100:
1

[Evan Gilman](https://app.slack.com/team/U5QR1EDJQ)  [15 minutes ago](https://spiffe.slack.com/archives/C7XDP01HB/p1644360901466669?thread_ts=1644359857.487869&cid=C7XDP01HB)
Oops
[Evan Gilman](https://app.slack.com/team/U5QR1EDJQ)  [15 minutes ago](https://spiffe.slack.com/archives/C7XDP01HB/p1644360915502479?thread_ts=1644359857.487869&cid=C7XDP01HB)
sadlol
[Brandon Lum](https://app.slack.com/team/UT51FJKB9)  [14 minutes ago](https://spiffe.slack.com/archives/C7XDP01HB/p1644360983363539?thread_ts=1644359857.487869&cid=C7XDP01HB)
hmm ok , so back off up till 20s sounds like enough leeway? :smile:
Only visible to you
[Slackbot](https://app.slack.com/team/USLACKBOT)  [14 minutes ago](https://spiffe.slack.com/archives/C7XDP01HB/p1644360988xxx125?thread_ts=1644359857.487869&cid=C7XDP01HB)
/me is not supported in threads. Sorry!
[Evan Gilman](https://app.slack.com/team/U5QR1EDJQ)  [13 minutes ago](https://spiffe.slack.com/archives/C7XDP01HB/p1644361022204859?thread_ts=1644359857.487869&cid=C7XDP01HB)
heh yea should be fine for now .. there is some overhead on k8s workload attestation too etc .. but 20 will probably get you there when also considering the cache refresh that andrew has pointed out
[Evan Gilman](https://app.slack.com/team/U5QR1EDJQ)  [13 minutes ago](https://spiffe.slack.com/archives/C7XDP01HB/p1644361049352669?thread_ts=1644359857.487869&cid=C7XDP01HB)
(signing load on SPIRE at the time, load on kublet, etc etc)
[Brandon Lum](https://app.slack.com/team/UT51FJKB9)  [10 minutes ago](https://spiffe.slack.com/archives/C7XDP01HB/p1644361192424359?thread_ts=1644359857.487869&cid=C7XDP01HB)
is this documented somewhere? if not can i create an issue (just purely for referencing this in code?)
[Brandon Lum](https://app.slack.com/team/UT51FJKB9)  [10 minutes ago](https://spiffe.slack.com/archives/C7XDP01HB/p1644361207479529?thread_ts=1644359857.487869&cid=C7XDP01HB)
issue can be closed, just need to point to something :slightly_smiling_face:
[Evan Gilman](https://app.slack.com/team/U5QR1EDJQ)  [8 minutes ago](https://spiffe.slack.com/archives/C7XDP01HB/p1644361317637049?thread_ts=1644359857.487869&cid=C7XDP01HB)
I don't believe we have anything explicitly documented around delay between registration and SVID availability. One problem is that it's highly variable based on load, another problem is that development changes can impact (e.g. the introduction of this cache with 10s refresh) .. but yes it would be great if we had something somewhere

**Comment by lumjjb** [comment]
Closing this since issue is answered! Thanks @evan2645 @azdagron !
