### ISSUE TITLE
Update federation commands in the SPIRE Server Configuration Reference

### ISSUE THREAD

**Issue by arielroque** [spiffe/spire#2790]
Reading the [SPIRE Server Configuration Reference](https://github.com/spiffe/spire/blob/main/doc/spire_server.md), it seemed to me that  [spire-server show](https://github.com/spiffe/spire/blob/main/doc/spire_server.md#spire-server-show) and  [spire-server refresh](https://github.com/spiffe/spire/blob/main/doc/spire_server.md#spire-server-show) commands  in the federation section should be, respectively,
```spire-server federation show``` and ```spire-server federation refresh``` according to Spire-server CLI v1.2.0:

```bash
./bin/spire-server federation
...
...
Subcommands:
    create     Creates a dynamic federation relationship with a foreign trust domain
    delete     Deletes a dynamic federation relationship
    list       Lists all dynamic federation relationships
    refresh    Refreshes the bundle from the specified federated trust domain
    show       Shows a dynamic federation relationship
    update     Updates a dynamic federation relationship with a foreign trust domain
```

**Comment by azdagron** [comment]
Thanks for bringing this to our attention!

**Comment by arielroque** [comment]
You're welcome. I'm happy to contribute to the project!
