### ISSUE TITLE
Error Using aws_iid NodeAttestor Plugin When Instance Profile Has a Path

### ISSUE THREAD

**Issue by y3gj3ib3tjr** [spiffe/spire#2796]
The following error was encountered when using the `aws_iid` NodeAttestor plugin.

`ERRO[0000] Agent crashed                                 error="failed to receive attestation response: rpc error: code = Internal desc = nodeattestor(aws_iid): failed to get intance profile: ValidationError: 1 validation error detected: Value 'xxxxx/yyyyy/MyProfile' at 'instanceProfileName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\w+=,.@-]+\n\tstatus code: 400, request id: 13ed13cc-c636-44d8-9cce-438f43fe6f83
`

The instance profile used for the error scenario above was: `arn:aws:iam::123456789012:instance-profile/xxxxx/yyyyy/MyProfile`

However it works (Node Attestation successful) when using another instance profile with identical permissions/trust policy but with a different path: `arn:aws:iam::123456789012:instance-profile/MyProfile`

The working instance profile does not have the `/xxxxx/yyyyy/` path.  It looks like AWS is only expecting the profile name (excluding the path) based on the regex error.  

This issue is being created after having been confirmed in the Slack channel.  It is related to the following code:
- https://github.com/spiffe/spire/blob/main/pkg/server/plugin/nodeattestor/aws/iid.go#L435

Version: spire-1.2.0
Platform: Amazon Linux
Subsystem: aws_iid Server NodeAttestor Plugin

**Comment by evan2645** [comment]
thank you for opening this @y3gj3ib3tjr 

We are trying to determine AWS behavior here. Is the instance profile name a flat namespace, blind to the specified path? In other words, is it possible to have both of the following instance profiles defined at once?
- `arn:aws:iam::123456789012:instance-profile/xxxxx/yyyyy/MyProfile`
- `arn:aws:iam::123456789012:instance-profile/yyyyy/xxxxx/MyProfile`

If you could provide some links to AWS documentation about how these profile paths are handled, that would be super helpful
