### ISSUE TITLE
k8s-workload-registrar container restarts because spire-server's socket is not ready

### ISSUE THREAD

**Issue by szvincze** [spiffe/spire#2872]
* **Version**: 1.0.1, 1.1.0 and 1.2.0
* **Platform**: Linux 5.13.0-30-generic - 20.04.1-Ubuntu SMP x86_64
* **Subsystem**: server

I used this [configuration](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/spire) for my tests.

In case I run it first time on a fresh cluster there is no container restart because while spire-server container starts, kubelet is just downloading k8s-workload-registrar image. Therefore spire-server has some time to start its UDS server and k8s-workload-registrar will be able to connect.

To reproduce the restart, delete spire related resouces by the below commands:
```
kubectl delete validatingwebhookconfiguration k8s-workload-registrar
kubectl delete crd spiffeids.spiffeid.spiffe.io
kubectl delete ns spire
```

Then deploy it again: `kubectl apply -k spire`

Now the restart of the k8s-workload-registrar container can be observed:
```
$ kubectl get pods -n spire`
NAME                READY   STATUS    RESTARTS   AGE
spire-agent-6prkf   1/1     Running   0          42s
spire-agent-9xpqk   1/1     Running   0          42s
spire-server-0      2/2     Running   1          42s
```
In the attached logs it can be seen that the UDS server is just starting in the same second when k8s-workload-registrar wants to connect to the socket which is not ready yet. Which causes the container restart.
[k8s-workload-registrar-err.log](https://github.com/spiffe/spire/files/8315021/k8s-workload-registrar-err.log)
[spire-server-err.log](https://github.com/spiffe/spire/files/8315024/spire-server-err.log)

I applied the below temporary workaround in the spire-server container specification:
```
lifecycle:
  postStart:
    exec:
      command: ["sleep", "2"]
```

According to the logs the k8s-workload-registrar container starts 2 seconds after UDS server started and the connection is successful, there are no restarts.

**Comment by richardstone** [comment]
I have seen issues in case of spire-agent too, which could have been avoided with a bit of waiting.

In some rare cases, one or two of the spire-agents fail to start on first try with this error:
`could not parse trust bundle: open /run/spire/bundle/bundle.crt: no such file or directory`

**Comment by szvincze** [comment]
The image (```fmemon/k8s-workload-registrar:2872```) from @faisal-memon seems to be working fine.
Most probably because of timing I did not manage to reproduce the original issue with the latest kind release (0.12.0) that creates nodes with 1.23.4 k8s version by default, but it is reproducible on k8s 1.21.1 nodes and the above image fixes the restarts on this version.
