### ISSUE TITLE
Bootstrap trust bundle for SPIRE Agent authenticating SPIRE Server should be separate from other bundle logic

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#2887]
Secure SPIRE Agent is configured with a "bootstrap trust bundle", which it uses to authenticate SPIRE Server for node attestation.
From node attestation, the [bundle from the Agent SVID](https://sourcegraph.com/github.com/spiffe/spire@d2541628d8dff3630f80a575e255e7e84063c2e9/-/blob/pkg/agent/attestor/node/node.go?L210) replaces the bootstrap bundle for all future operations in authenticating SPIRE Server.

However, what if the trust bundle configured in SPIRE Server contains CAs (still within the same trust domain) that no SPIRE Server is expected to be issuing under?

Example 1:
Example company has an `example.org` CA for SPIRE, and an `example.org` CA for some other issuance system `Foo`. I think this is a realistic case, not only if `Foo` is somehow serving highly-specialized cases SPIRE does not, but also if the Example company is in the middle of migrating from `Foo` to SPIRE.
We should expect workloads under `example.org` domain to interoperate, whether they are given identity by `Foo` or by SPIRE. For separation of duties, we probably should not have the CA for `Foo` and SPIRE be the same.
If a SPIRE Server starts issuing under `Foo`'s CA, I don't think SPIRE Agents should trust that Server just because `Foo`'s CA is in the bundle. This is likely a misconfiguration of Server:
- SPIRE Agent trusting such a Server also means Agent would trust `Foo`, or a malicious impersonator of `Foo`.
- `Foo`'s CA and Server's expected CA likely have different expiry times, potentially leading to unexpected failure.
- When `Foo` is decommissioned, the owners may very well attempt to revoke its CA. This causes the misconfigured SPIRE Server's issued SVIDs to become invalid unexpectedly.

Example 2:
Example company has created a new upstream CA `B` for SPIRE, and placed it proactively in the trust bundle so that in the future all workloads will trust it. However, since SPIRE Server itself is not yet configured to issue under `B`, SPIRE Agent should  probably not trust such Servers until configured explicitly to expect it, as close as reasonably possible to when Server will be rotated. The window from SPIRE Agent trusting `B` to SPIRE Server using it is a window where SPIRE Agent is trusting too many things.

Example 3:
Example company has fully migrated SPIRE Server to CA `B`. There are still workloads out there that are issued under `A`, so they should probably still be trusted by other workloads.
However, there is no reason anymore for SPIRE Agent to still trust any SPIRE Server under `A`.

Example 4:
SPIRE Server clusters are each issued separate CAs, but for interoperation of workloads the distributed trust bundle contains all of these CAs (or their common issuer). However, SPIRE Agents that only ever talk to Cluster 1 SPIRE Server should have no reason to trust Cluster 2 SPIRE Server.

Question 1:
Is SPIRE Server expected to be the *only* issuer for its trust domain?

Question 2:
Is SPIRE Server expected to distribute the entire trust bundle for its domain, or only the portions of the bundle that Server itself issues under?
If only portions, does it make sense for workloads to be getting a trust bundle for `example.org` from their SPIRE-issued SVIDs, but in order to interoperate with other workloads fetch the rest of the `example.org` bundle from somewhere else?

Proposal:
If we allow for other issuers in the domain and expect Server to distribute the entire bundle, then the bundle SPIRE Agent uses to authenticate SPIRE Server should only ever be a subset of the full bundle- the subset that the Agent's expected SPIRE Server is expected to be issuing under (or are about to issue under).

**Comment by amoore877** [comment]
From 2022.04.05 contributor sync:
- "lesser trusted" CAs vs "CAs for specific things"
- Maybe instead (in addition to) a SPIFFE ID specific per SPIRE clusters? Agents get configured to know which to talk to?
-- codebase has baked-in assumptions throughout on the Server's ID
- SPIRE distribute "Agent bundle" vs "workload bundle"?
-- What about new Agent's bootstrap?
- CAs are taken to be "keys to the kingdom"; maybe SPIRE Server should be the only issuer for a trust domain? Is attempting to tease the CAs apart an indication of need for separate domain+federation?
-- But UpstreamCA plugins are for plugging into larger domains. Maybe SPIRE is just a slice of the domain's pie.
-- Some other dissemination of things in the domain?

**Comment by amoore877** [comment]
Additional dimension to think of:
What about registrants / other direct requestors to SPIRE Server API?
The natural way they integrate is by using their issued workload identity + trust bundle, but these consumers should likely also expect:
- a specific SPIRE Server cluster and/or
- SPIRE Server to be signed by some specific subset of CAs, rather than anything in the full bundle

**Comment by evan2645** [comment]
I think the crux of this issue is the desire to decouple SPIRE internal communication security from the workload identity domain that SPIRE serves upwards. There is definitely value in doing this, but I also feel it has the potential to be pretty large in scope (and disruptive).

This issue discusses a low hanging and concrete way to take a step in that direction. Whether it is the step we would choose to take if we were being intentional about decoupling these domains, I'm not sure. I think it makes sense to further discuss what ideal solutions to this decoupling could look like before deciding on taking steps in that direction (whether it's via the suggested approach here or a different one)
