### ISSUE TITLE
go-check (Makefile) doesn't appear to work as intended

### ISSUE THREAD

**Issue by bnevis-i** [spiffe/spire#2913]
* **Version**: 1.2.1
* **Platform**: apline 3.15 (x86_64)
* **Subsystem**: build

The go-check hook doesn't appear to be working as intended when run in an Alpine build container.

```
Step 7/18 : RUN wget -q https://github.com/spiffe/spire/archive/refs/tags/v${SPIRE_RELEASE}.zip &&     unzip "v${SPIRE_RELEASE}" &&     cd "spire-${SPIRE_RELEASE}" &&     make V=1 bin/spire-server-static bin/spire-agent-static
 ---> Running in 9cef9f3fb0ef
Archive:  v1.2.1.zip
71bd1e0e464abfaa36a8b3f934ff2ca61805afcd
   creating: spire-1.2.1/

(some details omitted)

  inflating: spire-1.2.1/test/util/util.go  
finishing deferred symbolic links:
  spire-1.2.1/test/integration/suites/ghostunnel-federation/07-check-workload-connectivity -> 05-check-workload-connectivity
  spire-1.2.1/test/integration/suites/ghostunnel-federation/08-start-servers -> 01-start-servers
  spire-1.2.1/test/integration/suites/ghostunnel-federation/09-check-workload-connectivity -> 05-check-workload-connectivity
  spire-1.2.1/test/integration/suites/ghostunnel-federation/11-check-workload-connectivity -> 05-check-workload-connectivity
  spire-1.2.1/test/integration/suites/ghostunnel-federation/13-check-workload-connectivity -> 05-check-workload-connectivity
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Installing go1.17.7...
rm -rf /edgex-go/spire-1.2.1/.build/linux-x86_64/go/
mkdir -p /edgex-go/spire-1.2.1/.build/linux-x86_64/go/1.17.7
curl -sSfL https://storage.googleapis.com/golang/go1.17.7.linux-amd64.tar.gz | tar xz -C /edgex-go/spire-1.2.1/.build/linux-x86_64/go/1.17.7 --strip-components=1
Building bin/spire-server-static...
PATH="/edgex-go/spire-1.2.1/.build/linux-x86_64/go/1.17.7/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" CGO_ENABLED=1 go build  -ldflags '-s -w -linkmode external -extldflags "-static"' -o bin/spire-server-static ./cmd/spire-server
/bin/sh: go: not found
make: *** [Makefile:264: bin/spire-server-static] Error 127
The command '/bin/sh -c wget -q https://github.com/spiffe/spire/archive/refs/tags/v${SPIRE_RELEASE}.zip &&     unzip "v${SPIRE_RELEASE}" &&     cd "spire-${SPIRE_RELEASE}" &&     make V=1 bin/spire-server-static bin/spire-agent-static' returned a non-zero code: 2
make: *** [Makefile:222: docker_security_spire_server] Error 2
```

**Comment by azdagron** [comment]
The error message is a little vague, but comes from the linker not being able to locate libc. The precompiled go binaries for amd64 linux depend on glibc, which isn't installed into alpine by default. I'm not sure we'd want to make a change that detects if we're in a musl environment and compiles go from source. Possibly a more practical approach would be to install base your build container on `golang:alpine`...

**Comment by bnevis-i** [comment]
What makes this difficult is that even if you have an alpine go build container, if the go version doesn't match IDENTICALLY, the go-check will fire and try to download an inappropriate precompiled go binary and fail as above.

**Comment by azdagron** [comment]
> if the go version doesn't match IDENTICALLY, the go-check will fire and try to download an inappropriate precompiled go binary and fail as above

That isn't an ideal experience, I agree. I'm very much on board figuring something out here.

>  In other words, it would be nice to be able to bypass go-check, or at least the forced install of a go compiler.

That's an option. Though we have our reasons for pushing folks to build with the same version of Go (see below).

> IMO the build container should provide the go compiler, not the makefile.

For certain classes of software, I'm in large agreement. However, we have made the choice to try and control the version of Go used to build the project with the official tooling for a few reasons.

1. Very often, the point release really matters, particularly in cases where we've updated our toolchain in response to fixed 
 CVE's in the Go standard library. Pinning the compiler version in our official tooling helps us ensure that we're building with the version we expect to be building with. As a security project, this kind of thing is table stakes.

2. We can depend on certain features and behaviors in our tooling (e.g. `go install` behavior, `go mod` behavior). We have CI/CD checks that ensure that our code generation, module files, etc. are clean and tidy. Not pinning our go version causes undo friction for contributors who can't be sure that their local environment will produce results that will pass CI/CD.

3. We very often  leverage the latest language additions and changes to the standard library. Contributors who have an older version of the compiler will be unable to build. This often leads to issues being opened. Providing a stable compiler version in our official tooling avoids this altogether.

4. Not everyone builds the project in a container. We wanted to make it easy for somebody to clone this repository on any machine, type `make`, and have something they can try out. We've obviously have a gap here for folks running musl-based distributions.

**Comment by bnevis-i** [comment]
Additional input: if the release spire binaries were statically linked, or came in a MUSL version, I would just use the precompiled binaries.

**Comment by azdagron** [comment]
That's good feedback. The docker images we publish to GHCR contain statically linked binaries (against MUSL). You could use those (or copy the binary out for your own purposes).

```
$ docker create --name temp ghcr.io/spiffe/spire-server:1.2.3
$ docker cp temp:/opt/spire/bin/spire-server .
$ docker rm test
$ ldd spire-server 
	not a dynamic executable
$ ./spire-server 
Usage: spire-server [--version] [--help] <command> [<args>]

Available commands are:
    agent          
    bundle         
    entry          
    federation     
    healthcheck    Determines server health status
    jwt            
    run            Runs the server
    token          
    validate       Validates a SPIRE server configuration file
    x509           
```

**Comment by bnevis-i** [comment]
Good suggestion!  That will save so much time!

**Comment by bnevis-i** [comment]
@azdagron Is there an ARM64 version as well?

**Comment by azdagron** [comment]
Not yet. There is an open issue in the backlog to provide multi-arch images: #1984
