### ISSUE TITLE
Consider deprecating webhook mode in the k8s-workload-registrar

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#2917]
In the k8s-workload-registrar, webhook mode is well known to suffer from a number of problems, many of which are documented [here](https://github.com/spiffe/spire/tree/main/support/k8s/k8s-workload-registrar#differences-between-modes). It is the default mode, however we constantly and consistently discourage its use.

The mode should just be deprecated in favor of the remaining two, making the `mode` configurable mandatory.

**Comment by azdagron** [comment]
Discussed this as maintainers. We're going to plan on this. #2918 and #2919 track the work.
