### ISSUE TITLE
Apple ARM Support - Mac OS

### ISSUE THREAD

**Issue by wibarre** [spiffe/spire#2920]
Mac OS - X quick start throws error when starting the agent. ARM is not supported. 
ERRO[0000] failure getting variant            error="getCPUInfo for OS darwin: not implemented"

From Andrew H.
We have an indirect dependency on containerd, which is doing this check during process init, unrelated to anything we use it for. We support macOS so we should look into fixing this, if possible.

**Comment by evan2645** [comment]
Thanks @wibarre 

@azdagron I was able to transfer the issue to SPIRE repo

**Comment by azdagron** [comment]
TIL you can transfer issues! Thanks, @evan2645 !

**Comment by azdagron** [comment]
I believe this is fixed now. We've updated our docker library dependencies over the last few months, which indirectly pulled in containerd v0.6.1, which includes a fix for the function that caused the failure at package init time. @faisal-memon confirmed that he was able to run the agent on an M1-based macbook.

Please let us know if you still can't run the agent, @wibarre !

**Comment by wibarre** [comment]
All is working well now. Thank you!
