### ISSUE TITLE
SPIFFE ID CRD Mode is not working. No new workload get attested with k8s-workload-registrar sidecar

### ISSUE THREAD

**Issue by pbhalera** [spiffe/spire#2958]
i have installed spire server with k8s-workload-registrar sidecar with crd mode. But when i create a workload with give pod label with `spiffe.io/spiffe-id: true`, i still not see workload attested.

When.i check the logs on server i found following in in k8s-workload-registrar sidecar container logs
`time="2022-04-19T06:20:56Z" level=info msg="Connecting to local registration server socket unix:///tmp/spire-server/private/api.sock"
I0419 06:20:57.770866      38 request.go:665] Waited for 1.040246717s due to client-side throttling, not priority and fairness, request: GET:https://172.18.0.1:443/apis/kafka.strimzi.io/v1beta1?timeout=32s
M-C02F1PYNMD6M:spire pbhalerao$ kubectl logs -n spire spire-server-0 -c k8s-workload-registrar
time="2022-04-19T06:20:56Z" level=info msg="Connecting to local registration server socket unix:///tmp/spire-server/private/api.sock"
I0419 06:20:57.770866      38 request.go:665] Waited for 1.040246717s due to client-side throttling, not priority and fairness, request: GET:https://x.x.x.x:443/apis/rbac.authorization.k8s.io/v1?timeout=32s
time="2022-04-19T06:20:58Z" level=info msg="Initializing SPIFFE ID CRD Mode"
time="2022-04-19T06:20:58Z" level=debug msg="Minting new SVID for webhook"` 

can you please help me resolve this. I am using k8s 1.21.6-gke.1503 cluster in GKE.

**Comment by azdagron** [comment]
What is the status of the SPIRE server container? Do you have logs for it?

**Comment by pbhalera** [comment]
Its running.

here are logs
`$ kubectl logs -n spire spire-server-0 --all-containers=true
time="2022-04-19T06:20:56Z" level=warning msg="Current umask 0022 is too permissive; setting umask 0027"
time="2022-04-19T06:20:56Z" level=info msg=Configured admin_ids="[]" data_dir=/run/spire/data
time="2022-04-19T06:20:56Z" level=info msg="Opening SQL database" db_type=sqlite3 subsystem_name=sql
time="2022-04-19T06:20:56Z" level=debug msg="Code and DB schema versions are the same. No migration needed" schema=18 subsystem_name=sql version_info=1.2.3
time="2022-04-19T06:20:56Z" level=info msg="Connected to SQL database" read_only=false subsystem_name=sql type=sqlite3 version=3.38.0
time="2022-04-19T06:20:56Z" level=info msg="Plugin loaded" external=false plugin_name=k8s_psat plugin_type=NodeAttestor subsystem_name=catalog
time="2022-04-19T06:20:56Z" level=info msg="Plugin loaded" external=false plugin_name=disk plugin_type=KeyManager subsystem_name=catalog
time="2022-04-19T06:20:56Z" level=info msg="Plugin loaded" external=false plugin_name=k8sbundle plugin_type=Notifier subsystem_name=catalog
time="2022-04-19T06:20:56Z" level=debug msg="Loading journal" path=/run/spire/data/journal.pem subsystem_name=ca_manager
time="2022-04-19T06:20:56Z" level=info msg="Journal loaded" jwt_keys=1 subsystem_name=ca_manager x509_cas=1
time="2022-04-19T06:20:56Z" level=info msg="X509 CA activated" expiration="2022-04-20T06:20:23Z" issued_at="2022-04-19T06:20:23Z" slot=A subsystem_name=ca_manager
time="2022-04-19T06:20:56Z" level=debug msg="Successfully rotated X.509 CA" subsystem_name=ca_manager trust_domain_id="spiffe://example.org" ttl=86366.244387357
time="2022-04-19T06:20:56Z" level=info msg="JWT key activated" expiration="2022-04-20T06:20:23Z" issued_at="2022-04-19T06:20:23Z" slot=A subsystem_name=ca_manager
time="2022-04-19T06:20:56Z" level=debug msg="Rotating server SVID" subsystem_name=svid_rotator
time="2022-04-19T06:20:56Z" level=debug msg="Signed X509 SVID" expiration="2022-04-19T07:20:56Z" spiffe_id="spiffe://example.org/spire/server" subsystem_name=svid_rotator
time="2022-04-19T06:20:56Z" level=info msg="Building in-memory entry cache" subsystem_name=endpoints
time="2022-04-19T06:20:56Z" level=info msg="Completed building in-memory entry cache" subsystem_name=endpoints
time="2022-04-19T06:20:56Z" level=debug msg="Initializing API endpoints" subsystem_name=endpoints
time="2022-04-19T06:20:56Z" level=info msg="Starting UDS server" address=/tmp/spire-server/private/api.sock subsystem_name=endpoints
time="2022-04-19T06:20:56Z" level=info msg="Starting TCP server" address="[::]:8081" subsystem_name=endpoints
time="2022-04-19T06:20:56Z" level=debug msg="Starting checker" name=catalog.datastore subsystem_name=health
time="2022-04-19T06:20:56Z" level=debug msg="Starting checker" name=server.ca subsystem_name=health
time="2022-04-19T06:20:56Z" level=debug msg="Starting checker" name=server.ca.manager subsystem_name=health
time="2022-04-19T06:20:56Z" level=debug msg="Starting checker" name=server subsystem_name=health
time="2022-04-19T06:20:56Z" level=debug msg="Notifier handled event" event="bundle loaded" notifier=k8sbundle subsystem_name=ca_manager
time="2022-04-19T06:20:58Z" level=debug msg="Signed X509 SVID" authorized_as=local authorized_via=transport dns_name=k8s-workload-registrar.spire.svc expiration="2022-04-19T07:20:58Z" method=MintX509SVID request_id=a8bb2268-5aef-43eb-a9c2-17dd17098e8d service=svid.v1.SVID spiffe_id="spiffe://example.org/k8s-workload-registrar/demo-cluster/webhook" subject= subsystem_name=api
time="2022-04-19T06:20:56Z" level=info msg="Connecting to local registration server socket unix:///tmp/spire-server/private/api.sock"
I0419 06:20:57.770866      38 request.go:665] Waited for 1.040246717s due to client-side throttling, not priority and fairness, request: GET:https://x.x.x.x:443/apis/rbac.authorization.k8s.io/v1?timeout=32s 
time="2022-04-19T06:20:58Z" level=info msg="Initializing SPIFFE ID CRD Mode"
time="2022-04-19T06:20:58Z" level=debug msg="Minting new SVID for webhook"`

**Comment by azdagron** [comment]
I don't see anything wrong. Do you mind sharing your registrar config?

**Comment by pbhalera** [comment]
I used samples from this:- https://github.com/spiffe/spire/tree/main/support/k8s/k8s-workload-registrar/mode-crd/config

**Comment by pbhalera** [comment]
Let me know if you need any other info

**Comment by azdagron** [comment]
Do you have any deviation from the example configuration other than using SPIRE 1.2.3?

**Comment by pbhalera** [comment]
No.

**Comment by faisal-memon** [comment]
can you post the spire agent logs?

**Comment by faisal-memon** [comment]
@pbhalera were you able to get this figured out?
