### ISSUE TITLE
Start up fails with spire-0.2

### ISSUE THREAD

**Issue by omallassi** [spiffe/spire#296]
* **Version**: spire-0.2
* **Platform**: Ubuntu

Hi all, 

I experienced some issues while trying to start the 0.2 release.
_Symptoms_: while starting the server (or the agent), I got an error message saying that ca_memory/ca_memory was not a directory (and indeed it is not). 

I had to do the following : 
- edit the .conf files from /spire-0.2/conf/agent/plugin/*
- update the pluginCmd to remote the end of the path (e.g. replace plugin/agent/nodeattestor-jointoken/nodeattestor-jointoken/ with plugin/agent/nodeattestor-jointoken)
- do the same for spire-0.2/conf/server/plugin

to be honest, I am not sure where the issue comes from but it fixes it. 

Does anyone met the same issue?

**Comment by walmav** [comment]
Thank you @omallassi for pointing this out. I see this is an issue with the way we package the executable. We need to change the relative path of the plugin binary.
When using from source the relative path for the default plugin binaries is one level deeper.

**Comment by ajessup** [comment]
@walmav can this be closed?

**Comment by walmav** [comment]
this was a valid issue in 0.2. will verify if this has been fixed in 0.3 and close it

**Comment by walmav** [comment]
This is no longer a issue in latest version.
