### ISSUE TITLE
Document how to use the registration API (via API and the CLI)

### ISSUE THREAD

**Issue by ajessup** [spiffe/spire#298]
We should provide documentation that describes how the registration API works, and how node and workload attestor & resolver plugins open up different options for working with it. We should cross-reference with the node and workload attestor/resolver plugin documentation (eg. [here](https://github.com/drrt/spire/blob/e69c26e6fd16aeb6a27f0e0a438f6d6061f0a725/doc/plugin_agent_workloadattestor_unix.md))

**Comment by evan2645** [comment]
Is this still a valid issue?

**Comment by azdagron** [comment]
Considering this stale. We will revisit at some future point after we refresh the registration api.
