### ISSUE TITLE
Cannot set the windows spire-agent named_pipe_name configuration

### ISSUE THREAD

**Issue by rgl** [spiffe/spire#3065]
* **Version**: 1.3.0
* **Platform**: Windows Server 2022
* **Subsystem**: agent

The Linux version of spire-agent lets us set the unix domain socket path with:

```hcl
agent {
    socket_path = "/tmp/spire-agent/public/api.sock"
}
```

But this does not work on Windows, and it tells us to set the `named_pipe_name` property instead:

```console
PS C:\ProgramData\spire-agent> &"$agentHome\bin\spire-agent" validate -config "$agentHome\conf\spire-agent.conf"
SPIRE agent configuration file is invalid: invalid configuration: socket_path is not supported in this platform; please use named_pipe_name instead
```

Modifying the configuration to use the `named_pipe_name` property (and using the named pipe syntax):

```hcl
agent {
    named_pipe_name = "\\spire-agent\\public\\api"
}
```

But that also fails, with a different error:

```console
PS C:\ProgramData\spire-agent> &"$agentHome\bin\spire-agent" validate -config "$agentHome\conf\spire-agent.conf"
time="2022-05-14T12:46:33+01:00" level=error msg="Unknown configuration detected" keys=named_pipe_name section=agent
SPIRE agent configuration file is invalid: unknown configuration detected
```

So it seems something is broken, what could it be?

**Comment by amartinezfayo** [comment]
Hi @rgl, please note that the `named_pipe_name` setting needs to be inside the experimental section, e.g.::

```
experimental {
        named_pipe_name = "\\spire-agent\\public\\api"
    }
```

If it's not under the experimental section, the setting will be unknown. Including it under `experimental` should fix the problem.

**Comment by rgl** [comment]
That was it! I completely missed that `experimental` section.

Thank You!
