### ISSUE TITLE
k8s-quickstart configure-a-workload-container-to-access-spire something error

### ISSUE THREAD

**Issue by sys0613** [spiffe/spire#3099]
I operation as the tutorials
https://spiffe.io/docs/latest/try/getting-started-k8s/#configure-a-workload-container-to-access-spire

when operation as https://spiffe.io/docs/latest/try/getting-started-k8s/#configure-a-workload-container-to-access-spire

after run
**kubectl apply -f client-deployment.yaml**
then run
**kubectl exec -it $(kubectl get pods -o=jsonpath='{.items[0].metadata.name}'  -l app=client)  -- /bin/sh**
something wrong，

```
[root@control-plane quickstart]# kubectl exec -it $(kubectl get pods -o=jsonpath='{.items[0].metadata.name}' \
>    -l app=client)  -- /bin/sh
Error from server (Forbidden): pods "client-5888c4f8dc-hgk9p" is forbidden: cannot exec into or attach to a container using host network
```
only this step begin failed

what I can do？？thanks

**Comment by azdagron** [comment]
Sounds like you are running a cluster with the deprecated [DenyEscalatingExec](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#denyescalatingexec) Admission Controller. The tutorial won't work with that AdmissionController enabled since it relies on exec'ing into privileged containers for demonstrative purposes.

**Comment by sys0613** [comment]
It is ok，thank you very much..
but some other thing wrong,can you help me ?

```
[root@control-plane ~]# kubectl exec -it client-5888c4f8dc-tpnf9 -- /bin/sh
/opt/spire # /opt/spire/bin/spire-agent api fetch -socketPath /run/spire/sockets/agent.sock
rpc error: code = PermissionDenied desc = no identity issued
```
after exec to container
run shell ,some thing error..
"rpc error: code = PermissionDenied desc = no identity issued"

**Comment by sys0613** [comment]
@azdagron

**Comment by azdagron** [comment]
What is the output of ```
# kubectl exec -n spire spire-server-0 -- /opt/spire/bin/spire-server entry show
```

**Comment by azdagron** [comment]
Let's continue this discussion on the issue you have opened in the SPIRE tutorials repository.
