### ISSUE TITLE
Fetch bundles methods are generating phony updates

### ISSUE THREAD

**Issue by maxlambrecht** [spiffe/spire#3101]
Using the `WatchX509Bundles` method from `go-spiffe` library I’m seeing that the updates arrive based on the `SVID_TTL` and not on the `CA_TTL` as I’d expect.

Looking into the SPIRE workload handler, the `FetchX509Bundles` method is using `SubscribeToCacheChanges`, thus it's generating phony updates.

* **Version**: Any
* **Platform**: Any
* **Subsystem**: Agent

**Comment by azdagron** [comment]
`SubscribeToBundleUpdates` generically subscribes to bundle updates for every bundle that the agent knows about. `SubscribeToCacheChanges` filters the subscription by the workload selectors.

Off the top of my head, we can fix this one of two ways:
1. Add a new way to subscribe to bundles for a specific workload
2. Remember the last response we sent to the caller and when we get notified of a change, only send the new response if the bundles have changed.

The second option seems like it would be fairly trivial to implement. For example, sendX509BundlesResponse could return the response that was composed. it could also take a "previous response" parameter, that would be nil on first invocation, and after composing the new response, compare it with the old and only call `stream.Send` if they differ.

That technique could be applied to other streaming handlers as well to reduce spurious updates (e.g. FetchJWTBundles)

**Comment by azdagron** [comment]
Fixed by #3102
