### ISSUE TITLE
Deletion of registration entries is leaving orphaned `dns_names` rows

### ISSUE THREAD

**Issue by dennisgove** [spiffe/spire#3126]
* **Version**: Seen in 1.1.4  (issue appears in `main` branch)
* **Platform**: Ubuntu 
* **Subsystem**: DataStore "sql"

When a registration entry is deleted via [`deleteRegistrationEntrySupport`](https://github.com/spiffe/spire/blob/main/pkg/server/datastore/sqlstore/sqlstore.go#L3219-L3234) the method deletes from both the `registered_entries` and `selectors` tables. However, it does not also delete from `dns_names` which leads to orphaned records in that table. When updating a registration entry the `dns_names` records [are deleted](https://github.com/spiffe/spire/blob/main/pkg/server/datastore/sqlstore/sqlstore.go#L3139-L3141).

These extra records result in significant query execution time when [`ListRegistrationEntries`](https://github.com/spiffe/spire/blob/main/pkg/server/datastore/sqlstore/sqlstore.go#L357) is executed. Following that code path we see that it uses a SQL query that UNIONs a few tables together ([Postgres query](https://github.com/spiffe/spire/blob/main/pkg/server/datastore/sqlstore/sqlstore.go#L2354-L2431), with similar queries for MySQL and SQLite).

I found this after seeing delays between a new registration being created and the SVID becoming available to the workload; anywhere from 1 - 2 minutes. Through that investigation I saw that the UNION clause linked above is taking approximately 1m20s to complete. Our SPIRE instance currently has over 810,000 rows in the `dns_names` table, of which only about 8500 are for currently registered entries.

PR #1191 added a clause to delete the selector records. I believe a similar change to also delete the `dns_names` records is needed. This PR is also referenced [here](https://github.com/spiffe/spire/blob/main/pkg/server/datastore/sqlstore/sqlstore.go#L2204-L2212) which ensures that these orphaned records are filtered out before returning. However, all of the records were already read from the database, or at least considered as part of the pagination.

**Comment by azdagron** [comment]
Thanks for finding this @dennisgove! Depending how quickly you think you can prepare a PR, we'd love to include this in our 1.3.1 release. The plan was to pick a commit today, but we can hold off a day or two.

Is your plan to just "stop the bleeding" or also include code to clear the orphaned rows?

**Comment by dennisgove** [comment]
I'd love to get this in soon. I'll begin working on it now. Certainly plan to "stop the bleeding", but if there's an existing place to put cleanup code (perhaps the db migration flow?) I'm happy to do that too.

At the very least, we're going to manually delete the orphaned records in our instances to alleviate the immediate issue for us. However, I think it would be nice to take care of that as part of this fix.

**Comment by dennisgove** [comment]
How does the project handle backporting fixes like this? If additional PRs are needed I can send those in as well.
