### ISSUE TITLE
Question: max length of the pod name

### ISSUE THREAD

**Issue by glazychev-art** [spiffe/spire#3128]
Hi,
We are using `k8s-workload-registrar` in the our project. It creates a new `SpiffeID` entry based on the Pod name. 
But we found, that it doesn't work if the pod name is longer than _**63**_. And there is no information in the logs.

Why is this happening? Am I missing something?

Thanks

* **Version**: v.1.2.3

**Comment by azdagron** [comment]
This is likely the [validation](https://github.com/spiffe/spire/blob/946f2a8ffde4046b0da02ddc1c6483ba75ad14cf/support/k8s/k8s-workload-registrar/mode-crd/api/spiffeid/v1beta1/spiffeid_webhook.go#L136) that the DNSNames on the entry are valid DNS names. It uses the [x509util.ValidateDNS](https://github.com/spiffe/spire/blob/946f2a8ffde4046b0da02ddc1c6483ba75ad14cf/pkg/common/x509util/dns.go#L13) which ultimately checks whether or not any individual label exceeds 63 characters. The pod name is included as a label in the DNS name, which causes this to fail validation if it exceeds 63 characters.

**Comment by azdagron** [comment]
Here is the object naming constraints for Kubernetes:

https://kubernetes.io/docs/concepts/overview/working-with-objects/names/

Apparently, Pod names are only constrained to DNS subomain names according to [this](https://kubernetes.io/docs/concepts/workloads/pods/)

> When you create the manifest for a Pod object, make sure the name specified is a valid [DNS subdomain name](https://kubernetes.io/docs/concepts/overview/working-with-objects/names#dns-subdomain-names).

This is a little strange, seeing as [this](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/) page shows examples of the pod name being used as a DNS label in FQDN's, which means, as far as I understand, it should have been constrained to 63 characters to begin with.

**Comment by azdagron** [comment]
Closing this out for now. Let us know if you have further questions!
