### ISSUE TITLE
Re-attest existing Agent after Agent NodeAttestor configuration changes

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#3133]
Consider the following sequence of events:

1. A SPIRE Agent is initialized and successfully attests to SPIRE Server
2. While the Agent has a valid Agent SVID still cached on disk, the Agent is re-configured with a new NodeAttestor configuration and restarted. Some examples of NodeAttestor configuration changes are a different X.509 certificate/private key for `x509pop` or using a different NodeAttestor plugin altogether.

In this case, the Agent will start up and be able to use the cached Agent SVID corresponding to the old NodeAttestor configuration. This has downstream implications for Agent entry authorization, since the Agent with the new NodeAttestor configuration will get entries mapped to the old Agent node selectors / SPIFFE ID.

In this case, it would be ideal to force the Agent to re-attest on startup to prevent it from getting incorrect entries/SVIDs rather than relying on expiry of the Agent SVID to control this migration.

**Comment by amoore877** [comment]
Can we not just evict the Agent? Then Agent will be told it's not valid and it will attempt attestation?

Or would attestation not happen until the Agent's SVID is expired?

**Comment by rturner3** [comment]
Agent eviction is generally how this should be handled by an operator since the Server is the authority on what SVIDs are valid for the trust domain. This proposal is more of a catch-all for the case when agents are not evicted, maybe due to operator error, accidental Agent misconfiguration, or challenges with handling eviction across a lot of Agents.
