### ISSUE TITLE
Improve Agent cache manager

### ISSUE THREAD

**Issue by paul-argeniss** [spiffe/spire#314]
Cache manager takes long when there are many registration entries to process. Find out what tasks can be done in parallel. A general refactor might be necessary to improve the performance.

* **Version**: d678415a431fe8b6abc2f4c97dc6db879d828d68
* **Subsystem**: Agent

**Comment by evan2645** [comment]
Refactors have occurred since this was filed. No performance issues are currently observed. Marking this as done
