### ISSUE TITLE
Plugin how to guide

### ISSUE THREAD

**Issue by y2bishop2y** [spiffe/spire#317]
Detailed explanation on how to create a plugin for the SPIRE Agent and SPIRE Server.

How is the code forked (Template example that people can start of from )
1. Explain step by step how to setup development environment. 
2. Each plugin interface for the SPIRE agent and SPIRE server. 
3. How to build and run plugin 
4. How to submit Plugin for review.

* **0.4**: 
* **Documentation**: 
* **Pugins, server and agent**:

**Comment by evan2645** [comment]
Fixed in https://github.com/spiffe/plugin-template/pull/1
