### ISSUE TITLE
in docker-compose tutorial，where the cert from?? 

### ISSUE THREAD

**Issue by sys0613** [spiffe/spire#3176]
use spire-tutorials-main\docker-compose\nested-spire\scripts\gencerts.go
I can generate
one root-server cert
two cert for root-agent

but ,I don't know ,how to generate nestedA-server cert and nestedA-agent cert
and so on nestedB-server cert and nestedB-agent cert,
I use command,"./gencerts ../root/server ../root/agent ../nestedA/agent ../nestedB/agent"

**Comment by MarcosDY** [comment]
you will need to call gencert 3 time:
- create [root](https://github.com/spiffe/spire-tutorials/blob/main/docker-compose/nested-spire/scripts/set-env.sh#L66)
- create [NestedA](https://github.com/spiffe/spire-tutorials/blob/main/docker-compose/nested-spire/scripts/set-env.sh#L103)
- create [NestedB](https://github.com/spiffe/spire-tutorials/blob/main/docker-compose/nested-spire/scripts/set-env.sh#L117)

**Comment by sys0613** [comment]
@MarcosDY Thank You very much .I will hava a try .
I also have a other question,please help me 
the problem is found in https://spiffe.io/docs/latest/architecture/nested/readme/
.I also can not fint the "/opt/spire/conf/agent/bootstrap.crt".how can I get bootstrap.crt for root-agent,nestedA-agent and nestedB-agent,thanks.where them from ??

**Comment by sys0613** [comment]
Thank you very much for your help.All the problems have been solved. I will review the doc,thanks.
