### ISSUE TITLE
External plugins exit with errors

### ISSUE THREAD

**Issue by hiyosi** [spiffe/spire#3178]
* **Version**: 1.3.0
* **Platform**: Linux x86_64
* **Subsystem**: external plugins

In my system which uses external plugins in both server and agent.
When shutting down the process, error messages are logged.

I found out that log level of a message in the plugin code has been changed from go-plugin@v1.4.4.

https://github.com/hashicorp/go-plugin/blob/v1.4.4/client.go#L638-L645
https://github.com/hashicorp/go-plugin/blob/v1.4.3/client.go#L642

rel: https://github.com/spiffe/spire/pull/3033

However, in my opinion, even if it is debug level, these messages should be fundamentally suppressed.

```
 tifme="2022-06-21T02:02:49Z" level=debug msg="Stopping checker" name=agent subsystem_name=health
 time="2022-06-21T02:02:49Z" level=debug msg="Checker exiting" name=agent subsystem_name=health
 time="2022-06-21T02:02:49Z" level=info msg="Stopping Workload and SDS APIs" subsystem_name=endpoints
 time="2022-06-21T02:02:49Z" level=debug msg="Stopping SVID rotator" subsystem_name=manager
 time="2022-06-21T02:02:49Z" level=info msg="Cache manager stopped" subsystem_name=manager
 time="2022-06-21T02:02:49Z" level=debug msg="Unloading plugin" external=true plugin_name=my_attestor plugin_type=WorkloadAttestor subsystem_name=catalog
 time="2022-06-21T02:02:49Z" level=error msg="plugin process exited" error="signal: terminated" external=true path=/path/to/node_attestor pid=8516 plugin_name=my_attestor plugin_type=NodeAttestor subsystem_name=catalog
 time="2022-06-21T02:02:49Z" level=debug msg="received EOF, stopping recv loop" err="rpc error: code = Canceled desc = context canceled" external=true plugin_name=my_attestor plugin_type=NodeAttestor subsystem_name=my_attestor.stdio
 time="2022-06-21T02:02:49Z" level=debug msg="received EOF, stopping recv loop" err="rpc error: code = Unavailable desc = error reading from server: EOF" external=true plugin_name=my_attestor plugin_type=WorkloadAttestor subsystem_name=my_attestor.stdio
 time="2022-06-21T02:02:49Z" level=error msg="plugin process exited" error="signal: terminated" external=true path=/path/to/workload_attestor pid=8521 plugin_name=my_attestor plugin_type=WorkloadAttestor subsystem_name=catalog
 time="2022-06-21T02:02:49Z" level=debug msg="plugin exited" external=true plugin_name=my_attestor plugin_type=WorkloadAttestor subsystem_name=catalog
 time="2022-06-21T02:02:49Z" level=info msg="Plugin unloaded" external=true plugin_name=my_attestor plugin_type=WorkloadAttestor subsystem_name=catalog
 time="2022-06-21T02:02:49Z" level=debug msg="Unloading plugin" external=false plugin_name=disk plugin_type=KeyManager subsystem_name=catalog
 time="2022-06-21T02:02:49Z" level=info msg="Plugin unloaded" external=false plugin_name=disk plugin_type=KeyManager subsystem_name=catalog
 time="2022-06-21T02:02:49Z" level=debug msg="Unloading plugin" external=true plugin_name=my_attestor plugin_type=NodeAttestor subsystem_name=catalog
 time="2022-06-21T02:02:49Z" level=debug msg="plugin exited" external=true plugin_name=my_attestor plugin_type=NodeAttestor subsystem_name=catalog
 time="2022-06-21T02:02:49Z" level=info msg="Plugin unloaded" external=true plugin_name=my_attestor plugin_type=NodeAttestor subsystem_name=catalog
 time="2022-06-21T02:02:49Z" level=info msg="Agent stopped gracefully"
```

related this? https://github.com/spiffe/spire/blob/v1.3.0/pkg/common/catalog/external.go#L45-L48

**Comment by hiyosi** [comment]
If I understand correctly,  the go-plugin does not handle SIGTERM, so the plugin server exit abnormally with Terminated status and the plugin client receive an error.

They only handles os.Interrupt.
https://github.com/hashicorp/go-plugin/blob/v1.4.4/server.go#L432

**Comment by hiyosi** [comment]
Should this issue be closed?

**Comment by hiyosi** [comment]
@azdagron 

> I wonder what is sending the SIGTERM. I can't find anywhere inside go-plugin where they send a TERM.  
> The only two exit paths are a graceful shutdown (by closing the gRPC server on the plugin side) and a forced process.Kill, 

I see.
I wondered how SIGTERM propagated to the child processes.

> Also, I can't reproduce this on my side:

I finally found out that the problem is with the systemd configuration that manages the process.

The systemd is able to configure kill behavior(`KillMode`) and it default `control-group`.
When I set `KillMode=process`, the error is not occurred.

**Comment by azdagron** [comment]
That makes sense! I have considered if we should keep the logging. While I agree that its a little verbose, I hesitate to remove any logging there that might compromise a debug situation. The `error` logging can certainly be problematic, since it can trigger alerts, but the debug logging seems useful. What do you think?

**Comment by hiyosi** [comment]
> The error logging can certainly be problematic, since it can trigger alerts, but the debug logging seems useful. What do you think?

That's right.
I have found that it is possible to suppress the error, so I'm going to close this issue.
