### ISSUE TITLE
Create a Test Matrix for different Combinations of SPIRE Agent and SPIRE Server plugins. 

### ISSUE THREAD

**Issue by y2bishop2y** [spiffe/spire#318]
Test Matrix. 
As we create more Plugin implementation for a Plugin Type 
we need a way to test all the different combinations.
Create a system that will build and verify all the different combinations (when they make sense )

1. Setup a test environment ( for the different platforms).
2. Build and configure the different combinations (this has to be driven via some config file that 
will combine the different plugin implementations )
3. Run a set of functional tests across the configured SPIRE Agent and SPIRE Server.
4. Produce a results report. 

* **All **: 
* **All **: 
* **Plugins **:

**Comment by martincapello** [comment]
I saw that we have RunConfig struct for both, SpireAgent and SpireServer. Now I'm thinking in a way to generate their configuration based on the verispiffe config file. I was thinking in using Go to generate the appropriate configuration files, but I don't want to duplicate the RunConfig struct so I thought in using the structs that we have defined already, but this will introduce an explicit dependency to sprire server and spire agent. Do you think that this could be a problem?

**Comment by ajessup** [comment]
This is assigned to release 0.4 and 0.5. Which is it scheduled for?

**Comment by y2bishop2y** [comment]
This will be an ongoing process. We will get the basic testing in for 0.4 and add more cells in the matrix next month. Maybe we will create another issue for this.

**Comment by walmav** [comment]
we might need some changes to account for the consolidated configurations #312
