### ISSUE TITLE
KMS plugin for GCP

### ISSUE THREAD

**Issue by Kathiresan-durairaj** [spiffe/spire#3194]
Currently spire configuration supports storing the certificates/tokens in AWS KMS service. we would like to have a plugin with GCP KMS service since the workloads will be deployed/migrated to GCP environment.

Spire version used in the current aws environment 0.12

**Comment by amartinezfayo** [comment]
Thank you @Kathiresan-durairaj for opening this issue!
We have been having requests to also support the Google Cloud Key Management Service in addition to the AWS Key Management Service.
This is definitely something that we would like to have support in SPIRE, and we hope that we can have an update about this soon.
