### ISSUE TITLE
Improve the test coverage of the `spire-server run` and `spire-agent run` commands

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#3199]
Current tests don't cover the `Run` function (in the server and in the agent) that runs the server and the agent.
There are things like endpoints preparation (create / not create directories depending on the transport) that are not currently tested and should be tested.

**Comment by guilhermocc** [comment]
Hello? can i be assigned to this issue, please?

**Comment by amartinezfayo** [comment]
Thank you for taking this, @guilhermocc!
