### ISSUE TITLE
Feature request: Log SVID on note attestation failure in AWS_IID

### ISSUE THREAD

**Issue by chdalski** [spiffe/spire#3205]
When trying to attest a node with the aws_iid node-attesator after it was already attested once the attesation fails as described.
However it would be nice if the error message could contain the SVID in order to allow manual intervention.
This might also help to pinpoint the instance in question if it's possibly compromised.
https://github.com/spiffe/spire/blob/45a900c0eab1069c5500ec795c04937dbadd5904/pkg/server/plugin/nodeattestor/aws/iid.go#L193

* **Version**: main-branch
* **Platform**: K8S
* **Subsystem**: [plugin_server_nodeattestor_aws_iid](https://github.com/spiffe/spire/blob/45a900c0eab1069c5500ec795c04937dbadd5904/doc/plugin_server_nodeattestor_aws_iid.md)

**Comment by amartinezfayo** [comment]
Thank you @chdalski for opening this issue. We have discussed it in today's maintainer's sync and we think that logging which agent (identified by the agent SPIFFE ID) failed a TOFU check would be a good thing to have.

Thanks @azdagron for addressing this so quickly (#3211)!

**Comment by chdalski** [comment]
I'm the one that needs to thank you @amartinezfayo for your fast response to my request :1st_place_medal:
