### ISSUE TITLE
spire-k8s: allow automated injection of sidecar and proxy function

### ISSUE THREAD

**Issue by jainvipin** [spiffe/spire#324]
Kubernetes defines [dynamic admission control](https://kubernetes.io/docs/admin/extensible-admission-controllers/#what-are-initializers) or use [mutating webhooks]( https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/admission-control-webhooks.md). Spire implementation can use the mechanisms in to:
1. Specify the sidecar and/or proxy/tunnel container to be included in the pod spec individually as pods are created
2. For now, automated injection can be done for all workloads, but spire-registration information can provide some hints as to where to not inject the sidecar e.g. if workloads implement the workload api natively and thus do not need automated injection.
3. Provide entry-time delay to ensure that sidecar container starts before application starts communicating out

Version: 0.2 onwards (since K8s support)
Platform: k8s-spire

**Comment by ajessup** [comment]
Idle question: Would it make sense for an admission controller to be able to automatically register a workload?

**Comment by jainvipin** [comment]
yes it makes a lot of sense, however I created a separate issue #325 for this  because they are logically different functions; let's discuss implementation.

I'd prefer one entity that does all k8s work, this avoids having to authenticate multiple different entities with spire-server and leaves less surface area for vulnerabilities.

**Comment by jainvipin** [comment]
> I'd prefer one entity that does all k8s work, this avoids having to authenticate multiple different entities with spire-server and leaves less surface area for vulnerabilities.

#320 could address the concern if this becomes the default plugin

**Comment by ajessup** [comment]
Ah cool. Makes sense to treat the functionality separately IMHO.

**Comment by evan2645** [comment]
I think we've learned a lot since this was opened. Proxy configuration can be complex, and managing it is a domain of its own (service mesh). I don't think this should really be in scope for SPIRE, however automatic injection of the SPIFFE Workload API should be. This work is currently planned as part of our upcoming k8s controller for SPIRE.

Going to go ahead and close this issue out as stale. Hope you are doing well Vipin :)
