### ISSUE TITLE
spire-k8s: automate creation of registration entries using api-server hooks

### ISSUE THREAD

**Issue by jainvipin** [spiffe/spire#325]
Spire-server allows creating registration entries for various workloads by defining selectors for workloads when issuing SVIDs. On the other hand, K8s APIServer provides APIs to know objects like Pods, Service Account, or Namespaces creation. In order to simplify deploying spire with k8s, an entity (say spire-server-k8s-plugin) can be implemented to automate:
1. registering the workloads as they are discovered based on pod's properties e.g. service-account and namespace. But use labels and/or other parameters
2. deregister the entries as pods are removed from k8s system
3. allow specifying the choice of selectors with k8s

Other considerations:
- spire-server-k8s-plugin would need to run alongside spire-server and must authenticate to spire-server. In order to avoid join token between spire-server-k8s-plugin could be implemented as a plugin that is authenticated in the standard way
- spire-server-k8s-pulgin should also authenticate with K8s APIserver and would need to be given API credentials to be able to perform these actions
- additional selectors for the pod/workload would need to be done at one place (perhaps via spire-server-k8s-plugin entity in order to provide augmented list of auth parameters. 

Version: 0.2 onwards (since K8s support)
Platform: k8s-spire

**Comment by evan2645** [comment]
This work was completed some months ago in #885 

Thanks for opening this @jainvipin, I'm sad it took so long to get in but happy that it's there now. Hopefully it is not too far from what you originally envisioned. Closing this out for now
