### ISSUE TITLE
Some questions about spire federation

### ISSUE THREAD

**Issue by loveyana** [spiffe/spire#3252]
* **Version**: 1.3.0
* **Platform**: Linux n249-128-131 5.4.56.bsk.9-amd64 #5.4.56.bsk.9 SMP Debian 5.4.56.bsk.9 Wed Aug 25 03:42:38 UTC 20 x86_64 GNU/Linux
* **Subsystem**: server federation

I have encountered the following two questions, and I want to meet this need through federation, but it is not currently satisfied, and I would like to ask for comments.

1. In the current trust domain, we have multiple spire clusters. We hope that the tokens obtained from them can authenticate each other. Therefore, we want to create a relationship where the current trust domain belongs to other cluster endpoints through federation to share JWT BundleSet. Currently, we use PublishJWTAuthority to let them share jwtbundle. This introduces a new synchronization service, so we want to solve it in a more community way

2. When establishing a federation relationship with other trust domains, there are also multiple spire clusters in that trust domain. The current federation function of spire limits the existence of only one endpoint in the same trust domain. Does allowing multiple endpoints meet the requirements of the community?

**Comment by azdagron** [comment]
1. If I understand correctly, you want to build a service that UpstreamAuthority plugins can publish JWT authorities too for all SPIRE servers in your cluster?

2. What would be the advantage of configuring multiple endpoints v.s. using some sort of load balancer or DNS round robin in front of the endpoints? Would the latter be sufficient?

**Comment by azdagron** [comment]
Just checking in to see if you got what you needed here, @loveyana. If so, can we close this issue?

**Comment by azdagron** [comment]
Closing due to inaction. Please let us know if you still need some help here!
