### ISSUE TITLE
Agent Debug GetInfo method returns only count of cached X.509-SVIDs in svids_count field

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#3256]
[Agent Debug GetInfo API definition](https://github.com/spiffe/spire-api-sdk/blob/27e2edf0882bd5ad3aaaa51f986dd53748772bdf/proto/spire/api/agent/debug/v1/debug.proto#L29-L30)

The comment for the response field `svids_count` says:
```
// Number of SVIDs cached in memory
int32 svids_count = 3;
```

There is no specificity in the API documentation about what types of cached SVIDs are included in this count.

The SPIRE implementation of the Debug GetInfo method currently only returns the number X.509-SVIDs in the primary cache. It does not include other SVIDs cached, such as:
- JWT-SVIDs
- X.509-SVIDs in the svidstore cache

There appear to be a few high-level ways to rectify this inconsistency:
1. Start including all cached SVIDs in `svids_count`
2. Clarify the comment in the API proto to mention the count is only of X.509-SVIDs in the primary cache
3. Deprecate the `svids_count` field in favor of more scoped fields, such as `x509_svids_count` and `jwt_svids_count`.

I would propose some version of option 3 for the long-term fix, as https://github.com/spiffe/spire/pull/3181 is attempting to rely on `svids_count` in an integration test to verify the number of X.509-SVIDs in the primary cache. Option 2 may optionally be done as well to address the immediate inconsistency.

**Comment by MarcosDY** [comment]
I agree with option `3` looks like the more natural and useful solution

**Comment by azdagron** [comment]
The API changes have been made, just looking for someone to pick this up.

**Comment by FedeNQ** [comment]
I can take this one ☝️
