### ISSUE TITLE
Enhance K8s workload attestor with content-addressable selectors.

### ISSUE THREAD

**Issue by colek42** [spiffe/spire#3262]
Kubernetes does not currently reflect the content-addressable [`image_id` ](https://github.com/opencontainers/image-spec/blob/main/config.md#imageid)as defined in the OCI spec in a constant manner.  It does, however, reflect the manifest digest.

Binding artifact identity to the [`image_id`](https://github.com/opencontainers/image-spec/blob/main/config.md#imageid) will allow users to make images portable across repositories.

There are a few ways this can be done, and probably more

- Query the CRI API
The CRI API is extremely powerful and over-scoped for what we need.

- Query the ContanerD API
@MarcosDY has an implementation for this in Windows.

- Query the filesystem
On my system config digests are located here `/var/lib/docker/image/overlay2/imagedb/content/sha256`

**Comment by azdagron** [comment]
I think we'd be open to providing the content-addressable image ID if it can be sourced consistently and cleanly. The last thing we want is something that is super touchy depending on the environment, like our determination of the pod/container ID of the workload by inspecting cgroups (which has been a bit nightmarish).

> Query the CRI API

This seems like the only consistent source. I think the question here how hard it is to make this available to the agent container.

> Query the ContanderD API

This has the same concerns as the CRI API, with an additional problem that we only then have the information available when using ContainerD as the container runtime. Seems like we'd be better off trying to go with the CRI API.

> Query the filesystem

This doesn't feel like a very stable solution.... Is that path on your host? or was it available to the agent container? Are all image IDs for all containers available there? How do we know which one belongs to the workload being attested?

**Comment by azdagron** [comment]
Would it be more appropriate to push for K8s to provide this more consistently?
