### ISSUE TITLE
Revamp X509-SVID Subject DN construction

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#3341]
As pointed out in #3110, SPIRE is not RFC compliant in its issuance of X509-SVIDs. The requirement of the RFC is that the Subject DN be unique to each entity, but currently it is static for all X509-SVIDs. Further, the Subject DN does does not reflect other customizations that have been done to the Issuer (i.e. SPIRE Server CA) DN.

This issue tracks the work to bring the server into RFC conformance as well as the rules for reflecting custom values of the SPIRE Server CA Subject DN.

To complete this work, SPIRE Server behavior should be modified as follows:

1. Set the X509-SVID Subject DN to the contents of the SPIRE Server CA Subject DN. If the CN is configured for the SPIRE Server CA, the CN value ~instead be reflected as an OU~ is not carried over to the X509-SVID. The SPIRE Server CA Subject DN should be obtained from the current CA certificate that is issuing the certificate and _not_ what is currently in the SPIRE Server configuration (which may diverge).
2. Set the x500UniqueIdentifer (OID extension `2.5.4.45`) to a hex representation of the hash of the SPIFFE ID. This satisfies the uniqueness requirement tempting consumers to use this extension (or another) extension as a substitute for the SPIFFE ID contained in the URI SAN.

An outstanding question is what hash function to use for generating the x500UniqueIdentifier. SHA256 is a safe default but results in _fairly_ long identifiers:

```
Subject: C = US, O = SPIRE, x500UniqueIdentifier = 27258f0274dd3407db17e90bc4b9adf2e1cb671579d2c2cf6689e8fb7c9aab3b
```

Something like xxh3 (a very fast non-cryptographic hash function with 64 bit hashes) would likely be more than sufficient to satisfy uniqueness across the input domain of SPIFFE IDs minted by a single CA in a given trust domain though:

```
subject=C = US, O = SPIRE, x500UniqueIdentifier = 8ba2ad461d2adc8a
```

**Comment by azdagron** [comment]
If we really feel like we need a cryptographic hash function (I'm not yet convinced we do), then we might be able to have our cake and eat it too using a 64-bit or 128-bit blake2 hash.

**Comment by azdagron** [comment]
Since legacy systems may use the CN as an identifier, I think I've convinced myself we need ample collision resistance, even though attackers would be limited on the input domain.

Maybe SHA256 is just fine for this purpose even though it produces a pretty long identifier and increases the size of an SVID by ~64 bytes (hex encoded id + asn.1 encoding overhead). We could do something like a base64 (or maybe a modified base58) encoding of the hash instead of hex encoding to shrink that somewhat.

**Comment by azdagron** [comment]
Base58 isn't so bad:
```
Subject: C = US, O = SPIRE, x500UniqueIdentifier = 3dp7oTAHPXMvad3NWJfKhwFqKPo33cSoW81unMD9qeJn
```

**Comment by azdagron** [comment]
Even better if we truncate the SHA256 hash to 128-bits (xor'ing the two halves, which AFAIK is ok according to NIST since sha256 has good diffusion properties):

```
Subject: C = US, O = SPIRE, x500UniqueIdentifier = RZn5KUjmEHMSrWCucmCkq6
```

At this point I might just be overcomplicating things :)

**Comment by azdagron** [comment]
As a discussion, we landed on a hex encoding of the left most 128-bits of the SHA256 of the SPIFFE ID.

We also discussed the semantics of carrying over the CN from the CA and decided that it might be better just to drop the CN from the subject instead of moving to another arbitrary field.

**Comment by evan2645** [comment]
Seems like the outstanding conversation(s) here are around DN inheritance, as noted in the edited message in #3367, and not DN uniqueness or RFC compliance. Since the DN construction issue is more or less solved, we can go ahead and close this issue out. If folks would like to continue discussion on DN inheritance, we can open a new issue.
