### ISSUE TITLE
gRPC API Design: Consider developing a pattern for idempotent APIs

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#340]
Idempotency means that is safe to retry RPCs not knowing whether or not they have completed.

As a client talking to a service, you don’t necessarily know whether the operation that you are attempting has been committed or not before an error occurs.
We want to make sure that the RPC API enables you to proceed even when you don’t know for sure whether that happened or not and allow clients to retry calls when there is a failure.

- Retrying an RPC should be safe without knowing If it was already processed.

**Comment by evan2645** [comment]
Going to go ahead and close this out as stale, since we've recently completed an API redesign
