### ISSUE TITLE
gRPC API Design: Check the use of repeated fields

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#341]
Repeated fields can be problematic because they are essentially lists that have no bound on their size. That means that the service is allowing potentially an unlimited amount of work.

Whenever we use repeated fields we should consider setting limits and check them when we are validating incoming requests and answer with an error if the request cannot be handled.

In the same way, in a response wherever we need a repeated field that we want to send back we should think about what that represent and make sure that we are not going to be returning potentially an unbounded amount of data. And if that is really what we want, we should make sure that either the API supports pagination so that users can do repeated queries and get a section of the result back each time or use a streaming RPC where the results are sent back one result at a time.

- Check the use of repeated fields
   - Validate that the amount of items to handle is within the limits that we want to handle.
   - Use pagination or a streaming RPC if needed.

**Comment by evan2645** [comment]
Closing this out as stale, it was addressed in a recent API redesign
