### ISSUE TITLE
gRPC API Design: Check for long-running operations

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#342]
The longer an operation takes to complete, the more likely it is that it will fail at some point.

When we have long-running operations in an RPC handler, we should consider options like performing the operation in the background and return from the RPC as quickly as possible while it’s still processing in the background and deliver the results through some other mechanism besides the RPC response.

- Long-running operations should be performed in the background and the results should be sent back asynchronously.

**Comment by evan2645** [comment]
Closing this out as stale since we recently completed an API redesign
