### ISSUE TITLE
SPIRE Server does not support binding to hostname

### ISSUE THREAD

**Issue by mchurichi** [spiffe/spire#3421]
SPIRE Server help says it supports binding to a DNS name, but it fails when passing in `localhost`, is this right?
```bash
$ bin/spire-server run -h                    
Usage of run:
  -bindAddress string
        IP address or DNS name of the SPIRE server

$ bin/spire-server run -bindAddress localhost
could not parse bind_address "localhost"
```
* **Version**: 8a5b108a8d2abbfe3f83404258b7039363a09741
* **Platform**: Darwin workstation.local 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64 x86_64
* **Subsystem**: server

**Comment by azdagron** [comment]
Looks like an oversight. Code calls net.ParseIP, when it should probably combine the BindAddress and BindPort and pass it to net.ResolveTCPAddr
