### ISSUE TITLE
gRPC API Design:  Check for the use of Deadlines / Timeouts

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#343]
We should make sure to set deadlines.

Deadlines can be set as a timeout or as an absolute time.
- Check deadlines in the request handlers.
- Choose and have a strategy for propagation of deadlines.

E.g.:
```
// As a timeout

ctx, cancel := context.WithTimeout(
  context.Background(), 8*time.Second)
defer cancel()

res, err := client.Call(ctx, req)
```

```
// As an absolute time

ctx, cancel := context.WithTimeout(
  context.Background(),
  time.Unix(1514764800, 0)
defer cancel()

res, err := client.Call(ctx, req)
```

**Comment by evan2645** [comment]
Closing this out as stale since we recently completed an API redesign. Additionally, the use of deadlines/timeouts has also recently been examined
