### ISSUE TITLE
gRPC API Design: Check for error handling and propagation

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#344]
Check that we don't just directly return errors from libraries or other services.

We should try to avoid returning error information in the response because if there is not a failure in the RPC itself but the result message says that there was a failure, the client logic has to check to see whether the RPC actually succeeded or not and analyze the response message, which can be complex. Is better to use the built-in error system.

- In general, do not include error information in the response payload.
- Avoid batching multiple, independent operations because it makes difficult to identify the status of each operation.

```
//Server
//To send an error, return status.Errorf with error message and code:
return status.Errorf(codes.InvalidArgument, "Invalid!")

//Client
//To handle the error, check error returned from gRPC call:
resp, err := client.GRPCMethod(...)
statusCode := status.FromError(err)
```

```
// Handle errors and translate them
res, err := client.Call(...)
if err != nil {
  s, ok := status.FromError(err)
  if !ok {
     return status.Errorf(codes.Internal,
        "client.Call: unknown error: %v", err)
  }
  switch s.Code() {
     case codes.InvalidArgument:
        return status.Errorf(codes.Internal,
           "client.Call: unexpected status: %v", s)
     ...   
```

**Comment by evan2645** [comment]
Closing this out as stale since we recently completed an API redesign
