### ISSUE TITLE
Deprecate k8s-workload-registrar

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#3458]
The K8s Workload Registrar has been a playground for various approaches to automatic registration of K8s workloads. The result has been a component with an organic growth of several operating modes and features with various tradeoffs. It has long been planned to eventually settle on one approach for the project.

The [spire-controller-manager](https://github.com/spiffe/spire-controller-manager) has been developed with the learnings of the K8s Workload Registrar in mind and is now the preferred component for K8s workload registration being promoted by the project. Any future features and design should be directed there.

With this in mind, the k8s-workload-registrar should be deprecated and eventually removed from the project.

To complete this issue we need to perform the following tasks:

- [x] #3501
- [x] #3614
- [x] Migrate all tutorials and examples to use the spire-controller-manager
- [x] Remove the component from the code base

**EDIT**: Version 1.5.4 is the last planned release of the k8s-workload-registrar. If we need to cut a security release, we'll do so based on the v1.5.4 release branch.

**Comment by rturner3** [comment]
This will affect our ability to deprecate the alpine-based images that we currently push to GCR because we don't publish the k8s-workload-registrar scratch image to GHCR (related to https://github.com/spiffe/spire/issues/3545)

**Comment by vish-k** [comment]
pls let me know if I can help.

**Comment by evan2645** [comment]
Hi @vish-k , thank you! We just got this over the hump, so I think we're good to go ❤️ 

If you'd like to help out, here are a couple issues that we could use help that could be good for you to pick up:
https://github.com/spiffe/spire/issues/3825
https://github.com/spiffe/spire/issues/2626

**Comment by vish-k** [comment]
ok. I'll take a look at these. How do I assign it if I can contribute to them?

**Comment by evan2645** [comment]
Leave a comment on the issue(s) you'd like to contribute, and I can assign to you. A few words on how you intend to implement is also very helpful 🙏 🙌
