### ISSUE TITLE
gRPC API Design: Look for memory management issues and set limits accordingly

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#346]
`gRPC-go` does not limit concurrent server goroutines. Every time a request comes in, gRPC will handle it and it will fire off a new goroutine in order to have the application serve it.

Example of how to set listener and concurrent streams limits:
```
// Listener and concurrent streams limits
import "golang.org/x/net/netutil"

l, err := net.Listen("tcp", fmt.Sprintf("localhost:%d", *port))
if err != nil {
  log.Fatalf("failed to listen: %v", err)
}
l = netutil.LimitListener(l, connectionLimit)
grpcServer := grpc.NewServer(grpc.MaxConcurrentStreams(streamsLimit))
```

Large requests can result in out of memory also. We should consider setting a maximum request payload size:

```
// Maximum Request Payload Size
grpc.NewServer(grpc.MaxRecvMsgSize(16384 /* size in bytes */))
```

Finally, small requests can require large response sizes. Options to solve this can be:
- Use a streaming response.
- Support pagination with maximum result limits.

**Comment by evan2645** [comment]
Closing this out as stale since we recently redesigned the API. Pagination is now universal and uniformly applied
