### ISSUE TITLE
Add --version flag for k8s-workload-registrar and oidc-discovery-provider binaries

### ISSUE THREAD

**Issue by keeganwitt** [spiffe/spire#3464]
I think it would be useful to be able to run `k8s-workload-registrar --version` and `oidc-discovery-provider --version` to see what version of the binary is on disk.

* **Version**: 1.4.2
* **Subsystem**: registar and oidc-provider

**Comment by rturner3** [comment]
Hey @keeganwitt , this seems like a useful thing to add. We would accept a PR for this.

**Comment by keeganwitt** [comment]
If I made a PR for this, would the cli.go for these be under `support/` or `cli/`?

**Comment by azdagron** [comment]
Those projects have a very limited CLI. The flag parsing is done in each project's main.go. That's probably where I'd add the flag and subsequent behavior. The `pkg/common/version` package can be used to get the version. These components are released with the same version as SPIRE.
