### ISSUE TITLE
Entry similarity check is racy

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#3467]
SPIRE attempts to prevent what is more than likely an erroneous entry from being created where there is already another "similar" entry, where similarity is defined as an entry with the same (spiffeID, parentID, selectors) tuple.

This check was historically done outside of the datastore layer, which was racy when two or more registrars attempted to create a "similar" entry at the same time.

PR #2475 attempted to fix this problem by moving the check inside of a transaction inside of the datastore. However, it failed to use proper isolation levels or table locks that would actually prevent the race.

The race on the similarity check should be fixed. A serializable isolation level would likely fix it, but puts limitations on database choice (i.e. certain configurations of Percona Xtra DB Cluster). A table lock on the registered_entries table might do it. Care should be taken to only lock against writes, we want reads to be able to execute.

**Comment by rturner3** [comment]
This is related to #1008. We thought we had fixed it in the past, but there are still problems in the entry uniqueness check.

**Comment by evan2645** [comment]
Closing in favor of https://github.com/spiffe/spire/issues/4329
