### ISSUE TITLE
Deprecate k8s_sat attestor

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#3495]
In a conversation with @azdagron and @MarcosDY, we noted that the regular SAT token in k8s is now the exact same shape as the PSAT token, and therefor the PSAT attestor can be used to validate SAT tokens.

We continue to support SAT based attestation, which has many known security shortcomings, however the time has come to move on. Deprecate k8s_sat attestor in favor of k8s_psat, and validate that k8s_psat attestor works with SAT tokens.

Obviates #1827

**Comment by evan2645** [comment]
Double check that this is in fact the case, and that it applies to all currently supported k8s versions

**Comment by rturner3** [comment]
We should consider doing this in 1.9.0 since Kubernetes projected service account tokens have been supported in Kubernetes versions for 2+ years now.
