### ISSUE TITLE
plugin server nodeattestor aws iid: Allow for additional selectors from the Instance Identity Document?

### ISSUE THREAD

**Issue by jessesanford** [spiffe/spire#3514]
Is there any reason we can't surface more fields from the instance identity document to be used as selectors?
https://github.com/spiffe/spire/blob/02d7af3ad63147acd847dd09853a251dfe0c18b9/pkg/server/plugin/nodeattestor/awsiid/iid.go#L355-L397

```
$ curl http://169.254.169.254/latest/dynamic/instance-identity/document
{
“accountId” : “XXXXXXXXX",
“architecture” : “x86_64",
“availabilityZone” : “us-west-2b”,
“billingProducts” : null,
“devpayProductCodes” : null,
“marketplaceProductCodes” : null,
“imageId” : “ami-0e81828bfafcdddbd”,
“instanceId” : “i-06309d51c78628654”,
“instanceType” : “r5.large”,
“kernelId” : null,
“pendingTime” : “2021-04-22T18:21:27Z”,
“privateIp” : “172.22.78.250",
“ramdiskId” : null,
“region” : “us-west-2”,
“version” : “2017-09-30”
}
```

Particularly `imageId` would be handy to only allow spiffe ids for nodes built on known hardened or blessed images

**Comment by azdagron** [comment]
We reviewed this in our maintainer sync and were surprised we didn't already emit some of these. We agree there are some valuable selectors that could be produced from these claims (e.g. imageId, region, availabilityZone). A contribution would of course be welcome here :)

**Comment by guilhermocc** [comment]
Hi there, i would love to contribute to resolving this issue, could it be assigned to me please @azdagron?

**Comment by azdagron** [comment]
Sure thing! Thanks, @guilhermocc !
