### ISSUE TITLE
k8sbundle notifier plugin throws an error if kube_config_file_path is not provided

### ISSUE THREAD

**Issue by developer-guy** [spiffe/spire#3518]
We (w/@dentrax) followed up on the [documentation](notifier_k8sbundle.md) of the _k8sbundle_ plugin, and it says if the `kube_config_file_path` parameter is not provided, in-cluster credentials will be used, however, we saw an error once we try to configure the k8sbundle notifier plugin like the following:

```hcl
    Notifier "k8sbundle" {
        plugin_data {
           clusters = {
             "demo-cluster" = {
                namespace = "test"
			}  
          }
        }
      }
    }
```

> kube_config_file_path | The path on disk to the kubeconfig containing configuration to enable interaction with the Kubernetes API server. If unset, it is assumed the notifier is in-cluster and in-cluster credentials will be used.
-- | --

We investigated the error a little bit and saw the following code part that requires `kube_config_file_path` must be set in the configuration of the plugin:

https://github.com/spiffe/spire/blob/bfa325e021e1bb53a5c4e9b376a9422bd63a1416/pkg/server/plugin/notifier/k8sbundle/k8sbundle.go#L137

So, I think we should remove this line and add a warning message to inform people that in-cluster credentials will be used.

* **Version**: 
* **Platform**: 
* **Subsystem**:

**Comment by amartinezfayo** [comment]
@developer-guy Thanks for opening this issue.
Unfortunately, the documentation of the `k8sbundle` plugin is not clear about this. 
This plugin did not support multiple clusters from the beginning and the introduction of this support had to be done in a backwards-compatible way. Hence, some confusion was generated around the top-level settings and the `clusters` section.

Clusters configured in the ` clusters` section are assumed to be remote clusters that require a `kube_config_file_path` setting. An in-cluster config can only be specified in the top-level configuration. An out-of-cluster config can be specified either in the top-level configuration or in the `clusters` section, where multiple clusters could be specified.

I filed #3543 to update the documentation to reflect this.
I'll go ahead and close this issue. Please re-open if you think that's needed.
