### ISSUE TITLE
Remove x509_svid_ttl column

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#3536]
In anticipation of introducing seperate X509-SVID and JWT-SVID TTL registration entry fields, two new columns were added to the registration entry model in the datastore (see #3174). Support was added to SPIRE core to support these fields in (#3445), which would consume these columns. However, while developing and evaluating the new support we came to the conclusion that backcompat and downgrade support became much simpler if the existing ttl column was used as it has traditionally been used, for the X509-SVID ttl.

As such, the x509_svid_ttl column added in #3174 is no longer relevant. In accordance with our deprecation policies, it can be removed in 1.6.0.

The field for the model was removed in 1.5.0 (see #3541) so that we could support a 1.6.0 --> 1.5.x downgrade. This means that new deployments of 1.5.x will NOT have the column. This means that the migration code **MUST** be idempotent, checking for existence of the column before trying to remove it.

**Comment by dennisgove** [comment]
I'm happy to take this on.

**Comment by azdagron** [comment]
That'd be great! Thanks @dennisgove. The `main` branch will open up for 1.6.0 changes roughly after we ship 1.5.2 in a few months. I'll assign this to you.

**Comment by azdagron** [comment]
@dennisgove is this something you are still willing to take? If so, repo is open now for 1.6.0 changes :) If not, no worries, one of the maintainers can also pick it up.

**Comment by dennisgove** [comment]
Yup, happy to work on it. I'll try to get a PR in in the next week.
