### ISSUE TITLE
No longer test against database versions that are end-of-life

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#3538]
We currently have integration tests against the following EOL'd database versions:
- MySQL 5.5 (EOL Dec 2018) 
- MySQL 5.6 (EOL Feb 2021)
- PostgreSQL 9 (EOL Nov 2021)

These database versions have been EOL for at least a year (in a few days, that is). They take significant time to test in our CI/CD pipeline, particularly MySQL.

This issue is to discuss the removal of integration testing for these versions. The datastore is likely to continue working against them, but we would no longer verify that through CI/CD.

**Comment by bri365** [comment]
Looks like straightforward changes to ~5 test suite files for MySQL and ~6 for PostgreSQL.
Do we want to let folks know a release ahead of time?

**Comment by azdagron** [comment]
I don't know if we need to give much more heads up, since we're not removing support, just not explicitly testing against those versions. Datastore churn has also reduced over the last year so it's likely we'll keep supporting them for a very long time.

We also gave a shout to the community via slack and gave everyone a heads up and invited commentary, and as you can see, crickets :)

I'm personally ok with just pulling the plug, so to speak. Don't know if others maintainers have opinions. I'll bring it up in today's contributor sync.
