### ISSUE TITLE
Use kubernetes secret as a keymanager plugin

### ISSUE THREAD

**Issue by swamibluedata** [spiffe/spire#3582]
In a pure kubernetes environment, when running spire-server in HA configuration, pvc is still required to share keys.json across multiple replicas. Does it make sense to implement a keymanager plugin that utilizes kubernetes secret.

**Comment by azdagron** [comment]
Hey @swamibluedata, SPIRE Server instances do not share signing keys. You shouldn't need to share these keys between instances, and in fact it will probably cause some problems.

**Comment by azdagron** [comment]
(i.e. SPIRE servers, when restarted, will not recognize the keys since they are not part of the journal and will force a key rotation)

**Comment by swamibluedata** [comment]
Thanks @azdagron . 

Can the keys.json just be ephemeral in that case? 

If the spire-server is restarted without persistent signing keys, do the agents need to be restarted for attestation?

**Comment by azdagron** [comment]
The answer is, it depends. If the keys are not persisted then when SPIRE server starts up, it will immediately rotate its signing keys. If you are using JWT-SVID, then this means that any new JWT-SVIDs signed by that server will not be verifiable  until the updated bundle (which is updated by the rotation event) is propagated. For X509-SVIDs this will also be the case _unless_ you are also using an upstream authority, in which case the X509-SVIDs signed with the new SPIRE server intermediate will still chain up to the trusted upstream roots.
