### ISSUE TITLE
Documentation does not answer some specific questions about SPIRE server scaling.

### ISSUE THREAD

**Issue by idexter** [spiffe/spire#3613]
* **Version**: `any`
* **Platform**: `any`
* **Subsystem**: `server`

## Horizontal scale schema

Lets imagine we want to scale SPIRE server horizontally within single trust domain, so we have 2 instances on different nodes which uses single [DataStore](https://github.com/spiffe/spire/blob/v1.5.1/doc/plugin_server_datastore_sql.md):

```mermaid
C4Container
title Container Diagram for SPIRE Server horizontal scale

SystemDb(db, "SPIRE Server DB", "Postgres")

Deployment_Node(node1, "node1", ""){
  Container(server1, "SPIRE Server", "Go Application", "Instance 1")
SystemDb(data1, ".data", "SPIRE runtime data directory for instance 1")
Container(ks1, "KeyManager","in memory", "In memory private key storage for instance 1")

}
Deployment_Node(node2, "node2", ""){
Container(server2, "SPIRE Server", "Go Application", "Instance 2")
SystemDb(data2, ".data", "SPIRE runtime data directory for instance 2")
Container(ks2, "KeyManager", "in memory", "In memory private key storage for instance 2")
}

Rel(server1, db, "")
Rel(server2, db, "")

Rel(server1, data1, "")
Rel(server2, data2, "")


Rel(server1, ks1, "")
Rel(server2, ks2, "")

```

## About `data_dir ` parameter

As we know from [SPIRE Server Configuration Reference](https://spiffe.io/docs/latest/deploying/spire_server/), the server has `data_dir ` parameter which is used by the Server at runtime. For example it stores X509 Journal on disk.

**The question is:**

- If I scale SPIRE Server instance horizontally, should I share this directory between the instances like in diagram below? Or it's ok to use separate runtime directories as in the first diagram. Does it have any pitfalls?

```mermaid
C4Container
title Container Diagram for SPIRE Server horizontal scale

SystemDb(db, "SPIRE Server DB", "Postgres")
Container(data, ".data", "shared storage", "Shared SPIRE runtime data directory with SPIRE CA Journal for both instances")

Deployment_Node(node1, "node1", ""){
  Container(server1, "SPIRE Server", "Go Application", "Instance 1")
}

Deployment_Node(node2, "node2", ""){
Container(server2, "SPIRE Server", "Go Application", "Instance 2")
}

Rel(server1, db, "")
Rel(server2, db, "")

Rel(server1, data, "")
Rel(server2, data, "")

```

## About `KeyManager` plugin

As we know from [SPIRE Server Configuration Reference](https://spiffe.io/docs/latest/deploying/spire_server/), the server stores private keys using `KeyManager` plugin.

By default it uses `KeyManager` [memory](https://github.com/spiffe/spire/blob/v1.5.1/doc/plugin_server_keymanager_memory.md) plugin.

**The question is:**

- If I scale SPIRE Server instance horizontally, should I sync private keys between the instances using [disk](https://github.com/spiffe/spire/blob/v1.5.1/doc/plugin_server_keymanager_disk.md) plugin for example like in diagram below or I can use memory plugin for each instance like in first diagram? What will happens if I don't do so? Will both SPIRE Server instances work without any pitfalls?

```mermaid
C4Container
title Container Diagram for SPIRE Server horizontal scale

SystemDb(db, "SPIRE Server DB", "Postgres")
Container(ks, "KeyManager", "disk", "In memory private key storage for both instances")

Deployment_Node(node1, "node1", ""){
  Container(server1, "SPIRE Server", "Go Application", "Instance 1")
}

Deployment_Node(node2, "node2", ""){
Container(server2, "SPIRE Server", "Go Application", "Instance 2")
}

Rel(server1, db, "")
Rel(server2, db, "")

Rel(server1, ks, "")
Rel(server2, ks, "")

```

**Comment by evan2645** [comment]
Hi @idexter - the only thing that needs to be shared between SPIRE Servers is the database. Any files that a server drops to disk (i.e. journal and disk-based key manager, etc) should _not_ be shared and each server instance is expected to generate and maintain its own copy

Hopefully this answers your question. We'd be happy to take a PR to the docs to clarify this point if you'd like to send one. I'll go ahead and close this out, please ping back if you have any further questions. You can also join our slack at https://slack.spiffe.io

**Comment by idexter** [comment]
> We'd be happy to take a PR to the docs to clarify this point if you'd like to send one.

Thanks, @evan2645 I'll try to make a PR to the docs to clarify this as soon as I understand where it's better to place such explanation. 🙏 

> You can also join our slack at https://slack.spiffe.io/

Thanks a lot. I know about Slack. Unfortunatelly, I'm from Russia which has been banned by Slack by political reasons, so I can't use it and therefore I need to find alternative ways for asking questions. 😢
