### ISSUE TITLE
Feature request: On Windows have agent check work load process is code signed

### ISSUE THREAD

**Issue by bbeuning** [spiffe/spire#3647]
Windows supports code signing executable files.
If the agent verifies a work load process is code signed
that is strong evidence the process can be trusted.

**Comment by amartinezfayo** [comment]
Hi @bbeuning, thank you for opening this request.
Are you referring to enhancing the ["windows" workload attestor](https://github.com/spiffe/spire/blob/main/doc/plugin_agent_workloadattestor_windows.md) to provide selectors with details of digital signatures of the workload binary that is attesting?

**Comment by bbeuning** [comment]
Yes.  The details might be
Is the binary signed?
Did Windows verify the signature of the binary before launching the process?
(I don't know how to do either of those.)

At the risk of saying things you already know.
Windows will store hashes of multiple (binary) files in a CAB file, and then sign the CAB file.
Code signing is a PKI thing with CA issuing code signing certs.
Windows has a list of trusted code signing CA.

Windows can check signatures on DLL files but they discourage it as too expensive.
I know a couple of projects that store DLL hashes in the EXE files and check DLL at startup.
The hashes are protected by the EXE signing.
