### ISSUE TITLE
Feature request: support pem format in federates_with configuration

### ISSUE THREAD

**Issue by StupidScience** [spiffe/spire#3648]
Hello.

As far as I can see there is possibility to use PEM format in federation create command. Would be nice if it will be possible to support it in configuration file for `https_web` profile.
Smth like
```hcl
bundle_endpoint_profile "https_web" {
    trust_bundle_format = "PEM"
}
```

Actually I didn't follow if `trustDomainBundleFormat` flag available in command for any case but when `trustDomainBundlePath` is defined.
Anyway not sure why `https_web` and `https_spiffe` are required to provide data in same format. So if you want to use `https_web` you have to convert your certificate to JWK while command line allow you to use just PEM-certificate.

**Comment by evan2645** [comment]
Hi @StupidScience , sorry for the delay.

The federation configuration section adheres to the [SPIFFE federation spec](https://github.com/spiffe/spiffe/blob/main/standards/SPIFFE_Federation.md), which adheres to the [SPIFFE trust bundle](https://github.com/spiffe/spiffe/blob/main/standards/SPIFFE_Trust_Domain_and_Bundle.md) format. One crucial aspect of this format is that it supports both X.509 and JWT signing keys.

The SPIRE Server `bundle` subcommands were written before these specifications were in place, and to preserve compatibility, the `bundle show` command defaults to PEM (which does not include JWT keys). If you want to federate and use the bundle subcommands in conjunction, you should use the SPIFFE format.

> Anyway not sure why https_web and https_spiffe are required to provide data in same format.

Bundle endpoint profiles are supposed to capture the authentication and transport modes, not the format of the bundle provided. The `https_web` profile relies on TLS-protected HTTP transport, authenticated using traditional Web PKI (i.e. a publicly trusted CA cert). The `https_spiffe` profile relies on a TLS-protected HTTP transport, authenticated using SPIFFE (i.e. an explicitly trusted authority that is not a public authority).

I'm going to go ahead and close this issue out, as we will likely not support non-SPIFFE format on bundle endpoints. That said, we recognize that there's a lot of room for improvement on the experience here, and we're happy to open further issues to address that directly... please feel free to leave more comments or open more issues ❤️
