### ISSUE TITLE
AWS Node Resolver plugin: Index out of range error

### ISSUE THREAD

**Issue by paul-argeniss** [spiffe/spire#367]
* **Version**: https://github.com/spiffe/aws-resolver/commit/70b82663cffca874b8fcfb305ad7bdea6df1e131
* **Platform**: Ubuntu
* **Subsystem**: Server

Plugin sometimes panics with an index out of range error. I've seen this in the Drew demo when there are many agents/workloads. I don't have steps to reproduce this yet.

Clone of https://github.com/spiffe/aws-resolver/issues/7

**Comment by evan2645** [comment]
@paul-argeniss can you post a stacktrace too? Would really help in trying to track it down

**Comment by paul-argeniss** [comment]
I don't have a stack trace right now. The logs were lost in a terminated AWS instance. Also this error is sporadic and hard to notice because the drew demo restarts the processes when they fail so it can easily go unnoticed.

**Comment by evan2645** [comment]
@drrt mind leaving some notes here about how you managed to repro this?

**Comment by drrt** [comment]
Looks like the code that was panicing has been refactored away. Will close.
