### ISSUE TITLE
Feature request: Metrics for rotating SVIDs

### ISSUE THREAD

**Issue by thejohnrichard** [spiffe/spire#3683]
For our services we want to observe that the SVIDs are rotated successfully every 60 min and if not, trigger an alert.

We have not really found a metrics that lets us check the timestamp when the SVID has been rotated the last time. We managed to come up with an expression that check the status of the SVID rotation and observes the delta, like this:

`- alert: SpireAgentFailedToRotateSVID`
`  expr: delta(spire_agent_agent_svid_rotate{status="OK"}[5m]) == 0`
`  for: 65m`

This accounts for the unique behaviour at start up when the SVID is set but not really rotated. Without these time windows we would be getting false positives for the first hour.

What would be an ideal solution for this situation would be a metric that we can check when the SVID has been updated the last time using a timestamp. Potentially even two metrics that track the last successful and unsuccessful SVID rotations. This would allow us to either use the current time to check when the last successful SVID rotation was or to simply validate that the last successful rotation is more recent than the last failed SVID rotation. To catch initial failures initialising both values with 0 would help.

* **Version**: latest

**Comment by rturner3** [comment]
Hi @thejohnrichard, just to clarify are you looking for a way to observe rotation events of workload SVIDs managed by an agent, or are you interested in the rotation of the agent SVID specifically? The metric you pointed is only emitted on agent SVID rotation events, so just wanted to make sure I understood what you're trying to achieve.

**Comment by thejohnrichard** [comment]
Hi @rturner3 , the rotation of the agent SVID is of interest to us.

**Comment by rturner3** [comment]
Would monitoring for successive failures reported by the `spire_agent_agent_svid_rotate` metric where the `status` label is not a value of `OK` satisfy your monitoring requirements? The Agent SVID rotation task is run every five seconds, so that should provide pretty steady signal if there are some problems renewing the Agent SVID.

Regarding emitting timestamps - I don't think a timestamp is generally a valid data type for metrics systems, so I'm not sure how that would work.

**Comment by thejohnrichard** [comment]
Your proposal sounds good so far to me. I will suggest that to my team. I am wondering though, how will that look like initially, at the very first "rotation" which is not really a rotation?

**Comment by rturner3** [comment]
> Your proposal sounds good so far to me. I will suggest that to my team. I am wondering though, how will that look like initially, at the very first "rotation" which is not really a rotation?

The first agent certificate fetch happens as part of the node attestation process. If the agent certificate fails to get a certificate from the server on startup (i.e. node attestation is not successful), the agent will crash, which should be detectable through other means like the `uptime_in_ms` metric or through signals provided by the orchestrator of spire-agent.

**Comment by robinp-tw** [comment]
Thank you, we confirmed the behavior that it retries renewing every 5-ish seconds, up until the SVID is expired, where the agent would crash.

So monitoring for delta[1m] > 0, holding for a few minutes, should be a good-enough signal.

**Comment by rturner3** [comment]
Sounds good, I'll go ahead and close this for now.
