### ISSUE TITLE
SPIRE Agent can fail to start if DNS search domains are configured

### ISSUE THREAD

**Issue by nweedon-u** [spiffe/spire#3685]
* **Version**: Spotted on 1.4.4, but likely affects other versions
* **Platform**: Spotted on Linux, but likely affects Windows
* **Subsystem**: Initial client-server attestation

A few of our machines were hitting this issue seemingly at random, but then would consistently crash with the following:
```
time="2022-12-07T11:33:50-05:00" level=error msg="Agent crashed" error="create attestation client: failed to dial dns:///<redacted_host>:<redacted_port>: timed out"
```

The rest of our fleet configured to use SPIRE did not have this issue.

We had to open up `pcap` to see what was going on and it turns out that the agent attempts to resolve a DNS `TXT` entry at `_grpc_config.<trust_domain>` when connecting to the server. We didn’t have this configured - the failing machines had DNS search domains configured which ended up piling up and timing out (after the hardcoded 30 second period) before the agent even made a request to the server.

We resolved this on our end by specifying a `TXT` record with an empty JSON object: `{}`.

**Comment by azdagron** [comment]
We explicitly set a [round robin service config](https://github.com/spiffe/spire/blob/08c48976b2050d9ba8d567264be87910d72836ad/pkg/agent/client/dial.go). I don't know that we need to support resolver supplied service config. If not, we should be able to disable it using [WithDisableServiceConfig](https://pkg.go.dev/google.golang.org/grpc#WithDisableServiceConfig).

**Comment by azdagron** [comment]
Yeah, we should treat this as a bug. We've thought a lot about or balancing strategy and have settled on round robin. We don't see a good reason to allow this config to be dynamically configurable via the resolver.

We should update the two spots in spire that dial to use WithDisableServiceConfig:
https://github.com/spiffe/spire/blob/593c5e5a150c0f92d5cb423e29cc10c4809ac337/pkg/agent/attestor/node/node.go#L260
https://github.com/spiffe/spire/blob/593c5e5a150c0f92d5cb423e29cc10c4809ac337/pkg/agent/client/dial.go#L66

**Comment by guilhermocc** [comment]
Hey there, @azdagron. Could this task be assigned to me, please? i would like to help to that.

**Comment by guilhermocc** [comment]
For more context about how gRPC load balancing works internally: https://github.com/grpc/grpc/blob/master/doc/load-balancing.md
