### ISSUE TITLE
SVID issuance audit log

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#3688]
When SPIRE Server mints an SVID for a remote caller, we should get to know details about both the entry that the SVID was minted against, as well as the SVID itself.

Currently, when SPIRE Server mints an SVID, it logs a message with the SPIFFE ID, Caller ID, Entry ID, and Expiration date, amongst other things. Notably missing is the SVID serial number, and the revision number of the Entry. We should definitely log these as well, in a pair of new fields.

```DEBU[0061] Signed X509 SVID                              authorized_as=agent authorized_via=datastore caller_addr="127.0.0.1:61745" caller_id="spiffe://example.org/spire/agent/join_token/99a9a879-4e18-46bb-8389-2dde59050faa" entry_id=d1004dd5-364f-43a3-bdcb-57cce31256d9 expiration="2022-12-08T20:07:26Z" method=BatchNewX509SVID request_id=4a7b1f7e-96d2-42a5-8c98-a8a8f6e28379 service=svid.v1.SVID spiffe_id="spiffe://example.org/foo" subsystem_name=api```

_Originally requested by @amoore877 in https://github.com/spiffe/spire/issues/3253#issuecomment-1341296289_

**Comment by alexviktorov** [comment]
Adding serial and revision number to Batch/New method and only the serial to Mint method

**Comment by rturner3** [comment]
I chatted with @alexviktorov offline and he volunteered to take up this issue, assigning him here. Thanks, @alexviktorov!
