### ISSUE TITLE
Frequent MySQL database deadlocks on calls to BatchUpdateEntry

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#3690]
We are sometimes seeing this error reported from calls to `BatchUpdateEntry`:

```
code:13, error: failed to update entry: datastore-sql: Error 1213: Deadlock found when trying to get lock; try restarting transaction
```

We are using MySQL 5.7. In our environment, we are serializing all our calls to `BatchUpdateEntry`, so there shouldn't be concurrent update calls being handled by the server.

We have a usage pattern where we infrequently perform `BatchUpdateEntry` calls in a bursty manner at a somewhat low rate (0-3 RPS). This seems to be often enough to randomly trigger these deadlocks once in a while, and we have encountered prolonged periods (order of hours) where these deadlocks can happen 5-10 times per minute.

Usually DB deadlocks are a result of multiple concurrent queries being executed that grab multiple database locks in different orders (see [Stack post](https://stackoverflow.com/questions/2332768/how-to-avoid-mysql-deadlock-found-when-trying-to-get-lock-try-restarting-trans) for reference), e.g. query 1 grabs lock A, then lock B and query 2 grabs lock B, then lock A.

**Comment by evan2645** [comment]
I wonder if this is related to SPIRE Server cache hydration occurring during your BatchUpdateEntry

**Comment by zmt** [comment]
We have not seen this recur. We were on old code when we saw this with any frequency. We have not seen it at all since adopting SPIRE v1.6.1. Safe to close.
