### ISSUE TITLE
Document supported database (and other) dependencies

### ISSUE THREAD

**Issue by bri365** [spiffe/spire#3711]
Discuss adding database and other supported dependency/integration versions; we currently only document supported integrations in docs. A few ways to approach this:

1. add `docs/supported_databases.md` with mysql and postgres sections, and a link to it in `docs/spire_server.md`
2. rename `docs/supported_integrations.md` to `docs/supported_versions.md` and add a section for datastore databases
3. something else? ¯\_(ツ)_/¯

**Comment by evan2645** [comment]
We discussed this during our maintainer sync today, and consensus there was that option 1 is the way to go ❤️
