### ISSUE TITLE
Envoy Incremental SDS

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#3778]
The Envoy SDS v3 [handler](https://github.com/spiffe/spire/blob/d8262d0dee5b212dcf2cc429211a883224ad64cb/pkg/agent/endpoints/sdsv3/handler.go#L212-L214) doesn't implement the incremental version of SDS (`DeltaSecrets`). The incremental version of SDS improves the efficiency of the xDS protocol by only sending changed resources as updates rather than all resources on every response.

**Comment by divaspathak** [comment]
Hello @rturner3 , I want to work on this issue, can you please assign it to me?

**Comment by rturner3** [comment]
Sure, thank you for volunteering to do this @divaspathak!

**Comment by rturner3** [comment]
@divaspathak Before we start on the PR, would you mind providing an implementation plan here in the issue that we can review? This API implementation will be a little more involved since it's a server-streaming API that needs to comply with the Envoy xDS protocol. It might be easier to talk through some of those details in the issue upfront to help you streamline the development process.

**Comment by rturner3** [comment]
@divaspathak Are you still interested in taking up this issue?
