### ISSUE TITLE
Failing integration tests on linux arm64

### ISSUE THREAD

**Issue by guilhermocc** [spiffe/spire#3821]
* **Version**: `main` branch
* **Platform**: linux arm64
* **Subsystem**: spire agent and server

There are some failing integration tests when running spire integration tests on a `Debian GNU/Linux 11 (bullseye) aarch64`. Below is the list of tests that are failing:
- datastore-mysql 
    - Apparently, the MySQL image that we are using does not have a candidate for arm64 architecture: `Pulling mysql-5-7 (mysql:5.7)...
5.7: Pulling from library/mysql
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries`
- datastore-mysql-replication 
    -  Same problem as above
- envoy-sds-v2 envoy-sds-v3
    -  Apparently, the envoy image that we are using does not have a candidate for arm64 architecture: ` ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 15761d6f4957
standard_init_linux.go:219: exec user process caused: exec format error`
- envoy-sds-v3-spiffe-auth 
    - Same thing as envoy-sds-v2
- k8s-crd-mode
    - We are using a hardcoded version of kind that is not compatible with arm64: `[2023-02-03T13:46:06Z] downloading kind from https://github.com/kubernetes-sigs/kind/releases/download/v0.11.1/kind-linux-amd64...
[2023-02-03T13:46:09Z] downloading kubectl from https://storage.googleapis.com/kubernetes-release/release/v1.21.1/bin/linux/amd64/kubectl...
[2023-02-03T13:46:13Z] starting cluster...
[2023-02-03T13:46:13Z] unable to create cluster` 
- k8s-reconcile
    - Same problem as above 
- upstream-authority-cert-manager
    - Same problem as above
- upgrade
    - We are using a version of spire that does not yet support arm64 architecture: `spire-server-1.5.0           | standard_init_linux.go:219: exec user process caused: exec format error` 

Here is the complete run logs of the failing tests:
[result-run-failed-3.txt](https://github.com/spiffe/spire/files/10579838/result-run-failed-3.txt)

**Comment by rturner3** [comment]
- `datastore-mysql` and `datastore-mysql-replication`:

Oracle doesn't publish MySQL 5.7 arm64 images. They only publish arm64 images for MySQL 8.0 today: https://hub.docker.com/r/arm64v8/mysql/

Considering Oracle doesn't release [arm64 binaries for 5.7,](https://dev.mysql.com/downloads/mysql/5.7.html) I think it's unlikely they'll publish arm64 Docker images for 5.7 given its community end of life date is October 2023.

I don't think we want to maintain our own MySQL 5.7 image just for this integration test. We could detect in the test when we are running on arm64 and skip testing 5.7 with a warning message. I think it's worth considering to just drop testing against 5.7 at the end of this year given it's close to EOL.

- `envoy-sds-v2`, `envoy-sds-v3`, and `envoy-sds-v3-spiffe-auth`

We can fix these tests by migrating from the `envoyproxy/envoy-alpine` image to the `envoyproxy/envoy` image. The latter image is published for arm64 for the versions we depend on (1.16+): https://hub.docker.com/r/envoyproxy/envoy/tags

- `k8s-crd-mode`, `k8s-reconcile`

These tests were recently removed as part of the deprecation of k8s-workload-registrar: https://github.com/spiffe/spire/pull/3853

- `upstream-authority-cert-manager`

kind and kubectl publish arm64 release binaries. We just need to add some architecture detection logic in [test/integration/common](https://github.com/spiffe/spire/blob/65c8e0a239d92a7e5c550c0c1271ddeba4c1e907/test/integration/common#L199-L227) by parsing `uname -m`, mapping {`x86_64`, `amd64`} -> `amd64` and {`aarch64`, `arm64`} -> `arm64`, and including `amd64`/`arm64` in the correct part of the path of the release binary URLs.

We probably also need to do the same for the [kindest/node image](https://github.com/spiffe/spire/blob/65c8e0a239d92a7e5c550c0c1271ddeba4c1e907/test/integration/common#L229-L238), which is published for arm64 today: https://hub.docker.com/r/kindest/node/tags

- `upgrade`

This is going to fail until the 1.7 release series. We should detect if the test is running on arm64, and if so, skip it. If we ignore this test, we should also add a TODO comment to remind us to re-enable the test in 1.7.0.

I think with these changes, we should be able to run `make integration` on an arm64-based system without seeing any errors.

**Comment by rturner3** [comment]
I've created separate issues for each of these tests so we can track the approach and status a little easier for each individual one:

https://github.com/spiffe/spire/issues/3874
https://github.com/spiffe/spire/issues/3875
https://github.com/spiffe/spire/issues/3876
https://github.com/spiffe/spire/issues/3877

**Comment by guilhermocc** [comment]
Thank you for mapping this, @rturner3 😄
