### ISSUE TITLE
Support Hashi's Vault in addition to AWS secrets manager for ECS platform

### ISSUE THREAD

**Issue by sudeeptoroy** [spiffe/spire#3861]
This is a feature request to support Hashi's Vault in addition to AWS secrets manager for supporting RFC #1843 (Serverless architecture support) on AWS ECS platform.
Cost being a driver here.

**Comment by evan2645** [comment]
Hey @sudeeptoroy, thank you for opening this. Would you mind sharing a little more about what you're trying to accomplish? The main thing I wonder about is, if you have workloads pulling secrets from vault, and you want to pull SVIDs from there too, why not ask vault to mint the SVIDs for you rather than deploy SPIRE to push certs into it?

**Comment by sudeeptoroy** [comment]
Hi @evan2645 , we are in a very initial phase of design and what you suggested does make sense for ECS. With Spire we were trying to have a single plane/touch-point for all attestation across various compute like EKS, EC2 and ECS. 
Do you think we can still achieve this if we use vault for minting SVIDs?

**Comment by evan2645** [comment]
Hey @sudeeptoroy , sorry for the delay .. we've had a few discussions around this and are still a bit stuck on the best path forward.

Most folks agree that AWS Secrets Manager is your best option .. I think they charge $0.40 per secret per month, so at 1,000 workloads each with one X509-SVID, the cost is ~$400 .. which doesn't seem bad for supporting 1,000 workloads, but still we understand that every person's situation is different.

Another solution is something like a Credential Exchange API on SPIRE Server, paired with SPIRE SDK extensions to allow workloads to call SPIRE Server directly with some kind of platform credential (e.g. AWS IAM creds). It has the notable downside of cold start perf and availability hit, but I think you are already taking this hit if you're going to use Vault?

Finally, we don't see any technical challenge in supporting a Vault as an SVIDStore plugin, but the use case question still stands, and some usability issues around it. My personal feeling is you'll spend more trying to support Vault (in eng time/cost) than you would if you used AWS Secrets Manager. You will need to not only stand up and run the Vault and its persistence, but you'll also need to solve Vault secret injection in k8s, Vault role and permissions management, and mapping workload identities to vault roles. If the only thing you're getting is last mile delivery of a SPIRE-minted credential, that feels like a lot of work for only a little value.

**Comment by evan2645** [comment]
@sudeeptoroy if you're ok using k8s secrets, another option could be an SVIDStore plugin for k8s secrets .. that has clearer use case/usability properties IMO
