### ISSUE TITLE
EC2 Node attestation for specific IAM role or other selector value

### ISSUE THREAD

**Issue by vish-k** [spiffe/spire#3879]
* **Version**:  1.5.4 
* **Subsystem**: server aws_iid 

Since NodeResolver plug-in is deprecated, how can we configure aws_iid plugin to attest nodes with specific iam role or other selectors? I looked at docs, server full config etc. but it's not clear on how to attest EC2 nodes with specific selector value.

**Comment by evan2645** [comment]
Hi @vish-k!

Node attestors also emit selectors. I referenced [the docs](https://github.com/spiffe/spire/blob/main/doc/plugin_server_nodeattestor_aws_iid.md#supported-selectors) for the AWS IID attestor, and noticed that there is an IAM label already being emitted by it (`aws_iid:iamrole`). Does this answer your question, or are you looking for something else?

**Comment by vish-k** [comment]
Thanks! This helps.
