### ISSUE TITLE
Update NewDowstreamX509CA to propagate metadata

### ISSUE THREAD

**Issue by MarcosDY** [spiffe/spire#3899]
Propagate Tainted keys when using NewDownstreamX509CA

Depends on #3885

**Comment by nikzayn** [comment]
@MarcosDY I would like to work on this. Can you brief me more about the issue?

**Comment by MarcosDY** [comment]
Hello, it is not ready yet, it depends on some proto changes that are on PR yet

**Comment by nikzayn** [comment]
Sure @MarcosDY.

**Comment by MarcosDY** [comment]
to keep this issue alive
