### ISSUE TITLE
not able to start workload api

### ISSUE THREAD

**Issue by vellimani-pixel** [spiffe/spire#3913]
* **Version**: 
* **Platform**: 
* **Subsystem**: 

We are having challenges with initiating the workload API. We have a process running and we want to use SVID while communicating betwene nodes via this process.
We have installed SPIRE Server/Agent and able to establish a connection using JoinToken method. We are also able to regiser a workload but not able to proceed further with the usage of workload API.
Can someone share the starting point of initiating our workload?
And also Can I get setp by step instructions on the complete setup?

**Comment by faisal-memon** [comment]
The workload needs to be able to speak the workload API. Is your workload go based? We have a [go-spiffe](https://github.com/spiffe/go-spiffe) library if so.

**Comment by vellimani-pixel** [comment]
@faisal-memon We are trying to build in Java, do you have any reference for java workload?

**Comment by faisal-memon** [comment]
Yes there is a java-spiffe library: https://github.com/spiffe/java-spiffe

**Comment by faisal-memon** [comment]
@vellimani-pixel Were you able to make use of the java-spiffe library?

**Comment by azdagron** [comment]
I'll close this out for now. Please let us know if you need additional help.
