### ISSUE TITLE
When initializing multiple SPIRE servers at the same time, deadlock occurs

### ISSUE THREAD

**Issue by hiyosi** [spiffe/spire#3948]
* **Version**:  <= 1.5.3
* **Platform**: x86_64 GNU/Linux
* **Subsystem**: server

When initializing multiple SPIRE servers at the same time, sometime errors are occurred such as db deadlock. 
Is this a problem that must be avoided with deployment strategies such as rolling deployments?

We use Percona Server for MySQL 5.7(57-5.7.33-36.1) as datastore.
https://docs.percona.com/percona-server/5.7/release-notes/release-notes_index.html

Errors seem to occur in multiple places.

e.g db migration
```
msg="\x1b[35m(/home/runner/work/spire/spire/pkg/server/datastore/sqlstore/migration.go:303)\x1b[0m\n\x1b[33m[2022-09-14 02:29:45]\x1b[0m\x1b[31;1m
msg="\x1b[35m(/home/runner/work/spire/spire/pkg/server/datastore/sqlstore/migration.go:303)\x1b[0m\n\x1b[33m[2022-09-14 02:29:45]\x1b[0m\x1b[31;1m
panic: Error 1146: Table 'spire.attested_node_entries' doesn't exist
```

```
msg="Fatal run error" error="datastore-sql: migrating from schema version 0 requires a previous SPIRE release; please follow the upgrade strategy at doc/upgrading.md"
```

e.g. ca preparation
```
msg="Unable to rotate X509 CA" error="rpc error: code = Unknown desc = datastore-sql: Error 1213 (40001): Deadlock found when trying to get lock; try restarting transaction" subsystem_name=ca_manager
```
```
msg="Unable to rotate JWT key" error="datastore-sql: Error 1213: WSREP detected deadlock/conflict and aborted the transaction. Try restarting the transaction."
```

**Comment by hiyosi** [comment]
https://spiffe.slack.com/archives/C7XDP01HB/p1677824966711739

**Comment by azdagron** [comment]
Can you add details about which database backend you are using?

**Comment by hiyosi** [comment]
Update descrpition and added the db details.
