### ISSUE TITLE
Remove all references to "control plane" and "cp"

### ISSUE THREAD

**Issue by drrt** [spiffe/spire#395]
The nomenclature switched quote a while ago from "control plane" to "server," but a few things (the server's SPIFFE ID, for example) still use the old lingo.

**Comment by evan2645** [comment]
Server spiffe id should be `/spire/server`. I think a couple of the server plugins also use `cp` in some spots (ca?)...

**Comment by evan2645** [comment]
This was done in https://github.com/spiffe/spire/pull/434
