### ISSUE TITLE
Provide integration tests for builtin AWS plugins

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#3953]
Currently the builtin AWS plugins have no integration tests, so it is hard to catch regressions when things change in those plugins, such as AWS SDK dependency updates. The CNCF provides the project access to an AWS account with some budget for running jobs, so we should tap into this to test AWS integrations in the project.

The following builtin AWS plugins could use integration test support:
- `aws_iid` NodeAttestor (server + agent)
- `aws_kms` KeyManager (server)
- `aws_secretsmanager` SVIDStore (agent)
- `aws_pca` UpstreamAuthority (server)
- `awssecret` UpstreamAuthority (server)

**Comment by evan2645** [comment]
Work on this is blocked until we get #2168 in place
