### ISSUE TITLE
Automated process for root CA generation

### ISSUE THREAD

**Issue by drrt** [spiffe/spire#396]
Given no automated upstream CA, a mechanism should exist to create a new root CA to use in a trust domain. This could be accomplished with a modified/new upstream_ca or ca plugin. The resulting CA would have to be distributed to new agents on first launch, so it should be easily extractable from the server.

In addition, this approach should persist the cert and key to disk via files or the datastore.

**Comment by evan2645** [comment]
The upstream ca plugin is now optional. The ca plugin has been transformed into a keymanager plugin, and a keymanager "disk" plugin also exists. Using keymanager "disk" and not enabling the upstream ca plugin will result in a new root ca being generated and persisted on disk. Marking this as done
