### ISSUE TITLE
Expose ListEntriesBatch rpc for larger requests of entries

### ISSUE THREAD

**Issue by stevend-uber** [spiffe/spire#3963]
Currently [ListEntriesRequest](https://github.com/spiffe/spire-api-sdk/blob/7ff3eb0759ce242a38fd02aa368b3d7a33ac7316/proto/spire/api/server/entry/v1/entry.proto#L57) can take a filter that allows you to select on 1 ParentID. With requests where many parentIDs or spiffeIDs are needed to be retrieved, this incurs an individual RPC per filter. 

To reduce the number of calls to SPIRE Server, we could expose a ListEntriesBatch that takes an array of Filters and OR's them when querying SPIRE db. 

Loosely:
```    
rpc ListEntries(ListEntriesRequest) returns (ListEntriesResponse);
```

```
message ListEntriesRequest {
    message Filter {
        spire.api.types.SPIFFEID by_spiffe_id = 1;
        spire.api.types.SPIFFEID by_parent_id = 2;
        spire.api.types.SelectorMatch by_selectors = 3;
        spire.api.types.FederatesWithMatch by_federates_with = 4;
    }

    // Filters the entries returned in the response.
    repeated Filter filters = 1;
}
```

**Comment by azdagron** [comment]
Can you elaborate more on the use cases you hope to solve with this?

- does this result in a single query where the relationship between filters is an AND? an OR?
- does this result in multiple queries where the results are aggregated?

The answers to the above have some pretty large impact on the complexity of the implementation.

If this is just to avoid making multiple RPCs to the server, I'd argue it isn't worth the additional complexity.

**Comment by stevend-uber** [comment]
A mix of point 1 and point 2 is what I imagined this being. 

Given **FilterA** and **FilterB**, we can funnel those into a single DB call that returns an aggregation of those values (an **OR**).

Right now, we have a component that is concerned with a large subset of the total registrations in the spire-db (say 80%), but in order to retrieve all of those registrations but not the entire DB, we'd have to make 1000's of RPCs to retrieve that info.
