### ISSUE TITLE
Upstream Authority "vault" Plugin doesn't make X509 Certificate with SAN

### ISSUE THREAD

**Issue by inajob** [spiffe/spire#3968]
* **Version**: v1.6.1
* **Platform**: `Linux HOSTANAME 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* **Subsystem**: server

We use SPIRE with Upstream Authority "vault" Plugin.
When we try to upgrade Spire 1.5.5 -> 1.6.1, SPIRE Server can'r start with below error.
> level=error msg="Fatal run error" error="rpc error: code = InvalidArgument desc = X509 CA minted by upstream authority is invalid: invalid upstream-signed X509 CA: invalid X509 CA: missing URI SAN"

It seems to be no URI SAN field in upsrtream minted X509 Certificate.

I found the [interface of Vault](https://developer.hashicorp.com/vault/api-docs/secret/pki#uri_sans-2), it requires `uri_sans` field if I want to get X509 Certificate with SAN.
but plugin's code doesn't specify this filed ( https://github.com/spiffe/spire/blob/v1.6.1/pkg/server/plugin/upstreamauthority/vault/vault_client.go#L353 )

How to fix this issue?

I don't know which is the best solution.

1. fix vault plugin to speficy this field.
2. fix validation logic to ignore SAN filed.

Or are there other solution about this probrem?

**Comment by hiyosi** [comment]
If a value of URI SAN(SPIFFE ID) is required in certificates for X509SVID CA, I will open a PR ( #3971 ).

**Comment by amartinezfayo** [comment]
Fixed by https://github.com/spiffe/spire/issues/3968.
