### ISSUE TITLE
Audit infinitely growing datasets in the datastore

### ISSUE THREAD

**Issue by drrt** [spiffe/spire#397]
Some datasets (like AWS EC2identity document based node attestation) cause the datastore to grow without bounds. Enumerate the cases where this occurs and possible solutions.

**Comment by scotte** [comment]
This is a problem for the k8s node attestor as well. In a 15 hour period I had 2 agents that were respawning in CrashLoopBackoff - they restarted 210 times each, resulting in 420 rows in "attested_node_entries" and 1260 rows in "node_resolver_map_entries".

While this particular environment was in a broken state, in a large production environment this will be a pretty big issue - stale entries should be expired.

**Comment by evan2645** [comment]
attested node entries and node resolver map entries are the only place this still occurs. Unfortunately, it's not an easy problem to fix. I'm closing this out in favor of tracking in https://github.com/spiffe/spire/issues/1836 as it is tighter scoped
