### ISSUE TITLE
Nothing error logged when dns_name_templates create a DNS name that is too long

### ISSUE THREAD

**Issue by keeganwitt** [spiffe/spire#3976]
* **Version**: 1.5.5
* **Subsystem**: Registrar

We had a `dns_name_templates` value of `{{.Pod.Namespace}}--{{.Pod.ServiceAccount}}`. When you have a namespace and service account combination longer than 61 characters, you end up with a DNS name with a component longer than the 63-character limit supported by Kubernetes. Even when using dot separators, you could have a similar issue if the total length is longer than the supported 128-character limit. Since the Registrar didn't log this error, there was no way other than guessing to know this was the problem (the behavior exhibited was that some pods got an SVID, and some didn't).

The length gets checked [here](https://github.com/spiffe/spire/blob/9eeefd0536bc9fa9a0be16c7cc4c6a75e847e7a1/support/k8s/k8s-workload-registrar/mode-crd/api/spiffeid/v1beta1/spiffeid_webhook.go#L135-L139), but then the error returned isn't logged [here](https://github.com/spiffe/spire/blob/9eeefd0536bc9fa9a0be16c7cc4c6a75e847e7a1/support/k8s/k8s-workload-registrar/mode-crd/api/spiffeid/v1beta1/spiffeid_webhook.go#L55-L57).

**Comment by keeganwitt** [comment]
I wonder if we should also consider changing https://github.com/spiffe/spire/blob/v1.5.5/support/k8s/k8s-workload-registrar/mode-crd/controllers/pod_controller.go#L187. It is validating the template, but not the template after the variable substitutions.

**Comment by faisal-memon** [comment]
assign to me

**Comment by keeganwitt** [comment]
> This can be closed. Not sure why auto close didn't kick in. Maybe because it wasn't merged to main?

I couldn't find anywhere in their documentation they discuss this, but their blog post introducing the feature seems to indicate it has to be your default branch, yea.
https://github.blog/2013-01-22-closing-issues-via-commit-messages/
