### ISSUE TITLE
Generate release artifacts statically linked to musl

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#4008]
The project's release binaries currently require linking to glibc, which implicitly restricts which distributions of Linux SPIRE can run on. The release container images now statically link to musl to support minimal images built from scratch. We should be able to do the same for the release binaries, and ideally could just use the same binaries generated in the containers in the release pipeline.

**Comment by maxlambrecht** [comment]
Should we create and release these musl-linked artifacts in addition to the glibc artifacts, or would it be more beneficial to solely focus on releasing musl-linked artifacts?

**Comment by azdagron** [comment]
This was covered by #4491
