### ISSUE TITLE
Inconsistent behavior when creating registration entries

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#4057]
Running the following command (with two selectors) for the first time, it creates an entry successfully:
```
./bin/spire-server entry create -selector color:red -selector size:medium  -parentID spiffe://example.org/agent -spiffeID spiffe://example.org/test
Entry ID         : 70e5514c-09e6-4172-9928-e1ac01a18fae
SPIFFE ID        : spiffe://example.org/test
Parent ID        : spiffe://example.org/agent
Revision         : 0
X509-SVID TTL    : default
JWT-SVID TTL     : default
Selector         : color:red
Selector         : size:medium
```
After that, running the following command (with only one of the two selectors above), it returns an error,, even though the selectors are a subset of the selectors in the previous entry:
```
./bin/spire-server entry create -selector color:red  -parentID spiffe://example.org/agent -spiffeID spiffe://example.org/test
Failed to create the following entry (code: AlreadyExists, msg: "similar entry already exists"):
Entry ID         : (none)
SPIFFE ID        : spiffe://example.org/test
Parent ID        : spiffe://example.org/agent
Revision         : 0
X509-SVID TTL    : default
JWT-SVID TTL     : default
Selector         : color:red

Error: failed to create one or more entries
```
However, if running the following (with 3 selectors, 2 of them identical to the first command), it creates the entry successfully.
```
./bin/spire-server entry create -selector color:red -selector size:medium -selector shape:round  -parentID spiffe://example.org/agent -spiffeID spiffe://example.org/test
Entry ID         : 58834c99-ad87-4d05-a742-2ab343b45f1a
SPIFFE ID        : spiffe://example.org/test
Parent ID        : spiffe://example.org/agent
Revision         : 0
X509-SVID TTL    : default
JWT-SVID TTL     : default
Selector         : color:red
Selector         : shape:round
Selector         : size:medium
```
The entry could be created. This is an inconsistent behavior.

**Comment by amoore877** [comment]
https://sourcegraph.com/github.com/spiffe/spire@390f09c/-/blob/pkg/server/datastore/sqlstore/sqlstore.go?L2435 for relevant bit.

We should check that the proposed and existing selectors are an exact match, not that one is a subset of the other.

**Comment by MarcosDY** [comment]
`filterEntriesBySelectorSet` is never called on Entry creation, 
when we search for lookupSimilarEntry, we are using the response from listRegistrationEntriesOnce,
that function on Exact response is returning the list of entries filtered by Exact OR Superset in case of Exact is choose, 
We can call listRegistrationEntries that is filtering or add logic to prevent listRegistrationEntriesOnce to return an uncomplete filtering
