### ISSUE TITLE
FailedPrecondition desc = workloadattestor(k8s) - arm64

### ISSUE THREAD

**Issue by doffi88** [spiffe/spire#4088]
Hi all,

I have the following error when i verify that the container can access the socket following k8s QuickStart. 

```shell

failed: rpc error: code = FailedPrecondition desc = workloadattestor(k8s): multiple container IDs found in cgroups (20d8ec296f8e480195d35056548d49a6409966957741d2205601c66fe1effceb, service)" pid=100240 subsystem_name=workload_attestor

``` 

I'm using version 1.6.3 spire version ( agent/server) with 3 nodes  k8s (1.27.1) cluster with cri-o (1.6.3). every node is a raspberry pi 4 with ubuntu 20-04.lts 64 bit

the following is the cgroup of corresponding client pod:

```shell
12:pids:/system.slice/crio-conmon-20d8ec296f8e480195d35056548d49a6409966957741d2205601c66fe1effceb.scope
11:hugetlb:/
10:memory:/system.slice/crio-conmon-20d8ec296f8e480195d35056548d49a6409966957741d2205601c66fe1effceb.scope
9:cpuset:/
8:rdma:/
7:net_cls,net_prio:/
6:perf_event:/
5:freezer:/
4:devices:/system.slice/crio-conmon-20d8ec296f8e480195d35056548d49a6409966957741d2205601c66fe1effceb.scope
3:blkio:/system.slice/crio-conmon-20d8ec296f8e480195d35056548d49a6409966957741d2205601c66fe1effceb.scope
2:cpu,cpuacct:/system.slice/crio-conmon-20d8ec296f8e480195d35056548d49a6409966957741d2205601c66fe1effceb.scope
1:name=systemd:/system.slice/crio-conmon-20d8ec296f8e480195d35056548d49a6409966957741d2205601c66fe1effceb.scope
0::/system.slice/crio-conmon-20d8ec296f8e480195d35056548d49a6409966957741d2205601c66fe1effceb.scope
``` 

what's the problem?there is something that I'm doing wrong?

**Comment by azdagron** [comment]
Hmm, when i ran those cgroups through the parsing code, it came up with a different result (could not locate the pod uid or container id).

Did you capture these from running a command in the client pod itself?

If so, can you capture them from a container running in the agent pod instead? That is the view that the agent will see, and can differ.

**Comment by doffi88** [comment]
Hi I took it from node host. 
today the pod was scheduled in an other node the error is always the same

```shell
time="2023-04-21T21:14:08Z" level=error msg="Failed to collect all selectors for PID" error="workload attestor \"k8s\" failed: rpc error: code = FailedPrecondition desc = workloadattestor(k8s): multiple container IDs found in cgroups (ed793913de79618a73fa0a3939b713404f1a5fcff469fcfc063e75520c8d5d87, service)" pid=20015 subsystem_name=workload_attester
``` 

I used debug to enter inside spire agent pod:

```shell
kubectl -n spire debug -it spire-agent-drd8q  --image=busybox:1.28 --target=spire-agent
``` 

and then, inside the pod:

```shell
ps -ef | grep watch
   98 root      0:00 [watchdogd]
 1885 root      0:01 /opt/spire/bin/spire-agent api watch -socketPath /run/spire/sockets/agent.sock
75522 root      0:00 grep watch
``` 


```shell
cat /proc/1885/cgroup 
12:pids:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod42f1fc72_249e_4f67_8773_cff4f8f9d157.slice/crio-ed793913de79618a73fa0a3939b713404f1a5fcff469fcfc063e75520c8d5d87.scope
11:rdma:/
10:devices:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod42f1fc72_249e_4f67_8773_cff4f8f9d157.slice/crio-ed793913de79618a73fa0a3939b713404f1a5fcff469fcfc063e75520c8d5d87.scope
9:perf_event:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod42f1fc72_249e_4f67_8773_cff4f8f9d157.slice/crio-ed793913de79618a73fa0a3939b713404f1a5fcff469fcfc063e75520c8d5d87.scope
8:cpuset:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod42f1fc72_249e_4f67_8773_cff4f8f9d157.slice/crio-ed793913de79618a73fa0a3939b713404f1a5fcff469fcfc063e75520c8d5d87.scope
7:memory:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod42f1fc72_249e_4f67_8773_cff4f8f9d157.slice/crio-ed793913de79618a73fa0a3939b713404f1a5fcff469fcfc063e75520c8d5d87.scope
6:hugetlb:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod42f1fc72_249e_4f67_8773_cff4f8f9d157.slice/crio-ed793913de79618a73fa0a3939b713404f1a5fcff469fcfc063e75520c8d5d87.scope
5:net_cls,net_prio:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod42f1fc72_249e_4f67_8773_cff4f8f9d157.slice/crio-ed793913de79618a73fa0a3939b713404f1a5fcff469fcfc063e75520c8d5d87.scope
4:freezer:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod42f1fc72_249e_4f67_8773_cff4f8f9d157.slice/crio-ed793913de79618a73fa0a3939b713404f1a5fcff469fcfc063e75520c8d5d87.scope
3:cpu,cpuacct:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod42f1fc72_249e_4f67_8773_cff4f8f9d157.slice/crio-ed793913de79618a73fa0a3939b713404f1a5fcff469fcfc063e75520c8d5d87.scope
2:blkio:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod42f1fc72_249e_4f67_8773_cff4f8f9d157.slice/crio-ed793913de79618a73fa0a3939b713404f1a5fcff469fcfc063e75520c8d5d87.scope
1:name=systemd:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod42f1fc72_249e_4f67_8773_cff4f8f9d157.slice/crio-ed793913de79618a73fa0a3939b713404f1a5fcff469fcfc063e75520c8d5d87.scope
0::/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod42f1fc72_249e_4f67_8773_cff4f8f9d157.slice/crio-ed793913de79618a73fa0a3939b713404f1a5fcff469fcfc063e75520c8d5d87.scope
```

**Comment by azdagron** [comment]
Hmm. Interesting. I ran those cgroups through the code internal to the workload attestor that extracts the pod uid and container ID (the one that returns the error you are seeing) and it correctly identifies the pod uid and container and returns success.

I also tried with an older version of last year before we made other changes for crio and it also succeeded.

Can you please verify that you are indeed running with SPIRE 1.6.3?

**Comment by doffi88** [comment]
this is DaemonSet, spire agent

```shell
kubectl get daemonsets.apps -n spire spire-agent -o yaml
``` 

and the result

```shell
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"app":"spire-agent"},"name":"spire-agent","namespace":"spire"},"spec":{"selector":{"matchLabels":{"app":"spire-agent"}},"template":{"metadata":{"labels":{"app":"spire-agent"},"namespace":"spire"},"spec":{"containers":[{"args":["-config","/run/spire/config/agent.conf"],"image":"ghcr.io/spiffe/spire-agent:1.6.3","livenessProbe":{"failureThreshold":2,"httpGet":{"path":"/live","port":8080},"initialDelaySeconds":15,"periodSeconds":60,"timeoutSeconds":3},"name":"spire-agent","readinessProbe":{"httpGet":{"path":"/ready","port":8080},"initialDelaySeconds":5,"periodSeconds":5},"volumeMounts":[{"mountPath":"/run/spire/config","name":"spire-config","readOnly":true},{"mountPath":"/run/spire/bundle","name":"spire-bundle"},{"mountPath":"/run/spire/sockets","name":"spire-agent-socket","readOnly":false}]}],"dnsPolicy":"ClusterFirstWithHostNet","hostNetwork":true,"hostPID":true,"initContainers":[{"args":["-t","30","spire-server:8081"],"image":"cgr.dev/chainguard/wait-for-it","name":"init"}],"serviceAccountName":"spire-agent","volumes":[{"configMap":{"name":"spire-agent"},"name":"spire-config"},{"configMap":{"name":"spire-bundle"},"name":"spire-bundle"},{"hostPath":{"path":"/run/spire/sockets","type":"DirectoryOrCreate"},"name":"spire-agent-socket"}]}}}}
  creationTimestamp: "2023-04-15T15:56:28Z"
  generation: 1
  labels:
    app: spire-agent
  name: spire-agent
  namespace: spire
  resourceVersion: "361062"
  uid: 38957135-ebd1-406b-b4fb-b3fa2ba546eb
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spire-agent
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spire-agent
      namespace: spire
    spec:
      containers:
      - args:
        - -config
        - /run/spire/config/agent.conf
        image: ghcr.io/spiffe/spire-agent:1.6.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 3
        name: spire-agent
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/spire/config
          name: spire-config
          readOnly: true
        - mountPath: /run/spire/bundle
          name: spire-bundle
        - mountPath: /run/spire/sockets
          name: spire-agent-socket
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      initContainers:
      - args:
        - -t
        - "30"
        - spire-server:8081
        image: cgr.dev/chainguard/wait-for-it
        imagePullPolicy: Always
        name: init
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: spire-agent
      serviceAccountName: spire-agent
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: spire-agent
        name: spire-config
      - configMap:
          defaultMode: 420
          name: spire-bundle
        name: spire-bundle
      - hostPath:
          path: /run/spire/sockets
          type: DirectoryOrCreate
        name: spire-agent-socket
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 2
  desiredNumberScheduled: 2
  numberMisscheduled: 0
  numberReady: 0
  numberUnavailable: 2
  observedGeneration: 1
  updatedNumberScheduled: 2
``` 

this is statefulset, spire server

```shell
kubectl get statefulsets.apps -n spire spire-server  -o yaml
``` 

and the result

```shell
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"labels":{"app":"spire-server"},"name":"spire-server","namespace":"spire"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"spire-server"}},"serviceName":"spire-server","template":{"metadata":{"labels":{"app":"spire-server"},"namespace":"spire"},"spec":{"containers":[{"args":["-config","/run/spire/config/server.conf"],"image":"ghcr.io/spiffe/spire-server:1.6.3","livenessProbe":{"failureThreshold":2,"httpGet":{"path":"/live","port":8080},"initialDelaySeconds":15,"periodSeconds":60,"timeoutSeconds":3},"name":"spire-server","ports":[{"containerPort":8081}],"readinessProbe":{"httpGet":{"path":"/ready","port":8080},"initialDelaySeconds":5,"periodSeconds":5},"volumeMounts":[{"mountPath":"/run/spire/config","name":"spire-config","readOnly":true},{"mountPath":"/run/spire/data","name":"spire-data","readOnly":false}]}],"serviceAccountName":"spire-server","volumes":[{"configMap":{"name":"spire-server"},"name":"spire-config"}]}},"volumeClaimTemplates":[{"metadata":{"name":"spire-data","namespace":"spire"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}}}}]}}
  creationTimestamp: "2023-04-15T15:41:00Z"
  generation: 1
  labels:
    app: spire-server
  name: spire-server
  namespace: spire
  resourceVersion: "361083"
  uid: d23daa11-ae68-481a-93f5-549fa175e7b0
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spire-server
  serviceName: spire-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spire-server
      namespace: spire
    spec:
      containers:
      - args:
        - -config
        - /run/spire/config/server.conf
        image: ghcr.io/spiffe/spire-server:1.6.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 3
        name: spire-server
        ports:
        - containerPort: 8081
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/spire/config
          name: spire-config
          readOnly: true
        - mountPath: /run/spire/data
          name: spire-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: spire-server
      serviceAccountName: spire-server
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: spire-server
        name: spire-config
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: spire-data
      namespace: spire
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 0
  collisionCount: 0
  currentReplicas: 1
  currentRevision: spire-server-788c57c868
  observedGeneration: 1
  replicas: 1
  updateRevision: spire-server-788c57c868
  updatedReplicas: 1
```

**Comment by azdagron** [comment]
Hmm, I'm still struggling to reproduce this. The output you gave me parses clean with the code. Further, the word `service`, which is one of the conflicting IDs that was extracted, does not even show up in the output you provided.

I'm not quite sure how to proceed here. My only guess is that the agent container itself is seeing a different view that the debug container you executed in that last comment.

**Comment by azdagron** [comment]
Hey @doffi88 ! Just checking in here. Were you able to find any differences in the cgroups view from the agent container v.s. the debug container? From our assessment, that's about the only thing that we can think of that would cause the disparity.

**Comment by doffi88** [comment]
Hi sorry! I wasn't able to check. sorry for the following stupid question, how can I enter inside agent container? because I wasn't able to enter with kubectl exec and sh or bash.

**Comment by azdagron** [comment]
The agent container doesn't have a shell or anything (to keep the size minimal and remove attack surface). One way you can do this is to build your own container that has a shell and copy in the agent binary using `COPY --from` and deploy that.

**Comment by azdagron** [comment]
Any chance you've been able to give this a go?

**Comment by doffi88** [comment]
Yes, it is clear what should be done. I've been quite busy at work this week. I'll try it on Sunday and let you know. I'm so sorry about that, but I haven't had much time

**Comment by doffi88** [comment]
Hi all,

this is the dockerfile that I made:

``` sh 
FROM  debian:bullseye-slim

WORKDIR /opt/spire

COPY spire-agent ./bin/spire-agent
ENTRYPOINT ["/opt/spire/bin/spire-agent", "run"]
``` 

and then:

``` sh 
kubectl -n spire exec -it spire-agent-vsnfq -c spire-agent  -- sh
``` 


``` sh 
ps -ef | grep watch
   99 root      0:00 [watchdogd]
 1752 1000      0:02 /bin/prometheus-config-reloader --listen-address=:8080 --reload-url=http://127.0.0.1:9090/-/reload --config-file=/etc/prometheus/config/prometheus.yaml.gz --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml --watched-dir=/etc/prometheus/rules/prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0
10999 root      0:03 /opt/spire/bin/spire-agent api watch -socketPath /run/spire/sockets/agent.sock
103747 root      0:00 grep watch
``` 


``` sh 
ps -ef | grep watch
   99 root      0:00 [watchdogd]
 1752 1000      0:02 /bin/prometheus-config-reloader --listen-address=:8080 --reload-url=http://127.0.0.1:9090/-/reload --config-file=/etc/prometheus/config/prometheus.yaml.gz --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml --watched-dir=/etc/prometheus/rules/prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0
10999 root      0:03 /opt/spire/bin/spire-agent api watch -socketPath /run/spire/sockets/agent.sock
103747 root      0:00 grep watch
``` 

``` sh 
/opt/spire # cat /proc/10999/cgroup 
12:hugetlb:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podccfb2838_0553_4f4d_8d7a_6eeb61421a3c.slice/crio-e9f013be7f8fc664afec0b24b875c484c5ef134a0b2a6c8c7ad08ddb672ea057.scope
11:perf_event:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podccfb2838_0553_4f4d_8d7a_6eeb61421a3c.slice/crio-e9f013be7f8fc664afec0b24b875c484c5ef134a0b2a6c8c7ad08ddb672ea057.scope
10:rdma:/
9:devices:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podccfb2838_0553_4f4d_8d7a_6eeb61421a3c.slice/crio-e9f013be7f8fc664afec0b24b875c484c5ef134a0b2a6c8c7ad08ddb672ea057.scope
8:freezer:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podccfb2838_0553_4f4d_8d7a_6eeb61421a3c.slice/crio-e9f013be7f8fc664afec0b24b875c484c5ef134a0b2a6c8c7ad08ddb672ea057.scope
7:cpuset:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podccfb2838_0553_4f4d_8d7a_6eeb61421a3c.slice/crio-e9f013be7f8fc664afec0b24b875c484c5ef134a0b2a6c8c7ad08ddb672ea057.scope
6:memory:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podccfb2838_0553_4f4d_8d7a_6eeb61421a3c.slice/crio-e9f013be7f8fc664afec0b24b875c484c5ef134a0b2a6c8c7ad08ddb672ea057.scope
5:net_cls,net_prio:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podccfb2838_0553_4f4d_8d7a_6eeb61421a3c.slice/crio-e9f013be7f8fc664afec0b24b875c484c5ef134a0b2a6c8c7ad08ddb672ea057.scope
4:pids:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podccfb2838_0553_4f4d_8d7a_6eeb61421a3c.slice/crio-e9f013be7f8fc664afec0b24b875c484c5ef134a0b2a6c8c7ad08ddb672ea057.scope
3:blkio:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podccfb2838_0553_4f4d_8d7a_6eeb61421a3c.slice/crio-e9f013be7f8fc664afec0b24b875c484c5ef134a0b2a6c8c7ad08ddb672ea057.scope
2:cpu,cpuacct:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podccfb2838_0553_4f4d_8d7a_6eeb61421a3c.slice/crio-e9f013be7f8fc664afec0b24b875c484c5ef134a0b2a6c8c7ad08ddb672ea057.scope
1:name=systemd:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podccfb2838_0553_4f4d_8d7a_6eeb61421a3c.slice/crio-e9f013be7f8fc664afec0b24b875c484c5ef134a0b2a6c8c7ad08ddb672ea057.scope
0::/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podccfb2838_0553_4f4d_8d7a_6eeb61421a3c.slice/crio-e9f013be7f8fc664afec0b24b875c484c5ef134a0b2a6c8c7ad08ddb672ea057.scope
``` 

the error is the same:

``` sh 
time="2023-06-03T17:58:35Z" level=error msg="Failed to collect all selectors for PID" error="workload attestor \"k8s\" failed: rpc error: code = FailedPrecondition desc = workloadattestor(k8s): multiple container IDs found in cgroups (e9f013be7f8fc664afec0b24b875c484c5ef134a0b2a6c8c7ad08ddb672ea057, service)" pid=104184 subsystem_name=workload_attestor
```

**Comment by azdagron** [comment]
Thanks @doffi88 for providing this information. This is very bewildering! I've run those inputs through the code in question and cannot reproduce the issue. I think we have two options at this point:

1. Deploy a modified SPIRE binary that log all of the observed cgroups so we can figure out the inputs that are causing this problem.
2. Provide steps for a minimum viable repro of the problem so that I can test it myself to figure out what is happening.

I appreciate your help tracking this down!

**Comment by doffi88** [comment]
Hi @azdagron yes it looks very weird, if you want I can deploy a modified binary with some logs. You should just wait for the first week of July because I'm not at home right now.

The steps I have done are as follows.

I used the deployments available on spire kubernetes getting started.
I changed the container version due to arm64 compatibility.
I changed the hostpath part because I used the csi driver.

On the 3 raspberries, as I said, is installed vanilla kubernetes.

At beginning I had some doubts about the configuration of my nfs client provider, but in this case I should have some problems on the spire server, right?

**Comment by doffi88** [comment]
hi this logs can be helpful


2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroups - cgroup groupPath [/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podccfb2838_0553_4f4d_8d7a_6eeb61421a3c.slice/crio-ad65d88fc253f565f3cdfcc61f7207eed2b6db383f32669ff93c3100dd835186.scope] ControllerList [hugetlb] HierarchyID [12]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroupPath - podUID [ccfb2838-0553-4f4d-8d7a-6eeb61421a3c] containerid [ad65d88fc253f565f3cdfcc61f7207eed2b6db383f32669ff93c3100dd835186]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroups - cgroup groupPath [/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podccfb2838_0553_4f4d_8d7a_6eeb61421a3c.slice/crio-ad65d88fc253f565f3cdfcc61f7207eed2b6db383f32669ff93c3100dd835186.scope] ControllerList [net_cls,net_prio] HierarchyID [11]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroupPath - podUID [ccfb2838-0553-4f4d-8d7a-6eeb61421a3c] containerid [ad65d88fc253f565f3cdfcc61f7207eed2b6db383f32669ff93c3100dd835186]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroups - cgroup groupPath [/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podccfb2838_0553_4f4d_8d7a_6eeb61421a3c.slice/crio-ad65d88fc253f565f3cdfcc61f7207eed2b6db383f32669ff93c3100dd835186.scope] ControllerList [pids] HierarchyID [10]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroupPath - podUID [ccfb2838-0553-4f4d-8d7a-6eeb61421a3c] containerid [ad65d88fc253f565f3cdfcc61f7207eed2b6db383f32669ff93c3100dd835186]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroups - cgroup groupPath [/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podccfb2838_0553_4f4d_8d7a_6eeb61421a3c.slice/crio-ad65d88fc253f565f3cdfcc61f7207eed2b6db383f32669ff93c3100dd835186.scope] ControllerList [cpuset] HierarchyID [9]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroupPath - podUID [ccfb2838-0553-4f4d-8d7a-6eeb61421a3c] containerid [ad65d88fc253f565f3cdfcc61f7207eed2b6db383f32669ff93c3100dd835186]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroups - cgroup groupPath [/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podccfb2838_0553_4f4d_8d7a_6eeb61421a3c.slice/crio-ad65d88fc253f565f3cdfcc61f7207eed2b6db383f32669ff93c3100dd835186.scope] ControllerList [devices] HierarchyID [8]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroupPath - podUID [ccfb2838-0553-4f4d-8d7a-6eeb61421a3c] containerid [ad65d88fc253f565f3cdfcc61f7207eed2b6db383f32669ff93c3100dd835186]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroups - cgroup groupPath [/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podccfb2838_0553_4f4d_8d7a_6eeb61421a3c.slice/crio-ad65d88fc253f565f3cdfcc61f7207eed2b6db383f32669ff93c3100dd835186.scope] ControllerList [memory] HierarchyID [7]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroupPath - podUID [ccfb2838-0553-4f4d-8d7a-6eeb61421a3c] containerid [ad65d88fc253f565f3cdfcc61f7207eed2b6db383f32669ff93c3100dd835186]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroups - cgroup groupPath [/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podccfb2838_0553_4f4d_8d7a_6eeb61421a3c.slice/crio-ad65d88fc253f565f3cdfcc61f7207eed2b6db383f32669ff93c3100dd835186.scope] ControllerList [perf_event] HierarchyID [6]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroupPath - podUID [ccfb2838-0553-4f4d-8d7a-6eeb61421a3c] containerid [ad65d88fc253f565f3cdfcc61f7207eed2b6db383f32669ff93c3100dd835186]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroups - cgroup groupPath [/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podccfb2838_0553_4f4d_8d7a_6eeb61421a3c.slice/crio-ad65d88fc253f565f3cdfcc61f7207eed2b6db383f32669ff93c3100dd835186.scope] ControllerList [blkio] HierarchyID [5]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroupPath - podUID [ccfb2838-0553-4f4d-8d7a-6eeb61421a3c] containerid [ad65d88fc253f565f3cdfcc61f7207eed2b6db383f32669ff93c3100dd835186]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroups - cgroup groupPath [/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podccfb2838_0553_4f4d_8d7a_6eeb61421a3c.slice/crio-ad65d88fc253f565f3cdfcc61f7207eed2b6db383f32669ff93c3100dd835186.scope] ControllerList [cpu,cpuacct] HierarchyID [4]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroupPath - podUID [ccfb2838-0553-4f4d-8d7a-6eeb61421a3c] containerid [ad65d88fc253f565f3cdfcc61f7207eed2b6db383f32669ff93c3100dd835186]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroups - cgroup groupPath [/] ControllerList [rdma] HierarchyID [3]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroups - cgroup groupPath [/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podccfb2838_0553_4f4d_8d7a_6eeb61421a3c.slice/crio-ad65d88fc253f565f3cdfcc61f7207eed2b6db383f32669ff93c3100dd835186.scope] ControllerList [freezer] HierarchyID [2]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroupPath - podUID [ccfb2838-0553-4f4d-8d7a-6eeb61421a3c] containerid [ad65d88fc253f565f3cdfcc61f7207eed2b6db383f32669ff93c3100dd835186]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroups - cgroup groupPath [/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podccfb2838_0553_4f4d_8d7a_6eeb61421a3c.slice/crio-ad65d88fc253f565f3cdfcc61f7207eed2b6db383f32669ff93c3100dd835186.scope] ControllerList [name=systemd] HierarchyID [1]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroupPath - podUID [ccfb2838-0553-4f4d-8d7a-6eeb61421a3c] containerid [ad65d88fc253f565f3cdfcc61f7207eed2b6db383f32669ff93c3100dd835186]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroups - cgroup groupPath [/system.slice/crio.service] ControllerList [] HierarchyID [0]
2023/07/05 22:08:00 getPodUIDAndContainerIDFromCGroupPath - podUID [] containerid [service]
time="2023-07-05T22:08:00Z" level=error msg="Failed to collect all selectors for PID" error="workload attestor \"k8s\" failed: rpc error: code = FailedPrecondition desc = workloadattestor(k8s): multiple container IDs found in cgroups (ad65d88fc253f565f3cdfcc61f7207eed2b6db383f32669ff93c3100dd835186, service)" pid=66450 subsystem_name=workload_attestor
time="2023-07-05T22:08:00Z" level=debug msg="PID attested to have selectors" pid=66450 selectors="[type:\"unix\" value:\"uid:0\" type:\"unix\" value:\"gid:0\" type:\"unix\" value:\"supplementary_gid:0\"]" subsystem_name=workload_attestor
time="2023-07-05T22:08:00Z" level=error msg="No identity issued" method=FetchX509SVID pid=66450 registered=false service=WorkloadAPI subsystem_name=endpoints

**Comment by doffi88** [comment]
How it's possible that the input pid is not the container pid that made the request?

**Comment by azdagron** [comment]
Great, this output helps. We can fix out detection code to avoid triggering this bug.

> How it's possible that the input pid is not the container pid that made the request?

Are you saying that 82738 is not the PID for the process running in the  Workload container? Is it connecting to the Workload API indirectly through a sidecar (e.g. Envoy)?

**Comment by doffi88** [comment]
Yeah , it’s clear what’s happened. I was looking for pid workload process instead of pid process inside the workload  😝  oook my fault…..🤪 thank you very much for the explanation
