### ISSUE TITLE
Propagate federation relationships to other nodes in a domain

### ISSUE THREAD

**Issue by hellerda** [spiffe/spire#4128]
In a nested SPIRE deployment, if one nested node has a federation relationship with another trust domain, only that server will be federated to the remote domain.  That is, the federation relationship does not automatically apply to other nodes in the nested deployment.  To have a federation with a remote domain, each SPIRE server must be federated individually.

While this provides the greatest security -- or at least, isolation between federated nodes -- it can be burdensome to have to federate nodes individually.  It would be convenient to have the federation relationship "propagate", or apply to more than one node in the nested

To federate a node two things are needed: a) to create the federation relation itself, in server.conf, or by "federation create" command or API call, and b) the remote domain trust bundle.

Of the two, it's really the trust bundle I'm thinking of here.  I don't think it's too burdensome to create the federation relation at each node explicitly.  And it may be better that way, to maintain tight control over which nodes are federated.

But for "https_spiffe" federations, having to set the remote domain trust bundle at each node can be burdensome.  Once set at one server, It would be convenient to have the bundle propagate to other nodes in the domain where the federation is desired.  The natural thing to do here would be to propagate the remote trust bundle to *downstream* nodes.

Consider such a feature that could be controlled in server.conf by toggling "downstream propagation" on.  Any server downstream of that parent would get a copy of the remote domain bundle.  A downstream server would still have to explicitly enable the federation for it to be active.  But it could federation w/o having to seed the bundle.

Any node downstream of that level would be able to do the same, if the parent server had downstream propagation set in server.conf.  In this way you could "fan out" to nodes in the trust domain.  If desired, a trust domain admin could create the federation (and seed the bundle) at at the root server, and have almost any node in the domain get a copy of the remote domain trust bundle.

Implied is that the downstream copies of the bundle must be kept up to date.  This doesn't seem too difficult, as the update interval is not controlled on the "propagating" side: it just passes the update downstream as soon as practical.  But if enough levels are involved in the propagation, updates could be delayed as compared to a deployment where the bundle is seeded directly.

It's true there are some security concerns here.  If an attacker is able to inject a rogue bundle to one node, this increases the blast radius of the attack.  But I wonder how risky this really is, as after all, the federation endpoint is set in config, so if there is a mismatch in domain name, the rogue cert wouldn't work.

Does this sound viable?  Do others think it would be useful as well?

**Comment by amartinezfayo** [comment]
Thank you @hellerda for filing this request. I think that the propagation of federated trust bundles to downstream servers would be something useful to have in SPIRE with a nested topology.
I think that there are some open questions around how this would be implemented. I'm particularly concerned about being able to provide a predictable experience and behavior. I'm interested to dig into some specific aspects:
1) Would operators be able to know if a trust bundle for a federated trust domain has been set in this server or comes from an upstream server? This may help with the next question.
2) What happens if the trust bundle was propagated from an upstream server and an operator tries to update it?
3) How a downstream server that "inherits" a federated trust bundle enables the federation relationship with the federated trust domain? It seems that it would be confusing to use the same mechanism of configuring federation relationships, since you would be also configuring a bundle endpoint URL and profile, but that will not be used (or if it's used it will conflict/race with the propagation mechanism).

I think that this would be a great feature to have, but we have a lot to figure out yet.

**Comment by hellerda** [comment]
If I understand correctly, there is only ever one copy of a remote domain's bundle in a SPIRE server DB.  And that bundle gets populated in one of three ways (pls correct if any is wrong):

- added by a "federation create" operation with bundle provided
- added by a "bundle set" operation
- updated as needed by the remote server, once the federation is established.

If this is true, it means the same copy of the bundle serves as the "bootstrap" bundle and the "operational" bundle.

So the new behavior would be like this:

- If a server currently has no copy of a remote domain bundle, and one is available from upstream, AND the upstream server has "downstream propagation" set, AND this server has "allow propagation" from upstream set, then the bundle would be added to the this server DB.  It might not be USED currently, if there is no federation relationship to the remote domain at this server.  But if this server ever does want to federate with the remote domain it can do wo w/o having to be bootstrapped.

- If a server ALREADY has a copy of the remote domain bundle, and another if available from upstream, AND the server.conf are both set as in the previous case: then there would have to be some comparison of the currently set bundle and the one that's available from upstream.  In that case I would say:

  * If the currently set bundle is expired, replace it.  Probably that means it got set previously by downstream propagation and there is no federation relation to refresh it.  So this would be the process of keeping the propagated bundle up-to-date.

  * If the currently set bundle is not expired.. no action is required.  Now, you could handle this differently and say ALWAYS replace it if the upstream bundle is different.  This probably means the upstream bundle is just a newer "rotated" bundle that was issued before the current one has expired (good practice).  So that means you COULD could chose to replace it if the upstream bundle is newer, even if the currently set bundle is valid.  So in that case, updating with newer is probably better.

**Comment by hellerda** [comment]
To answer your questions:

> 1. Would operators be able to know if a trust bundle for a federated trust domain has been set in this server or comes from an upstream server? This may help with the next question.

You probably *wouldn't* know how it was set, so you could check the server logs.  If necessary there could be a field in the DB indicating how it was set.. but so far it doesn't seem necessary.

> 2. What happens if the trust bundle was propagated from an upstream server and an operator tries to update it?

I would say the administrative operations, "bundle set" and "federation create" with bundle provided, would always update the DB copy of bundle, just as they do currently.  If an operator is setting a bundle by either of these methods, probably the goal is to get the federation established, and the current bundle is either not set, or is expired, or is not available from upstream, or otherwise just not working.  So of course you'd have to allow the operator to fix this.  Once done, operation continues as before.

> 3. How a downstream server that "inherits" a federated trust bundle enables the federation relationship with the federated trust domain?  It seems that it would be confusing to use the same mechanism of configuring federation relationships, since you would be also configuring a bundle endpoint URL and profile, but that will not be used (or if it's used it will conflict/race with the propagation mechanism).

In my view (so far :-) I'd say it's OK for the bundle to be present but not used.  If propagation has been enabled at both parent and this server, probably the intent is that a federation relation is going to be established, and this server is now ready.  OR it's enabled just to allow another (below this) downstream node to get the bundle, and this node is just a "pass through".  If neither case applies, don't enable propagation here.
