### ISSUE TITLE
AWS Node Resolver should be a built in plugin

### ISSUE THREAD

**Issue by ajessup** [spiffe/spire#415]
Most users who wish to build attestation policies on AWS will likely prefer to describe those policies in terms of AWS constructs such as Tags, Security Groups etc. rather than specific instance IDs provided by the AWS Node Attestor.

This is the function of the (currently 2nd party) https://github.com/spiffe/aws-resolver plugin. However as a separate plugin, it is incumbent upon the user to separately identify, build, install and configure this plugin before being able to use it. The plugin is also undocumented.

We should include this as a built in plugin to the main SPIRE distribution, and document it accordingly.

**Comment by evan2645** [comment]
Thanks for this @ajessup

**Comment by evan2645** [comment]
Blocked on #367
