### ISSUE TITLE
CLI Delete should expose BatchDeleteEntry as an option

### ISSUE THREAD

**Issue by stevend-uber** [spiffe/spire#4248]
We recently found thousands of SPIRE entries parented to the same ID that needed to be deleted. That parentID was used for performance tests so it was a controlled environment. It'd be valuable to expose parentID as a filterable option when deleting an entry via the CLI.

**Comment by stevend-uber** [comment]
We recently ran into an incident where thousands of IDs were parented to the same parent entry. All of these entries needed to be deleted. It'd be valuable to expose parentID as a filterable option for entry-delete in the CLI.

**Comment by evan2645** [comment]
Hey @stevend-uber, thanks for filing this. I think we already have parent id filtering on list entries .. is it possible to achieve this by first listing with the filter and then deleting those specific entries?

**Comment by stevend-uber** [comment]
It is possible to achieve it this way but it does add an unnecessary extra RPC + some client-side filtering logic. It might be valuable to possibly consider a server-side way to filter on the db to delete these entries. Especially when we are deleting 1000's of entries, the deleteEntry RPC needs to be called once for each time.

**Comment by evan2645** [comment]
Thanks for the extra context!

We've had some discussions about this, and the general consensus is that the CLI should support everything the API does (including batch RPCs). That said, it sounds like there is a bit of work to do in figuring out how to do that in a consistent way (e.g. how do we do batch entry create?).

Implementing filtering can also be complex and comes with a different set of questions. Would it be sufficient to implement batch delete in the CLI, which would result in a two step operation (filter entries, then invoke batch delete)?

**Comment by stevend-uber** [comment]
Looking at BatchDeleteEntry it looks like it's just a repeated list of ID's? Yeah, I think that would still help plenty!

**Comment by stevend-uber** [comment]
I've updated the title to the issue!

**Comment by evan2645** [comment]
Awesome, thank you @stevend-uber!

> a bit of work to do in figuring out how to do that in a consistent way (e.g. how do we do batch entry create?).

I think the next step here is to answer this question. Reading from a file, and perhaps supporting stdin, may be acceptable. One thing we discussed was the fact that there can be max limits on the number of args a command can be passed.

Another outstanding question is the format of this input. I assume JSON aligned with the underlying proto?

There are probably some other questions that need to be answered as well that I'm not thinking of at the moment
