### ISSUE TITLE
Agent status: "Agent is unhealthy: unable to determine health"

### ISSUE THREAD

**Issue by TnGadaria** [spiffe/spire#4252]
* **Version**: 
1.6.4

* **Platform**: 
Linux (Rocky Linux 8.8): Two VMs (One acting as server and another acting as agent)

* **Subsystem**: 
I do have a spire server running and in a healthy state. Now I have started the agent on the node for attestation, Attestation type is "join_token". Node is already attested now, however, `bin/agent healthcheck` reports `Agent is unhealthy: unable to determine health`. There is no error message in the log. `bin/server agent list` lists 1 attested agent with all the parameters. I did enable health-check on the agent and it reports `{"agent":{}}` for both `ready` and `live` endpoints, not sure what it means though. Kindly let me know if I am missing something.

**Comment by edwbuck** [comment]
Please assign to me for follow up to see if this is a bug or an environmental setup issue.

**Comment by edwbuck** [comment]
@TnGadaria Please rerun your test with the following command:

```
bin/agent healthcheck -verbose
```

and past the output into this issue.  There are a number of known responses, which help us determine which root causes are contributing to the issue.

An example of the output is (my executable is called `spire-agent`)
```
[spire@m2-ess-vm166 bin]$ ./spire-agent healthcheck -verbose
Checking agent health...
Failed to check health: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-agent/public/api.sock: connect: no such file or directory"
Agent is unhealthy: unable to determine health
```

**Comment by TnGadaria** [comment]
Hi @edwbuck 
Thanks for your response. 

For me, the output of `bin/agent healthcheck -verbose` is exactly the same as what you have.

```
[root@spagt-1 sp]# bin/agent healthcheck -verbose
Checking agent health...
Failed to check health: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /tmp/spire-agent/public/api.sock: connect: no such file or directory"
Agent is unhealthy: unable to determine health
```
I noticed, my the agent.conf had the `socket_path`. I commented on that and restarted the agent. Now agent reports healthy. 

```
[root@spagt-1 sp]# bin/agent healthcheck -verbose
Checking agent health...
Agent is healthy.
```

Sharing my configuration for reference.

```
agent {
    data_dir = "./data/agent"
    log_level = "DEBUG"
    log_file = "/var/log/agent1.log"
    trust_domain = "mydomain.com"
    server_address = "server"
    server_port = 8081
    #socket_path = "/tmp/spire-server/private/api.sock"

    # Insecure bootstrap is NOT appropriate for production use but is ok for
    # simple testing/evaluation purposes.
    insecure_bootstrap = true
}

health_checks {
        listener_enabled = true
        bind_address = "client"
        bind_port = "8080"
        live_path = "/live"
        ready_path = "/ready"
}

telemetry {
    Prometheus {
        port = 3333
    }
}

plugins {
   KeyManager "disk" {
        plugin_data {
            directory = "./data/agent"
        }
    }

    NodeAttestor "join_token" {
        plugin_data {}
    }

    WorkloadAttestor "unix" {
        plugin_data {
            discover_workload_path = "true"
            workload_size_limit = 0
        }
    }
}
```

**Comment by edwbuck** [comment]
@TnGadaria Thank you.

What I don't see is the logs a bit before attempting to use the `spire-agent healthcheck` command to a bit after attempting to use the command.  The `spire-agent  healthcheck` command uses an "embedded client" in the spire-agent executable to connect to a different launch of the spire-agent, typically launched as `spire-agent run <options>`. 

A quick check of running processes should show a `spire-agent run <options>` command.  If no command like that exists, odds are the spire-agent either wasn't launched as a daemon, or was launched and then it decided to shutdown, the default behavior when the spire-agent loses connection to the spire-server for too long.

While running, the spire-agent will open (create) the `/tmp/spire-agent/public/api.sock` socket when it is ready to process requests.  When it cannot process requests (or is shutdown), this file will not exist.  This is why the launch of `spire-agent healthcheck` is reporting the lack of a the file, from the healthcheck's point of view, it cannot determine why the file is missing.

Please report if the spire-agent was running, and if it was not, attempt to start it, and report if that fixed the issue, or if it shutdown again.  If it shutdown again, copy and paste the relevant log file messages from `/var/log/agent1.log` into the ticket, and I'll be happy to take a look at them.

**Comment by TnGadaria** [comment]
Hi @edwbuck 
Thanks for the explanation, it's helpful.

I am not running the server and agent in daemon mode as of now. However, I can confirm that both were running.
I noticed I had provided the incorrect `socket_path (/tmp/spire-server/private/api.sock)` in my agent.conf file and that was the issue. Now, I changed `socket_path` to  `/tmp/spire-agent/public/api.sock` and started the agent. it's working fine and reporting healthy. 

sharing agent logs for your reference. 
I noticed, `bin/agent healthcheck` is not generating any logs. So the logs provided below is generated before I executed the `bin/agent healthcheck`. 

```
time="2023-06-15T05:50:50Z" level=warning msg="Current umask 0022 is too permissive; setting umask 0027"
time="2023-06-15T05:50:50Z" level=info msg="Starting agent with data directory: \"./data/agent\""
time="2023-06-15T05:50:50Z" level=info msg="Plugin loaded" external=false plugin_name=disk plugin_type=KeyManager subsystem_name=catalog
time="2023-06-15T05:50:50Z" level=info msg="Plugin loaded" external=false plugin_name=join_token plugin_type=NodeAttestor subsystem_name=catalog
time="2023-06-15T05:50:50Z" level=info msg="Plugin loaded" external=false plugin_name=unix plugin_type=WorkloadAttestor subsystem_name=catalog
time="2023-06-15T05:50:50Z" level=info msg="Bundle loaded" subsystem_name=attestor trust_domain_id="spiffe://mydomain.com"
time="2023-06-15T05:50:50Z" level=info msg="SVID loaded" spiffe_id="spiffe://mydomain.com/spire/agent/join_token/6ccf61b5-1541-41f1-8350-1d4fea91a0be" subsystem_name=attestor trust_domain_id="spiffe://mydomain.com"
time="2023-06-15T05:50:50Z" level=debug msg="Bundle updated" subsystem_name=cache_manager trust_domain_id=mydomain.com
time="2023-06-15T05:50:50Z" level=debug msg="Bundle added" subsystem_name=svid_store_cache trust_domain_id=mydomain.com
time="2023-06-15T05:50:50Z" level=info msg="Starting Workload and SDS APIs" address=/tmp/spire-agent/public/api.sock network=unix subsystem_name=endpoints
time="2023-06-15T05:50:50Z" level=debug msg="Initializing health checkers" subsystem_name=health
time="2023-06-15T05:50:50Z" level=info msg="Serving health checks" address="10.81.176.69:8080" subsystem_name=health
```

**Comment by edwbuck** [comment]
@TnGadaria One last note.

I noticed that in your configuration reference, you have the socket_path commented out.  While different people like to do different things, I am a big believer in not overusing comments because they tend to make it look like something is configured, when it is not.

>     #socket_path = "/tmp/spire-server/private/api.sock"

for example, is why you likely thought the socket was at a path containing the word `private` when in reality, you are using the default path built into the executable.

**Comment by TnGadaria** [comment]
Hi @edwbuck 
yes, completely agree. I have removed the line so the file looks unclustered.

Appreciate your help and the quick response. I will issue. 
Are you available on spire slack? I would like to catch up.

**Comment by edwbuck** [comment]
I'm available on SPIRE slack.  I'll be one for a about 1/2 an hour after this post, and during working 9AM CST to 5PM CST tomorrow (except for the odd meeting here and there).  Feel free to send me a chat when you can, and I'll respond as soon as I am available.
