### ISSUE TITLE
Rate-limiting on SPIRE Server should also support total number of requests an RPC can serve at a time

### ISSUE THREAD

**Issue by prasadborole1** [spiffe/spire#4265]
The SPIRE Server currently supports per IP rate limits. If a certain SPIRE Deployment has large number of SPIRE Agents then this type of rate-limiting will be insufficient mainly for high CPU intensive RPCs like BatchNewX509SVID.

In addition to limit per IP, server should also support configurable limits on total num of requests supported for a particular RPC.

**Comment by zmt** [comment]
I think I volunteered to rephrase this or file a new issue that outlines the goal/concern of making the server resilient from thundering herd when recovering from incidents.

**Comment by zmt** [comment]
We should close this in favor of #4490.

**Comment by prasadborole1** [comment]
Closing in favor of #4490
