### ISSUE TITLE
Avoid spiky svid renewal requests to SPIRE server

### ISSUE THREAD

**Issue by prasadborole1** [spiffe/spire#4268]
Currently spire-agent svid rotation happens at half life of svid validity. This may cause spiky svid renewal requests mainly after spire-agent deployments. Perform svid rotation at a time with some jitter e.g. `ttl <= (lifetime/2 + jitter(15 * time.minute))`) so that we get more uniform distribution of svid renewal requests over time.

**Comment by azdagron** [comment]
Having something like this sounds very valuable. Happy for a contribution here.

**Comment by stevend-uber** [comment]
I'll take a stab at this!

**Comment by stevend-uber** [comment]
Would like some feedback on implementation thoughts here: 

1. Option 1
The simpler method would be to gen a random duration within the [ShouldRotate()](https://github.com/spiffe/spire/blob/main/pkg/common/rotationutil/rotationutil.go#L12) method. This would be a single liner and easily maintainable.
 
2. Option 2
Precalculate the in-agent rotation time on SVID creation/rotation. We can add a field to [SVID state here](https://github.com/spiffe/spire/blob/main/pkg/agent/svid/rotator.go#L248C10-L248C10) and calculate the jittered rotation and keep it in the struct which is used in the above's rotationutil.ShouldRotate()

**Comment by amoore877** [comment]
For ref, this is a similar request to #1240 , which was also agreed as potentially valuable but closed for lack of volunteers and lack of operational need at the time. Specifically https://github.com/spiffe/spire/issues/1240#issuecomment-554582758 containing ideas of the time.

(1) and (2) here seem similar to (A) from that old issue.

**Comment by prasadborole1** [comment]
I'd vote for Option 1 as well. Just have to ensure that jitter is proportional to configured svid ttl(`expiryTime-beginTime`).

**Comment by zmt** [comment]
Concur that 1 seems like a better direction. Agree with all points that any jitter should ultimately be porportional to SVID validity period and potential future configurable rotation period. Further, I think we should avoid opening up any tuning to consumers and only expose an enable/disable configurable. Giving users the ability to tune seems like a foot-gun. We need to account for a wide distribution of SVID TTL, realizing that the lower the TTL, the smaller and less effective the jitter will be. Perhaps we want a min and a max jitter to handle either extreme of TTL that caps proportional calculation at either end.

**Comment by stevend-uber** [comment]
Sounds like option 1 is the unanimous favorite. Taking recommendations into consideration, I propose:

Given: 
Half Life: **H**
Jitter: **J**
Max Jitter: **Mj**

**H** = (NotAfter - NotBefore) / 2
**Mj** = H/2
**J** = rand(0, Mj)

This caps the jitter's effective time to from the **1/2 life** to the **3/4 life**. After the **3/4 life**, spire-agent attempts to rotate no matter what. 

As for tunable flags, I'd agree that both enabling/disabling and time configuration both seem like foot-guns.

**Comment by zmt** [comment]
>This caps the jitter's effective time to from the 1/2 life to the 3/4 life. After the 3/4 life, spire-agent attempts to rotate no matter what.

I would expect narrower jitter - more like +/- ~10% or so of H. We want to inject just enough randomness to diffuse a thundering herd.

**Comment by stevend-uber** [comment]
>I would expect narrower jitter - more like +/- ~10% or so of H. We want to inject just enough randomness to diffuse a thundering herd.

I would expect that 10% would be too small. For short TTLs say 5 minutes, that equates to 15 seconds vs 75 seconds.

**Comment by amoore877** [comment]
The default TTL I believe is an hour? Do we know of community cases with 5m TTL SVIDs?

To my prior point of `gives a recurring shot at early rotations for each SVID`; we'll be executing in a loop every period to see if SVIDs need renewal. A very large jitter proportional means many more early renewals.
Can imagine it as a skewed distribution. Origin is SVID count renewing exactly at half TTL, and as we go to the right (more time before half TTL) the count would exponentially increase. If anything I think we may want the jitter amount to be partially determined by Agent's SVID Sync interval, or at least take that into account to determine an absolute max jitter.

**Comment by amoore877** [comment]
Do we also want to take into account #4279 , backoff renewal strategy? In event of failures, should we be eagerly renewing SVIDs at all?

**Comment by stevend-uber** [comment]
https://github.com/spiffe/spire/pull/4534
