### ISSUE TITLE
Remove support for MySQL 5.7

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#4270]
Oracle is ending extended support for MySQL 5.7 in October 2023, see page 29 of https://www.oracle.com/us/support/library/lifetime-support-technology-069183.pdf

In general, supporting different versions of databases in the project is challenging, especially when the project wants to use database-native features that may not be available across all supported versions. It is also time consuming to run the unit and integration tests against each version of databases, and this results in longer PR CI build times (currently 5-10 minutes per database version).

Furthermore, SPIRE now supports arm64 architecture, but MySQL 5.7 does not, and presumably it never will since it's rapidly approaching EOL. This currently prevents us from running the MySQL 5.7 integration tests for SPIRE on arm64 architecture.

Starting in November 2023, we should strongly consider removing support for MySQL 5.7. This includes some production code that works around the lack of support for common table expressions in MySQL 5.7 as well as testing against MySQL 5.7 in the integration tests.

While the project doesn't yet publish an official matrix of supported database versions (see https://github.com/spiffe/spire/issues/3711), today this is largely implied by the versions that are tested in the repository.

**Comment by edwbuck** [comment]
Per team discussion, we should couple the removal of testing support with the removal of 5.7 specific code support.

**Comment by azdagron** [comment]
This could have gone out in 1.10.0 but we missed the window. Reprioritized urgent for 1.11.0 so that we don't forget.
