### ISSUE TITLE
AWS NodeAttestor issue: api error InvalidClientTokenId: The security token included in the request is invalid

### ISSUE THREAD

**Issue by sarroutbi** [spiffe/spire#4280]
* **Version**: 1.7.0
* **Platform**: OpenShift / K8S
* **Subsystem**: Server

I included next config in the server:
```bash
NodeAttestor "aws_iid" {
   access_key_id = "..."
   secret_access_key = "..."
   assume_role = "..."
   }
}
``` 
I am getting next error:
```bash
RRO[0000] Agent crashed error="failed to receive attestation response: rpc error: code = Internal desc = nodeattestor(aws_iid): failed to describe instance: operation error EC2: DescribeInstances, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, operation error STS: AssumeRole, https response error StatusCode: 403, RequestID: ..., api error InvalidClientTokenId: The security token included in the request is invalid
```
Is there a mechanism to provide a security token in AWS NodeAttestor? Or is this attestor limited to non [multi-factor authentication (MFA) devic](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa.html) configurations in AWS?

**Comment by azdagron** [comment]
Hi @sarroutbi. SPIRE Server does not support tokens that require MFA to use. This is fundamentally problematic because these credentials are used very frequently (e.g. whenever a node attests to the server). Having to participate in MFA on such a frequent basis is impractical.
