### ISSUE TITLE
RFE: Network+Device trust: Spire Agent EAP(oL) Device Attestation

### ISSUE THREAD

**Issue by mmaymann** [spiffe/spire#4281]
Roots of trust:
1. [Manufacturer:				Spire (FDO)](https://github.com/spiffe/spire/issues/4289)
2. [SupplyChain:				Spire (FDO)](https://github.com/spiffe/spire/issues/4289)
3. Network:					**This RFE** = Spire + SONiC (L2 security + agentless support)
4. Device:						**This RFE** = Spire + SONiC ((P)NAC/ACL)
5. User:						Spire + KeyCloak + Biometric MFA Securitykey
6. Workload:					Spire + KeyCloak
7. Data:						Spire + KeyCloak

This RFE is regarding 3+4. Network+Device based root of trust (B below):

A. XIoT Onboarding: Manufacturer produces device + forwards ownership to company using SpireServerFDO + CaptivePortal
B. [XIoT attestation](https://youtu.be/j30PhEWKgG4): [**agentless** EAP(oL) device](https://www.securew2.com/blog/802-1x-eap-tls-authentication-flow-explained) (-> AP) -> SONiCSpireAgentEAP(L2) -> SpireServer -> SONiCSpireAgent(P)NAC/ACL:
-- 802.1x EAP(oL)-TLS X.509 certificate check
-- [TPM_Certify_Info(2) (PCR status)](https://trustedcomputinggroup.org/wp-content/uploads/TPM_Keys_for_Platform_Identity_v1_0_r3_Final.pdf): Firmware version, BootLoader, OS version, firewall enabled, antivirus enabled, ...
--- Additional [Keylime](https://github.com/keylime) [functionality?](https://keylime.dev/#features) into upstream
--- [MUD](https://github.com/fido-device-onboard/release-fidoiot/issues/28) ([Manufacturer Usage Description](https://datatracker.ietf.org/doc/rfc8520)) -> ITAM -> XIoT identification
--- [SBOM](https://github.com/fido-device-onboard/release-fidoiot/issues/28) ([SoftwareBillOfMaterial](https://cyclonedx.org/specification/overview)) -> ITAM -> continuous lightweight vulnerability scanning -> proactive remediation actions
-- (P)NAC/ACL: SpireServer -> SONiC NAC
C. Company provisions validated devices to their desired state
D. Day2 operations (Realtime Spire Network+Device+User+Workload+Data attestation)

I have given my free OSS GoldenPath KubernetesNative version of a [GitOps Zero-Conf|Trust|Touch XIoT management](https://github.com/sonic-net/SONiC/issues/1362) target architecture - directly from network devices.

Suggestions/enhancements would be highly appreciated :)

Thanks in advance :)

**Comment by mmaymann** [comment]
Hi @evan2645,
Thanks for your reply :)

1. SpireServerFDO is Fido Device Onboard functionality that could be integrated into Spire Server mentioned in https://github.com/spiffe/spire/issues/4289.
2. Agentless = Spire agentless devices = devices that are not able to run Spire Agent (IoT devices etc.).
Applying POLP in a ZeroTrust infrastucture, where devices that have not been - preferably hardware - attested are not allowed:
Spire(Agentless)Device -> SONiC_EAP(oL)_TPM_Attest -> SpireAgentonSONiC -> SpireServer -> SpireAgentonSONiC -> SONiC(P)NAC/ProvisionACL -> SpireAgentlessDevice provisioning -> SONiC(P)NAC/ProductionACL
I have given my free OSS GoldenPath KubernetesNative version of a [GitOps Zero-Conf|Trust|Touch XIoT management](https://github.com/sonic-net/SONiC/issues/1362) target architecture.
3. Would it be possible to join a community session or perhaps a 1-1 where we could discuss if/how/where to best implement this functionality?

Thanks in advance :)

**Comment by mmaymann** [comment]
@evan2645 awesome :)
Sounds really cool... I will be able to participate earliest 17.8 - I have added it to my calendar and will try to prepare a small presentation for that.
Thanks :)

**Comment by evan2645** [comment]
Awesome! That date works, I can help to make sure you have time on the agenda. If you can join the Slack and send me a DM, that would also be great: https://slack.spiffe.io

I'm going to go ahead and close these issues out for now, and we can re-open them once we talk, if it makes sense. Thanks again, looking forward to it!

**Comment by alwaysastudent** [comment]
> Awesome! That date works, I can help to make sure you have time on the agenda. If you can join the Slack and send me a DM, that would also be great: https://slack.spiffe.io
> 
> I'm going to go ahead and close these issues out for now, and we can re-open them once we talk, if it makes sense. Thanks again, looking forward to it!

@mmaymann @evan2645 what came out of the meeting?
