### ISSUE TITLE
Revisit defaults for mysql plugin

### ISSUE THREAD

**Issue by nweedon-u** [spiffe/spire#4300]
* **Version**: all
* **Platform**: all
* **Subsystem**: `mysql` database plugin (maybe others too?)

By default, the `max_open_conns` and `conn_max_lifetime` are set to "unlimited". This can cause unintended performance bottlenecks as well as overuse of resources in infrastructure, in particular, the number of sockets used.

As discussed on Slack, at a minimum, the documentation should be updated to mention that these options should be set to a "reasonable value". As part of this issue, we could also explore what sensible defaults could be.

**Comment by IvMdlc** [comment]
We hit this issue with `postgres` as it opens hundreds of concurrent connections against the DB.

**Comment by azdagron** [comment]
This seems very reasonable. I think it would be great to figure out saner defaults.

If someone wants to do the legwork of looking at the more common DB engines that are supported by the project (MySQL and variants, PostgreSQL and variants) and looking at what default limits they might impose already, that might be a good starting point.

In any case, I fully agree that "unlimited" is likely the wrong default here.

Happy to have someone help out here!
