### ISSUE TITLE
RFE: Phone attestation: Android and iPhone SpireAgent app

### ISSUE THREAD

**Issue by mmaymann** [spiffe/spire#4306]
Roots of trust:
1. [Manufacturer:				Spire (FDO)](https://github.com/spiffe/spire/issues/4289)
2. [SupplyChain:				Spire (FDO)](https://github.com/spiffe/spire/issues/4289)
3. [Network:					Spire + SONiC (L2 security + agentless support)](https://github.com/spiffe/spire/issues/4281)
4. [Device:					Spire + SONiC ((P)NAC/ACL](https://github.com/spiffe/spire/issues/4281)
5. User:						Spire + KeyCloak + Biometric MFA Securitykey
6. Workload:					Spire + KeyCloak
7. Data:						Spire + KeyCloak

This RFE is regarding 4. Device - Phone attestation (+[MDM features](https://mobiletrans.wondershare.com/mobile-device-management/mdm-features-and-functions.html)) through Spire:
-- Google Play Android SpireAgent app
-- Apple Appstore iPhone SpireAgent app

I have given my free OSS GoldenPath KubernetesNative version of a [GitOps Zero-Conf|Trust|Touch XIoT management](https://github.com/sonic-net/SONiC/issues/1362) target architecture - directly from network devices.

Suggestions/enhancements would be highly appreciated :)

Thanks in advance :)

**Comment by amartinezfayo** [comment]
Thank you @mmaymann for filing this issue.
Similarly to https://github.com/spiffe/spire/issues/4281, I think that it would be great if we can discuss this request in the SIG-SPIRE meeting, where we can gather more context and discuss the request in detail.

**Comment by mmaymann** [comment]
@amartinezfayo  awesome :)
Sounds really cool... I will be able to participate earliest 17.8 - I have added it to my calendar and will try to prepare a small presentation for that.
Thanks :)

**Comment by evan2645** [comment]
Related to: https://github.com/spiffe/spire/issues/4281

Closing this out until we have more time to discuss over video
