### ISSUE TITLE
Improve SPIRE build experience

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#431]
The current SPIRE build process requires users to have a golang directory structure on disk, with the repo checked out in the right place, in order to build properly. Investigate what it would take to eliminate this requirement, and reduce the SPIRE build to only two steps: `clone` then `make`. Implement if possible/reasonable.

**Comment by martincapello** [comment]
I found the following Go issues that could impact in how to approach a solution for this:
https://github.com/golang/go/issues/17271 which ends up referencing https://github.com/golang/go/issues/24301 as a solution.
They are pretty long discussions...24301 was created a month ago, and its last comment is 2 days ago, so this is quite recent.

**Comment by azdagron** [comment]
This is now trivially achievable with go modules (introduced experimentally in go1.11).
