### ISSUE TITLE
workloadattestor systemd: failed to collect all selectors - dbus use of closed network connection

### ISSUE THREAD

**Issue by IvMdlc** [spiffe/spire#4315]
* **Version**: 1.7.0
* **Platform**: Linux 3.10.0-1160.53.1.el7.x86_64 SMP
* **Subsystem**: workloadattestor systemd

spire-agent config

```
    WorkloadAttestor "unix" {
        plugin_data {
            discover_workload_path = true
            workload_size_limit = -1
        }
    }

    WorkloadAttestor "systemd" {}
```

```
time="2023-07-03T18:28:44+01:00" level=error msg="Failed to collect all selectors for PID" error="workload attestor \"systemd\" failed: rpc error: code = Internal desc = workloadattestor(systemd): error getting value for FragmentPath: read unix @->/run/dbus/system_bus_socket: use of closed network connection" pid=30949 subsystem_name=workload_attestor
time="2023-07-03T18:28:44+01:00" level=debug msg="PID attested to have selectors" pid=30949 selectors="[type:\"unix\"  value:\"uid:600\" type:\"unix\"  value:\"user:mc\" type:\"unix\"  value:\"gid:600\" type:\"unix\"  value:\"group:mc\" type:\"unix\"  value:\"supplementary_gid:600\" type:\"unix\"  value:\"supplementary_group:mc\" type:\"unix\"  value:\"supplementary_gid:602\" type:\"unix\"  value:\"supplementary_group:mcapp\" type:\"unix\"  value:\"path:/usr/local/corretto/amazon-corretto-11.0.5.10.1-linux-x64-fips-none/bin/java\"]" subsystem_name=workload_attestor
time="2023-07-03T18:28:44+01:00" level=error msg="No identity issued" method=FetchX509SVID pid=30949 registered=false service=WorkloadAPI subsystem_name=endpoints
```

Can be reproduced using java-spiffe with a couple of threads calling a few times

```
        try (DefaultX509Source defaultX509Source = DefaultX509Source.newSource(getX509SourceOptions())) {
            defaultX509Source.getX509Svid();
        } catch (SocketEndpointAddressException | X509SourceException e) {
            //
```

**Comment by amartinezfayo** [comment]
Thank you @IvMdlc for opening this issue. It seems that this may be related with a previous issue that was fixed in #4165.
@rkaippully Is there a chance that you could take a look at this? Thanks!

**Comment by azdagron** [comment]
I dug into this a little. Looks like a misuse of the dbus library.

The code is doing the following to get a DBus connection:
```
	conn, err := dbus.SystemBus()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "failed to open dbus connection: %v", err)
	}
	defer conn.Close()
```

However, dbus.SystemBus() returns a "shared" dbus connection. The documentation on Close() explicitly indicates that it should not be called on the "shared" connection.

My guess is two attestations are happening concurrently and one invocation ends up closing the shared dbus connection from underneath the other.

My suggestion is that we stop using the shared dbus connection. I don't know if we want to open a connection for each attestation attempt still or if we want to maintain a connection lifetime at the plugin level. If we do the latter, we will have to be robust against that connection failing and handle reconnecting.

**Comment by rkaippully** [comment]
It looks like the common usage is to share the connection: https://github.com/godbus/dbus/issues/179#issuecomment-1006847775. I don't think they should be closed - i.e. `defer conn.Close()` should be removed.

The `dbus.SystemBus()` function [has logic to detect and reconnect](https://github.com/godbus/dbus/blob/v5.1.0/conn.go#L124) in case of errors.

**Comment by amartinezfayo** [comment]
@IvMdlc We have merged a fix for this in the main branch. It would be greatly appreciated if you could test this issue again with the fix. Would that be possible?

Thank you @rkaippully for providing the fix!
