### ISSUE TITLE
Allow spire-agent to retry connection to the server indefinitely instead of crashing during initial node attestation

### ISSUE THREAD

**Issue by shashankram** [spiffe/spire#4341]
When spire-agent starts up and it can't connect to the server to perform node attestation, it crashes. To improve resiliency, it would be nice if the agent could delay node attestation until it connects, where it retries the connection to the server indefinitely vs crashing. A config option for this would make sense to not break backward compatibility.

**Comment by shashankram** [comment]
Hi @evan2645, the error pertains to the agent crashing when it tries to perform the attestation upon startup and can't connect to the server.

Logs:
```
time="2023-07-18T17:46:10Z" level=warning msg="Current umask 0002 is too permissive; setting umask 0027"
time="2023-07-18T17:46:10Z" level=info msg="Starting agent with data directory: \"/var/lib/spire/data/agent\""
time="2023-07-18T17:46:10Z" level=info msg="Plugin loaded" external=false plugin_name=disk plugin_type=KeyManager subsystem_name=catalog
time="2023-07-18T17:46:10Z" level=info msg="Plugin loaded" external=false plugin_name=join_token plugin_type=NodeAttestor subsystem_name=catalog
time="2023-07-18T17:46:10Z" level=info msg="Plugin loaded" external=false plugin_name=unix plugin_type=WorkloadAttestor subsystem_name=catalog
time="2023-07-18T17:46:10Z" level=info msg="Bundle loaded" subsystem_name=attestor trust_domain_id="spiffe://example.org"
time="2023-07-18T17:46:10Z" level=debug msg="No pre-existing agent SVID found. Will perform node attestation" subsystem_name=attestor
time="2023-07-18T17:46:10Z" level=info msg="SVID is not found. Starting node attestation" subsystem_name=attestor trust_domain_id="spiffe://example.org"
time="2023-07-18T17:46:10Z" level=debug msg="Closing catalog" subsystem_name=catalog
time="2023-07-18T17:46:10Z" level=debug msg="Unloading plugin" external=false plugin_name=unix plugin_type=WorkloadAttestor subsystem_name=catalog
time="2023-07-18T17:46:10Z" level=debug msg="Plugin deinitialized" external=false plugin_name=unix plugin_type=WorkloadAttestor subsystem_name=catalog
time="2023-07-18T17:46:10Z" level=info msg="Plugin unloaded" external=false plugin_name=unix plugin_type=WorkloadAttestor subsystem_name=catalog
time="2023-07-18T17:46:10Z" level=debug msg="Unloading plugin" external=false plugin_name=join_token plugin_type=NodeAttestor subsystem_name=catalog
time="2023-07-18T17:46:10Z" level=debug msg="Plugin deinitialized" external=false plugin_name=join_token plugin_type=NodeAttestor subsystem_name=catalog
time="2023-07-18T17:46:10Z" level=info msg="Plugin unloaded" external=false plugin_name=join_token plugin_type=NodeAttestor subsystem_name=catalog
time="2023-07-18T17:46:10Z" level=debug msg="Unloading plugin" external=false plugin_name=disk plugin_type=KeyManager subsystem_name=catalog
time="2023-07-18T17:46:10Z" level=debug msg="Plugin deinitialized" external=false plugin_name=disk plugin_type=KeyManager subsystem_name=catalog
time="2023-07-18T17:46:10Z" level=info msg="Plugin unloaded" external=false plugin_name=disk plugin_type=KeyManager subsystem_name=catalog
time="2023-07-18T17:46:10Z" level=info msg="Catalog closed" subsystem_name=catalog
time="2023-07-18T17:46:10Z" level=error msg="Agent crashed" error="create attestation client: failed to dial dns:///spire-server.svc:8081: connection error: desc = \"transport: error while dialing: dial tcp 10.244.0.7:8081: connect: connection refused\""
```

In out env, the DNS record for the server may not be set up at the time agent startup, but it happens within a few seconds typically. I would like an option for the agent to indefinitely retry the connection to the server instead of crashing in this scenario. This is common in a service mesh environment, where a DNS proxy may be running alongside the agent, which provides the DNS resolution for the server DNS name.

**Comment by evan2645** [comment]
The error in the output you pasted says connection refused, which is not what I'd expect for a DNS-related error. Perhaps there's something to look into w.r.t. liveness and readiness probes?

How about a new configurable like `bootstrap_retry_timeout` where we will retry with backoff up until the configured timeout?

**Comment by shashankram** [comment]
> The error in the output you pasted says connection refused, which is not what I'd expect for a DNS-related error. Perhaps there's something to look into w.r.t. liveness and readiness probes?
> 
> How about a new configurable like `bootstrap_retry_timeout` where we will retry with backoff up until the configured timeout?

My bad, it's due to the fact that in our env the agent might not be able to access the server on startup. It's definitely not DNS related, but rather being able to not connect to the server causing the agent to crash.

The `bootstrap_retry_timeout` config seems reasonable for this scenario.
