### ISSUE TITLE
SPIRE Agent: allow to configure a bootstrap retry timeout

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#4359]
When SPIRE Agent starts and needs to go through the attestation process, connection to the SPIPRE Server may fail.
This is currently an unrecoverable error and the agent exits.

Provide a configurable `bootstrap_retry_timeout` that instructs the agent to retry (connecting to the server) with backoff up until the configured timeout.

**Comment by SilvaMatteus** [comment]
Hi @amartinezfayo,

I would be happy to implement this, if there is no one working on it yet.

**Comment by amartinezfayo** [comment]
Great, thank you @SilvaMatteus!

**Comment by amartinezfayo** [comment]
Fixed in #4597, thank you @SilvaMatteus for this contribution!
