### ISSUE TITLE
Remove dependency on key metadata files of KMS plugins

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#4375]
As part of the goal of removing server dependency on on-disk data, we need the KMS plugins to avoid having to store a file that  stores an auto-generated server ID, that's used to keep track of the keys managed by the plugin.
This file is referenced as the key metadata file by the KMS plugins.

**Comment by keeganwitt** [comment]
This ticket said metadata files. Does that mean AWS's `key_policy_file`, and GCP's `service_account_file` and `key_policy_file` don't need removed?

**Comment by amartinezfayo** [comment]
None of those configs are a required configuration, so they haven't been targeted as a primary goal to remove the dependency on disk storage for the plugins. If those configs are a problem in your use case, I suggest to explore solutions separately.

**Comment by keeganwitt** [comment]
> None of those configs are a required configuration, so they haven't been targeted as a primary goal to remove the dependency on disk storage for the plugins. If those configs are a problem in your use case, I suggest to explore solutions separately.

They're not, just confirming I understood the requirements.

**Comment by Propfend** [comment]
what is this field, btw? It is not even documented in th kms plugin page.

**Comment by sorindumitru** [comment]
@Propfend which plugin? Most plugins seem to have it, e.g. key_identifier_file or key_identifier_value in https://github.com/spiffe/spire/blob/main/doc/plugin_server_keymanager_aws_kms.md. If it's not documented it is not required, e.g. in the memory or disk plugins.

**Comment by Propfend** [comment]
and how about `key_metadata_file`? If it does not exist anymore, then consider removing it from documentation so it wont lead to misinformation:

https://github.com/spiffe/spire/blob/v1.14.1//doc/plugin_server_keymanager_aws_kms.md#basic-configuration
