### ISSUE TITLE
BatchCreateEntry does not allow specifying an entry id

### ISSUE THREAD

**Issue by sorindumitru** [spiffe/spire#4380]
It would be useful to be able to specify the entry id when creating registration entry through the API or the CLI. Currently this an automatically generated UUID, but I see any reason why it couldn't also allow the caller to specify it. This would simplify entry management in some cases, since you no longer need to keep track ofthe entry id generated at creation to be able to easily update an entry.

The easiest way to do that would be to not generate an UUID when EntryId is not empty. It may present an upgrade issue in case someone has some random, non globally-unique, data in there, but I think that should be rare so maybe a note in the release would be enough. If we want to be certain we don't break anything, we can log an error for a release so users will be notified about it.

* **Version**: all
* **Platform**: all
* **Subsystem**: server

**Comment by edwbuck** [comment]
assign to me

**Comment by edwbuck** [comment]
In conversation with Sorin, this request is to enable the easier management of SPIRE Entries across multiple SPIRE clusters.

The API should still take a valid UUID, and should fail on non-valid UUIDs to ensure data consistency.  Currently the code doesn't use the UUID as anything other than an identifying string; and, checks at the request level that a valid v4 UUID would ensure data homogeneity.

A review of the code indicates that the v4 UUID is only an identifier, and once set, the only exposure of it is as a stable ID for subsequent calls that permit the modification of other entry attributes.

There are no technical reasons why we are enforcing that a SPIRE server is the sole generator of the Entry UUID, and in the fault tolerant deployments, we already have multiple SPIRE servers generating the UUID without coordination, relying on the large key space to avoid collisions.

We should move forward with this request or document the technical reasons why denying it is an issue so we can establish a policy around EntryID UUIDs.

**Comment by edwbuck** [comment]
Per maintainer decision, this change will move forward.

During the discussion, the shape of the data in the ID field was considered, and the maintainers feel that a UUID may be too constrictive.  For this reason, any arbitrary string of 255 characters will be permissible; provided that every character is limited to a subset of characters (letters, underscores, numbers) similar to other locations where we limit characters to prevent SQL injection attacks.

**Comment by mjptree** [comment]
I'd like to work on this one.

**Comment by edwbuck** [comment]
@mjptree I'll get clarity on the constrained character set.  My commentary on the limited character set was meant to be an example character set, not the actual limited character set implementation.

**Comment by azdagron** [comment]
Thanks for volunteering to take this on @mjptree. We can think about the character set for a bit and come back with the acceptable set.

**Comment by azdagron** [comment]
Ok, I think we're good with the following, `a-z`, `A-Z`, `0-9`, dots, dashes, and underscores. And outside of that no extra shape validation (e.g. leading underscore is ok).
