### ISSUE TITLE
spire-{server,agent}: add support for reconfiguration

### ISSUE THREAD

**Issue by sorindumitru** [spiffe/spire#4390]
It would be helpful if spire-server/spire-agent had some support for reconfiguration, particularly for the plugins. These are already expected to be able to reconfigure so it sounds like something like that was in mind when designing the plugin system.

An example where this would be helpful is a spire-server instance servicing multiple k8s clusters, with k8s_psat node attestation. If I want to add a new k8s cluster to the trust domain, I have to update the configuration and restart spire-server for that change to take affect. It would be better if I can make that change without affecting any agents connected to the spire-server instance.

This could be triggered in the following way:
* A SIGUSR1 signal sent to spire-server/spire-agent
* An RPC, for environments where signals are not the best option, e.g. k8s. I don't think there's a good place for this particular RPC at the moment but it could be a new `server`/`agent` endpoint with `Reconfigure` RPC.

Not everything is easy to reconfigure so maybe it's best to limit this to the plugins?

* **Version**:  any
* **Platform**: any
* **Subsystem**: spire-server, spire-agent

**Comment by sorindumitru** [comment]
Happy to implement this myself if there's consensus that it's the right direction to go with.

**Comment by amartinezfayo** [comment]
Thank you @sorindumitru for filing this issue.
Reconfiguration of SPIRE is something that we have considered in the past.
As you also point, I think that the main challenges are related with the SPIRE Server and SPIRE Agent specific configurations. All the plugins should already support changes in configuration while they are loaded. I think that we can limit the scope of this implementation to reconfigure plugins.

Thank you also for volunteering to work on this. I personally think that we just need to get consensus in the maintainer's team about the approach that we want to take for the implementation. I'll comment here once we have an implementation plan.

**Comment by amartinezfayo** [comment]
@sorindumitru This has been addressed in #5165, I'm closing this. Please re-open if that doesn't solve your use case.
