### ISSUE TITLE
spire-agent: signature check attempts limit reached while verifying certificate chain

### ISSUE THREAD

**Issue by sorindumitru** [spiffe/spire#4415]
I find myself in the following predicament:
```
Agent crashed error="create attestation client: failed to dial dns://spire-server:443: context deadline exceeded: connection error: desc = \"transport: authentication handshake failed: x509svid: could not verify leaf certificate: x509: signature check attempts limit reached while verifying certificate chain\""
```

What’s happening there is that we run into a [crypto/x509 limit](https://cs.opensource.google/go/go/+/refs/tags/go1.20.7:src/crypto/x509/verify.go;l=896). It limits how many signature checks are allowed to happen to validate a certificate, most likely to avoid DoS attacks.

The verification of a certificates starts of against the [root certs](https://cs.opensource.google/go/go/+/refs/tags/go1.20.7:src/crypto/x509/verify.go;l=945) and then the intermediates. For the spire-server certificate that means we first try to build a chain with the root certs and then with an intermediates (e.g. if we have an UpstreamAuthority). `findPotentialCandidates` will try to lookup candidates by the [Issuer field of the certificate](https://cs.opensource.google/go/go/+/master:src/crypto/x509/cert_pool.go;l=133). In the case of SPIRE all roots have the same Subject (so same Issuer for certs issued by them). So all roots are potential candidates. When we have >100 CAs in the trust bundle we hit that 100 signature checks limit and fail.

Getting into this situation depends a bit on number of spire-server instances, ca TTLs, upstream authorities. Those can be tuned a bit to avoid getting into this situation, but I don't think there's any way to guarantee you can avoid it. You're also likely to hit the issue in uncomfortable situations, e.g. scaling a deployment horizontally to deal with increased load. We should try to do something about it.

A way to fix it is to make sure that each self-signed CA issued by SPIRE has an unique Subject. For example it could include the serial number or some other attribute, similar to what has been done for X509-SVIDs in https://github.com/spiffe/spire/issues/3341. From what I can tell from that the X.509 RFC seems to be ok, there's no restriction on what the Subject of the CA needs to be.

* **Version**: 1.7.1 (but I guess that it applies for most/all older versions of SPIRE)
* **Platform**: any
* **Subsystem**: agent,server

**Comment by azdagron** [comment]
We haven't really seen those kinds of limits being hit before (outside of a buggy situation where a self-signed server was in a crash loop and filled the bundle). I'm curious if this was encountered as part of a "stress" exercise or if the combination of number of SPIRE servers and CA TTLs that would produce a bundle this big is being planned for a production deployment.

Either way, I think it's reasonable for us to figure out a way around this, possibly through introducing some randomness into to the CA. There are some concerns here for backcompat on our existing CA subjects, so it may need to be opt-in.

**Comment by sorindumitru** [comment]
This was a test deployment I was toying around with which had short TTLs (2 hours for the CAs) and 4 instances running. I'm not concerned about it from this regard, I'm more worried about those buggy situations you mentioned or if I need to increase the number of instances.

**Comment by sorindumitru** [comment]
With regards to backcompat, is it about users hard coding/expecting a specific subject for the CAs or is it something else?

It sounds reasonable to be opt-in, but we should probably think ahead towards making it the default after a few releases or even removing the option completely (my preference). I think it's the behaviour that most people would want:
* You don't get any surprises if the trust bundle grows too big.
* Establishing TLS connections is faster since you wouldn't have to do an O(n) search to find the right CA to chain up to.

**Comment by sorindumitru** [comment]
@azdagron I've done some tests to see how the number of CAs that are part of the bundle affects the TLS handshake time. With spire-server using self-signed CAs it looks like every other 10 CAs that are part of the trust bundle adds 1 millisecond to the time it takes to connect and do the TLS handshake. Using https://gist.github.com/sorindumitru/c3a3e445e247258a0a6332508f1826da doing 1024 connections + handshakes against a local server takes:
0.9s - 1 CA
2s - 10 CAs
3s - 20 CAs
4s - 30 CAs

So even when having a smaller number of CAs in the trust bundle it still has a noticeable impact.

Using the following change to make each CA Subject is unique:
```
diff --git a/pkg/server/credtemplate/builder.go b/pkg/server/credtemplate/builder.go
index bfab7999..61e1f6bd 100644
--- a/pkg/server/credtemplate/builder.go
+++ b/pkg/server/credtemplate/builder.go
@@ -355,6 +355,7 @@ func (b *Builder) buildX509CATemplate(publicKey crypto.PublicKey, parentChain []
        }

        tmpl.Subject = b.config.X509CASubject
+       tmpl.Subject.SerialNumber = tmpl.SerialNumber.String()
        tmpl.NotBefore, tmpl.NotAfter = b.computeX509CALifetime(parentChain, ttl)
        tmpl.KeyUsage = x509.KeyUsageCertSign | x509.KeyUsageCRLSign
        tmpl.IsCA = true
```

I can see that time to connect+handshake starts stabilising around 1s (1.02-1.06) regardless of how many CAs I have in the bundle (only tested to ~40 CAs).

**Comment by edwbuck** [comment]
@azdagron Can we ensure this is mentioned in the contributors meeting.  This finding seems to use a combination of settings that would harm SPIRE availability.

**Comment by sorindumitru** [comment]
It is currently possible to work around this issue with the existing configuration options, by specifying an unique (or at least sufficiently diverse) name for each spire-server in `ca_subject` configurable. But it's not something that is easily discoverable.

Maybe having a spire-server identifier for each instance would be another way to solve the issue? That could automatically be populated in `ca_subject` somewhere. spire-server already needs this kind of identifier for some of the key managers (e.g. https://github.com/spiffe/spire/blob/main/doc/plugin_server_keymanager_gcp_kms.md#management-of-keys).

**Comment by edwbuck** [comment]
@azdagron Can we see if we can discuss this on Tuesday?  Even with the workaround which mitigates the problem, we probably should limit the conditions that raise this problem.

**Comment by azdagron** [comment]
Yes, let's bring this up on Tuesday. I'll also ping the other maintainers async to see if we can come to consensus beforehand.

**Comment by edwbuck** [comment]
As SPIRE doesn't know which of the keys are still active, it's hard to identify keys that are no longer in use.

The current solution being considered is to add a unique identifier to the certificate name to prevent the golang libraries from complaining.

**Comment by edwbuck** [comment]
@azdagron Since we now have a solution approach, can you remove the unscoped label?

**Comment by azdagron** [comment]
Yep. What we have settled on is replicating the serial number into the subject, as @sorindumitru suggested earlier:

> tmpl.Subject.SerialNumber = tmpl.SerialNumber.String()

Further, we should also provide a new configurable that can revert back to the old behavior and keep that for at least one minor release, in case there is a backcompat issue.
