### ISSUE TITLE
Allow SPIRE-Server to work in all AWS partitions

### ISSUE THREAD

**Issue by achaurasiaConfluent** [spiffe/spire#4423]
Current SPIRE Server `aws_iid` nodeattestor plugin assume that the role is in partition `aws`.
Due to current implementation https://github.com/spiffe/spire/blob/0527653971f1e32a8615d33f3203bc7dfb1cfda0/pkg/server/plugin/nodeattestor/awsiid/client.go#L80-L82
spire would only work in `aws` partition.

Refer https://docs.aws.amazon.com/IAM/latest/UserGuide/reference-arns.html
for aws partition and arn format.
 

* **Version**: 1.7.0
* **Platform**:  any
* **Subsystem**: Server node attestor plugin

**Comment by MarcosDY** [comment]
Done
