### ISSUE TITLE
Is it possible to prevent agents from being authorized to request SVIDs for 'node alias entries'?

### ISSUE THREAD

**Issue by sebastianGit** [spiffe/spire#4426]
Is it possible to prevent agents from being authorized to request SVIDs for 'node alias entries', such that the agent is only authorized to retrieve an agent SVID for itself and workload SVIDs that it will also make available via workload API?

---

**Example use case:** All processes that are executed with the user 'test-user' running in VMs in the GCP project with project-id p-123 are authorized to use SVIDs with the SPIFFE ID `spiffe://trust.domain/workload`. The example use the `gcp_iit` plugin for node attestation.

Registration entries are setup as follows:

Node alias entry:
```
Entry ID         : abc
SPIFFE ID        : spiffe://trust.domain/node_alias
Parent ID        : spiffe://trust.domain/spire/server
Selector         : gcp_iit:project-id:p-123
```
Workload entry:
```
Entry ID         : dcf
SPIFFE ID        : spiffe://trust.domain/workload
Parent ID        : spiffe://trust.domain/node_alias
Selector         : unix:user:test-user
```
Agent entry (created after the node attestation of a SPIRE agent running on a node in project p-123 has been successful):
```
SPIFFE ID         : spiffe://trust.domain/spire/agent/gcp_iit/project-123/<instance-id>
Attestation type  : gcp_iit
Selectors         : gcp_iit:instance-name:<instance-name>
Selectors         : gcp_iit:zone:<gcp_zone>
Selectors         : gcp_iit:project-id:project-123
```

**Expectation: Spire agent requests ONE SVID** after successful attestation with the SPIFFE ID `spiffe://trust.domain/workload`

**Observation: Spire agent requests TWO SVIDs** after successful attestation one with the SPIFFE ID `spiffe://trust.domain/workload` and one with the SPIFFE ID `spiffe://trust.domain/node_alias`.

---

**Question:** Is it possible to prevent agents from being authorized to request SVIDs for 'node alias entries', e.g. in such a way that an agent only gets back the 'workload SVIDs' from 'getAuthorizedEntries', but not the SVID of the 'node alias' entry? E.g. this might require to be able to exclude the SPIFFE IDs of the node alias entries from the `authorized entries`.

**Background:** In my use case, the 'node alias SVID' is clearly not required. It is also unclear to me whether the 'node alias SVID' is of  of any use at all, as it cannot be made available via workload API given its selectors. On the other hand, considering SVIDs (certificates and private keys) as security relevant objects, I would be happy to reduce issuing / requesting certificate objects to the minimum.

* **Version**: 1.6.x (likely any)
* **Platform**: any
* **Subsystem**: SPIRE server

**Comment by azdagron** [comment]
Hey @sebastianGit, thanks for opening this. We've considered a few times whether or not to change this behavior over the years. Conceptually, the agent has authorized for the SPIFFE ID of the alias, but you are 100% correct that there are no existing use cases where an SVID over that SPIFFE ID is put to use.

My personal opinion is that we should no longer return the alias as an authorized entry. I'll sync up with the other maintainers and see if there are concerns and get back to you.

**Comment by sebastianGit** [comment]
@azdagron : Thanks for supporting this topic. It would be great, if it will possible to prevent those SVIDs from being successfully requested/created!

**Comment by sebastianGit** [comment]
Thanks for addressing the topic this fast!
