### ISSUE TITLE
Provide the ability to disable JWT-SVID support in SPIRE

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#4473]
There are some scenarios where JWT-SVID support is not needed, and servers could avoid having to maintain JWT authorities and the rotation of JWT keys.

There is consensus that having the ability to disable JWT-SVID issuance in SPIRE would be a good thing to have, but we need to find answers to some open questions before starting the implementation.

- The [SPIFFE Workload API](https://github.com/spiffe/spiffe/blob/main/standards/SPIFFE_Workload_API.md) standard mandates that both the X.509-SVID and the JWT-SVID profiles must be supported by SPIFFE implementations, but operators may disable a specific profile in their deployment. This means that there is no limitation from the spec perspective. But the error code in case that a profile is disabled is not defined by the specification. We need to address that at the specification level.
- Name and semantic of the config setting to be added in the server (e.g.: disable_jwt defaulting to false vs enable_jwt defaulting to true).
- How is this handled by agents? Servers can inform agents about the disabled profiles. Requests to the Workload API related with the JWT-SVID profile should return the code defined by the specification.
- What's the behavior in nested SPIRE deployments? The error code returned should be consistent across SPIRE.
- Considerations when federating with other trust domains. Define the behavior when validating JWT-SVIDs.

**Comment by nikotih** [comment]
Hi @amartinezfayo 

i see this issue got auto-closed. We would still benefit from disabling JWT in spire server. 

Specifically our use case is: we use AWS PCA upstream authority which does not support JWT in the first place
https://github.com/spiffe/spire/blob/main/pkg/server/plugin/upstreamauthority/awspca/pca.go#L310

There is already a warning printed during startup:
time="2025-06-02T13:29:18Z" level=warning msg="UpstreamAuthority plugin does not support JWT-SVIDs. Workloads managed by this server may have trouble communicating with workloads outside this cluster when using JWT-SVIDs." plugin_name=aws_pca subsystem_name=ca_manager

As a workaround we have made AWS PCA return empty JWT keys instead 
```
func (p *PCAPlugin) PublishJWTKeyAndSubscribe(_ *upstreamauthorityv1.PublishJWTKeyRequest, server upstreamauthorityv1.UpstreamAuthority_PublishJWTKeyAndSubscribeServer) error {
	return server.Send(&upstreamauthorityv1.PublishJWTKeyResponse{
		UpstreamJwtKeys: []*types.JWTKey{},
	})
}
```

Can we have some intermediate solution and either have AWS PCA return no keys or spire core not generate JWT if it has single upstream plugin with no support for JWT?
