### ISSUE TITLE
Improve unit testing in pkg/agent/client package

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#4474]
The unit tests in `pkg/agent/client` are missing assertions on log messages when the API calls to SPIRE Server fail to ensure they contain the gRPC status and error details.

**Comment by MeenuyD** [comment]
I would like to work on this issue can you guide me how to get start

**Comment by rturner3** [comment]
In #4262, which introduced some changes to log gRPC status message and error code, we noticed that there are not many verifications of log entries in unit tests in the `github.com/spiffe/spire/pkg/agent/client` package. We do log-based assertions in unit tests for most other parts of the code base using functionality from the `github.com/spiffe/spire/test/spiretest` package in [logs.go](https://github.com/spiffe/spire/blob/main/test/spiretest/logs.go), see [example](https://github.com/spiffe/spire/blob/fd3f79b59bf5178900f78ead949b6a3fefe278eb/pkg/server/api/agent/v1/service_test.go#L240).

The desired outcome from this issue is that the unit tests in `github.com/spiffe/spire/pkg/agent/client` include assertions on all log entries, including both messages and log fields.

**Comment by rturner3** [comment]
@MeenuyD Let us know if this is still something you're interested in taking on. Happy to answer any further questions if anything is still unclear.

**Comment by MeenuyD** [comment]
I am interested in contributing can you tell me should I have to log in for all the entries?

**Comment by rturner3** [comment]
I'm not sure I fully understood your question, but ideally the unit tests would contain assertions for all log statements emitted from the code in the `github.com/spiffe/spire/pkg/agent/client` package.

**Comment by rturner3** [comment]
Also, thank you @MeenuyD for volunteering! I have assigned this issue to you for now.

**Comment by sword-jin** [comment]
Seems @MeenuyD is busy recently, I'm glad to start this ticket.

**Comment by azimt** [comment]
this issue needs to be closed as completed. @rturner3
