### ISSUE TITLE
Zero out ram holding security materials upon disposal

### ISSUE THREAD

**Issue by edwbuck** [spiffe/spire#4516]
To ensure that secure materials are not leaked through page file / swap read attacks, or even after they are no longer necessary (post rotation), the memory pages holding these materials should be locked and zeroed.

Locking the RAM (mlock) prevents the RAM from being swapped to page files or swap partitions, where one could attempt an attack of reading the RAM in its pages / swapped form.  With the data ensured to exist in RAM only, zeroing based destruction of the data (explicit overwriting with zeros or garbage), ensures that the only copy of the item in RAM is fully destroyed and not freed in ways that dereference it but still (due to compiler optimizations) holds the data it previously held.

This feature was aske for in the go upstream https://github.com/golang/go/issues/18645 and the commentary provides a good introduction to the challenges.  To implement this, we would need:

- To manage a subset of the RAM containing sensitive items with mmap.
- To ensure that item creation and deletion are explicitly managed through an API that has deletion overwrite the RAM.
- To ensure that we can later discard the slab of RAM for clean shutdown

**Comment by sorindumitru** [comment]
One easier, the probably covers fewer issues, something like https://github.com/hashicorp/go-secure-stdlib/blob/main/mlock/mlock_unix.go could be used to lock all memory in handle. They are UNIX only, but that's most deployments out there so it might be worth doing.

It would be nice to also do something like `madvice(MADV_DONTDUMP)`, but I couldn't find something like that for go. I imagine the GC would make it hard to implement.

**Comment by evan2645** [comment]
The referenced upstream issue https://github.com/golang/go/issues/18645 is over 6 years old - has there been any movement upstream since then? More up-to-date information on what's available there will greatly help us in navigate this

**Comment by mjptree** [comment]
The https://github.com/golang/go/issues/18645 issue actually references another implementation that tries to solve the same problem (and some others): https://github.com/awnumar/memguard

The author has implemented the relevant page allocation and locking calls for Unix, MacOS, and Windows in a separate library: https://github.com/awnumar/memcall

**Comment by evan2645** [comment]
Thanks @mjptree for the pointer - I had noticed this link at the bottom of the issue but was wondering about the current thinking around support for this kind of thing in upstream Golang

@edwbuck which keys explicitly were you hoping to cover with this change? It would be helpful to have a couple examples of attacks we're trying to mitigate so we can make sure there are no other spots that would need attention

**Comment by edwbuck** [comment]
A quick review indicates that memguard or memcall are the only two viable solutions.

@evan2645 I agree that the materials to be protected have not been identified.  The originator's initial idea included "cryptographic materials"

Candidates include:

- the keys that are managed by the key manager plugin.
- the server key.
- the agent keys.
- the workload keys (so we can limit the exposure to only the workload keys being sent to workloads at the moment).

**Comment by evan2645** [comment]
I think this is going to boil down to a decision on whether we want to switch the handling of these keys over to one of the libraries you mentioned. Gaining some understanding of their stability, maintenance, and adoption would help in making that decision. Ideally there would be an upstream solution, which is why I was asking about that, it would be a lot easier to just accept.

I think this is generally good hygiene and we should do it if the cost/benefit works out, where cost is both maintenance overhead and risk
