### ISSUE TITLE
Cannot pull spire docker images

### ISSUE THREAD

**Issue by nsvijay04b1** [spiffe/spire#4602]
Cannot pull docker images from SPIFFE project later than 1.5.6 tags.

Can pull image until 1.5.6.

Tried pulling 1.6.0, 1.8.1, 1.8.2 & latest tags, all failed to download.

Tried using anonymous and also with docker login using PAT.

Is there any change recently the way images can be downloaded?

-bash-4.2$ **docker pull ghcr.io/spiffe/spire-server:1.8.2@sha256:642862f66e18e0a9f30260be8a5e732af430b1f0387a20161e235e35486148b8**
Trying to pull repository ghcr.io/spiffe/spire-server ...
**manifest for ghcr.io/spiffe/spire-server@sha256:642862f66e18e0a9f30260be8a5e732af430b1f0387a20161e235e35486148b8 not found**

**-bash-4.2$ docker pull ghcr.io/spiffe/spire-server:1.8.2**
Trying to pull repository ghcr.io/spiffe/spire-server ...
Pulling repository ghcr.io/spiffe/spire-server
**Error: image spiffe/spire-server:1.8.2 not found**

**-bash-4.2$ docker pull ghcr.io/spiffe/spire-server:1.5.6**
Trying to pull repository ghcr.io/spiffe/spire-server ...
1.5.6: Pulling from ghcr.io/spiffe/spire-server
67f7cc3b27fd: Pull complete
e9f8d8ba6cc9: Pull complete
894e39c91664: Pull complete
552f7c8d7046: Pull complete
Digest: sha256:aa3238742a60a13f00c3a0e4a19cd0900b9c2f5568c58136f075b8727883912a
**Status: Downloaded newer image for ghcr.io/spiffe/spire-server:1.5.6**

* **Version**: 1.6.0 and above cannot be pulled.
* **Platform**:  redhat linux 
* **Subsystem**: docker pull images failed

**Comment by nsvijay04b1** [comment]
Did anyone faced this or is it only us?

Surprised at no one even mentioned it before where a lot of images could not be pulled.

Are we pulling it wrong?  Please advise.

**Comment by azdagron** [comment]
Works fine for me?

```
$ docker pull ghcr.io/spiffe/spire-server:1.8.2
1.8.2: Pulling from spiffe/spire-server
eb8cf996025f: Pull complete 
ce667b5727c1: Pull complete 
da4606e1f327: Pull complete 
0929a1781500: Pull complete 
Digest: sha256:7d5367f39091d8e12c5487e9f68e997fba744ebec2f561376f7acae250d35b1d
Status: Downloaded newer image for ghcr.io/spiffe/spire-server:1.8.2
ghcr.io/spiffe/spire-server:1.8.2
```

**Comment by nsvijay04b1** [comment]
@azdagron  Thanks for the clue about docker version.

Docker client upgraded and also found it was pointing to old proxy which we recently decommissioned, after fixing proxy it started working.

Able to download 1.8.2.

Sorry if wasted yours time, Thank you. I will mark it as closed,

**Comment by azdagron** [comment]
Glad you have it working!
