### ISSUE TITLE
Allow unauthenticated callers of FetchX509Bundles/FetchJWTBundles to fetch federated trust bundles

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#4619]
Consider an environment where SPIRE is already deployed, but not all workloads have registered entries. For example, there may be some legacy orchestration platforms where SPIRE integration does not exist and where it is not practical to extend SPIRE support. All workloads in this environment need to be able to verify identities from a federated trust domain, even some which may not be part of the trust domain for the SPIRE deployment. It would be convenient to reuse the SPIRE control plane for federated bundles to these unattested workloads.

SPIRE Agent allows unauthenticated callers of `FetchX509Bundles` and `FetchJWTBundles` to obtain the trust domain of the agent. However the agent doesn't allow unauthenticated callers to fetch federated bundles. Currently distribution of federated trust bundles is tied to entries and can't be globally distributed in a deployment without specifying the federation relationship on all workload entries. #2272 discusses this related problem.

It would be convenient to leverage the existing bundle distribution control plane built into SPIRE for this use case to avoid having to build a parallel solution.

**Comment by evan2645** [comment]
Sounds like this will be dependent on #2272 - when "global bundles" are set on SPIRE Server , all workloads (including unauthenticated callers) receive them. Otherwise, unauthenticated callers receive the local bundle only, matching registered workload behavior
