### ISSUE TITLE
spire-agent: move "reattest_to_renew" to the main configuration

### ISSUE THREAD

**Issue by sorindumitru** [spiffe/spire#4658]
I noticed that my agents only renew their SVIDs, they don't do attestation even if the plugin specifies that it can reattest. There is a [feature flag](https://github.com/spiffe/spire/blob/0eb560833f76a2bf2a9436e6fefca392f656e8f4/pkg/common/fflag/fflag.go#L39) to make reattestation the default where possible.

This is hard to discover so it would be nicer if this was an actual configuration or at least documented somewhere. It would also be a bit nicer if it was the default, I don't know if there's anything preventing us from doing that, but if there is we should fix it.

Assuming that feature flags are supposed to be temporary, it would be good if they were documented somewhere along with details about what it would take for them to be made the default.

* **Version**: > 1.4.2
* **Platform**: any
* **Subsystem**: agent

**Comment by azdagron** [comment]
Feature flags in the SPIRE project are more intended as "developer feature flags" and used to enable complex changes to be broken up into multiple bodies of work without affecting other functionality. Once a feature is "complete" and received some initial testing to make sure it is behaving, we usually graduate them and remove the feature flag. Sometimes, if we still aren't comfortable, they move to an "experimental" flag that we document and make available for deployments to try out.

This feature never had that last mile testing to see if it was "complete" so we could graduate it and we dropped the ball on having doing that and never graduated it. If somebody can give this a run and observe that it behaving ok, then we can probably convert it into a documented experimental flag until we get some real evidence that it is behaving well at scale over a longer period.

**Comment by faisal-memon** [comment]
Would love to move this one out of feature flag state. We developed it hoping to use it at HPE but ended up not being used.

**Comment by sabrinabs** [comment]
Hello Everyone. I coincidentally tested the functionality just now, and the feature flag worked as expected. The reattestation took place, and I confirmed it by adding logs to the code where the attestation occurs.

**Comment by sabrinabs** [comment]
I'm interested in contributing to integrating this configuration into the main code. To demonstrate its effectiveness, I conducted a test using a built-in SPIRE plugin. I'll share the results in this discussion.

I chose the x509pop plugin to test, incorporating log messages at both the start and conclusion of the attestation
![Screenshot from 2023-11-19 20-01-17](https://github.com/spiffe/spire/assets/84942072/b0029380-994d-4bed-8f46-28da1f144f4e)

Following instructions, I included the feature_flag in the agent configuration.
![Screenshot from 2023-11-19 20-06-00](https://github.com/spiffe/spire/assets/84942072/2490622e-299d-4379-86ee-25526c11d77c)

After running both the server and agent, I confirmed that the attestation occurred again during the SVID rotation by checking the logs.
![Screenshot from 2023-11-19 20-10-51](https://github.com/spiffe/spire/assets/84942072/270127be-5ea8-4f43-bb9b-237bc77b644d)

I am available to conduct additional tests. Please let me know if there are specific preferences or guidelines.

**Comment by evan2645** [comment]
I've had a look at the history of this flag and its implementation, and it feels safe to move to this as default behavior. IIRC that was the intention anyway.

I don't immediately see any steps we can take to further de-risk the move to default behavior. We can move the flag to experimental (out of feature flag) but it would functionally be the same. We can ask users to test it more rigorously, but we can also do that with it existing as a feature flag in the current state.

If there is a specific condition we're worried about, we can try to detect it and log, but I can't think of any. So I think the next step here is to move this to default behavior, optionally with more rigorous testing first

**Comment by evan2645** [comment]
Since it's an important change in behavior, we should do it on a major release

**Comment by evan2645** [comment]
Hey @faisal-memon we're planning 1.9.0 release and wondering how long it will be until you're able to have a look here?

**Comment by faisal-memon** [comment]
@evan2645 hah good timing, just started working on it.
