### ISSUE TITLE
apparent connection leak in agent linux peertracker

### ISSUE THREAD

**Issue by zmt** [spiffe/spire#4665]
We received an escalation from an infrastructure team regarding spire-agent unresponsive refusing all connections due to too many open file descriptors. In our triage, we observed that it appeared to be:
* a few processes requesting many connections
* spire agent accepting those connections
* spire agent not closing those connections upon detection of suspected exit of pid being tracked for attestation
* spire agent hitting our file descriptor ulimit and no longer accepting inbound connections

On an affected host, there were numerous open STREAM connections on the spire agent socket associated with only a few PIDs. We then found numerous logs with "Caller exit suspected due to failure to get starttime" message associated with those same PIDs. We tracked the log message to This code path: https://github.com/spiffe/spire/blob/v1.6.4/pkg/common/peertracker/tracker_linux.go#L123-L135

It appears that when that error is returned from `IsAlive()`, [Close()](https://github.com/spiffe/spire/blob/main/pkg/common/peertracker/tracker_linux.go#L88-L98) is not called on the `linuxWatcher` so the file descriptor is not closed.

We also noticed a 4-year-old todo to revisit the process exit detection mechanism: "TODO: Evaluate the use of `starttime` as the primary exit detection mechanism." Perhaps this is a sign that we should revisit this TODO while here.

Unfortunately, we do not yet have a trivial repro. The theory is that _something_ is requesting numerous connections at once, repeating in a rapid crashloop, triggering the starttime exit detection code path, and the agent is leaking those connections. We have yet to verify this theory through direct observation.

* **Version**: v1.6.4
* **Platform**: linux
* **Subsystem**: agent

**Comment by azdagron** [comment]
It would be good to understand the underlying behavior that caused this.

Regardless, if there is a clear leak, we should plug that.

**Comment by zmt** [comment]
There may be little we can do here to thwart a malicious caller exhausting file descriptors associated with grpc connections. We can close the file descriptor watching the proc info when `IsAlive` fails, which should slow hitting the file descriptor ulimit, but we cannot prevent the bad actor from continuing to aggressively attempt to reconnect even if we force-close the connection grpc server side in the Agent.

**Comment by zmt** [comment]
Perhaps it would be a better tradeoff to limit the concurrent connections on the listener to some count below the hard file descriptor limit so that it would stop responding during an event, but not run out of file descriptors so could theoretically recover.
