### ISSUE TITLE
Introduce a gauge metric for the spire-server entry cache size

### ISSUE THREAD

**Issue by stevend-uber** [spiffe/spire#4720]
It would be valuable for spire users to be able to easily query how large in-memory cache size is at a metric's glance over time.

**Comment by edwbuck** [comment]
What units are you expecting? (size in number of entries, size in bytes / kb, etc.)

**Comment by azdagron** [comment]
Seems very reasonable to add a bunch of metrics around the internal cache details.

**Comment by stevend-uber** [comment]
Off the top of my head: 
* Entry Counts
* Size in bytes

**Comment by edwbuck** [comment]
Let's extend this to include missing event gauge

**Comment by stevend-uber** [comment]
@azdagron You can assign this issue to me. I think I can get to this in July :)

**Comment by azdagron** [comment]
Super! Thanks, @stevend-uber !
