### ISSUE TITLE
Event-Based Cache Hydration should Paginate on StartUp

### ISSUE THREAD

**Issue by stevend-uber** [spiffe/spire#4735]
Similar to https://github.com/spiffe/spire/issues/4488, right now, event-based cache hydration's initial startup behavior does not paginate on startup. This will result in timeouts on startup for large entry count spire-db's. We should add pagination to this call. https://github.com/spiffe/spire/blob/5ccf55fab31ed87e61f740fc319571d53f08682b/pkg/server/endpoints/authorized_entryfetcher.go#L203C17-L203C17

**Comment by azdagron** [comment]
Yes, agreed. Both registration entries and attested node loading could benefit for paged hydration.

**Comment by faisal-memon** [comment]
Good catch, please assign this to me.
