### ISSUE TITLE
Permissions and documentation

### ISSUE THREAD

**Issue by grittershub** [spiffe/spire#477]
* **Version**: 0.5.1 from tarball

Permissions in the README.md recommend chmod -R 777 - suggest these be changed to 644 or lower.

First time spire-server execution with the default config from tarball requires .data/datastore.sqlite3 to be writeable, but neither the directory nor db exist. Took a few attempts and then perm changes to fix as there wasn't any documentation on how/if this file should exist.

**Comment by evan2645** [comment]
Thank you for the report @grittershub 

Please see https://github.com/spiffe/spire/pull/476 - documentation update for creating .data directory

also see https://github.com/spiffe/spire/pull/478 - adding .data directory to the tarball. this should take effect after the next release

I am not sure why the chmod is there to begin with. Perhaps @kunzimariano can shed some light on that. Ideally, we shouldn't need it at all. If you or anyone else would like to test whether this step is required, a PR would be welcome.

**Comment by azdagron** [comment]
Ideally the tarball has the right permission set on the contents and we extract with `-p` to preserve those permissions. I think we should remove the chmod from the instructions.

**Comment by anvega** [comment]
This has been long time since this was fixed and removed from README.md.
