### ISSUE TITLE
Per-SVID Type Agent cache tuning.

### ISSUE THREAD

**Issue by edwbuck** [spiffe/spire#4794]
For each SVID type, an independent tuning of the Agent Cache should be exposed to the user.

This permits one to devise different cache tuning approaches for the different SVID types, for example, one could specify a different cache size for x509 SVIDs and JWT SVIDs, and potentially different caching policies.  This could be achieved with different caches in the Agent, or complex policies applied to the main Agent cache. 

To reduce the configuration complexity, perhaps the presence of a SVID-Type cache tuning parameter would raise configuration errors if the overall cache tuning parameters are also set.

**Comment by edwbuck** [comment]
To clarify, this is a call to make the SVID cache prefetch JWT SVIDs for a limited number of times, permitting bulk JWT SVID updates (for fast delivery of JWT SVIDs) using bulk requests, to warm the cache prior to the Workload using the Workload API from stalling on requests when the JWT SVID requires re-generation with the same audience shortly after the audience was previously used.

**Comment by amartinezfayo** [comment]
Closing in favor of the more specific approach in #4829.
