### ISSUE TITLE
Unconditionally populate/prune events data irrespective of experimental cache flag value

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#4813]
The experimental event-based cache flag currently gates population/pruning of the events table. Unfortunately this means that you cannot have a mixed deployment of servers with new servers where the feature is enabled and those where it is not (or old servers that don't have the feature at all). The consequence of mixing servers is that flag-enabled servers do not observe changes to entries/agents made by other servers, causing an incorrect authorized entry view for agents connected to the flag-enabled servers.

This breaks rolling upgrade of servers as well as mixed deployment testing.

The former is particularly heinous when considering the upgrade between 1.9.0 and (hopefully) 1.10.0 when this feature is enabled by default.

As such, the 1.9.0 release should unconditionally populate and prune the events data, irrespective of whether or not the events-based cache is utilized.

**Comment by faisal-memon** [comment]
@azdagron you can assign this to me

**Comment by azdagron** [comment]
Awesome. Thanks @faisal-memon .

**Comment by evan2645** [comment]
Just to double check, the migrations needed to put the tables down for these events .. it shipped in 1.7 ?

**Comment by faisal-memon** [comment]
@evan2645 1.7.2 https://github.com/spiffe/spire/pull/4379
