### ISSUE TITLE
Handle `DynamicUser` in the unix workload plugin.

### ISSUE THREAD

**Issue by immutableT** [spiffe/spire#4834]
The issue is applicable to environments where the spire agent is running under `systemd`, and the service is configured to dynamically create users (see a minimal unit file below, specifically `DynamicUser=yes`).
Concretely, (under the above conditions) the call to `user.LookupId` fails, because `systemd` does not create records in the `/etc/passwd`, and this is the logic used by the `LookupId` function (see https://github.com/spiffe/spire/blob/main/pkg/agent/plugin/workloadattestor/unix/unix_posix.go#L105).
 
**Note**: `systemd` (when `DymanicUser=yes`) generates user and groups just-in-time and removes such users/groups when the service is stopped (see https://0pointer.net/blog/dynamic-users-with-systemd.html for more details). 

**Why is this a problem?**
When spire agent runs under systemd (with `DynamicUser=yes`) the health checker produces a warning `p.log.Warn("Failed to lookup group name by gid", "gid", gid, "error", err)` which fills-up a log. This is because the health check triggers the unix workload plugin logic.

**A potential approach to address this:**
1. If `user.lookupId` fails,  check if the UID is in the 61184–65519 range - reserved by `systemd` for `DynamicUsers`. 
2. Use the existing [logic](https://github.com/spiffe/spire/blob/main/pkg/agent/plugin/workloadattestor/systemd/systemd_posix.go#L100) in the `systemd` workload attestation plugin to get the unit file and extract the `User` field.

```
[Unit]
Description=SPIRE Agent
Wants=network.target
After=syslog.target network-online.target
[Service]
DynamicUser=true
User=spire-agent
Group=spire-agent
RuntimeDirectory=spire-agent
ConfigurationDirectory=spire-agent
StateDirectory=spire-agent/data spire-agent/data/key-manager
ExecStartPre=+/opt/spire-agent/spire-agent-pre-start.sh
ExecStart=/opt/spire-agent/spire-agent run -config /etc/spire-agent/agent.conf
[Install]
WantedBy=multi-user.target
```

* **Version**: 1.8.7
* **Platform**: Linux
* **Subsystem**: unix workload

**Comment by immutableT** [comment]
Another potential approach is for the spire-agent to [determine](https://pkg.go.dev/github.com/coreos/go-systemd@v0.0.0-20191104093116-d3cd4ed1dbcf/util#RunningFromSystemService) that is is running under systemd and use the systemd workload plugin path during a health check.

**Comment by evan2645** [comment]
Thank you for filing this issue @immutableT , we are looking into it.

**Comment by azdagron** [comment]
That warning was introduced out of an abundance of caution. Since its introduction, there have been many legitimate cases where the user/group do not exist in the /etc/{passwd,group} files that the agent has access to, causing the lookup to fail. I think I'd advocate for just removing the warning. It doesn't seem helpful.

**Comment by amartinezfayo** [comment]
Thank you @immutableT for bringing this to our attention and thank you @azdagron for summarizing the discussion that we had during our maintainers sync. I also think that those warnings have been problematic and there isn't really a good reason to keep them. I've filed #4905 to address that.

Closing this issue in favor of #4905.
