### ISSUE TITLE
Add event addition metrics for latency and counter

### ISSUE THREAD

**Issue by stevend-uber** [spiffe/spire#4836]
Currently in the event-based cache hydration feature, we have metrics around latency/counts for fetch and prunes of events from the events table. I propose we add a counter and latency metrics around Event-Addition.

**Comment by Victorblsilveira** [comment]
Most of the metrics creation is done at `metricsWrapper`. Another aspect of this is that event creation is done in `createRegistrationEntryEvent`, an internal function. Even if we add the function to the interface and implement the metrics start at `metricsWrapper`, most internal calls wouldn't fire the latency/count metric. 

One solution would be to internalize the metrics fire to the `sqlstore.go`. Although looking at the code this breaks the patterns. Is that an acceptable solution for the spire community? I want to help here and appreciate any guidance.

**Comment by azdagron** [comment]
Talking in the contributor sync, we determined that with #4720 we should have enough metrics to start with for the events based cache.
