### ISSUE TITLE
can spire support this architecture?

### ISSUE THREAD

**Issue by penghuazhou** [spiffe/spire#4863]
can spire support this architecture?

<img width="724" alt="image" src="https://github.com/spiffe/spire/assets/13001038/99c7a282-fc99-4d6c-a7ce-2f9e2ed10070">

**Comment by evan2645** [comment]
Yes it can. It is a common pattern. I'll go ahead and close this issue, if you run into a specific problem please feel free to open a new one. We also have a slack you can join to ask questions: https://slack.spiffe.io

Hope this helps!

**Comment by penghuazhou** [comment]
thanks
