### ISSUE TITLE
Event-based Edge Cases

### ISSUE THREAD

**Issue by stevend-uber** [spiffe/spire#4865]
In the latest event-based [cache-hydration feature](https://github.com/spiffe/spire/blob/c8b40fae920f5dce8035c6ac7cd2fdfd16c7a7c4/pkg/server/endpoints/authorized_entryfetcher.go#L105), there contains failure modes that result in an incorrect cache. 

```
func (a *AuthorizedEntryFetcherWithEventsBasedCache) updateRegistrationEntriesCache(ctx context.Context) error {
	req := &datastore.ListRegistrationEntriesEventsRequest{
		GreaterThanEventID: a.lastRegistrationEntryEventID,
	}
	resp, err := a.ds.ListRegistrationEntriesEvents(ctx, req)
	if err != nil {
		return err
	}

	seenMap := map[string]struct{}{}
	for _, event := range resp.Events {
		// Skip fetching entries we've already fetched this call
		if _, seen := seenMap[event.EntryID]; seen {
			a.lastRegistrationEntryEventID = event.EventID
			continue
		}
		seenMap[event.EntryID] = struct{}{}

		commonEntry, err := a.ds.FetchRegistrationEntry(ctx, event.EntryID)
		if err != nil {
			return err
		}
		a.lastRegistrationEntryEventID = event.EventID

		entry, err := api.RegistrationEntryToProto(commonEntry)
		if err != nil {
			a.cache.RemoveEntry(event.EntryID)
			continue
		}

		a.cache.UpdateEntry(entry)
	}

	return nil
}
```
### Scenario - Failed calls to FetchRegistrationEntry

If there exists a temporary network partition or issues on the DB and `FetchRegistrationEntry` fails, this will delete the entry from the cache. Currently, we rely on implicit failures to the db for fetching registrations as a "delete" of the entry. We should consider a more fault-tolerant solution: 
* Explicit delete events to give high granularity and controls around failures. 
* Consider a retry+backoff to retry failed calls.
* A configurable reconciliation loop that does a full rebuild of the cache. (consider it a mixed mode between full cache-rebuild + events-based)

* **Version**: 1.8.x
* **Platform**: All
* **Subsystem**: Spire-Server Event-Based Cache Hydration

**Comment by azdagron** [comment]
From my reading of the code, if `FetchRegistrationEntry` fails, it will abort the update operation and not consider the event as "handled" (i.e. not update `lastRegistrationEntryEventID`). On the next event poll interval, it should retry that event.

Have you observed something different?

**Comment by stevend-uber** [comment]
So my understanding is that this behavior is somewhat expected as currently deleted events are implied by events with said entryID and that entryID in the entries table does not exist. 

We have not explicitly seen this behavior but as I was grokking through the code branches, I noticed it. I believe that in the next poll interval, it will actually get skipped over @azdagron because of the seenMap logic. 

```
		if _, seen := seenMap[event.EntryID]; seen {
			a.lastRegistrationEntryEventID = event.EventID
			continue
		}
		seenMap[event.EntryID] = struct{}{}
```

**Comment by azdagron** [comment]
`seenMap` is not retained between poll intervals. It is only used to not repeat the processing of a given entry in the face of multiple poll events for that entry noticed on a single poll.

**Comment by stevend-uber** [comment]
Ah, I see. Thanks for the rubberduck. So to be verbose, the expected behaviors are: 

Deleted Entries
1. `FetchRegistrationEntry` does not return error but returns nil entry. 
2.`lastRegistrationEntryEventID` is updated

Network Partition/DB Errors
1. `FetchRegistrationEntry` _returns_ error.
2.`lastRegistrationEntryEventID` is never updated
3. Rehydration of cache method exits with failure. 
4. Said failure should get picked up in the next poll

**Comment by azdagron** [comment]
Yes, that's correct.

**Comment by stevend-uber** [comment]
Thanks for the clarification @azdagron
