### ISSUE TITLE
Fix a confusing typo in readme

### ISSUE THREAD

**Issue by Zhengneng** [spiffe/spire#4884]
It's pretty confusing in this [profiling_names](https://spiffe.io/docs/latest/deploying/spire_agent/#profiling-names) session as saying set in the `profiling_freq` . I'd guess it might be a typo, which should be `profiling_names` instead.

[Update] SPIRE server also has the same issue.

For more details, please refer this in [this slack thread](https://spiffe.slack.com/archives/C7XDP01HB/p1707870319905059).

**Comment by evan2645** [comment]
Yes it is a typo, thank you for filing this. PRs welcome ❤️

**Comment by zhengneng-cb** [comment]
Will file a PR later.

**Comment by evan2645** [comment]
Fixed in https://github.com/spiffe/spire/pull/4890 thank you @Zhengneng!
