### ISSUE TITLE
Dockerfile does not honor the specified ${spireuid}:${spiregid} in the USER instructions

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#4903]
The [Dockerfile](https://github.com/spiffe/spire/blob/main/Dockerfile) does not honor the specified ${spireuid}:${spiregid} in the USER instructions of the build stages for SPIRE Server, SPIRE Agent and OIDC Discovery Provider.

**Comment by azdagron** [comment]
I'll go ahead and close out #4967 for now since we are at least a month out from being able to merge it. We can re-open it after 1.9.3 releases and get it merged.
