### ISSUE TITLE
Documentation on methods of using SPIRE with Kubernetes

### ISSUE THREAD

**Issue by ajessup** [spiffe/spire#492]
Right now we don't have great documentation on how to deploy SPIRE with Kubernetes. Issues to address in this documentation should include:

* Supported versions of Kubernetes
* Recommended mechanism for deploying the node agent in Kubernetes cluster (eg. on the node agent, or as a daemonset). 
* How to set up attestation policies with Kubernetes (extending the k8s plugin integration)

**Comment by rushabh268** [comment]
This will be a really good addition to have!

**Comment by eicnix** [comment]
It would also be great if a turnkey example for k8s were available. This should include: 

* publish docker images during the CI release process
* provide a default k8s deployment that can just be spun up without modifications

**Comment by azdagron** [comment]
I believe this has been satisfied.

Image building was tackled on #700 and there is now a SPIRE tutorial for k8s with accompanying config at https://spiffe.io/spire/getting-started-k8s/.
