### ISSUE TITLE
spire CLI federation command does not display federation entries created via config.

### ISSUE THREAD

**Issue by riuvshyn** [spiffe/spire#4930]
spire CLI federation command does not display federation entries created via config.

* **Version**: 1.6.5
* **Platform**: Linux
* **Subsystem**: server

Hello, we've noticed that running command to list federations it returns 0 items:
```
$ spire-server federation list
Found 0 federation relationships
```
However we have bunch of federation entries with created via config file.

Also if I create federtion via CLI like:
```
$ spire-server federation create ...
```
Then `federation list` shows that entry created via CLI.

**Comment by amartinezfayo** [comment]
Hi @riuvshyn, thank you for opening this issue.
The `spire-server federation list` command, is designed to list the _dynamic_ federation relationships, not the static ones. You can see that in the documentation [here](https://github.com/spiffe/spire/blob/main/doc/spire_server.md#spire-server-federation-list).
This is why those federation relationships that are configured statically en the config file will not be listed, and are only listed the ones that have been created through the [Trust Domain API](https://github.com/spiffe/spire-api-sdk/blob/main/proto/spire/api/server/trustdomain/v1/trustdomain.proto).

I'll go ahead and close this issue. Please feel free to re-open if needed. Thanks!
