### ISSUE TITLE
Update CA Manager and/or CA plugin to support second signing certificate

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#494]
Out of an abundance of caution, JWT-SVIDs will use a dedicated signing key. Currently, both CA Manager and the CA plugin in SPIRE server assume only a single signing certificate.

Prepare for JWT-SVID by refactoring CA Manager and/or the CA plugin to support a second CA certificate. The certificate signing the JWT **must** be a CA certificate. It does not, however, have to be a root. Here are a couple approaches that would work:
* Refactor the CA plugin and associated interface to be aware of the second CA certificate. Manage it in the same way as the current CA certificate. Pro: all CA cert handled by CA plugin. Con: CA bundle is double the size (new cert is now a root). CA plugin is more complex
* Refactor CA manager to create and maintain a second intermediate CA certificate, signed by the CA plugin. Pro: Bundle stays small, no breaking changes on CA plugin interface. Con: Split responsibility

One thing to keep in mind is that this new CA certificate will need to be accessed by an external package whenever a JWT needs to be signed. It must also be fully rotated, just as the current CA certificate is.

This issue is fixed when SPIRE server has a second (fully automated) CA certificate which can be consumed by external packages.

**Comment by azdagron** [comment]
Seems like option 2 (CA manager independently maintains a JWT CA) is promising. It would take a small tweak to the plugin SignCsr() method, in that currently SignCsr() only knows how to sign leaf certificates. At a minimum, this means adding a "CA" bool to the SignCsrRequest message.
