### ISSUE TITLE
SPIRE server is continuously creating JWT signing Keys in AWS KMS as it crash loops due to upstream CA unavailability.

### ISSUE THREAD

**Issue by naroraindeed** [spiffe/spire#5038]
Version: https://github.com/spiffe/spire/commit/b5879e2f4f8f2cc8146f1e07a1ee9ec2a97d6433
Platform: Linux server-1 5.15.0-1053-aws #58~20.04.1-Ubuntu SMP Mon Jan 22 17:15:01 UTC 2024 x86_64 Linux
Subsystem: [server\upstreamauthority](https://github.com/spiffe/spire-plugin-sdk/blob/main/templates/server/upstreamauthority/upstreamauthority.go)

Here's a sequence of event we are seeing on server bootup:
1. There is not a CA journal record that matches any of the local X509 authority IDs
2. Journal loaded
3. JWT key activated (local_authority_id  = some_new_id)
4. Creating a new CA journal entry
5. Waiting for certificaterequest to be signed
6. Failed to wait for CertificateRequest to become ready in time
7. Unable to rotate X509 CA
8. ...
9. Fatal run error / rpc error: code = Internal desc = upstreamauthority(cert-manager): request did not become ready in time

We know the upstream CA is not available right now and the crash loop is expected. The problem is the loop is spamming the AWS KMS with new JWT signing keys on each boot attempt. The problem was realized when the cloud monitoring team informed us.

Request: Load the x509 CA before JWT signing keys. In that case the Server can failfast and not unnecessarily create JWT signing keys which will not be used on next boot attempt anyways
OR 
persist partial CA_Journal information about JWT keys that were created and not recreate them over and over.

**Comment by amartinezfayo** [comment]
Thank you @naroraindeed for filing this issue.
I was able to reproduce the problematic behavior and I'm working on a solution to address the problem.
