### ISSUE TITLE
A Watcher for the configuration file synchronization with the current execution

### ISSUE THREAD

**Issue by ramon-lsd** [spiffe/spire#5102]
I'm writing to suggest an additional functionality for Spire-Server (and possibly Spire-Agent) that I believe will be beneficial, especially concerning dynamic configuration synchronization.
I would like to propose the implementation of an Observer that monitors modifications to the configuration file and allows “real-time” synchronization with the current execution of the server. This implementation offers two main benefits:

- Dynamic Synchronization: By detecting changes to the configuration file, the Spire-Server could adjust its settings at runtime, eliminating the need for manual restarts and ensuring that changes are reflected instantly.
- Testing Convenience: Developers can quickly test configurations, observing changes in the server execution, which would speed up the configuration and debugging process.

This could be set with a flag in the CLI or as an attribute in the configuration file. Our team already has a working prototype of this implementation, that we can further discuss in this issue.

**Comment by c4rlo** [comment]
This is pretty much the same as #4390.

**Comment by azdagron** [comment]
I think we're tracking this on #4390. If there are approaches you'd like to be considered, please add them to that issue. Thanks for opening this! I'll close it for now, in favor of #4390.
