### ISSUE TITLE
Rework the SPIRE modules to internally build their respective Config structs from a Config reference on creation.

### ISSUE THREAD

**Issue by edwbuck** [spiffe/spire#5107]
Currently, the handling of the Config within the server modules follows the prescribed pattern:

![current_approach](https://github.com/spiffe/spire/assets/4909368/25d9c488-83c3-448a-92f8-5929a0333eed)

This issue depends on #5105 and would transition these calls to the following pattern

![new_approach](https://github.com/spiffe/spire/assets/4909368/6ac39c7b-6fa0-4444-a6c8-e294c8005456)

This can be encapsulated into a new internal func if desired, or simply worked directly into the modules' New func as the implementor / reviewers see fit.

The goal here is to ensure that construction of Config structs is centralized within the same module being configured, and the code that reads specific values from the top-level Config struct clearly indicates where it comes from from the original Config struct within the same module being initialized.

**Comment by azdagron** [comment]
Closed in favor of #5165.
