### ISSUE TITLE
Defaults for all CheckConfig callbacks.

### ISSUE THREAD

**Issue by edwbuck** [spiffe/spire#5108]
This issue depends on #5105

For each module receiving a Config struct, they should implement the CheckConfig() func with default logic that parses the module-specific Config object(s) (hopefully with reused logic from #5107) and then compares the two Config objects.  If any difference exists, the comparison should raise an error.  This will indicate to the server that the configuration change is not supported.

By implementing this for each module that needs configuration items, the server will get decentralized validation that no item can be reconfigured.

Future efforts can then open up which items are permitted for reconfiguration, by whatever logic / reconfigurations the specific modules can support.

**Comment by azdagron** [comment]
Closed in favor of #5165.
