### ISSUE TITLE
Consider caching the Kubelet response

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#5111]
The Kubernetes Workload Attestor queries the Kubelet for pod information on each attestation attempt. Kubelet responses can be somewhat large (e.g. 1MiB). When many processes are concurrently under attestation, the large response can cause a spike in SPIRE agent memory usage.

This issue is to explore if and how we cache the kubelet response to share across attestation attempts.

Some considerations:
1. How long is this cached for?
2. What events would actively invalidate the cache ahead of expiration? (e.g. expected pod/container not found in response)
3. Each attestation invocation is looking for a different pod/container. Do we cache just the kubelet response and then use targeted parsing of the response to cherry-pick the specific pod/container (what we do today)? Or do we parse the whole response and then share the parsed version (maybe reduces load due to re-parsing)?

Any decisions about the considerations above should ideally be backed by benchmarking to understand the tradeoffs.

**Comment by Rishikesh01** [comment]
Hi @azdagron I am interested in helping out here. I am looking around to find code base where this caching needs to be done and I have found this  `/pkg/agent/plugin/workloadattestor/k8s` package I hope this is where I should start looking.

Also about caching part you plan it to be in-memory thing ?

**Comment by azdagron** [comment]
Yes, @Rishikesh01. That is the correct package for the Kubernetes workload attestor code.
