### ISSUE TITLE
Ensure that all config reading items listen to the central Config struct, with logging

### ISSUE THREAD

**Issue by edwbuck** [spiffe/spire#5112]
This depends on #5105 

For each module that reads the central Config struct, if the module maintains an internal Config struct, it should add itself as a listener, and log all calls for CheckConfig and ConfigChanged.  Minimum logged items should include:

- Each module should log when its CheckConfig() is called with labels allowing one to determine the module performing the logging.
- Each module should log every value being checked in a CheckConfig() call, with the top-level Config object being read, its value, and if it passes / fails the check.
- Each module should log success for the overall CheckConfig() call once all the CheckConfig() items have passed.
- Each module should log when its ConfigChanged() is called, and should log just prior to the module's ConfigChanged() call completing.

As the modules are modified to permit / react to configuration changes, these logging patterns should be extended such that every module clearly indicates if it can/can't support the change, or the issues it encounters during configuration change worked / didn't.

**Comment by azdagron** [comment]
Closed in favor of #5165.
