### ISSUE TITLE
k8s_psat node attestor: allow empty list of clusters

### ISSUE THREAD

**Issue by sorindumitru** [spiffe/spire#5211]
Now that the plugin configuration can be reloaded at runtime to add and remove new clusters it's possible to end up in the situation where you have a mostly valid configuration file (at least from the administrator point of view) with no clusters defined. 

This configuration is rejected by spire-server (see https://github.com/spiffe/spire/blob/04a0bcd1ad0f600241f3c9749a264fe689139a8a/pkg/server/plugin/nodeattestor/k8spsat/psat.go#L228). This might lead to situations where spire-server is unable to start up (e.g. if it crashes and has to restart), even though it might have still been able to serve other agents with other node attestors.

Would it be possible to remove that check? I can work around it by adding some dummy value in there, but that seems a bit icky to me.

* **Version**: 1.10.0
* **Platform**: any
* **Subsystem**: k8s_psat server nodeattestor

**Comment by edwbuck** [comment]
Clarification:  When the cluster name is empty the plugin should startup but not attest anything.

**Comment by amartinezfayo** [comment]
Thank you @sorindumitru for opening this and @edwbuck for the PR (https://github.com/spiffe/spire/pull/5216).
We have discussed this a little more in our maintainer's sync and we think that a warning should be logged when the configuration is being set to have no clusters defined. @azdagron added a comment about that in the PR.
