### ISSUE TITLE
aws_iid attestation fails when ec2 network interfaces aren't listed in expected order

### ISSUE THREAD

**Issue by Manbeardo** [spiffe/spire#5299]
When an EC2 instance has multiple network interfaces attached, IMDS does not always return the list sorted by device index.

The `aws_iid` agent NodeAttestor plugin expects the first network interface returned by IMDS to be device index 0 and fails with a message like this when IMDS reports them in a different order:

```
nodeattestor(aws_iid): failed aws ec2 attestation: the EC2 instance network interface attachment device index must be zero (has 1)
```

This can be especially problematic when running an agent on a kubernetes cluster node because they tend to have several attached network interfaces.

* **Version**: v1.9.2
* **Platform**: Linux spire-server-0 5.10.219-208.866.amzn2.x86_64 #1 SMP Tue Jun 18 14:00:06 UTC 2024 x86_64 GNU/Linux
* **Subsystem**: agent aws_iid NodeAttestor

**Comment by amartinezfayo** [comment]
Fixed by #5300.
