### ISSUE TITLE
Consider deprecating and removing usage of rsa-2048

### ISSUE THREAD

**Issue by nikotih** [spiffe/spire#5304]
Spire server and spire agent default configuration already defaults to ec-p256
However, one might still configure them to use RSA-2048

RSA-2048 is on a verge of being marked as "not enough" with modern computing power

E.g BSI recommends RSA key length bigger than 3000
https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TG02102/BSI-TR-02102-1.pdf
Page 18 or Page 31
`Key Length The length of the modulus n should be at least 3000 bit.`

**Comment by evan2645** [comment]
Hi @nikotih , thank you very much for raising the flag on this. We've been hearing some rumblings about it as well, predominantly from government agencies.

We've spent some time researching and discussing, specifically when would it be appropriate for SPIRE to deprecate. We've noticed that [Mozilla TLS security guidelines](https://wiki.mozilla.org/Security/Server_Side_TLS) still refers to RSA 2048 bit keys in the "intermediate compatibility" level. We've historically looked to these guidelines to help navigate the "moving target" issue as it relates to (modern) crypto.

The feeling currently is that RSA 2048 is on its way out, and for folks that have state actors included in their threat model, now is the time to start thinking about moving ... however, that is a relatively small number of consumers, and the default key choices in SPIRE are EC as you've correctly noted. In that context, it feels a little early to begin the deprecation in SPIRE, however it does seem to be coming at some point. We will be sure to keep an eye on it and phase out once we're a little closer. Thanks again for raising it
