### ISSUE TITLE
server, agent: Allow specifying CA when fetching bundles

### ISSUE THREAD

**Issue by sorindumitru** [spiffe/spire#5331]
spire-server allows specifying a server certificate/key to use for its bundle  endpoint. Users might want to use certificates issued by their own private CAs, which may not be present in the system trust store. In that case, spire-server won't be able to fetch any federated bundles and spire-agent won't be able to fetch the bootstrap bundle due to them not being able to verify the server certificate.

This could be fixed by allowing users to specify a CA to use to verify the remote endpoint. This goes a bit against the specification, which says that the `https_web` profile should be used with WebPKI, but it doesn't feel like to much of a difference.

* **Version**: any
* **Platform**: any
* **Subsystem**: server, agent

**Comment by azdagron** [comment]
We discussed this a bit and feel like this discussion should first be had in specification land. Would you mind opening an issue at github.com/spiffe/spiffe, @sorindumitru? I'd transfer this issue but it's worded very specifically for SPIRE.

**Comment by azdagron** [comment]
I'll close this for now until we've had a discussion in spec land.

**Comment by sorindumitru** [comment]
Thanks, I've created https://github.com/spiffe/spiffe/issues/297 to cover this.
