### ISSUE TITLE
929 SDS connections for stress testing, Spire agent experience memory leaks.

### ISSUE THREAD

**Issue by penghuazhou** [spiffe/spire#5348]
929 SDS connections for stress testing, Spire agent experience memory leaks.
![image](https://github.com/user-attachments/assets/72aa9345-ced6-4b2d-acf6-e07bebdc1a90)

929sds connection.
![image](https://github.com/user-attachments/assets/ac908d70-3468-4f68-aa42-e7d778b3c85c)

pprof heap file get at 2024-08-01 20:15
![image](https://github.com/user-attachments/assets/3aba9972-b005-451f-8bba-fa3ef1d57c47)
![image](https://github.com/user-attachments/assets/ac1c8b5f-3e6c-48ad-8997-9ce0ea95d33f)

pprof heap file get at 2024-08-02 09:15
![image](https://github.com/user-attachments/assets/2b676b98-cb6e-42e5-bd09-9cb8fde81e41)
![image](https://github.com/user-attachments/assets/605c8d11-e9d5-41c6-9380-434fa327c5e5)

Version: v1.9.6
Platform: linux-amd64
Subsystem: spire-agent

**Comment by azdagron** [comment]
I'd be curious to see the stress test code. Is that shareable?

**Comment by penghuazhou** [comment]
I use this architecture below.
![image](https://github.com/user-attachments/assets/9c62b179-5ce4-4fc1-bf1d-9c4c32368ce0)

**Comment by penghuazhou** [comment]
@azdagron , The number of spice agent connections is around 450, and the memory usage is maintained at around 3.5G.
![image](https://github.com/user-attachments/assets/54269797-5fd4-4b44-b227-5fe6a95a961b)

![image](https://github.com/user-attachments/assets/6931bf01-5e40-4986-af6b-667494de0cc9)

**Comment by azdagron** [comment]
The graph appears stable. So is this a leak or just a lot of clients?

Also, can you attach the raw pprof files?

**Comment by penghuazhou** [comment]
thanks, it  just a lot of clients.
