### ISSUE TITLE
Provide healthcheck endpoints for Kubernetes deployments

### ISSUE THREAD

**Issue by eicnix** [spiffe/spire#536]
As a Kubernetes operator I want to verify the health of my workloads through a http healthcheck.  
Therefore both the SPIRE server and agent should provide a health endpoint that can be used to determine their health and trigger restarts by Kubernetes if necessary.

**Comment by azdagron** [comment]
Hey @eicnix! Issue #730 has been opened to determine what the health checks should look like. Is there a particular reason you need an HTTP health check v.s. an exec-based one?

If you want to drop a comment on #730, we'd love to know your throughts.

**Comment by evan2645** [comment]
This has been addressed in #758 and #763
