### ISSUE TITLE
New agent test breaks deployments

### ISSUE THREAD

**Issue by kfox1111** [spiffe/spire#5455]
* **Version**: 1.10.2

https://github.com/spiffe/spire/pull/5298

Added a test to ensure that the agent has a svid. In the helm chart, in most configurations that currently is not true.

Its even harder to deal with in nested configurations where root-server -> nested-server may already have an entry, but root-server -> root-agent currently may not.

This patch breaks previously working configurations without potentially complicated reconfiguration.

It is more work in some situations then a patch release implies.

I suggest we revert this patch, cut a 1.10.3 asap, and then re-add the patch with an appropriate user configuration warning at 1.11.0. This will give users a chance to consider the config changes required to properly upgrade in a more cautious way.

**Comment by kfox1111** [comment]
After digging further, it seems like it may be a different issue then as described. Closing for now, and will reopen if it really is a problem.

**Comment by MarcosDY** [comment]
solved in 1.10.3, and reopend https://github.com/spiffe/spire/issues/5297
