### ISSUE TITLE
Make the JWT issuer configurable in the OIDC Discovery Provider

### ISSUE THREAD

**Issue by jer8me** [spiffe/spire#5480]
The issuer returned by the OIDC Discovery Provider is currently dynamically built based on the request host: https://github.com/spiffe/spire/blob/v1.10.3/support/oidc-discovery-provider/handler.go#L66

There are a couple of issues with this approach:

1. Only host-based issuers are supported. We cannot use a path component to support multiple issuers per host. For instance:
- https://example.com is a supported Issuer
- https://example.com/issuer1 is not a supported Issuer
We want to be able to specify a path component for our issuer, as per the OIDC specs: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationRequest

2. If the OIDC Discovery Provider service is reachable via more than one host, it will return a different issuer based on the host used for the request. This does not really make sense from an OIDC point of view because a SPIRE server is configured with exactly one `jwt_issuer`. The issuer returned by the OIDC Discovery Provider should match the one configured in the server.

**Comment by azdagron** [comment]
> The issuer returned by the OIDC Discovery Provider should match the one configured in the server.

This is the biggest sticking point for me on why this should be configurable.

We'd accept a change here.

**Comment by aluthra-37** [comment]
I talked to @jer8me about this issue. We were thinking that we could add an optional configuration item in the OIDC provider to set the jwt_issuer.
If missing, we would keep the existing behavior but if set, we could use it as the jwt_issuer, bypassing the dynamic logic.
If this sounds good, could you please assign this issue to me

**Comment by azdagron** [comment]
Sounds great. Thanks @aluthra-37 .

**Comment by kfox1111** [comment]
@aluthra-37, I have a need to resolve this too. Do you have time to work on this soon? If not, would you mind if I write up a pr for it?

**Comment by aluthra-37** [comment]
Hey @kfox1111. I'm currently working on a PR for this. I should have one out soon

**Comment by amartinezfayo** [comment]
This has been addressed by #5657.
