### ISSUE TITLE
[oidc-discovery-provider] Issuer missmatch

### ISSUE THREAD

**Issue by kfox1111** [spiffe/spire#5568]
The oidc discovery provider provides the port it is listening on as part of the issuer property returned to the user of the service. When you run it on an alternate port, for example, for load balancing, it will state the wrong port to the end user. If they are strict with their validation (ex: kube-apiserver) then it will reject it.

**Comment by kfox1111** [comment]
Actually, it looks to just return the hostname:port as passed from the client...

**Comment by azdagron** [comment]
Confirmed that this is a dup of 5480.
