### ISSUE TITLE
[spire-server] go template variable issue

### ISSUE THREAD

**Issue by kfox1111** [spiffe/spire#5574]
When loading a go-template into one of the plugins in the config file, and env substitution is enabled (default), env substitution eats all variables, and there currently is no way to escape the variables so the env substitution doesn't eat them.

As a work around, I was able to set an environment variable in the env of the spire server:
d=$

and then use that as a hack around the issue:
`agent_template = "{{ ${d}foo := \"thing\" }}{{ ${d}foo }}"`

Maybe the spire-server itself could try and set an env var named $ to value $ at start, and then maybe this might work:
`agent_template = "{{ $$foo := \"thing\" }}{{ $$foo }}"`

**Comment by azdagron** [comment]
Seems reasonable to fix.
