### ISSUE TITLE
[spire-server] go template functions (sprig)

### ISSUE THREAD

**Issue by kfox1111** [spiffe/spire#5575]
The embeded go template engine does not have many useful functions built in.

Other tools such as helm and step-ca embed a library named sprig (https://masterminds.github.io/sprig/)

In particular, some of the string functions are extremely useful. (contains, hasPrefix, trimPrefix, cat, replace, ...)

It would be very easy to embed the library and make it available for use in templates.

Alternately, it would be possible to embed the library and cherry pick only the functions we want to make available to our templates if  there is concern there is too many functions there.

**Comment by azdagron** [comment]
We gave it some discussion. The consensus was that many of these functions seem super useful but a few seem undesirable. In order to pick this up, someone needs to go through that list and make a proposal of functions we'd like to include in the first pass.

**Comment by kfox1111** [comment]
Would be happy to inventory the functions, but not being part of the discussion, am not privy to the thinking behind what might be undesirable. Could you please give some guidance on what that might be?

Alternately, we could start with just the string functions and skip the rest for now?

**Comment by azdagron** [comment]
Concerns were mostly around usefulness and some small safety concerns. I think taking only the immediately useful functions on the first pass is appropriate. Others can be added if a strong case can be made.

Things that seem immediately useful:
- anything to manipulate strings, lists, dicts
- some of the defaults functions
- path functions (but not filepath functions, e.g. `os*`)
- encoding functions
- `fail`
- `uuidv4`

Most of the advanced functions seem weird to include. Same with the math, time, and int/float functions.

**Comment by kfox1111** [comment]
Took a really rough stab at making a list.
