### ISSUE TITLE
Use DNS as bundlepublisher

### ISSUE THREAD

**Issue by mlgupta** [spiffe/spire#5604]
Hi Team, I am looking into ways I could contribute to the community. I saw a few threads related to cert bundle transmission and saw two existing plugins aws_s3 and gcp. I thought how about a plugin that uses DNS to publish the cert bundle. Went ahead and wrote a plugin that publishes cert bundle to AWS RT53. It uses TXT record for it. The idea is that if the DNS server uses DNSSEC then it would also be a secure channel to deliver cert bundle.  I am yet to fully finish it and then write one that to be used by consumers (agents). Although, instead of using TXT record, the correct approach here would be to use either TLSA (thx Matthew Bates) or CERT record. I chose TXT for RT53 as it does not support either. Before I proceed further I wanted to ask if there is any value in creating a plugins like these? Would appreciate any feedback.

**Comment by amartinezfayo** [comment]
Thank you @mlgupta for opening this issue.
Could you provide some more details about your use case? Is this to bootstrap agents?
I'm not sure if you were thinking about having the agent interacting directly with the Amazon Route 53 service.
There isn't any functionality within the agent (or agent plugin) that would provide the ability to interact with the Amazon Route 53 service directly.
The way that agents can be configured to read the initial trust bundle is either through a trust bundle path on disk (trust_bundle_path) or an URL from where it's downloaded (trust_bundle_url).
Learning more about your use case will allow us to better assist you in this request.

**Comment by mlgupta** [comment]
Hi @amartinezfayo sorry it took a little long for me to respond. I was thinking of using DNS as a channel to publish the trust bundle. I chose RT53 first because I work with AWS most of the time. Ideally, I'd write a server plugin that would publish the trust bundle to a DNS server (say bind9) running with DNSSEC. The agents would get this bundle by performing a DNS lookup (by performing a lookup against trust_bundle_dns_[record|name].

**Comment by amartinezfayo** [comment]
>Agents would then retrieve the bundle via DNS lookup using trust_bundle_dns_[record|name].

I'm not sure how that would work with the current available mechanisms to retrieve a trust bundle that agents have? (e.g. using the `trust_bundle_url` setting).

**Comment by azdagron** [comment]
Another question: bundles can be quite large. What size constraints exist for the TLSA and CERT record? TXT has a pretty small limit.

**Comment by amartinezfayo** [comment]
@mlgupta Do you have a use case for this? Is there something preventing you from using the `aws_s3` bundle publisher?

**Comment by amartinezfayo** [comment]
Thank you @mlgupta for your detailed response!
