### ISSUE TITLE
spire-server/agent: log version at startup

### ISSUE THREAD

**Issue by sorindumitru** [spiffe/spire#5632]
It would be helpful if the server and agent would log their versions. These can currently be retrieved with the `--version` option, but it would be helpful to have them in the logs. This would helpful for admins to easily check the currently running versions through logs and for debugging incoming issues from users when they provide a log (e.g. on the SPIFFE Slack)

* **Version**: any,
* **Platform**: any
* **Subsystem**: server and agent

**Comment by azdagron** [comment]
I'm surprised we didn't already log this. This is very reasonable.
