### ISSUE TITLE
Starting Pod upgrade crash 

### ISSUE THREAD

**Issue by didlawowo** [spiffe/spire#5649]
* **Version**: helm chart 0,24
* **Platform**:  Ubuntu 24.04.1 LTS               5.15.0-124-generic
* **Subsystem**: rke2 1.31

6.6.51+rpt-rpi-2712

i have installed spire using this helm chart : https://artifacthub.io/packages/helm/helm-spire/spire

i'm deploying this with argocd

the pod for upgrade start and say:
```
Error from server (NotFound): validatingwebhookconfigurations.admissionregistration.k8s.io "security-spire-controller-manager-webhook" not found
Stream closed EOF for security/spire-server-pre-upgrade-m2ppj (post-install-job)
```

this is the first installation on cluster .

i don't find anydocumentation about this webhook

**Comment by amartinezfayo** [comment]
Thank you @didlawowo for opening this issue.
This seems to be specific to the [SPIFFE Helm Charts](https://github.com/spiffe/helm-charts-hardened) project. Could you please open the issue in that repository?
I'm closing it here for now. Please re-open if you find that it's specific to SPIRE.
