### ISSUE TITLE
peertracker: CompareObjectHandles check for Windows does not run

### ISSUE THREAD

**Issue by jameshiew** [spiffe/spire#5748]
* **Version**: v1.11.1
* **Platform**: Windows
* **Subsystem**: peertracker

---

On Windows, if the `CompareObjectHandles` syscall is present, then `procCompareObjectHandlesErr` will be `nil` here.

https://github.com/spiffe/spire/blob/32cc98e140544810b501a4b6e7116f8d3054bac3/pkg/common/peertracker/npipe_windows.go#L15-L20

Further down, `compareObjectHandles()` will then always return `nil` and skip the check, since `isCompareObjectHandlesFound()` = `procCompareObjectHandlesErr == nil` = `true`.

https://github.com/spiffe/spire/blob/32cc98e140544810b501a4b6e7116f8d3054bac3/pkg/common/peertracker/npipe_windows.go#L61-L76

The only call path for these functions is here:

https://github.com/spiffe/spire/blob/32cc98e140544810b501a4b6e7116f8d3054bac3/pkg/common/peertracker/tracker_windows.go#L149-L154

**Comment by amartinezfayo** [comment]
Thank you @jameshiew for bringing this up and contributing the fix!
