### ISSUE TITLE
Having built and started the control_plane binary, I get strange errors

### ISSUE THREAD

**Issue by ajessup** [spiffe/spire#61]
I've built and started the control plane binary, and set the `CP_CONFIG_PATH` environment variable to point to `/root/go/src/github.com/spiffe/sri/control_plane/.conf/default_cp_config.hcl`.

When I try and run the control plane binary, I get the following output:

* When I run `./control_plane/control_plane` 
  
   I get `Usage: sri/control_plane...` (ie. the expected output)

* When I run `./control_plane/control_plane plugin-info` 
  
   I get `2017/08/24 14:02:33 error: rpc error: code = Unavailable desc = grpc: the connection is unavailable`
  
   I find this error confusing as there's no text that describes what the `control_plane` binary was trying to do, or what I should be doing to fix it. It would be nice if the error message included details about what CP was trying to connect to, and what configuration it was using to do so.

* When I run `./control_plane/control_plane server` 
   
   I get no output. 
   
   This is a little confusing, since now I'm not sure if the command worked or not. Ideally I'd see a line confirming success if it worked (and perhaps some extra detail, like the PID of the server). I would _definitely_ expect to see something if it failed. But running `ps aux` shows now new processes running, so I guess it failed.

* When I run `./control_plane/control_plane stop` 
   
   I get `2017/08/24 14:02:33 error: rpc error: code = Unavailable desc = grpc: the connection is unavailable`
  
   I find this error confusing for the same reasons as for when I ran `plugin-info`.

Build was from source, commit `65830d7996ffab21862ded6c4889980f441ac2e0`

**Comment by evan2645** [comment]
Most of these subcommands have since been removed. Closing due to staleness
