### ISSUE TITLE
Agent has a window during which it cannot recover from a restart

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#613]
The agent keymanager can generate a new key internally and return it, however when rotating the key, there is no way to persist the new key if and only if the agent's SVID was successfully renewed. The result is that if the agent restarts between the time it generates a new key and the time that the server fulfills its rotation request, the cert and key will no longer match.

Refactor agent's key manager interface to make rotation graceful and recoverable

**Comment by APTy** [comment]
We could solve this by extending the `KeyManager` plugin API to give the rotator module control over storage of the new key:

```proto
message StorePrivateKeyRequest {
    bytes privateKey = 1;
}

message StorePrivateKeyResponse {}

rpc StorePrivateKey(StorePrivateKeyrRequest) returns (StorePrivateKeyResponse)
```

Alternatively, we could have the `KeyManager` implementation maintain state about the key it just generated, but I think that's needlessly complex, and we'd still need a new rpc method to acknowledge successful renewal.

I take a shot at this if you like
