### ISSUE TITLE
Support multiple node attestors

### ISSUE THREAD

**Issue by ajessup** [spiffe/spire#632]
In some cases it is valuable to be able to define node attestation using multiple sources of third party trust (as is possible today for workloads).

It would be valuable, for example, to be able to identify a node based on both AWS and Kerberos selectors, or Kerberos and Kubernetes selectors. For example, a it should be possible to create a policy whereby a node would only be attested if it’s joined to a pre-defined Kerberos domain and belongs to a known K8S cluster and runs under a given namespace and services account.

**Comment by drrt** [comment]
Related https://github.com/spiffe/spire/issues/555

**Comment by andrewdomin** [comment]
Support for multiple attestors makes this platform quite powerful. Until this functionality is officially supported, is there an alternative suggested approach for enabling multiple node attestors without writing a custom plugin?

**Comment by azdagron** [comment]
I think this is a very interesting feature. Implementing this properly is going to require quite a bit of design work. I think we'd like to see some more concrete use cases laid out before we considered picking up this work.

I'm going to close this out until then.
