### ISSUE TITLE
Registration/delegation of downstream spire servers 

### ISSUE THREAD

**Issue by trilokgm** [spiffe/spire#635]
When spire servers are deployed in a hierarchy, the upstream server should be able to track the downstream server and the trust domain delegation. 
This allows to obtain intermediate chain only when authorized. 

See details shared by Evan in this [document](https://docs.google.com/document/d/1Mbsbo2xuWajU1h_XxNx2ChmNv4RIfZlb7VIaS2qM5K4/edit?usp=sharing). 
For previous discussions by @APTy @evan2645 @deepak-vij , please refer to #533 .

Detail design document to be published soon.

**Comment by evan2645** [comment]
s/obtain intermediate chain/obtain intermediate CA certificate/

**Comment by azdagron** [comment]
The code has been completed but hasn't been enabled until we can do more testing. We'll track that progress via #533. Closing this ticket.
