### ISSUE TITLE
Generate intermediate CA certificate for downstream spire server in hierarchical deployment. 

### ISSUE THREAD

**Issue by trilokgm** [spiffe/spire#637]
Downstream spire servers should be issued an intermediate CA certificate which can be used to sign certificates for the workloads attached to a downstream spire server. 
Currently, all intermediates and rootCAs are bundled in single trust bundle file. 
The upstream CA plugin should be able to retrieve intermediate certificates, chain and rootCA bundle. 

Detail design document to be published soon.

**Comment by evan2645** [comment]
Good news! This work has already been completed via https://github.com/spiffe/spire/pull/600 and https://github.com/spiffe/spire/pull/611

Gonna close this out - please feel free to re-open if necessary
