### ISSUE TITLE
Support and verification for message based communication(like MQTT) among workloads (including hierarchical spire) 

### ISSUE THREAD

**Issue by skdwriting** [spiffe/spire#646]
Background:
In most of the Edge Cloud Platforms, the workload to workload communication is message based like MQTT. Indirectly, there is no "direct" communication between the workloads. Hence, we need a suitable method in spiffe to handle this. 
Consideration: 
jwt token based communication support (basic) is available in spiffe (refer [#495](https://github.com/spiffe/spire/issues/495), [#531](https://github.com/spiffe/spire/issues/531), [#544](https://github.com/spiffe/spire/issues/544),  [#545](https://github.com/spiffe/spire/issues/545),[ #616](https://github.com/spiffe/spire/issues/616))

Hence one of the solutions to message-based workload - workload communication could be using jwt.

Scope:
1. Basic verification of JWT : Workloads using JWT tokens for communication. (fetch, verify apis and basic flow)
2. JWT in message based wl-wl communication: workloads communicating through MQTT using jwt for identity
3. Basic edge scenario verification using a simple case (single Spire server)
4. jwt in hierarchial spire server mode.
[[Refer some discussions on the same in the document prepared by Evan here]](https://docs.google.com/document/d/1Mbsbo2xuWajU1h_XxNx2ChmNv4RIfZlb7VIaS2qM5K4)

Tentative Idea:
workload1 fetches the jwt token from local spire agent --> add this to the message --> workload2 validates the jwt token with local spire agent
spire agent gets the signed token from the spire server.

Other option:
Explore Message Broker security (mTLS..). Then, jwt may not be needed

Optimization/Constraints Notes:
1. In a normal case, all the message needs to be with jwt tokens and validate to be done. This can affect the performance in edge? If yes, what are the other options?
2. Currently the validate is a workload api and goes to spire agent in case of jwt. Can this be local to workload?
3. Hierarchical spire server scenario in Edge to be handled. jwt chaining ?! 

We will update the design, flow and other details as a separate document.

**Comment by skdwriting** [comment]
MQTT/Message based:
Option1: 
WL1 fetch, WL2 validate JWT
Option2: (preferred) - may be no JWT needed to solve this requirement! :)
WL1 <-> Message Broker ---> mTLS (need to explore)
pub/sub will be secured at broker
Option3:
WL1 fetch ->Broker validate JWT 

Option 2 may be good option. Even the hierarchical spire server model can work automatically?
1 and 3 can impose perf and other impacts in edge scenarios...looks like

**Comment by skdwriting** [comment]
We are able to test the basic MQTT based workload to workload communication based on CA. So, currently, we may not need jwt based solution.
Also, this method can help us to test the hierarchical spire easily..We will do that after some more testing on the current model.

**Comment by evan2645** [comment]
Ok, thanks for the update @skdwriting. I think we will need to tackle the JWT problem eventually... I am not sure what the best approach is at the moment. We either need to distribute the JWKs across the whole tree, or we need a new token type which is chain-able

**Comment by skdwriting** [comment]
Yes, @evan2645 .
Some other updates and notes:
1. We are able to test hierarchical spire server (refer #635, #636)  with MQTT based workloads
2. We use sidecars with publisher, broker and subscriber. 
3. The verification is at broker, like publisher <-> broker, subscriber <-> broker 
4. In this case, the workload to workload identity is not established (in the real sense), though the broker takes care of the messaging based on the identity. FIXME : This we need to explore. Created the issue #660
