### ISSUE TITLE
Update agent's KeyManager interface to more closely match the server's

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#670]
The agent's keymanager interface currently passes private keys back and forth. This is far from ideal. Instead, we should implement an interface similar to that in the server's keymanager which allows the plugin to directly handle signing operations, and will position us well to support PKCS#11 hardware in the agent.

https://github.com/spiffe/spire/blob/master/proto/server/keymanager/keymanager.proto

**Comment by gaetanww** [comment]
What is the status on this issue?
- Is it still in plans to have an agent's key manager with a PKCS11-like interface?
- Are there ongoing discussions about the new API?
- Is there an ongoing effort to implement a new API?

Thanks!

**Comment by azdagron** [comment]
Thanks for checking in, @gaetanww.

>Is it still in plans to have an agent's key manager with a PKCS11-like interface?

Yes! This is being actively worked on. We hope to have it in soon.

 > Are there ongoing discussions about the new API?

The interface will be the same as the server keymanager, albeit namespaced under the agent.

> Is there an ongoing effort to implement a new API?

I have a bunch of changes in a local branch. Unfortunately, it required some tangential work on the catalog system to support both the old and new KeyManager plugins at the same time that has yet to be completed. The push to get 1.0.0 out the door has sidelined the work somewhat. I hope to pick it up again this week or next. I'd expect this to be in on or around the 1.0.1 release.

**Comment by azdagron** [comment]
This has been completed.
