### ISSUE TITLE
Remove upstreamca spire plugin UT static files

### ISSUE THREAD

**Issue by trilokgm** [spiffe/spire#680]
Upstream ca spire plugin UT is implemented to use csrs and test certificate/keys uploaded as part of feature PR .These files need not be uploaded to the repo .

This needs to be fixed to remove static files and configurations needed for UT and use test utilities to create csrs and run testcases . If required , update test utilities to meet the test code requirements.

**Comment by evan2645** [comment]
Closing this out as stale
