### ISSUE TITLE
Enhancement: Support batching in registration APIs

### ISSUE THREAD

**Issue by ZymoticB** [spiffe/spire#696]
While reasoning about the scale required from spire-server to integrate into our environment I've been thinking about the following motivating scenarios for registration:

- Scheduling Churn of long-running workloads, e.g. a bug causes the system to lose all scheduling state and all long-running workloads are scheduled simultaneously. 10s of thousands of adds and 10s of thousands of deletes "as fast as possible"
- Batch Workload scheduling. Short-lived collections of workloads that spawn workloads in large batches (for example, YARN). Popular times for ETLs can exaggerate this issue. 10s-100s of thousands of adds "as fast as possible"

The current Unary model for the various registration APIs will lead to significant head-of-line blocking for schedulers attempting to make these large number of writes in batches. This is potentially solved with multiple connections to the registration API but it seems prudent to make use of grpc facilities and create a bi-directional stream API for this instead. A stream API that enables batching within the messages will also allow the server side to do optimizations at the datastore level.

A potential starting point for the proto.

```
// Removes are always processed before adds.
message UpdateEntriesRequest {
  repeated RegistrationEntry entriesToAdd = 1;
  repeated RegistrationEntry entriesToRemove = 2;
}

message UpdateEntryResult {
  RegistrationEntry entry = 1;
  oneof error {
    string error = 2;
  }
}

message UpdateEntriesReply {
  repeated UpdateEntryResult addedEntries = 1;
  repeated UpdateEntryResult removeEntries = 2;
}

rpc UpdateEntries(stream UpdateEntriesRequest) returns (stream UpdateEntriesReply)
```

There are definitely issues in there, but I think it's enough to motivate the discussion. Alternatives include a message that has some sort of "action" in it (add vs remove), supporting in-place updates (instead of forcing remove, then add).

**Comment by evan2645** [comment]
This has been fixed in the new Entry API

**Comment by evan2645** [comment]
And by fixed I mean it is supported :)
