### ISSUE TITLE
Registration API List* and FetchEntries endpoint should be paginated

### ISSUE THREAD

**Issue by ZymoticB** [spiffe/spire#697]
Related to #346 the registration API currently has methods that can return responses with unbounded size. All 4 List endpoints as well as FetchEntries should be paginaged.

Potentially a FetchEntries method that took a non-empty argument that described the desired attributed to query on could completely replace the 3 List endpoint so pagination only needs to be implemented in one method for the registration API.

**Comment by evan2645** [comment]
The equivalent RPCs in the new Entry API are now paginated. Closing this as fixed
