### ISSUE TITLE
Agent Manager tests are flakey

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#705]
Agent Manager tests are overly complicated and end up exercising more code than necessary. One side effect is that it is littered with timers and timeouts that are sensitive to slow running environments (i.e. Docker in Travis CI).

Agent manager should be refactored to be passed an `svid.Rotator` and `client.Client` instead of instantiating its own. This will allow test infrastructure to be simplified.

Tests should also be refactored to be more deterministic and as much as possible remove the need for timeouts.

**Comment by evan2645** [comment]
Closing this as stale
