### ISSUE TITLE
Document how to use multiple SVIDs returned by the workload API

### ISSUE THREAD

**Issue by ajessup** [spiffe/spire#707]
We should document how to use the multiple SVIDs returned by the workload API? Why are there multiples? Is it just for API extensibility or rotation or something else?

_(The answer: The SPIFFE standard allows for multiple identities for each workload. If your workload doesn’t know how to choose amongst alternatives, it should just use the first one, as it is considered the default. Relevant spec bits:  https://github.com/spiffe/spiffe/blob/master/standards/SPIFFE_Workload_API.md#53-default-identity.  SPIRE has a outstanding issue to provide a way to demarcate which identity should be the default based on policy (multiple registration entries can match a workload, which results in multiple SVIDs)._

**Comment by azdagron** [comment]
I believe this documentation should live with the specification. There have also been additional works in this area (like the introduction of the hint field), that may have already addressed these concerns.

I'll close this issue for now. If there is additional clarification required, please open an issue up against the spec.

Thanks!
