### ISSUE TITLE
Update the Kubernetes workload attestor

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#715]
The k8s workload attestor currently only emits namespace and service account selectors, but we have access to much more than that. Update the attestor to emit additional information. At a minimum, the following should be emitted in addition to service account and namespace:
* pod labels
* container name
* container image
* node name

**Comment by azdagron** [comment]
As @mcpherrinm noted in the SPIFFE slack, we should also be able to pull the ReplicaSet or Deployment out of the pod listing.

**Comment by mcpherrinm** [comment]
Pod UID is another entry I'd like to be able to attest, so I can issue identities to individual pods.

**Comment by evan2645** [comment]
Someone mentioned on a call yesterday that the new kubernetes tokens have a pod uid in them... I could not find an example or documentation on these new tokens, but it is something we should explore, probably as part of this issue? If pod uid is included, it will be a huge improvement, as I think we should then be able to call api server and get the node name.
