### ISSUE TITLE
Define permissions for "admin" workloads

### ISSUE THREAD

**Issue by APTy** [spiffe/spire#716]
Currently a workload may have the "admin" attribute, which allows a number of actions: workload registration, generating join tokens, listing attested agents, etc.

The "admin" attribute is highly permissive and there is no way to attenuate the permissions of a workload within the "admin" scope. For example, perhaps we want a workload that is only capable of creating workload registration entries and nothing else. Further still, what if we want to constrain the registrations within certain spiffe paths?

As a concrete example, consider you have two admin workloads:
 - `spiffe://example.org/orchestrator/services` - launches stateless service workloads
 - `spiffe://example.org/orchestrator/storages` - launches stateful storage workloads

These admin workloads share the same spire control plane.

Creating a naming scheme that allows you to differentiate from `foo` the service and `foo` the storage is important:
 - `spiffe://example.org/service/foo`
 - `spiffe://example.org/storage/foo`

Even more, you want to prevent one admin workload (whether accidentally or otherwise) from registering identities in another admin workload's "namespace". Ideally, you could create an admin policy like:
``` 
allow "spiffe://example.org/orchestrator/services" to create registration entries
with spiffe id prefixed by "spiffe://example.org/service/"
```
Or something similar

**Comment by mcpherrinm** [comment]
Another potential use-case:

Say you have a process per k8s namespace, which is registering pods in that namespace.  I may want to have spiffe://example.org/namespace/service, and each k8s registrar has a fixed prefix, so we can reduce risk by restricting to a point in the heirarchy.

Counterpoint:
Should these just be different trust domains?

**Comment by APTy** [comment]
> Should these just be different trust domains?

It's a possibility; however, if the two orchestrators share the same spire clusters, they are bound to the same trust domain. The alternatives are that spire needs to change to support multiple trust domains per cluster (which I think is a much larger change), or users have to deploy multiple spire clusters (which I think adds too much operational complexity)

**Comment by evan2645** [comment]
We now have the `Notifier` plugin which has a feature `NotifyAndAdvise`. This allows the plugin to advise SPIRE core on whether or not a particular event should succeed or not. In thinking more about this, I wonder if we can use this facility to provide pluggable authz. We can call `NotifyAndAdvise` when registration entries are created/updated/deleted, and allow the plugin to evaluate whatever authz logic is necessary. While it's not exactly a use case we had in mind for Notifier when we put it in, it does give a lot of flexibility, and I think only minimal changes would be required in core to support it.

**Comment by APTy** [comment]
I like that idea. Here's some quick thoughts on what that could look like:

```
message RegistrationRequest {
    // The authenticated identity of the actor making a request.
    //
    // For TCP callers, this is the SPIFFE ID of the peer.
    // For UDS callers, this is the SPIFFE ID of the SPIRE Server.
    string caller = 1;

    // The fully-qualified name of the proto rpc service method.
    string full_method = 2;

    // The protobuf request payload serialized as JSON.
    string payload = 3;
}

message NotifyAndAdviseRequest {
    oneof event {
        ...
        // RegistrationRequest is emitted during calls to the Registration API.
        //
        // Specifically, this event is emitted *after* the caller is authenticated
        // and authorized as an admin, but *before* any application logic occurs.
        //
        // If an error is returned, the Registration API request will fail with
        // the same error.
        RegistrationRequest registration_request = 2;
    }
}
```

Maybe we can massage this a bit in the next couple weeks

**Comment by APTy** [comment]
Resurrecting this issue after some discussions with @azdagron and @amoore877..

Rather than create a new `Notifier` plugin, an alternative would be to expose some server configuration for the "bring your own main.go" approach. This configuration would enable users to hook in custom grpc interceptors to do their own logging or authorization decisions.

Any thoughts on taking one approach over the other?

**Comment by evan2645** [comment]
This seems like it will be a relatively common use case. Asking folks to compile from scratch in order to leverage it feels pretty heavy handed (can't use the artifacts now, what about version number, etc). IMO it is neat to have the ability to bring your own main.go, and afford additional flexibility when doing so, but to me it feels like that should not be the only answer for something like this.

I also agree that the notifier approach feels a little clumsy... the notifier in general feels clumsy.

Another option could be first class OPA support? Perhaps either by calling out to it, or by linking it and configuring SPIRE with rego policy?

**Comment by APTy** [comment]
Agreed it will probably be pretty common, and should probably eventually get integrated into SPIRE as a first class citizen. To start, I think I agree it makes sense to go for the Notifier approach, do some prototyping of an OPA integration and get it going in production, and then start to figure out how to mainline it.

**Comment by prasadborole1** [comment]
Just to revive this discussion again and document some sort of requirements. We're probably looking at mapping like:
`Actor -> Role` and `Role -> Permission`
e.g. `spiffe://example.ca/foo/workload -> registrant`

```
registrant ->  {
	permissions: “CREATE”, “UPDATE”, “DELETE”,
	namespace: “spiffe://example.ca/foo”,  “spiffe://example.ca/bar”,
}
```

In the above case `spiffe://example.ca/foo/workload` is admin workload which is mapped to a role `registrant`. 
The role `registrant` has permissions associated with it which govern what registration APIs this workload is authorized for and what spiffeID patterns this workload is allowed to work on.
