### ISSUE TITLE
Update k8s example to use postgres

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#734]
Update the k8s example created in #733 to use postgres as SPIRE server's datastore. It should probably use a persistent volume.

**Comment by scotte** [comment]
Created #752 to store database password as a k8s secret.

**Comment by scotte** [comment]
This is pretty straightforward - I have it working (with postgres running as a single-instance statefulset with a persistent data volume), but I'm not sure if this should go into the spire repo as an example, the spiffy-examples repo, or spire-tutorials - too many example repositories! :-/

**Comment by azdagron** [comment]
Awesome. I've started a little infrastructure for running a bunch of nightly scenarios out of spire against a series of check in configurations. I had to step away to focus on another change but am hoping to get back to it soon (today maybe). I think we should at LEAST put it in spire as a nightly systems test.

**Comment by scotte** [comment]
Definitely! It would also be worth running the nightlies with a multiple server setup - with my current configs, basic balancing is achieved simply by increasing the number of replicas for the server as a NodePort service is already in use. Although, unless the test has multiple agents it won't really be testing much.
