### ISSUE TITLE
Update k8s example to deploy multiple SPIRE servers

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#735]
Update the kubernetes example created in #733 to deploy multiple SPIRE servers, and ensure that agents are striped across both.

**Comment by scotte** [comment]
The load balancing part should be easy in Kubernetes, even a basic NodePort service will round-robin requests to all backing pods. An external LoadBalancer is better from a performance and production perspective, but then becomes platform-dependent. Kubernetes makes it pretty easy for this to be a deployment-time decision, so a NodePort example is probably the simplest.

**Comment by scotte** [comment]
One thing we will need is some connection controls in the SPIRE agent - #753 created for tracking that.

**Comment by scotte** [comment]
Also note this is dependent on using a database - see #734.

**Comment by evan2645** [comment]
Closing this as it's no longer aligned with our testing goals
