### ISSUE TITLE
Explore options for automatic registration of kubernetes workloads

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#739]
One of the major pain points of running SPIRE in kubernetes is the need to register workloads independently of creating and scheduling them. Most users will want a way to automatically register workloads in SPIRE server, enabling them to interact only with kubernetes API server in order to get SPIRE fully deployed and operational.

There are many points to consider here. Exactly what should we watch the API server for (e.g. new deployments, scheduling/placement events, etc)? How and where should a SPIFFE ID be declared/assigned (e.g. as an attribute of the deployment, as a dedicated CRD, etc)? Should we simply generate "automatic" SPIFFE IDs a-la Istio using namespace + service account? How do we manage the lifecycle of the entries we create i.e. know when to delete them?

@enricoschiattarella has done some work in this area, and left some code for us [here](https://github.com/spiffe/spire-k8s/tree/master/src/spire-k8s/skbridge). I am sure he has a lot of thoughts and opinions on this.

I think we will find that there are several ways to do this, and that one approach will not fit all use cases and workflows. We should engage the community to find out what folks think here, what they would like to see. For this issue, we should capture at least three fully-fleshed-out options that have community consensus as being "good".

**Comment by evan2645** [comment]
Here is a link to the design for @enricoschiattarella's work: https://docs.google.com/document/d/14PFWpKHbXLxJwPn9NYYcUWGyO9d8HE1H_XAZ4Tz5K0E/edit#heading=h.7wpw1n5u5zdr

Included in its scope was to inject a sidecar and configure the pod to have workload API socket mounted into it. For this work, that is out of scope (though we should get there eventually).

**Comment by mcpherrinm** [comment]
I have a small prototype of one potential approach.  This uses the Kubernetes API to watch all pods and nodes created in Kubernetes and register them with SPIRE.

As is, it has a number of bugs and is not suitable for production use, but does function somewhat.

https://github.com/mcpherrinm/spire-eks-ra

**Comment by evan2645** [comment]
This has been researched and it was decided to begin with an admission controller. The code can be extended in the future to implement a watcher mode. That work is already under review in #885
