### ISSUE TITLE
Introduce Node API v2

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#742]
This issue is to track a refactoring and cleanup of the node handler code. The node handler code has grown over time in funny directions. Some targeted issues have been created (e.g. #679) but fixing those would be more properly accomplished by a wider re-evaluation of code organization and flow.

**Comment by evan2645** [comment]
The node api has become pretty soupy with a lot of the recent changes we've made. At this point, we'd probably be better off introducing a v2 of this api. Updating this issue accordingly

**Comment by evan2645** [comment]
Please see https://github.com/spiffe/spire/issues/1057#issuecomment-548572755 for more information on the future of this change

**Comment by azdagron** [comment]
This has been completed with the server API refactor.
