### ISSUE TITLE
Administrative ability to specify the default SVID for a workload

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#744]
The SPIFFE Workload API specifies that in the case where multiple SVIDs are issued to a workload that the first SVID returned should be the [default](https://github.com/spiffe/spiffe/blob/master/standards/SPIFFE_Workload_API.md#53-default-identity).

SPIRE has no administrative function allowing operators to tag an SVID as the default or otherwise manipulate the ordering of SVIDs returned to workloads.

**Comment by bri365** [comment]
After some discussion with @rturner3 @amartinezfayo @zmt we touched on an idea for a long term solution. Adding a priority field to Entry (default 0 for backwards compatibility) would open the way for administratively prioritizing entries if a workload receives multiple SVIDs. If two entires share the highest priority, we would fall back to SPIFFE ID length + alphabetic sorting.

**Comment by esweiss** [comment]
This is a priority for us.

**Comment by bri365** [comment]
A [proposal](https://docs.google.com/document/d/1sPUkYZWosXI6xbA6QiX4O1ZMbmWFR3w-BH49M1MRQwk/edit?usp=sharing) has been drafted

**Comment by azdagron** [comment]
We talked about this today during a maintainer call. The consensus was that an opaque label on the Workload API X509SVID response message seemed to cover all of the practical use cases presented thus far?

There was some concern expressed over the complexity introduced by some sort of priority system. In our experience, these kinds of semantics are hard to reason about and are usually not tended to carefully by operators, where things tend to get a bunch of "magic number" assignments.

Is there a practical scenario we've missed that couldn't be reasonably handled with just a label empowering workloads to cherry-pick the right identity?

**Comment by evan2645** [comment]
@bri365 the proposal you linked is for SIG-Spec, right? If so, should we close this issue, and then continue work in #755 in SPIRE?

**Comment by bri365** [comment]
SPIRE will still need to implement whatever SIG-Spec decides, so we can leave this issue here for that or we can close it and open a new issue once https://github.com/spiffe/spiffe/issues/156 is resolved.

**Comment by azdagron** [comment]
I believe this will be covered by #2588.
