### ISSUE TITLE
Library with a function to easily use grpc with spiffe workload credentials

### ISSUE THREAD

**Issue by mcpherrinm** [spiffe/spire#746]
I'm working on migrating from using the unix socket workload registration to the spiffe-authenticated one, and was surprised at the amount of code it seems to take to call the API.

with the unix socket, I can do something like this:

```
   spireServer := "unix:///tmp/spire-registration.sock"
    spireConn, err := grpc.Dial(spireServer, grpc.WithInsecure())
    if err != nil {
        log.Fatal(err)
    }
    registrationClient := registration.NewRegistrationClient(spireConn)
```

Ideally, it would be as simple as:

```
  workloadAPI := "/var/run/envoy-agent/socks/workload.sock"

   spireServer := "dns://spire-server.default.svc.cluster.local"
    spireConn, err := grpc.Dial(spireServer, spiffe.WithWorkloadCredentials(workloadAPI))
    if err != nil {
        log.Fatal(err)
    }
    registrationClient := registration.NewRegistrationClient(spireConn)
```

That function call returns an appropriate grpc.DialOption (probably a PerRPCCredential?) that retrieves credentials from the workload API

**Comment by mcpherrinm** [comment]
Prototype:
https://github.com/mcpherrinm/spire-eks-ra/blob/master/grpcspiffe/grpcspiffe.go

**Comment by evan2645** [comment]
We updated the go-spiffe library with a bunch of convenience functions for doing things that are backed by credentials from the workload api... listeners, dialers, etc... there is also a DialGRPC function. Do these updates satisfy this issue, or you think there are still some things missing or things that should be changed?

https://godoc.org/github.com/spiffe/go-spiffe/spiffe

**Comment by mcpherrinm** [comment]
I think a DialGRPC function in go-spiffe is likely sufficient.  I'll close this then, and any further needs can be more specific follow-up tickets.  Thank you!
