### ISSUE TITLE
Use Kubernetes secret for SQL datastore plugin password

### ISSUE THREAD

**Issue by scotte** [spiffe/spire#752]
Currently, the SQL datastore plugin uses a plaintext password [in the configuration](https://github.com/spiffe/spire/blob/master/doc/plugin_server_datastore_sql.md#database_type--postgres). In kubernetes this should probably be a secret rather than a plaintext password in a config map.

**Comment by evan2645** [comment]
Any thoughts on how to better address this @scotte?

**Comment by scotte** [comment]
I think there's a few different ways - it would be nice to avoid coding up something that is Kubernetes specific One way to do that (not sure it's the best way, but it's one way) would be to have a `#include` type mechanism for the configuration file. The main part of the config file could remain a configmap, and at the relevant part would include a file from a secret that contains the DB connection string.

Is it worth all that? Kubernetes secrets are not super secure, but at least it makes the database connection string (including password) opaque, so it's at least a bit harder to accidentally expose that password.

**Comment by azdagron** [comment]
I _think_ this is now possible today by:
1) populating the container environment from the configmap/secret 
2) Use the envvar in the configuration with the `-expandEnv` CLI flag.

Please let us know if this is not the case.
