### ISSUE TITLE
Expose/create gRPC connection tuning options for SPIRE agent

### ISSUE THREAD

**Issue by scotte** [spiffe/spire#753]
To facilitate multi-server configuration behind a TCP load balancer, it would be useful to expose some knobs in the SPIRE agent for gRPC connections to the SPIRE server.

Off the top of my head, some possible/useful controls would be:

- Connection idle time.
- Maximum connection time.
- Connection request limit.

We need to provide enough knobs to allow a slow rate of connection churn - enough entropy to keep connections balanced across servers over time, letting a mid-tier load balancer handle the rest.

**Comment by drrt** [comment]
Maybe this should be configured and enforced on the server side of the connections?

**Comment by scotte** [comment]
There is probably a good case to have controls on both the agent and server side - I definitely agree with you that server side is probably a good idea, especially in a case where there's a diverse set of agents that may not be configured with optimal/consistent settings.

**Comment by scotte** [comment]
Related - #345

**Comment by azdagron** [comment]
I think we have our bases mostly covered today. If there is a specific configurable that we need to expose, please open a new issue.
