### ISSUE TITLE
TestLimit in pkg/server/endpoints/node can fail in travis

### ISSUE THREAD

**Issue by ZymoticB** [spiffe/spire#755]
This was noticed in #749. Currently the limiter in `pkg/server/endpoints/node` depends on `x/time/rate.Limiter` which internally uses the global funcs from the time package which has lead to the tests being written with a direct dependency on real time. It's always a struggle to keep tests like that speedy, but resilient to any sort of pause (for example a cgroup with a cpu_quota).

It seems to me the best way forward is to create an unexported interface for the usage of `x/time/rate.Limiter`, which is currently only [ReserveN](https://godoc.org/golang.org/x/time/rate#Limiter.ReserveN) and then mock that in tests. This will enable testing behaviours without relying on real time.

**Comment by amoore877** [comment]
Noticed this issue with current build attempt on #747
`pkg/agent/endpoints/sds` "TestStreamSecretsApplicationDoesNotSpin" also suffers from real time dependency failures

**Comment by evan2645** [comment]
This is stale, we don't use Travis anymore and we don't have the Node API anymore. Closing it out
