### ISSUE TITLE
The k8s workload attestor should use the secure kublet port

### ISSUE THREAD

**Issue by ajessup** [spiffe/spire#760]
Currently the kubernetes workload attestor relies on the kubelet read-only port to retrieve metadata to identify a workload. This port is deprecated and in some instances (eg. from an agent running as a linux process attempting to perform attestation on a v1.13.2 k8s cluster) is already no longer available.

The solution is to update the attestor to use the [secure kubelet port](https://kubernetes.io/docs/reference/access-authn-authz/controlling-access/#api-server-ports-and-ips) `:10250`

**Comment by ajessup** [comment]
cc @azdagron @andrewalexander

**Comment by scotte** [comment]
Note that running SPIRE agent as a DaemonSet is the current workaround, and is also the recommended configuration. Currently, a DaemonSet still has access to the insecure port, but we don't know for how long.

**Comment by mcpherrinm** [comment]
Amazon's EKS AMI doesn't listen on the insecure port by default. https://github.com/awslabs/amazon-eks-ami/issues/128
