### ISSUE TITLE
Reconnect to SPIRE server on error as appropriate

### ISSUE THREAD

**Issue by scotte** [spiffe/spire#769]
While investigating #766 in a multiple SPIRE server deployment with a load balancer I saw a case where the gRPC connection from the SPIRE agent to server was in an OK state, but the server is unable to service requests. The SPIRE agent kept retrying the request on the same connection in futility. In this sort of case, the SPIRE agent should try a new connection on the chance that it will get a good server.

It's probably worth looking at all cases where the SPIRE agent might have a failure mode where it does not currently reconnect on error, and a re-connection attempt would never be worse than not trying to reconnect.

**Comment by evan2645** [comment]
@scotte do you recall the exact error you were receiving?

**Comment by scotte** [comment]
I do, but my larger concern was making sure we've covered all the cases where this could happen versus my exact situation (which was using a configuration with very short TTLs to cause failure, and not a configuration that would normally be used).

The specific error I ran into was:
```
time="2019-02-21T22:51:46Z" level=error msg="synchronize failed: rpc error: code = Unknown desc = agent is not attested or no longer valid" subsystem_name=manager
time="2019-02-21T22:51:46Z" level=error msg="failed to consume entire SVID update stream: rpc error: code = Unknown desc = agent is not attested or no longer valid"
```

Also see https://github.com/spiffe/spire/pull/795
