### ISSUE TITLE
Optional expiry field and scheduled pruning of Registration Entries

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#773]
It would be helpful to add an optional `expiry` field (much like `JoinToken`) onto `RegistrationEntry` Additionally, to create an optionally configured scheduled pruning of `RegistrationEntry` (and probably `JoinToken`) on server-side.

The use case for this:
1. Assume high-workload-volume (10s of GB/day in registration entries) environment with short-lived workloads
2. Generally it is the responsibility of some admin process to register and de-register the workloads
3. The admin process may be irresponsible, break, or otherwise not fulfill the de-register requirement. Or, multiple such processes exist and it is preferred to have a generalized de-registration solution rather than each process being modified to include de-register logic.

Rather than letting the datastore continually pile up, having an automated way for the server to clean itself up would be helpful. Process would be:
1. Admin process registers the workload(s) with some expiry, with confidence the workload(s) would finish its work/become obsolete by that expiry time.
2. Admin process may or may not de-register the workload(s).
3. Pruning comes in on configured scheduled and checks for registration entries that have `expiry` set and are expired. Since there is [extra work to be done](https://github.com/spiffe/spire/blob/master/pkg/server/plugin/datastore/sql/sql.go#L1069) in deleting registration entries, first fetch all such entries and then call the existing delete logic.

**Comment by ZymoticB** [comment]
One concern that @azdagron and I discussed was that this implementation needs to ensure that it is low impact. With that in mind (as you are alluding to in the final point) there should be no guarantee that a registration will expire at exactly its expiry time.

This enables the implementation to have lots of control over how aggressive the pruning is, how often it happens, etc.

IMO this should start with a single policy focused on splaying cost over time to have minimal impact on tail latencies.

**Comment by mcpherrinm** [comment]
When implementing similar systems, we've thought about this more like a garbage collector.  Sometime after the expiry, the registration entry will be removed from the database.

To have the Expiry be a hard deadline, we could have no certificate be issues with a not_after time beyond the Expiry.

One thing I'd like to see is automatic expiry if a node goes away.  Nodes do not need to be explicitly registered, they can just connect and attest.   Since registration entries have a parent SPIFFE ID, it should be possible to notice when no node with that Parent ID has attested for some period of time and either immediately remove it or mark it for pending GC (ie, set the expiry).

**Comment by ZymoticB** [comment]
I actually had a reference to a keynote presentation about the go GC but decided to be briefer, I think we're on the same page :)

You do note something interesting, if a registration TTL is 10 and the cert TTL is 10, the cert will be refreshed after 5 so the cert will live past the registration TTL. I'm not sure this is something worth adding complexity to prevent.

The node GC could also be useful though the thresholds would need to be careful to avoid transient network issues tripping it. The eviction API (which I don't know if it has landed or not) should cover most of this. I agree this would be a good backup for misbehaving systems that fail to get evicted.

**Comment by azdagron** [comment]
Eviction has landed (#693) and is in the 0.7.3 release.

If memory serves, a very minor refactor would be needed to cap the SVID TTL to the registration entry expiry, but it seems pretty doable and useful.

**Comment by ZymoticB** [comment]
Capping the SVID TTL would net us an SVID that expires at most 50% of the TTL after the expiry of the registration entry right?

**Comment by amoore877** [comment]
I would be interested about the behavior of cert renewal if we were to cap TTL by looking at expiry; refresh logic is not something I've looked into detail about by if a cert wants to be refreshed at 50% TTL, and initial TTL is 10, wouldn't we have a bit of weird traffic with refresh at 5, then 2.5, then 1.25... and so on until latency overtakes the process and 0 TTL is available (which is also a case to handle in itself)?

**Comment by amoore877** [comment]
Pushed #776 with initial API for this

**Comment by evan2645** [comment]
> One thing I'd like to see is automatic expiry if a node goes away. Nodes do not need to be explicitly registered, they can just connect and attest. Since registration entries have a parent SPIFFE ID, it should be possible to notice when no node with that Parent ID has attested for some period of time and either immediately remove it or mark it for pending GC (ie, set the expiry).

This is an interesting idea... This issue has been closed now that the pruning feature is complete, but if you're interested in the above, it would be great if you could open a different issue so we can discuss this further. There are probably some other smart things we can do when we notice that an agent has expired.
