### ISSUE TITLE
UpstreamCA text unaligned in SPIRE Overview diagram

### ISSUE THREAD

**Issue by ZymoticB** [spiffe/spire#774]
The diagram in this section https://spiffe.io/spire/overview/#all-about-the-server has unaligned text, "UpstreamCA"  isn't centered in it's shape like the rest of the shapes in the diagram.

![image](https://user-images.githubusercontent.com/885383/53599676-9e471780-3b5c-11e9-8b57-84632b7ad74c.png)

**Comment by jennybeth** [comment]
Hilariously, I spent a BUNCH of time trying to fix this in draw.io and it just kept floating up to the top of the box! 

I will look into this. 

Thanks!

/Jenny Beth

**Comment by jennybeth** [comment]
Fixed. Please have a look!

https://github.com/spiffe/spiffe.io/pull/57
