### ISSUE TITLE
Misleading intro docs: spire-server doesn't always use a self-signed CA

### ISSUE THREAD

**Issue by ZymoticB** [spiffe/spire#775]
In this section https://spiffe.io/spire/overview/#a-day-in-the-life-of-a-spire-deployment point 2 states

> The server generates a self-signed certificate (a certificate signed with its own private key); the server will use this certificate to sign SVIDs for all the workloads in this server’s trust domain.

To my understanding, this is only true if there are 0 upstream CAs available (https://github.com/spiffe/spire/blob/master/pkg/server/ca/manager.go#L380). I think this could be clearer as it seems to indicate spire doesn't integrate with existing PKI.

**Comment by ZymoticB** [comment]
Same section, number 8
> The server calls the AWS API to validate the proof.
The proof in this case is validated using pre-shared public material (https://github.com/spiffe/spire/blob/master/pkg/server/plugin/nodeattestor/aws/iid.go#L37), the dependency on the AWS API for node attestation is used to implement some "anti-tampering" logic https://github.com/spiffe/spire/blob/master/pkg/server/plugin/nodeattestor/aws/iid.go#L142

**Comment by ZymoticB** [comment]
@jennybeth another one for you

**Comment by jennybeth** [comment]
Thanks, @ZymoticB. Adding it to my list. Many thanks.

/Jenny Beth

**Comment by jennybeth** [comment]
Fixed in https://github.com/spiffe/spiffe.io/pull/61.
