### ISSUE TITLE
Add instructions to SPIRE Getting Started on Kubernetes to explain how to introspect the running pod 

### ISSUE THREAD

**Issue by jennybeth** [spiffe/spire#796]
Guide tells users to introspect the running pod for kube-apiserver to determine which certificate Kubernetes uses to validate service accounts but doesn't explain how. 

* **Version**: 
* **Platform**: 
* **Subsystem**:

**Comment by anvega** [comment]
The reference file is no longer in this repository and is now at https://github.com/spiffe/spiffe.io/blob/master/content/docs/latest/spire/installing/getting-started-k8s.md
