### ISSUE TITLE
Evaluate use of andres-erbsen/clock import

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#797]
We have taken a dependency on github.com/andres-erbsen/clock in order to improve our test suite, however that project is unmaintained, declared as experimental, and has been failing tests for a long time now.

We should either pull this code in (it's only a few hundred lines) or switch to an actively maintained project (there are dozens of forks).

**Comment by ZymoticB** [comment]
I discussed this with at least @azdagron before that diff that added it landed. Totally on the same page with quality signals. Anecdotally, we've been running this clock library in production for 3-ish years and have never had a problem related to it. The non-mock code is very small, and I'm not aware of outstanding issues relating to the non-mock code.

I considered vendoring it at the time (as you suggest) but ultimately decided not to.

Again, totally agree this could be better.

**Comment by evan2645** [comment]
Going to close this for now... nobody seems to be very worried about it. We can revisit in the future if we decide to make a push in this direction as a more concerted effort.
