### ISSUE TITLE
observability logging/metrics, standards, and testing

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#799]
Proposing metrics and standards based on work my organization completed prior to switching to a SPIRE solution. Some of these may already exist, but are included for completeness:

- [ ] Ideally metrics should have all relevant information for that instance in time via the implemented `AddLabel` function, as long as the information is not a security/privacy risk (ex. private keys)
- [X] Successful SVID issuance, for each type (already complete)
- [ ] Failed SVID issuance, even better is metrics down to type of failure
- [ ] Success/failure on server handler (seems to be missing one for AuthorizeCall)
- [X] Success/failure on attestation (done)
- [ ] ^--distinguishing attestation types/plugins (not done)
- [x] Along the same lines as above, metrics of interest inside each plugin.
- [ ] Success/failure of starting up/`run`/configuration of various modules (which would overlap with above)
- [x] Metric names must be kept in a common file with documentation, for consistency of use, decreasing redundancy, and decreasing conflicting meanings.
- [x] Metric names should be standardized in some hierarchical/logical format (ex. not `attestor_name`, which is very generic, but perhaps something like `agent.attestor.workload.attestor_name`, which provides much more context and does not conflict with other similar names).
- [x] Unit tests should verify that metrics are actually emitted/attempted to be emitted. This will add burden to testing but will significantly increase confidence in production metrics.
- [ ] The telemetry package itself needs unit testing (may be addressed by #817).

Logging standards:

- [ ] At minimum, wherever a metric is emitted, a log must be as well. Ideally logs should have all relevant information for that instance in time via fields (below), as long as the information is not a security/privacy risk (ex. private keys).
- [ ] Of particular interest to the above would be serial numbers of X509s, so that the number of unique certificates issued could be tracked.
- [ ] Logging must not use string formatting. Instead, use logging fields. Ex. not `wla.c.L.Debugf("PID %v attested to have selectors %v", pid, selectors)` but instead `wla.c.L.WithField("pid", pid).WithField("selectors", selectors).Debugf("PID attested to have selectors")`
- [ ] Log field names must be kept in a common file with documentation, for consistency of use, decreasing redundancy, and decreasing conflicting meanings.
- [ ] Decide on and enforce desired casing for logs (all lower? regular sentence structure?)
- [ ] Decide on and enforce desired casing for error messages

**Comment by amoore877** [comment]
Separate issues / PRs should be made for each plugin to have metrics. Use the `HostService` `MetricsService` and `PluginMetrics` wrapper to add metrics to a plugin.
Marking "metrics of interest inside each plugin." as done

**Comment by amoore877** [comment]
Unit testing of metrics is a separate issue / PR per metric/plugin. This should be an enforced standard going forward and hopefully someday all old metrics will be logged through the good will of others.
Marking "Unit tests should verify that metrics are actually emitted/attempted to be emitted. This will add burden to testing but will significantly increase confidence in production metrics" as done and closing #830.

**Comment by amoore877** [comment]
closing `Metric names should be standardized in some hierarchical/logical format` since that is handled by metric plugins, flattening metric keys + labels

**Comment by azdagron** [comment]
I think we've tackled most of the things outlined in this issue and things have more or less settled around how SPIRE handles metrics. If there are additional features, guidelines, or suggestions in this area, please open a new issue. Thanks for this hard work, @amoore877 !
