### ISSUE TITLE
Graceful spire-agent restarts

### ISSUE THREAD

**Issue by APTy** [spiffe/spire#804]
Enable spire agent to restart and be upgraded without losing connections (interrupting streams). There are a few options for this, and we should be mindful of cross-platform support.

1. Cloudflare's [graceful-upgrades-in-go](https://blog.cloudflare.com/graceful-upgrades-in-go/) with [cloudflare/tableflip](https://github.com/cloudflare/tableflip).
2. Systemd [socket activation](http://0pointer.de/blog/projects/socket-activation.html) with [coreos/go-systemd](https://godoc.org/github.com/coreos/go-systemd/activation)

**Comment by azdagron** [comment]
I think this might be interesting, but haven't had many people ask for this in quite some time. Closing for now.

**Comment by edwbuck** [comment]
Related to #4783 , which was closed because the suggested approach may have been the wrong one.  There is still interest in an improvement.
