### ISSUE TITLE
AWS attestor error is not verbose enough

### ISSUE THREAD

**Issue by mcpherrinm** [spiffe/spire#812]
Log line looks like this:

time="2019-03-21T17:22:03Z" level=error msg="Attempted AWS IID attestation but an error occurred validating the IID: the IID has been used and is no longer valid" subsystem_name=node_api

It would be helpful if this included more information.  The SPIFFE ID of the agent who has used it would be the primary thing I'd like to see, because I might want to `spire-server agent evict -spiffeID <...>`. 

This came up because of #800 - I had to use kubernetes status to figure out which agent was broken, which isn't ideal.  SPIRE debugging should ideally be self-contained.

**Comment by azdagron** [comment]
This should be an easy fix. We should audit all of the built-in plugins that do the TOFU checks to ensure the ID is included in the error.
