### ISSUE TITLE
Add token review API support for k8s PSAT node attestor

### ISSUE THREAD

**Issue by scotte** [spiffe/spire#815]
The Kubernetes node attestors currently require SPIRE server to validate service account tokens, which is a problem in hosted Kubernetes environments where the token validation certificate is not readily available. An option to use the token review API would be useful in these environments.

**Comment by evan2645** [comment]
Just wanted to throw my two cents in here

IMO we should have a k8s node attestor plugin that "does the right thing" i.e. if you are using this plugin, you can be assured that you are following best practice. Currently, PSAT attestor has some configurations that are less secure than others.

I think the big thing here is that some folks might not want to take k8s API server dependence for node attestation to succeed... In reality, I am not sure if this is very important. Regardless, those folks can use the SAT attestor to get that property, and that attestor can be documented appropriately w.r.t. security concerns/considerations.

In my ideal world, PSAT attestor should require access to the TokenReview API, and should strongly associate the node to the agent either via agent ID or by additional selectors (or both). Doing so will overcome practically all of the sharp edges we have historically encountered in k8s node attestation, and give us a safe default that we can push people towards
