### ISSUE TITLE
Metrics on success/failure of SVID issuance

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#824]
Sub-issue of #799 

It seems we already have metrics on successful SVID issuance for each type of SVID. However it would be also helpful to have metrics on failure down to type of SVID and specific type of failure. This would aid debugging usage issues.

**Comment by esweiss** [comment]
This is a priority for us.

**Comment by azdagron** [comment]
I think this is handled by the per-rpc metrics emitted uniformly by the SVID API handler. Please let us know if this isn't sufficient.
