### ISSUE TITLE
Configuring node resolvers

### ISSUE THREAD

**Issue by APTy** [spiffe/spire#847]
For SPIRE users with hybrid infrastructure (cloud + on-prem), it's likely that node attestation and node resolution do not maintain a 1:1 mapping. In fact, users may want a single node resolver for all node attestation. For example, attest with `aws_iid` and `gcp_iit`, but resolve with `proprietary_plugin`. I see two options

## Node attestation configuration to select a node resolver
Node attestor plugins could provide a configuration option like `node_resolver`, which could select a particular node resolver by name. e.g.

```
NodeAttestor "aws_iid" {
    plugin_data {
        ...
        node_resolver = "my_resolver"
    }
}

NodeResolver "my_resolver" {
    plugin_cmd = "path/to/my_resolver"
}
```
This is a bit complex, and only a slight improvement over the alternative of overriding each resolver with your own plugin.

## A default node resolver
I could see this one going a couple ways..

(1) if users desire similar functionality, SPIRE could provide some common, configurable usage, such as granting a set of selectors to every node by default. this enables registrations that can span many infrastructure types.
```
NodeResolver "default" {
    plugin_data {
        selectors = ["org:example"]
    }
}
```
a sample of this is implemented [here](https://github.com/APTy/spire/commit/478509169121a10e814fe545c0b97ec90aadddb6)

(2) similar default fallback logic, but no functionality is provided by SPIRE itself
```
NodeResolver "default" {
    plugin_cmd = "path/to/my_resolver"
}
```

**Comment by evan2645** [comment]
@APTy I have filed #1127 which is related to this and am curious to hear your thoughts on it.

**Comment by azdagron** [comment]
I think at this point the plan is to eventually deprecate node resolvers.
