### ISSUE TITLE
Flesh out Kubernetes Getting Started Guide to demonstrate registering workloads, giving workloads their SVIDs

### ISSUE THREAD

**Issue by jennybeth** [spiffe/spire#851]
* **Version**: 
* **Platform**: 
* **Subsystem**:

**Comment by omerlh** [comment]
Yes please! I'm trying to figure out how to do this right now...

**Comment by ryysud** [comment]
Is this issue fixed by my changes ( https://github.com/spiffe/spiffe.io/pull/73 ) ?

**Comment by evan2645** [comment]
Hey, I think so! I missed that one... thanks for the poke @ryysud :-D
