### ISSUE TITLE
More configurable logging

### ISSUE THREAD

**Issue by mcpherrinm** [spiffe/spire#869]
Logrus is a very configurable logging platform, but not many options are exposed right now.

In #866 I added a flag to allow choosing Json or Text (if what Logrus' automatic selection doesn't do what you want).  However, it doesn't allow you to set any of the [JSON formatter options](https://godoc.org/github.com/sirupsen/logrus#JSONFormatter) or [text ones](https://godoc.org/github.com/sirupsen/logrus#TextFormatter)

Additionally, there's now three top-level "log" related configurables:  It may make sense to put them into a shared struct for less code duplication, and more organized configuration.  Then include per-formatter options in that.   I'm not really sure what the HCL would look like for that.

A whole bigger bucket of worms is that Logrus supports [3rd party hooks](https://github.com/sirupsen/logrus/wiki/Hooks) [and formatters](https://github.com/sirupsen/logrus#formatters).  It's not reasonable to compile every hook somebody might want into SPIRE by default, so I think the most likely option here is either (a) a new plugin type for logging, using the usual SPIRE plugin infrastructure, or (b) if you want a custom hook or formatter, provide a custom main.go that pre-configures Logrus before calling cli.Run.

My specific goals are to be able to force JSON output, which #866 handles, and to support custom hooks, like (local file hook)[https://github.com/rifflock/lfshook] and the (Sentry.io hook)[https://github.com/evalphobia/logrus_sentry], so that we can have logs go to multiple locations:  Debug to local logfiles, INFO and above to stdout, and WARN / ERROR to Sentry.io.

**Comment by azdagron** [comment]
We haven't had any more requests along these lines for quite some time. Closing for now.
