### ISSUE TITLE
Remove `umask` flag from server and agent cli

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#874]
The umask configuration is currently undocumented and will likely be removed in a future release in favor of standard OS-based methods for umask configuration. We moved the config variable to be undocumented, but it looks like we left a CLI flag behind. Since we can't have an undocumented flag, just remove it completely.

**Comment by ryysud** [comment]
I created https://github.com/spiffe/spire/pull/879 . It closes this issue.

**Comment by ryysud** [comment]
@evan2645 Cloud you close this issue?

**Comment by evan2645** [comment]
Thanks again @ryysud!
