### ISSUE TITLE
Bundle pruning is lossy in HA

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#892]
SPIRE servers occasionally check the trust bundle for expired certificates that should be pruned. The pruning operation is done by
1) reading the current bundle
2) removing certificates that have expired (beyond the safety threshold)
3) updating the bundle contents

This flow is broken in HA, where another SPIRE server could append to the bundle after step 1. When step 3 is executed the certificate added by the other SPIRE server will be overwritten.

One solution is to modify the datastore plugin interface and add a `PruneBundle` call that can perform these steps in a single transaction and handle conflict resolution when necessary.

**Comment by marcosy** [comment]
Fixed  https://github.com/spiffe/spire/pull/919
