### ISSUE TITLE
Re-examine DataStore strategy

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#896]
The current DataStore interface features a series of high-level mostly-CRUD functions for various objects that SPIRE needs to persist. The CRUD  design was intended to give a large amount of flexibility in how implementers chose to implement the datastore.

Unfortunately, as SPIRE grows the DataStore interface is perpetually changing. Each change means every implementor of the DataStore interface needs to go update their implementation, including writing per-plugin migration logic.

Additionally, as the datastore grows, the required behavior becomes more burdensome to implement (and document), especially where implicit relationships between models are concerned.

SPIRE might benefit from a re-examination of the DataStore layer that 1) reduces implementor burden, 2) provides consistent migration strategy as persisted models are added/updated/removed, 3) moves all complication into SPIRE core itself where it can be actively maintained and unit-tested.

**Comment by azdagron** [comment]
One such possibility would be a simple key-value interface supporting a minimal set of operations needed to implement an indexible protobuf-based document store.

**Comment by summerwind** [comment]
I agree your suggestion. While implementing '[k8s](https://github.com/summerwind/spire-plugin-datastore-k8s)' datastore plugin,  it was hard to understand relationships between internal resources. If the datastore plugin is only required to manage keys and values, it will be easier to implement.

**Comment by azdagron** [comment]
I've put together a document outlining some problems and a few potential solutions: https://docs.google.com/document/d/1NI-4WOINMvZy6pYImvuWGq3mDyFQPLS6j_FL9NsH4R8/edit#

**Comment by summerwind** [comment]
The document is very useful. I support solution #3.

**Comment by azdagron** [comment]
This issue is no longer relevant. We're exploring other, related options.
