### ISSUE TITLE
Stop using X509 CSRs in Node API

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#897]
The Node API currently uses X509 CSRs to convey information about the SVID the agent wants to sign. However, there are very few fields out of the CSR that should influence the minted SVID. Accidentally utilizing fields from the CSR could impact security. SPIRE has had bug fixes in the past to reduce the role of the CSR for this very reason. Practically speaking, the CSR is really only used to convey the SPIFFE ID (via URI SANs) and the public key.

The Node API should be redesigned to use something other than X509 CSRs to convey the necessary information (i.e. SPIFFEID and Public Key of the requested SVID) to remove the chance of the CSR being abused and to reduce confusion around how the agent influences signing.

**Comment by evan2645** [comment]
Removing CSR processing in SPIRE server also reduces the number of spots that we need to do ASN.1 parsing. Without CSR, the TLS stack is the only place that needs to process it. CSR parsing in Go is decidedly less well-exercised than X.509 parsing.

**Comment by azdagron** [comment]
The Node API is no more and the SVID API that superseded this functionality decided against this recommendation. The fields used from the CSR are explicitly documented.
