### ISSUE TITLE
Remove agent requirement to calculate the SPIFFE ID produced by attestation

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#898]
During node attestation, SPIRE requires agent plugins to calculate the SPIFFE ID the agent will receive in advance. It is used on the server side to check if the agent has already attested (and validated against the SPIFFE ID produced by the server side plugin to make sure they match).

This requirement is an implementation burden for agent side node attestor plugins. It requires extra work on the agent that oftentimes requires extra permissions or configuration to accomplish (e.g. access to the K8S API).

SPIRE should be augmented to remove the requirement for agent node attestor plugins to calculate the SPIFFE ID without impacting re-attestation checks, ideally in a backwards compatible manner.

One possible solution would be to change the server-side node attestor interface to return whether or not re-attestation is allowed from the Attest call. After attestation has succeeded, the server could see if re-attestation is disallowed before setting the attested node entry. This has the advantage of allowing re-attestation decisions on an attestation-by-attestation basis and well as being backwards compatible. The downside is that an agent can cause the server to do some amount of work for no reason (since it would have to do all the work of attestation just to have the server fail the attestation after the plugin is done if the agent has already re-attested).

Another solution is to add another RPC to the server-side node attestor interface whereby the server can pass the attestation data to the plugin and get back the SPIFFE ID that would result from the attestation. The server could then check if the agent has already attested before issuing the actual Attest call. The advantage is potential work savings (for plugins that don't need to do work to figure out the SPIFFE ID). The disadvantage is existing plugins wouldn't implement the RPC which would complicate backwards compatibility.

**Comment by evan2645** [comment]
Fixed in #922
