### ISSUE TITLE
Label SPIRE container images with "stable" tag

### ISSUE THREAD

**Issue by scotte** [spiffe/spire#913]
In the `spiffe-io` container registry we currently only have labels for "unstable" and specific releases (such as "0.7.3"). It would be nice to have a "stable" label as well to use for examples and demos that points to the most recent stable release. This helps prevent examples from getting too stale, and I'd rather see them break with a newer version of SPIRE than find someone using an ancient version of SPIRE.

**Comment by evan2645** [comment]
There have been many discussions recently about the maintenance of SPIFFE/SPIRE examples (or lack thereof). The current consensus is to have two kinds of examples: one that comes with a guide/documentation, and one that doesn't. The former would be exercised nightly and pinned to a specific version of SPIRE, and the latter would be exercised on master merge (or nightly) against the latest commit.

The reasoning was that as SPIRE versions change, the narrative of the guide/docs also changes. Updating the narrative is something that will always have to be done by hand, so for these cases, it makes sense to pin and to let a human bump the version and the docs at the same time.

You mention "helps prevent examples from getting too stale" - I'm curious to know if your idea/definition of example in this context fits into one of the two buckets above?

**Comment by azdagron** [comment]
We no longer publish under the unstable tag. Additionally, upgrading always requires careful consideration, so pinning to a "stable" version won't imply a safe upgrade if you move more than one minor release. I think what we have now is working well. Happy to consider other angles but will close for now.
