### ISSUE TITLE
Document the golang Workload API client

### ISSUE THREAD

**Issue by ajessup** [spiffe/spire#923]
The golang SPIFFE Workload API client is provided [as part of the SPIRE project](/spiffe/spire/tree/master/api/workload).

However no documentation exists for how to use it in a typical application. Some should be provided.

**Comment by evan2645** [comment]
Workload API client is now nominally provided by go-spiffe v2, and the client is documented there via godoc: https://pkg.go.dev/github.com/spiffe/go-spiffe/v2@v2.0.0-beta.5/workloadapi

Closing this out as done
