### ISSUE TITLE
Emit node label selectors from k8s_psat node attestor

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#933]
Kubernetes has a concept of node labels, and it would be useful to be able to use them in node entries e.g. "give all k8s nodes with label foo a SPIFFE ID of bar". The k8s_psat node attestor gets to know the identity of the node that the agent is running on, and thus should be in a position to discover any node labels that may have been applied to that node.

Update the k8s_psat node attestor to emit node selectors for node labels.

**Comment by azdagron** [comment]
Should this be opt-in, like we've done for label values in other attestors (i.e. GCP IIT)?

**Comment by azdagron** [comment]
Do we also want to add pod label selectors?

**Comment by evan2645** [comment]
Fixed in https://github.com/spiffe/spire/pull/1042
