### ISSUE TITLE
Improve docs for registrations with node resolvers 

### ISSUE THREAD

**Issue by APTy** [spiffe/spire#947]
This came up a bit in #help, but there aren't docs that explicitly show how to make registrations based on node resolver plugins. The example I offered was:

1. Create a node entry that represents an iam group (or other resolver selector).
```
$ spire-server entry create \
    -node \
    -spiffeID spiffe://example.org/my-foo-cluster \
    -selector aws_iid:iamrole:foo
```

2. Create a workload entry that is bound to any of the nodes defined in (1)
```
$ spire-server entry create \
    -spiffeID spiffe://example.org/foo \
    -parentID spiffe://example.org/my-foo-cluster \
    -selector unix:user:foo
```

We should make sure a reference example like this exists in the online docs so that future people with this question can be directed there.

Also: the AWS node resolver docs show an IAM selector format like `aws_iid:iamrole:arn:aws:iam::FOO:instance-profile/envoy-spire`, but it was noted in chat that the actual selector is `aws_iid:iamrole:arn:aws:iam::FOO:role/envoy-spire`. If this is a docs issue, we should also fix it.

**Comment by mbarrin** [comment]
https://github.com/spiffe/spire/pull/948 Is the fix for the second part.

**Comment by azdagron** [comment]
The docs have had some churn since this was first opened and I'm not sure it's still relevant. Closing for now.
