### ISSUE TITLE
spire-server mint feature

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#959]
SPIRE usability could benefit from some convenience functions for minting SVIDs without having to create a registration entry. There are a number of cases in which this could be useful:
* Manually generate an X509-SVID and key that can be passed to provider-based components (e.g. a Lambda function)
* Generate a JWT-SVID for manually testing calls to a SPIFFE-aware service in dev/staging
* Providing X509-SVID certificates to legacy on-prem workloads that may not have adjacent agents
* etc...

Since access to the registration API is effectively the same as being able to generate or obtain arbitrary identities, I don't think this convenience function significantly changes spire-server's security posture. We can add these methods alongside existing entry CRUD methods.

CLI subcommands should also be provided to make doing this as easy as possible. I recommend something like this:
```
spire-server x509 mint ...
spire-server jwt mint ...
```
This subcommand pattern will allow us to extend in the future with revocation, listing previously issued/active SVIDs, etc.

**Comment by mcpherrinm** [comment]
I think for X509-SVID at least, it would be helpful if the server took a CSR instead of generating a key, even if all fields in the CSR are ignored except public key.

The CLI subcommand could generate a key & CSR for convenience.
