### ISSUE TITLE
Agent creates UDS listener directory after umask

### ISSUE THREAD

**Issue by APTy** [spiffe/spire#966]
In case SPIRE Agent is configured with a `socket_path` for its unix domain socket (UDS) listener that contains a directory that doesn't exist, the agent creates that directory with `0755` in [agent/endpoints](https://github.com/spiffe/spire/blob/master/pkg/agent/endpoints/endpoints.go#L103).

Unfortunately, this occurs _after_ the umask has been set to `0027` in [cli/run](https://github.com/spiffe/spire/blob/master/cmd/spire-agent/cli/run/run.go#L106). This means that the directory is created with `0750`, which means the directory is not writable to other users on the system, which means users cannot communicate over the unix socket.

As a remedy, we could create the necessary directories in `cli/run` before the umask is set. Additionally, if we could log a warning that the agent is creating a directory, it could be good info to surface to users.

**Comment by malnick** [comment]
@APTy I'm happy to take a stab at this if nobody else is working on it.

**Comment by APTy** [comment]
That'd be great!

**Comment by malnick** [comment]
@APTy sorry it's taken so long to circle back to this. I'm wondering if the most effective way to do this would be to unset the umask in `cli/run`, then resetting it. This would circumvent creating a dependency chain between the code in `agent/endpoints` and `cli/run`. 

Something like this: https://github.com/spiffe/spire/compare/master...malnick:malnick/issue-966

Thoughts?

**Comment by azdagron** [comment]
Fixed by #1048.
