### ISSUE TITLE
Agentless API

### ISSUE THREAD

**Issue by omerlh** [spiffe/spire#986]
One of the challenges of using SPIFFE is workload running on platforms where installing an agent is almost impossible. This could be a non-docker deployment (legacy, AWS BeanStalk, Azure AppService) where installing an agent could be very complex or FaaS where it's impossible. I'm proposing the following changes to the protocol to support such deployments:
First, add "agentless" API in the following format:
```
POST api/v1/token
Header: Authorization <token>
Body:
{
  "additional_claims": {}
}
```
The `<token>` is provided by the platform where the code is running - AWS credentials from the metadata endpoint, Azure access token, Kubernetes service account token, etc. The additional claims will be added to the issued JWT.
The server will validate the token with the issuing platform, and if valid it will issue a new JWT token with SPIFFE format based on the original token. This endpoint could easily be consumed by any application exist, with a small modification (adding a post request) and make it a lot easier to move into SPIFFE.
The second is exposing something like OpenID connect metadata endpoint, for exposing the keys used to validate the issued JWT. Consumers can use this endpoint when verifying the token, making it easier for everyone to validate token leveraging existing implementations for JWT token validation.

**Comment by evan2645** [comment]
> @mcpherrinm suggested something similar to the virtual kubelet pattern, where an agent (or something like it) can get SVIDs issued, and manage their lifecycle, while persisting them into platform-specific stores. This would allow platforms with serverless/agentless offerings to manage the delivery of SVIDs as part of boot. The way that the SVIDs are persisted and manage could be pluggable, or easily extendable.

To put a bit of a finer point on this - the Workload API is meant to solve the "secret zero" problem, or the initial introduction of identity. The Node API is meant to facilitate agent functionality. The problem we want to solve in agentless (AFAICT) is the former and not the latter, so we should explore ways to introduce/inject SPIFFE credentials into agentless/serverless workloads. Since these platforms all have different ways of doing things, I think it makes sense to leverage platform-specific mechanisms to accomplish the injection of SPIFFE identities. Note that unlike a credential exchange API, this negates the need for the workload to authenticate either itself or the API it is calling.

**Comment by omerlh** [comment]
So you're basically suggesting a secret distribution solution (SDS)? This requires some thoughts, but I'm not sure this is possible. I would suggest taking a practical use case (e.g. PaaS offerings like AWS BeanStalk or Azure AppService or FaaS offering like Azure function or AWS lambda) and try to imagine how such a flow will work. I hear what you're saying about reliability and performance, and this is indeed a problem - especially when using HSM to sign the tokens (which makes things only slower). I just think a centralized solution might be feasible and support all platforms which might not be the case for SDS.

**Comment by evan2645** [comment]
Work on this is well underway, and is being tracked in https://github.com/spiffe/spire/issues/1843

Community feedback has steered us towards a push model for the first pass, but I think in the fullness of time we'll also want to support something centralized as is described here. It's unclear exactly what that would look like (e.g. "direct attestation" of workloads, or credential exchange API, or both?). The majority of the conversation is occurring in the RFC though, so going to close this out in favor of tracking there.
