### ISSUE TITLE
Changing trust domain in SPIRE is non-intuitive

### ISSUE THREAD

**Issue by ajessup** [spiffe/spire#989]
If one initializes a SPIRE Server with a particular trust domain, and then changes the value of `trust_domain` in the server configuration, it can lead to inconsistencies between the configuration file and the state in the Server's datastore.

This should be fixed such that if there is an inconsistency, this should be checked for at startup and clearly reported in an error to the user.

**Comment by ajessup** [comment]
The error in this situation may look like this:

`msg="Could not generate TLS config for gRPC client x.x.x.x:43206: bundle not found" subsystem_name=endpoints`

**Comment by ZymoticB** [comment]
Is this something that should actually be supported (changing a deployments trust domain)?

Federation bundles are keyed by trust domain right? How we would ensure that all validators, including federated ones, process this safely? This would also require rotating all SVIDs that have been issued to workload and potentially propagating a trust bundle that contains 2 trust domains in a non-federated way to ensure the running system can continue validating SVIDs out in the wild.

Definitely on board with a better error message but I'm not sure this should be supported. Is there a use case you have in mind or was this a happy accident with an unclear error message?

Internally at my company, we're thinking of the trust domain as fixed for a deployment and if we ever need to change it we will likely need to deploy a second cluster, federate them, and do per-workload migrations to new agents. This is something we hope to avoid ever having to do.

**Comment by ajessup** [comment]
During initial testing, changing trust domains mid-flight is a pretty common error (I've personally run into it several times). For now I don't think this is a production issue, and thus we don't need to support actually migrating the trust domain of a production, potentially federated, SPIRE server.

The "command or tool exists to update the datastore configuration to match the new one" could be to essentially re-set the SPIRE server (eg. invalidate all existing SVIDs and trust bundles, and zero existing configuration server's datastore).

**Comment by azdagron** [comment]
Switching the trust domain also requires resetting SPIRE agent configuration and state. Also, the trust domain is part of the global configuration passed to plugins, who are free to do with it what they might. As such, a total solution would require plugin support for cleaning up old state.

I think a good first pass at this would just be to detect a trust domain change and fail to start the agent/server with an error message. Anything beyond that might require some careful consideration.

**Comment by ZymoticB** [comment]
Sure, that makes sense to me. I agree having a better tool than "drop your DB" is useful. We should be clear that this is not intended to be a safe/supported command to run in a production environment.

**Comment by ajessup** [comment]
Makes sense. I'll scope this particular issue to showing a better error message, and file a separate one for a reset command.

**Comment by amok99** [comment]
Hello all,

Firstly, thank you for your help on slack in getting this fixed, it was quick and painless. With regards to the issue I was having, initially it was not clear to me that that the trust domain was an arbitrary setting and not a FQDN. I think the problem stems from this assumption.
After starting the spire server and agent and having fixed various issues with PV mapping, I decided to start from scratch having cleaned up a few config options. When starting the server/agent pair I got error/crashloopbackoff. In the logs I saw:-

kubectl log spire-agent-8vpwb -n spire
log is DEPRECATED and will be removed in a future version. Use logs instead.
level=warning msg="Current umask 0022 is too permissive; setting umask 0027."
level=info msg="data directory: \"/run/spire\""
level=info msg="Starting plugin catalog" subsystem_name=catalog
level=debug msg="NodeAttestor(k8s_sat): configuring plugin" subsystem_name=catalog
level=debug msg="KeyManager(memory): configuring plugin" subsystem_name=catalog
level=debug msg="WorkloadAttestor(k8s): configuring plugin" subsystem_name=catalog
level=debug msg="WorkloadAttestor(unix): configuring plugin" subsystem_name=catalog
level=debug msg="No pre-existing agent SVID found. Will perform node attestation" subsystem_name=attestor
level=error msg="SPIFFE ID mismatch" subsystem_name=attestor
level=info msg="Stopping plugin catalog" subsystem_name=catalog
[DEBUG] plugin: waiting for all plugin processes to complete...
level=error msg="agent crashed: opening stream for attestation: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: error while dialing: SPIFFE ID mismatch\""


kubectl log spire-server-0 -n spire
log is DEPRECATED and will be removed in a future version. Use logs instead.
level=warning msg="Current umask 0022 is too permissive; setting umask 0027."
level=info msg="data directory: \"/run/spire/data\""
level=info msg="Starting plugin catalog" subsystem_name=catalog
level=debug msg="NodeAttestor(k8s_sat): configuring plugin" subsystem_name=catalog
level=debug msg="NodeResolver(noop): configuring plugin" subsystem_name=catalog
level=debug msg="KeyManager(disk): configuring plugin" subsystem_name=catalog
level=debug msg="UpstreamCA(disk): configuring plugin" subsystem_name=catalog
level=debug msg="DataStore(sql): configuring plugin" subsystem_name=catalog
level=info msg="initializing database."
level=info msg="plugins started"
level=debug msg="Keypair set \"A\" does not exist" subsystem_name=ca_manager
level=debug msg="Keypair set \"B\" does not exist" subsystem_name=ca_manager
level=debug msg="Loaded keypair sets" subsystem_name=ca_manager
level=debug msg="Preparing keypair set \"A\"" subsystem_name=ca_manager
level=debug msg="Keypair set \"A\" will expire 2019-07-03T02:33:28Z" subsystem_name=ca_manager
level=debug msg="Activating keypair set \"A\"" subsystem_name=ca_manager
level=debug msg="Rotating server SVID" subsystem_name=svid_rotator
level=debug msg="Signed x509 SVID \"spiffe://example.org/spire/server\" (expires 2019-07-02T15:33:29Z)" subsystem_name=ca_manager
level=debug msg="Initializing API endpoints" subsystem_name=endpoints
level=info msg="Starting TCP server on [::]:8081" subsystem_name=endpoints
level=info msg="Starting UDS server /tmp/spire-registration.sock" subsystem_name=endpoints


I then changed the trust domain from example.org to something more meaningful to me applied the configmap change and restarted the pods.

kubectl log spire-agent-rtjq4 -n spire
log is DEPRECATED and will be removed in a future version. Use logs instead.
level=warning msg="Current umask 0022 is too permissive; setting umask 0027."
level=info msg="data directory: \"/run/spire\""
level=info msg="Starting plugin catalog" subsystem_name=catalog
level=debug msg="WorkloadAttestor(k8s): configuring plugin" subsystem_name=catalog
level=debug msg="WorkloadAttestor(unix): configuring plugin" subsystem_name=catalog
level=debug msg="NodeAttestor(k8s_sat): configuring plugin" subsystem_name=catalog
level=debug msg="KeyManager(memory): configuring plugin" subsystem_name=catalog
level=debug msg="No pre-existing agent SVID found. Will perform node attestation" subsystem_name=attestor
level=error msg="remote error: tls: internal error" subsystem_name=attestor
level=info msg="Stopping plugin catalog" subsystem_name=catalog
[DEBUG] plugin: waiting for all plugin processes to complete...
level=error msg="agent crashed: opening stream for attestation: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: error while dialing: remote error: tls: internal error\""


kubectl log spire-server-0 -n spire
log is DEPRECATED and will be removed in a future version. Use logs instead.
level=warning msg="Current umask 0022 is too permissive; setting umask 0027."
level=info msg="data directory: \"/run/spire/data\""
level=info msg="Starting plugin catalog" subsystem_name=catalog
level=debug msg="DataStore(sql): configuring plugin" subsystem_name=catalog
level=debug msg="NodeAttestor(k8s_sat): configuring plugin" subsystem_name=catalog
level=debug msg="NodeResolver(noop): configuring plugin" subsystem_name=catalog
level=debug msg="KeyManager(disk): configuring plugin" subsystem_name=catalog
level=debug msg="UpstreamCA(disk): configuring plugin" subsystem_name=catalog
level=info msg="plugins started"
level=debug msg="Loaded keypair set \"A\"" subsystem_name=ca_manager
level=debug msg="Keypair set \"B\" does not exist" subsystem_name=ca_manager
level=debug msg="Loaded keypair sets" subsystem_name=ca_manager
level=debug msg="Activating keypair set \"A\"" subsystem_name=ca_manager
level=debug msg="Rotating server SVID" subsystem_name=svid_rotator
level=debug msg="Signed x509 SVID \"spiffe://mydomain.com/spire/server\" (expires 2019-07-02T15:44:29Z)" subsystem_name=ca_manager
level=debug msg="Initializing API endpoints" subsystem_name=endpoints
level=info msg="Starting TCP server on [::]:8081" subsystem_name=endpoints
level=info msg="Starting UDS server /tmp/spire-registration.sock" subsystem_name=endpoints
level=error msg="Could not generate TLS config for gRPC client x.x.x.x:37779: bundle not found" subsystem_name=endpoints
level=error msg="Could not generate TLS config for gRPC client x.x.x.x:50639: bundle not found" subsystem_name=endpoints
level=error msg="Could not generate TLS config for gRPC client xx.xx.xx.xx:48140: bundle not found" subsystem_name=endpoints
level=error msg="Could not generate TLS config for gRPC client xx.xx.xx.xx:48142: bundle not found" subsystem_name=endpoints

Both of these errors, I presume, are artifacts for the datastore not being reset being teardown and initialisation. Deleting all files from the datastore and restarting the pods fixed the errors.

**Comment by azdagron** [comment]
SPIRE has for some time detected when change to the trust domain happens and fails to launch. Switching trust domains isn't likely to be supported in the short term. If we can come up with a strong enough use case that can be revisited.
