### ISSUE TITLE
Agent and Server should have consistent usage of catalog

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#991]
Noted in https://github.com/spiffe/spire/pull/990#discussion_r299567105

Among other discrepancies, `Agent` and `Server` load/fill `HostServices` in different ways. `Agent` and `Server` should use their catalogs in as similar of ways as possible to reduce maintenance burden from divergent patterns.

**Comment by evan2645** [comment]
@azdagron is this something we still need to track given your ongoing catalog work?

If it is, can we articulate the value here beyond adhering to DRY? Like, is it better, probably, but is it worth tracking in an issue if it's not impactful enough for someone to pick up independently

**Comment by azdagron** [comment]
Yes, I plan on addressing this in a follow up PR to #2229. It it wasn't directly related and the direction I ultimately want to go will involve removing the identitystore and agentstore deferred "SetDeps" pattern, which was too large a change to also include in the monstrous #2229.

**Comment by evan2645** [comment]
Ok great. I'm going to go ahead and close this out since the work is about to arrive and we will undoubtedly forget to close this issue once merged :)

Thanks @azdagron
