### ISSUE TITLE
The SQL datastore plugin should return appropriate GRPC status codes

### ISSUE THREAD

**Issue by ZymoticB** [spiffe/spire#992]
The SQL datastore plugin implementation should return GRPC status errors with appropriate codes. It has been updated to return NotFound where appropriate but we need to do a pass for the others

Likely candidates are: 
* `AlreadyExists` when a unique constraint fails
* `DeadlineExceeded` on timeouts
* `OK` on success
* `Unknown` for others.

**Comment by azdagron** [comment]
This is no longer relevant since the DataStore is no longer a plugin.
